/* SQL text to insert new entity field */

      IF NOT EXISTS (
         SELECT 1 FROM [${flyway:defaultSchema}].EntityField 
         WHERE ID = '20cdee13-4a8f-4bde-bd63-d8c4a69a38da'  OR 
               (EntityID = 'AE950179-A361-4185-9965-DF73533737ED' AND Name = 'RateLimitRequests')
         -- check to make sure we're not inserting a duplicate entity field metadata record
      )
      BEGIN
         INSERT INTO [${flyway:defaultSchema}].EntityField
         (
            ID,
            EntityID,
            Sequence,
            Name,
            DisplayName,
            Description,
            Type,
            Length,
            Precision,
            Scale,
            AllowsNull,
            DefaultValue,
            AutoIncrement,
            AllowUpdateAPI,
            IsVirtual,
            RelatedEntityID,
            RelatedEntityFieldName,
            IsNameField,
            IncludeInUserSearchAPI,
            IncludeRelatedEntityNameFieldInBaseView,
            DefaultInView,
            IsPrimaryKey,
            IsUnique,
            RelatedEntityDisplayType
         )
         VALUES
         (
            '20cdee13-4a8f-4bde-bd63-d8c4a69a38da',
            'AE950179-A361-4185-9965-DF73533737ED', -- Entity: MJ: API Keys
            100023,
            'RateLimitRequests',
            'Rate Limit Requests',
            'Maximum number of requests allowed within the rate limit window. Default: 1000 requests per hour.',
            'int',
            4,
            10,
            0,
            1,
            '(1000)',
            0,
            1,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search'
         )
      END

/* SQL text to insert new entity field */

      IF NOT EXISTS (
         SELECT 1 FROM [${flyway:defaultSchema}].EntityField 
         WHERE ID = '1b83f116-7570-4056-a526-976ea245ee9d'  OR 
               (EntityID = 'AE950179-A361-4185-9965-DF73533737ED' AND Name = 'RateLimitWindowSeconds')
         -- check to make sure we're not inserting a duplicate entity field metadata record
      )
      BEGIN
         INSERT INTO [${flyway:defaultSchema}].EntityField
         (
            ID,
            EntityID,
            Sequence,
            Name,
            DisplayName,
            Description,
            Type,
            Length,
            Precision,
            Scale,
            AllowsNull,
            DefaultValue,
            AutoIncrement,
            AllowUpdateAPI,
            IsVirtual,
            RelatedEntityID,
            RelatedEntityFieldName,
            IsNameField,
            IncludeInUserSearchAPI,
            IncludeRelatedEntityNameFieldInBaseView,
            DefaultInView,
            IsPrimaryKey,
            IsUnique,
            RelatedEntityDisplayType
         )
         VALUES
         (
            '1b83f116-7570-4056-a526-976ea245ee9d',
            'AE950179-A361-4185-9965-DF73533737ED', -- Entity: MJ: API Keys
            100024,
            'RateLimitWindowSeconds',
            'Rate Limit Window Seconds',
            'Time window in seconds for rate limiting. Default: 3600 (1 hour). Common values: 60 (1 min), 300 (5 min), 3600 (1 hour), 86400 (1 day).',
            'int',
            4,
            10,
            0,
            1,
            '(3600)',
            0,
            1,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search'
         )
      END

/* Index for Foreign Keys for APIKey */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key UserID in table APIKey
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_APIKey_UserID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[APIKey]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_APIKey_UserID ON [${flyway:defaultSchema}].[APIKey] ([UserID]);

-- Index for foreign key CreatedByUserID in table APIKey
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_APIKey_CreatedByUserID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[APIKey]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_APIKey_CreatedByUserID ON [${flyway:defaultSchema}].[APIKey] ([CreatedByUserID]);

/* Base View SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: vwAPIKeys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: API Keys
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  APIKey
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwAPIKeys]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwAPIKeys];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwAPIKeys]
AS
SELECT
    a.*,
    User_UserID.[Name] AS [User],
    User_CreatedByUserID.[Name] AS [CreatedByUser]
FROM
    [${flyway:defaultSchema}].[APIKey] AS a
INNER JOIN
    [${flyway:defaultSchema}].[User] AS User_UserID
  ON
    [a].[UserID] = User_UserID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[User] AS User_CreatedByUserID
  ON
    [a].[CreatedByUserID] = User_CreatedByUserID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwAPIKeys] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
    

/* Base View Permissions SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: Permissions for vwAPIKeys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwAPIKeys] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: spCreateAPIKey
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR APIKey
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateAPIKey]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateAPIKey];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateAPIKey]
    @ID uniqueidentifier = NULL,
    @Hash nvarchar(64),
    @UserID uniqueidentifier,
    @Name nvarchar(100),
    @Status nvarchar(20) = NULL,
    @ExpiresAt datetimeoffset,
    @LastUsedAt datetimeoffset,
    @CreatedByUserID uniqueidentifier,
    @RateLimitRequests int,
    @RateLimitWindowSeconds int
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[APIKey]
            (
                [ID],
                [Hash],
                [UserID],
                [Name],
                [Status],
                [ExpiresAt],
                [LastUsedAt],
                [CreatedByUserID],
                [RateLimitRequests],
                [RateLimitWindowSeconds]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @Hash,
                @UserID,
                @Name,
                ISNULL(@Status, 'Active'),
                @ExpiresAt,
                @LastUsedAt,
                @CreatedByUserID,
                @RateLimitRequests,
                @RateLimitWindowSeconds
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[APIKey]
            (
                [Hash],
                [UserID],
                [Name],
                [Status],
                [ExpiresAt],
                [LastUsedAt],
                [CreatedByUserID],
                [RateLimitRequests],
                [RateLimitWindowSeconds]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @Hash,
                @UserID,
                @Name,
                ISNULL(@Status, 'Active'),
                @ExpiresAt,
                @LastUsedAt,
                @CreatedByUserID,
                @RateLimitRequests,
                @RateLimitWindowSeconds
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwAPIKeys] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAPIKey] TO [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for MJ: API Keys */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAPIKey] TO [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: spUpdateAPIKey
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR APIKey
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateAPIKey]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateAPIKey];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateAPIKey]
    @ID uniqueidentifier,
    @Hash nvarchar(64),
    @UserID uniqueidentifier,
    @Name nvarchar(100),
    @Status nvarchar(20),
    @ExpiresAt datetimeoffset,
    @LastUsedAt datetimeoffset,
    @CreatedByUserID uniqueidentifier,
    @RateLimitRequests int,
    @RateLimitWindowSeconds int
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[APIKey]
    SET
        [Hash] = @Hash,
        [UserID] = @UserID,
        [Name] = @Name,
        [Status] = @Status,
        [ExpiresAt] = @ExpiresAt,
        [LastUsedAt] = @LastUsedAt,
        [CreatedByUserID] = @CreatedByUserID,
        [RateLimitRequests] = @RateLimitRequests,
        [RateLimitWindowSeconds] = @RateLimitWindowSeconds
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwAPIKeys] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwAPIKeys]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAPIKey] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the APIKey table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateAPIKey]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateAPIKey];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateAPIKey
ON [${flyway:defaultSchema}].[APIKey]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[APIKey]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[APIKey] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for MJ: API Keys */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAPIKey] TO [cdp_Developer], [cdp_Integration]



/* spDelete SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: spDeleteAPIKey
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR APIKey
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteAPIKey]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteAPIKey];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteAPIKey]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[APIKey]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAPIKey] TO [cdp_Integration]
    

/* spDelete Permissions for MJ: API Keys */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAPIKey] TO [cdp_Integration]



