-- Add Status column to ComponentLibrary table
-- This migration adds a Status field to track whether libraries are Active, Deprecated, or Disabled
-- Deprecated libraries will show console warnings, Disabled libraries will throw errors

-- Add Status column with CHECK constraint
ALTER TABLE ${flyway:defaultSchema}.ComponentLibrary
ADD Status NVARCHAR(20) NOT NULL 
    CONSTRAINT DF_ComponentLibrary_Status DEFAULT 'Active'
    CONSTRAINT CK_ComponentLibrary_Status CHECK (Status IN ('Active', 'Deprecated', 'Disabled'));

-- Add extended property description for the Status column
EXEC sp_addextendedproperty 
    @name = N'MS_Description',
    @value = N'Status of the component library. Active: fully supported; Deprecated: works but shows console warning; Disabled: throws error if used',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}',
    @level1type = N'TABLE',  @level1name = N'ComponentLibrary',
    @level2type = N'COLUMN', @level2name = N'Status';
  





/* SQL text to insert new entity field */

      IF NOT EXISTS (
         SELECT 1 FROM [${flyway:defaultSchema}].EntityField 
         WHERE ID = 'cb48a0f4-c84d-42ab-bd73-b075244f9655'  OR 
               (EntityID = '2264AA9A-2197-48E2-BB3D-A498006B37A5' AND Name = 'Status')
         -- check to make sure we're not inserting a duplicate entity field metadata record
      )
      BEGIN
         INSERT INTO [${flyway:defaultSchema}].EntityField
         (
            ID,
            EntityID,
            Sequence,
            Name,
            DisplayName,
            Description,
            Type,
            Length,
            Precision,
            Scale,
            AllowsNull,
            DefaultValue,
            AutoIncrement,
            AllowUpdateAPI,
            IsVirtual,
            RelatedEntityID,
            RelatedEntityFieldName,
            IsNameField,
            IncludeInUserSearchAPI,
            IncludeRelatedEntityNameFieldInBaseView,
            DefaultInView,
            IsPrimaryKey,
            IsUnique,
            RelatedEntityDisplayType
         )
         VALUES
         (
            'cb48a0f4-c84d-42ab-bd73-b075244f9655',
            '2264AA9A-2197-48E2-BB3D-A498006B37A5', -- Entity: MJ: Component Libraries
            100012,
            'Status',
            'Status',
            'Status of the component library. Active: fully supported; Deprecated: works but shows console warning; Disabled: throws error if used',
            'nvarchar',
            40,
            0,
            0,
            0,
            'Active',
            0,
            1,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search'
         )
      END

/* SQL text to insert entity field values */
INSERT INTO [${flyway:defaultSchema}].EntityFieldValue
                                       (EntityFieldID, Sequence, Value, Code)
                                    VALUES
                                       ('CB48A0F4-C84D-42AB-BD73-B075244F9655', 1, 'Active', 'Active')

/* SQL text to insert entity field values */
INSERT INTO [${flyway:defaultSchema}].EntityFieldValue
                                       (EntityFieldID, Sequence, Value, Code)
                                    VALUES
                                       ('CB48A0F4-C84D-42AB-BD73-B075244F9655', 2, 'Deprecated', 'Deprecated')

/* SQL text to insert entity field values */
INSERT INTO [${flyway:defaultSchema}].EntityFieldValue
                                       (EntityFieldID, Sequence, Value, Code)
                                    VALUES
                                       ('CB48A0F4-C84D-42AB-BD73-B075244F9655', 3, 'Disabled', 'Disabled')

/* SQL text to update ValueListType for entity field ID CB48A0F4-C84D-42AB-BD73-B075244F9655 */
UPDATE [${flyway:defaultSchema}].EntityField SET ValueListType='List' WHERE ID='CB48A0F4-C84D-42AB-BD73-B075244F9655'

/* Index for Foreign Keys for ComponentLibrary */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Component Libraries
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------


/* Base View SQL for MJ: Component Libraries */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Component Libraries
-- Item: vwComponentLibraries
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: Component Libraries
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ComponentLibrary
-----               PRIMARY KEY: ID
------------------------------------------------------------
DROP VIEW IF EXISTS [${flyway:defaultSchema}].[vwComponentLibraries]
GO

CREATE VIEW [${flyway:defaultSchema}].[vwComponentLibraries]
AS
SELECT
    c.*
FROM
    [${flyway:defaultSchema}].[ComponentLibrary] AS c
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwComponentLibraries] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
    

/* Base View Permissions SQL for MJ: Component Libraries */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Component Libraries
-- Item: Permissions for vwComponentLibraries
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwComponentLibraries] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for MJ: Component Libraries */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Component Libraries
-- Item: spCreateComponentLibrary
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ComponentLibrary
------------------------------------------------------------
DROP PROCEDURE IF EXISTS [${flyway:defaultSchema}].[spCreateComponentLibrary]
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateComponentLibrary]
    @ID uniqueidentifier = NULL,
    @Name nvarchar(500),
    @DisplayName nvarchar(500),
    @Version nvarchar(100),
    @GlobalVariable nvarchar(255),
    @Category nvarchar(100),
    @CDNUrl nvarchar(1000),
    @CDNCssUrl nvarchar(1000),
    @Description nvarchar(MAX),
    @Status nvarchar(20)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ComponentLibrary]
            (
                [ID],
                [Name],
                [DisplayName],
                [Version],
                [GlobalVariable],
                [Category],
                [CDNUrl],
                [CDNCssUrl],
                [Description],
                [Status]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @Name,
                @DisplayName,
                @Version,
                @GlobalVariable,
                @Category,
                @CDNUrl,
                @CDNCssUrl,
                @Description,
                @Status
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ComponentLibrary]
            (
                [Name],
                [DisplayName],
                [Version],
                [GlobalVariable],
                [Category],
                [CDNUrl],
                [CDNCssUrl],
                [Description],
                [Status]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @Name,
                @DisplayName,
                @Version,
                @GlobalVariable,
                @Category,
                @CDNUrl,
                @CDNCssUrl,
                @Description,
                @Status
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwComponentLibraries] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateComponentLibrary] TO [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for MJ: Component Libraries */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateComponentLibrary] TO [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for MJ: Component Libraries */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Component Libraries
-- Item: spUpdateComponentLibrary
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ComponentLibrary
------------------------------------------------------------
DROP PROCEDURE IF EXISTS [${flyway:defaultSchema}].[spUpdateComponentLibrary]
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateComponentLibrary]
    @ID uniqueidentifier,
    @Name nvarchar(500),
    @DisplayName nvarchar(500),
    @Version nvarchar(100),
    @GlobalVariable nvarchar(255),
    @Category nvarchar(100),
    @CDNUrl nvarchar(1000),
    @CDNCssUrl nvarchar(1000),
    @Description nvarchar(MAX),
    @Status nvarchar(20)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ComponentLibrary]
    SET
        [Name] = @Name,
        [DisplayName] = @DisplayName,
        [Version] = @Version,
        [GlobalVariable] = @GlobalVariable,
        [Category] = @Category,
        [CDNUrl] = @CDNUrl,
        [CDNCssUrl] = @CDNCssUrl,
        [Description] = @Description,
        [Status] = @Status
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwComponentLibraries] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwComponentLibraries]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateComponentLibrary] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ComponentLibrary table
------------------------------------------------------------
DROP TRIGGER IF EXISTS [${flyway:defaultSchema}].trgUpdateComponentLibrary
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateComponentLibrary
ON [${flyway:defaultSchema}].[ComponentLibrary]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ComponentLibrary]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ComponentLibrary] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for MJ: Component Libraries */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateComponentLibrary] TO [cdp_Developer], [cdp_Integration]



/* spDelete SQL for MJ: Component Libraries */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Component Libraries
-- Item: spDeleteComponentLibrary
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ComponentLibrary
------------------------------------------------------------
DROP PROCEDURE IF EXISTS [${flyway:defaultSchema}].[spDeleteComponentLibrary]
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteComponentLibrary]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ComponentLibrary]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteComponentLibrary] TO [cdp_Integration]
    

/* spDelete Permissions for MJ: Component Libraries */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteComponentLibrary] TO [cdp_Integration]



