-- SQL Logging Session
-- Session ID: 16fea9ba-a70b-4d71-abb0-9d0b974f70b5
-- Started: 2025-09-29T21:29:19.114Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction SQLServerDataProvider

-- Save Actions (core SP call only)
DECLARE @ID_7da253a5 UNIQUEIDENTIFIER,
@CategoryID_7da253a5 UNIQUEIDENTIFIER,
@Name_7da253a5 NVARCHAR(425),
@Description_7da253a5 NVARCHAR(MAX),
@Type_7da253a5 NVARCHAR(20),
@UserPrompt_7da253a5 NVARCHAR(MAX),
@UserComments_7da253a5 NVARCHAR(MAX),
@Code_7da253a5 NVARCHAR(MAX),
@CodeComments_7da253a5 NVARCHAR(MAX),
@CodeApprovalStatus_7da253a5 NVARCHAR(20),
@CodeApprovalComments_7da253a5 NVARCHAR(MAX),
@CodeApprovedByUserID_7da253a5 UNIQUEIDENTIFIER,
@CodeApprovedAt_7da253a5 DATETIME,
@CodeLocked_7da253a5 BIT,
@ForceCodeGeneration_7da253a5 BIT,
@RetentionPeriod_7da253a5 INT,
@Status_7da253a5 NVARCHAR(20),
@DriverClass_7da253a5 NVARCHAR(255),
@ParentID_7da253a5 UNIQUEIDENTIFIER,
@IconClass_7da253a5 NVARCHAR(100)
SET
  @ID_7da253a5 = '77d34b5a-f636-49e1-a20b-6446502bd65e'
SET
  @CategoryID_7da253a5 = 'E959A850-7842-456D-AB51-F232DF12E709'
SET
  @Name_7da253a5 = N'File Storage Operations'
SET
  @Description_7da253a5 = N'Comprehensive action for performing file storage operations across different storage providers (Azure Blob, AWS S3, Google Cloud, Google Drive, Dropbox, Box, SharePoint). Supports listing, uploading, downloading, copying, moving, deleting files and directories.'
SET
  @Type_7da253a5 = N'Custom'
SET
  @CodeApprovalStatus_7da253a5 = N'Pending'
SET
  @CodeLocked_7da253a5 = 0
SET
  @ForceCodeGeneration_7da253a5 = 0
SET
  @Status_7da253a5 = N'Active'
SET
  @DriverClass_7da253a5 = N'File Storage Operations'
SET
  @IconClass_7da253a5 = N'fa-solid fa-cloud'
EXEC [${flyway:defaultSchema}].spCreateAction @ID = @ID_7da253a5,
  @CategoryID = @CategoryID_7da253a5,
  @Name = @Name_7da253a5,
  @Description = @Description_7da253a5,
  @Type = @Type_7da253a5,
  @UserPrompt = @UserPrompt_7da253a5,
  @UserComments = @UserComments_7da253a5,
  @Code = @Code_7da253a5,
  @CodeComments = @CodeComments_7da253a5,
  @CodeApprovalStatus = @CodeApprovalStatus_7da253a5,
  @CodeApprovalComments = @CodeApprovalComments_7da253a5,
  @CodeApprovedByUserID = @CodeApprovedByUserID_7da253a5,
  @CodeApprovedAt = @CodeApprovedAt_7da253a5,
  @CodeLocked = @CodeLocked_7da253a5,
  @ForceCodeGeneration = @ForceCodeGeneration_7da253a5,
  @RetentionPeriod = @RetentionPeriod_7da253a5,
  @Status = @Status_7da253a5,
  @DriverClass = @DriverClass_7da253a5,
  @ParentID = @ParentID_7da253a5,
  @IconClass = @IconClass_7da253a5;

-- Save Action Params (core SP call only)
DECLARE @ID_79d662cd UNIQUEIDENTIFIER,
@ActionID_79d662cd UNIQUEIDENTIFIER,
@Name_79d662cd NVARCHAR(255),
@DefaultValue_79d662cd NVARCHAR(MAX),
@Type_79d662cd NCHAR(10),
@ValueType_79d662cd NVARCHAR(30),
@IsArray_79d662cd BIT,
@Description_79d662cd NVARCHAR(MAX),
@IsRequired_79d662cd BIT
SET
  @ID_79d662cd = 'b87a7269-b21b-445f-9a6a-627b94745777'
SET
  @ActionID_79d662cd = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_79d662cd = N'Operation'
SET
  @Type_79d662cd = N'Input'
SET
  @ValueType_79d662cd = N'Scalar'
SET
  @IsArray_79d662cd = 0
SET
  @Description_79d662cd = N'The operation to perform: ListObjects, GetMetadata, GetObject, GetDownloadUrl, GetUploadUrl, ObjectExists, DirectoryExists, CopyObject, MoveObject, DeleteObject, CreateDirectory, DeleteDirectory'
SET
  @IsRequired_79d662cd = 1
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_79d662cd,
  @ActionID = @ActionID_79d662cd,
  @Name = @Name_79d662cd,
  @DefaultValue = @DefaultValue_79d662cd,
  @Type = @Type_79d662cd,
  @ValueType = @ValueType_79d662cd,
  @IsArray = @IsArray_79d662cd,
  @Description = @Description_79d662cd,
  @IsRequired = @IsRequired_79d662cd;

-- Save Action Params (core SP call only)
DECLARE @ID_3d914030 UNIQUEIDENTIFIER,
@ActionID_3d914030 UNIQUEIDENTIFIER,
@Name_3d914030 NVARCHAR(255),
@DefaultValue_3d914030 NVARCHAR(MAX),
@Type_3d914030 NCHAR(10),
@ValueType_3d914030 NVARCHAR(30),
@IsArray_3d914030 BIT,
@Description_3d914030 NVARCHAR(MAX),
@IsRequired_3d914030 BIT
SET
  @ID_3d914030 = '0fed2ad0-0841-4271-be18-58ca55dfff5b'
SET
  @ActionID_3d914030 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_3d914030 = N'StorageProvider'
SET
  @Type_3d914030 = N'Input'
SET
  @ValueType_3d914030 = N'Scalar'
SET
  @IsArray_3d914030 = 0
SET
  @Description_3d914030 = N'Name of the storage provider (e.g., ''Azure Blob Storage'', ''AWS S3 Storage'', ''Google Cloud Storage'', ''Google Drive'', ''Dropbox'', ''Box.com'', ''SharePoint Storage'')'
SET
  @IsRequired_3d914030 = 1
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_3d914030,
  @ActionID = @ActionID_3d914030,
  @Name = @Name_3d914030,
  @DefaultValue = @DefaultValue_3d914030,
  @Type = @Type_3d914030,
  @ValueType = @ValueType_3d914030,
  @IsArray = @IsArray_3d914030,
  @Description = @Description_3d914030,
  @IsRequired = @IsRequired_3d914030;

-- Save Action Params (core SP call only)
DECLARE @ID_5e446769 UNIQUEIDENTIFIER,
@ActionID_5e446769 UNIQUEIDENTIFIER,
@Name_5e446769 NVARCHAR(255),
@DefaultValue_5e446769 NVARCHAR(MAX),
@Type_5e446769 NCHAR(10),
@ValueType_5e446769 NVARCHAR(30),
@IsArray_5e446769 BIT,
@Description_5e446769 NVARCHAR(MAX),
@IsRequired_5e446769 BIT
SET
  @ID_5e446769 = 'c813855e-6bf1-488f-b6f2-faf3b6d0f6bd'
SET
  @ActionID_5e446769 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_5e446769 = N'ObjectName'
SET
  @Type_5e446769 = N'Input'
SET
  @ValueType_5e446769 = N'Scalar'
SET
  @IsArray_5e446769 = 0
SET
  @Description_5e446769 = N'Name/path of the file object (used by most operations)'
SET
  @IsRequired_5e446769 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_5e446769,
  @ActionID = @ActionID_5e446769,
  @Name = @Name_5e446769,
  @DefaultValue = @DefaultValue_5e446769,
  @Type = @Type_5e446769,
  @ValueType = @ValueType_5e446769,
  @IsArray = @IsArray_5e446769,
  @Description = @Description_5e446769,
  @IsRequired = @IsRequired_5e446769;

-- Save Action Params (core SP call only)
DECLARE @ID_3b6564b3 UNIQUEIDENTIFIER,
@ActionID_3b6564b3 UNIQUEIDENTIFIER,
@Name_3b6564b3 NVARCHAR(255),
@DefaultValue_3b6564b3 NVARCHAR(MAX),
@Type_3b6564b3 NCHAR(10),
@ValueType_3b6564b3 NVARCHAR(30),
@IsArray_3b6564b3 BIT,
@Description_3b6564b3 NVARCHAR(MAX),
@IsRequired_3b6564b3 BIT
SET
  @ID_3b6564b3 = 'c6b8f51f-74eb-4474-8955-236e62de88e3'
SET
  @ActionID_3b6564b3 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_3b6564b3 = N'SourceObjectName'
SET
  @Type_3b6564b3 = N'Input'
SET
  @ValueType_3b6564b3 = N'Scalar'
SET
  @IsArray_3b6564b3 = 0
SET
  @Description_3b6564b3 = N'Source file path for CopyObject or MoveObject operations'
SET
  @IsRequired_3b6564b3 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_3b6564b3,
  @ActionID = @ActionID_3b6564b3,
  @Name = @Name_3b6564b3,
  @DefaultValue = @DefaultValue_3b6564b3,
  @Type = @Type_3b6564b3,
  @ValueType = @ValueType_3b6564b3,
  @IsArray = @IsArray_3b6564b3,
  @Description = @Description_3b6564b3,
  @IsRequired = @IsRequired_3b6564b3;

-- Save Action Params (core SP call only)
DECLARE @ID_c2b46277 UNIQUEIDENTIFIER,
@ActionID_c2b46277 UNIQUEIDENTIFIER,
@Name_c2b46277 NVARCHAR(255),
@DefaultValue_c2b46277 NVARCHAR(MAX),
@Type_c2b46277 NCHAR(10),
@ValueType_c2b46277 NVARCHAR(30),
@IsArray_c2b46277 BIT,
@Description_c2b46277 NVARCHAR(MAX),
@IsRequired_c2b46277 BIT
SET
  @ID_c2b46277 = '280a62e7-f54f-4551-8d51-a88604c1ef8f'
SET
  @ActionID_c2b46277 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_c2b46277 = N'DestinationObjectName'
SET
  @Type_c2b46277 = N'Input'
SET
  @ValueType_c2b46277 = N'Scalar'
SET
  @IsArray_c2b46277 = 0
SET
  @Description_c2b46277 = N'Destination file path for CopyObject or MoveObject operations'
SET
  @IsRequired_c2b46277 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_c2b46277,
  @ActionID = @ActionID_c2b46277,
  @Name = @Name_c2b46277,
  @DefaultValue = @DefaultValue_c2b46277,
  @Type = @Type_c2b46277,
  @ValueType = @ValueType_c2b46277,
  @IsArray = @IsArray_c2b46277,
  @Description = @Description_c2b46277,
  @IsRequired = @IsRequired_c2b46277;

-- Save Action Params (core SP call only)
DECLARE @ID_bf22bae4 UNIQUEIDENTIFIER,
@ActionID_bf22bae4 UNIQUEIDENTIFIER,
@Name_bf22bae4 NVARCHAR(255),
@DefaultValue_bf22bae4 NVARCHAR(MAX),
@Type_bf22bae4 NCHAR(10),
@ValueType_bf22bae4 NVARCHAR(30),
@IsArray_bf22bae4 BIT,
@Description_bf22bae4 NVARCHAR(MAX),
@IsRequired_bf22bae4 BIT
SET
  @ID_bf22bae4 = 'ad6f05ce-ae88-48a6-bcda-683c644c4bf8'
SET
  @ActionID_bf22bae4 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_bf22bae4 = N'DirectoryPath'
SET
  @Type_bf22bae4 = N'Input'
SET
  @ValueType_bf22bae4 = N'Scalar'
SET
  @IsArray_bf22bae4 = 0
SET
  @Description_bf22bae4 = N'Directory path for CreateDirectory, DeleteDirectory, or DirectoryExists operations'
SET
  @IsRequired_bf22bae4 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_bf22bae4,
  @ActionID = @ActionID_bf22bae4,
  @Name = @Name_bf22bae4,
  @DefaultValue = @DefaultValue_bf22bae4,
  @Type = @Type_bf22bae4,
  @ValueType = @ValueType_bf22bae4,
  @IsArray = @IsArray_bf22bae4,
  @Description = @Description_bf22bae4,
  @IsRequired = @IsRequired_bf22bae4;

-- Save Action Params (core SP call only)
DECLARE @ID_2f195cdf UNIQUEIDENTIFIER,
@ActionID_2f195cdf UNIQUEIDENTIFIER,
@Name_2f195cdf NVARCHAR(255),
@DefaultValue_2f195cdf NVARCHAR(MAX),
@Type_2f195cdf NCHAR(10),
@ValueType_2f195cdf NVARCHAR(30),
@IsArray_2f195cdf BIT,
@Description_2f195cdf NVARCHAR(MAX),
@IsRequired_2f195cdf BIT
SET
  @ID_2f195cdf = '4203fc8c-35b4-4e03-b49e-e34c0a65f8a0'
SET
  @ActionID_2f195cdf = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_2f195cdf = N'Objects'
SET
  @Type_2f195cdf = N'Output'
SET
  @ValueType_2f195cdf = N'Simple Object'
SET
  @IsArray_2f195cdf = 1
SET
  @Description_2f195cdf = N'Array of file objects returned by ListObjects operation'
SET
  @IsRequired_2f195cdf = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_2f195cdf,
  @ActionID = @ActionID_2f195cdf,
  @Name = @Name_2f195cdf,
  @DefaultValue = @DefaultValue_2f195cdf,
  @Type = @Type_2f195cdf,
  @ValueType = @ValueType_2f195cdf,
  @IsArray = @IsArray_2f195cdf,
  @Description = @Description_2f195cdf,
  @IsRequired = @IsRequired_2f195cdf;

-- Save Action Params (core SP call only)
DECLARE @ID_ce2eab84 UNIQUEIDENTIFIER,
@ActionID_ce2eab84 UNIQUEIDENTIFIER,
@Name_ce2eab84 NVARCHAR(255),
@DefaultValue_ce2eab84 NVARCHAR(MAX),
@Type_ce2eab84 NCHAR(10),
@ValueType_ce2eab84 NVARCHAR(30),
@IsArray_ce2eab84 BIT,
@Description_ce2eab84 NVARCHAR(MAX),
@IsRequired_ce2eab84 BIT
SET
  @ID_ce2eab84 = 'ffe1d84e-83a0-45a6-a846-99582b29519f'
SET
  @ActionID_ce2eab84 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_ce2eab84 = N'Path'
SET
  @DefaultValue_ce2eab84 = N'/'
SET
  @Type_ce2eab84 = N'Input'
SET
  @ValueType_ce2eab84 = N'Scalar'
SET
  @IsArray_ce2eab84 = 0
SET
  @Description_ce2eab84 = N'Directory path for ListObjects operation'
SET
  @IsRequired_ce2eab84 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_ce2eab84,
  @ActionID = @ActionID_ce2eab84,
  @Name = @Name_ce2eab84,
  @DefaultValue = @DefaultValue_ce2eab84,
  @Type = @Type_ce2eab84,
  @ValueType = @ValueType_ce2eab84,
  @IsArray = @IsArray_ce2eab84,
  @Description = @Description_ce2eab84,
  @IsRequired = @IsRequired_ce2eab84;

-- Save Action Params (core SP call only)
DECLARE @ID_7097a3ca UNIQUEIDENTIFIER,
@ActionID_7097a3ca UNIQUEIDENTIFIER,
@Name_7097a3ca NVARCHAR(255),
@DefaultValue_7097a3ca NVARCHAR(MAX),
@Type_7097a3ca NCHAR(10),
@ValueType_7097a3ca NVARCHAR(30),
@IsArray_7097a3ca BIT,
@Description_7097a3ca NVARCHAR(MAX),
@IsRequired_7097a3ca BIT
SET
  @ID_7097a3ca = 'ac9187c9-d4b0-4c57-b96d-b85ec88fdc23'
SET
  @ActionID_7097a3ca = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_7097a3ca = N'Delimiter'
SET
  @DefaultValue_7097a3ca = N'/'
SET
  @Type_7097a3ca = N'Input'
SET
  @ValueType_7097a3ca = N'Scalar'
SET
  @IsArray_7097a3ca = 0
SET
  @Description_7097a3ca = N'Path delimiter for ListObjects operation'
SET
  @IsRequired_7097a3ca = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_7097a3ca,
  @ActionID = @ActionID_7097a3ca,
  @Name = @Name_7097a3ca,
  @DefaultValue = @DefaultValue_7097a3ca,
  @Type = @Type_7097a3ca,
  @ValueType = @ValueType_7097a3ca,
  @IsArray = @IsArray_7097a3ca,
  @Description = @Description_7097a3ca,
  @IsRequired = @IsRequired_7097a3ca;

-- Save Action Params (core SP call only)
DECLARE @ID_23f2b51e UNIQUEIDENTIFIER,
@ActionID_23f2b51e UNIQUEIDENTIFIER,
@Name_23f2b51e NVARCHAR(255),
@DefaultValue_23f2b51e NVARCHAR(MAX),
@Type_23f2b51e NCHAR(10),
@ValueType_23f2b51e NVARCHAR(30),
@IsArray_23f2b51e BIT,
@Description_23f2b51e NVARCHAR(MAX),
@IsRequired_23f2b51e BIT
SET
  @ID_23f2b51e = '94e21d26-cd01-43c9-a311-ada77b8213f8'
SET
  @ActionID_23f2b51e = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_23f2b51e = N'Recursive'
SET
  @DefaultValue_23f2b51e = N'false'
SET
  @Type_23f2b51e = N'Input'
SET
  @ValueType_23f2b51e = N'Scalar'
SET
  @IsArray_23f2b51e = 0
SET
  @Description_23f2b51e = N'Boolean flag for recursive directory deletion'
SET
  @IsRequired_23f2b51e = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_23f2b51e,
  @ActionID = @ActionID_23f2b51e,
  @Name = @Name_23f2b51e,
  @DefaultValue = @DefaultValue_23f2b51e,
  @Type = @Type_23f2b51e,
  @ValueType = @ValueType_23f2b51e,
  @IsArray = @IsArray_23f2b51e,
  @Description = @Description_23f2b51e,
  @IsRequired = @IsRequired_23f2b51e;

-- Save Action Params (core SP call only)
DECLARE @ID_67905b41 UNIQUEIDENTIFIER,
@ActionID_67905b41 UNIQUEIDENTIFIER,
@Name_67905b41 NVARCHAR(255),
@DefaultValue_67905b41 NVARCHAR(MAX),
@Type_67905b41 NCHAR(10),
@ValueType_67905b41 NVARCHAR(30),
@IsArray_67905b41 BIT,
@Description_67905b41 NVARCHAR(MAX),
@IsRequired_67905b41 BIT
SET
  @ID_67905b41 = '99c87e3b-a0e5-4352-a722-572c5e67211f'
SET
  @ActionID_67905b41 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_67905b41 = N'Prefixes'
SET
  @Type_67905b41 = N'Output'
SET
  @ValueType_67905b41 = N'Scalar'
SET
  @IsArray_67905b41 = 1
SET
  @Description_67905b41 = N'Array of directory prefixes returned by ListObjects operation'
SET
  @IsRequired_67905b41 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_67905b41,
  @ActionID = @ActionID_67905b41,
  @Name = @Name_67905b41,
  @DefaultValue = @DefaultValue_67905b41,
  @Type = @Type_67905b41,
  @ValueType = @ValueType_67905b41,
  @IsArray = @IsArray_67905b41,
  @Description = @Description_67905b41,
  @IsRequired = @IsRequired_67905b41;

-- Save Action Params (core SP call only)
DECLARE @ID_c8cda396 UNIQUEIDENTIFIER,
@ActionID_c8cda396 UNIQUEIDENTIFIER,
@Name_c8cda396 NVARCHAR(255),
@DefaultValue_c8cda396 NVARCHAR(MAX),
@Type_c8cda396 NCHAR(10),
@ValueType_c8cda396 NVARCHAR(30),
@IsArray_c8cda396 BIT,
@Description_c8cda396 NVARCHAR(MAX),
@IsRequired_c8cda396 BIT
SET
  @ID_c8cda396 = '9f541958-3b0f-46b7-a32c-d77da388e12f'
SET
  @ActionID_c8cda396 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_c8cda396 = N'ObjectCount'
SET
  @Type_c8cda396 = N'Output'
SET
  @ValueType_c8cda396 = N'Scalar'
SET
  @IsArray_c8cda396 = 0
SET
  @Description_c8cda396 = N'Number of objects returned by ListObjects operation'
SET
  @IsRequired_c8cda396 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_c8cda396,
  @ActionID = @ActionID_c8cda396,
  @Name = @Name_c8cda396,
  @DefaultValue = @DefaultValue_c8cda396,
  @Type = @Type_c8cda396,
  @ValueType = @ValueType_c8cda396,
  @IsArray = @IsArray_c8cda396,
  @Description = @Description_c8cda396,
  @IsRequired = @IsRequired_c8cda396;

-- Save Action Params (core SP call only)
DECLARE @ID_e0857e55 UNIQUEIDENTIFIER,
@ActionID_e0857e55 UNIQUEIDENTIFIER,
@Name_e0857e55 NVARCHAR(255),
@DefaultValue_e0857e55 NVARCHAR(MAX),
@Type_e0857e55 NCHAR(10),
@ValueType_e0857e55 NVARCHAR(30),
@IsArray_e0857e55 BIT,
@Description_e0857e55 NVARCHAR(MAX),
@IsRequired_e0857e55 BIT
SET
  @ID_e0857e55 = '1ab01dbd-2dfd-40fe-ac85-2d46683e23ab'
SET
  @ActionID_e0857e55 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_e0857e55 = N'DirectoryCount'
SET
  @Type_e0857e55 = N'Output'
SET
  @ValueType_e0857e55 = N'Scalar'
SET
  @IsArray_e0857e55 = 0
SET
  @Description_e0857e55 = N'Number of directories returned by ListObjects operation'
SET
  @IsRequired_e0857e55 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_e0857e55,
  @ActionID = @ActionID_e0857e55,
  @Name = @Name_e0857e55,
  @DefaultValue = @DefaultValue_e0857e55,
  @Type = @Type_e0857e55,
  @ValueType = @ValueType_e0857e55,
  @IsArray = @IsArray_e0857e55,
  @Description = @Description_e0857e55,
  @IsRequired = @IsRequired_e0857e55;

-- Save Action Params (core SP call only)
DECLARE @ID_e230cc17 UNIQUEIDENTIFIER,
@ActionID_e230cc17 UNIQUEIDENTIFIER,
@Name_e230cc17 NVARCHAR(255),
@DefaultValue_e230cc17 NVARCHAR(MAX),
@Type_e230cc17 NCHAR(10),
@ValueType_e230cc17 NVARCHAR(30),
@IsArray_e230cc17 BIT,
@Description_e230cc17 NVARCHAR(MAX),
@IsRequired_e230cc17 BIT
SET
  @ID_e230cc17 = '601a8d87-0fb2-4ea5-aac9-76df5432a37b'
SET
  @ActionID_e230cc17 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_e230cc17 = N'Name'
SET
  @Type_e230cc17 = N'Output'
SET
  @ValueType_e230cc17 = N'Scalar'
SET
  @IsArray_e230cc17 = 0
SET
  @Description_e230cc17 = N'File name from GetMetadata operation'
SET
  @IsRequired_e230cc17 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_e230cc17,
  @ActionID = @ActionID_e230cc17,
  @Name = @Name_e230cc17,
  @DefaultValue = @DefaultValue_e230cc17,
  @Type = @Type_e230cc17,
  @ValueType = @ValueType_e230cc17,
  @IsArray = @IsArray_e230cc17,
  @Description = @Description_e230cc17,
  @IsRequired = @IsRequired_e230cc17;

-- Save Action Params (core SP call only)
DECLARE @ID_6bc18a14 UNIQUEIDENTIFIER,
@ActionID_6bc18a14 UNIQUEIDENTIFIER,
@Name_6bc18a14 NVARCHAR(255),
@DefaultValue_6bc18a14 NVARCHAR(MAX),
@Type_6bc18a14 NCHAR(10),
@ValueType_6bc18a14 NVARCHAR(30),
@IsArray_6bc18a14 BIT,
@Description_6bc18a14 NVARCHAR(MAX),
@IsRequired_6bc18a14 BIT
SET
  @ID_6bc18a14 = 'd5b942a0-9f41-4ffa-8a58-b6dbdfa97b86'
SET
  @ActionID_6bc18a14 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_6bc18a14 = N'FullPath'
SET
  @Type_6bc18a14 = N'Output'
SET
  @ValueType_6bc18a14 = N'Scalar'
SET
  @IsArray_6bc18a14 = 0
SET
  @Description_6bc18a14 = N'Full path from GetMetadata operation'
SET
  @IsRequired_6bc18a14 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_6bc18a14,
  @ActionID = @ActionID_6bc18a14,
  @Name = @Name_6bc18a14,
  @DefaultValue = @DefaultValue_6bc18a14,
  @Type = @Type_6bc18a14,
  @ValueType = @ValueType_6bc18a14,
  @IsArray = @IsArray_6bc18a14,
  @Description = @Description_6bc18a14,
  @IsRequired = @IsRequired_6bc18a14;

-- Save Action Params (core SP call only)
DECLARE @ID_3679dd9d UNIQUEIDENTIFIER,
@ActionID_3679dd9d UNIQUEIDENTIFIER,
@Name_3679dd9d NVARCHAR(255),
@DefaultValue_3679dd9d NVARCHAR(MAX),
@Type_3679dd9d NCHAR(10),
@ValueType_3679dd9d NVARCHAR(30),
@IsArray_3679dd9d BIT,
@Description_3679dd9d NVARCHAR(MAX),
@IsRequired_3679dd9d BIT
SET
  @ID_3679dd9d = '33ce6e85-9814-434e-a913-b345e7ae720c'
SET
  @ActionID_3679dd9d = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_3679dd9d = N'Size'
SET
  @Type_3679dd9d = N'Output'
SET
  @ValueType_3679dd9d = N'Scalar'
SET
  @IsArray_3679dd9d = 0
SET
  @Description_3679dd9d = N'File size in bytes from GetMetadata or GetObject operations'
SET
  @IsRequired_3679dd9d = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_3679dd9d,
  @ActionID = @ActionID_3679dd9d,
  @Name = @Name_3679dd9d,
  @DefaultValue = @DefaultValue_3679dd9d,
  @Type = @Type_3679dd9d,
  @ValueType = @ValueType_3679dd9d,
  @IsArray = @IsArray_3679dd9d,
  @Description = @Description_3679dd9d,
  @IsRequired = @IsRequired_3679dd9d;

-- Save Action Params (core SP call only)
DECLARE @ID_2998e578 UNIQUEIDENTIFIER,
@ActionID_2998e578 UNIQUEIDENTIFIER,
@Name_2998e578 NVARCHAR(255),
@DefaultValue_2998e578 NVARCHAR(MAX),
@Type_2998e578 NCHAR(10),
@ValueType_2998e578 NVARCHAR(30),
@IsArray_2998e578 BIT,
@Description_2998e578 NVARCHAR(MAX),
@IsRequired_2998e578 BIT
SET
  @ID_2998e578 = '5f09e32a-367c-46c4-9139-d809e83813e0'
SET
  @ActionID_2998e578 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_2998e578 = N'ContentType'
SET
  @Type_2998e578 = N'Output'
SET
  @ValueType_2998e578 = N'Scalar'
SET
  @IsArray_2998e578 = 0
SET
  @Description_2998e578 = N'Content MIME type from GetMetadata operation'
SET
  @IsRequired_2998e578 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_2998e578,
  @ActionID = @ActionID_2998e578,
  @Name = @Name_2998e578,
  @DefaultValue = @DefaultValue_2998e578,
  @Type = @Type_2998e578,
  @ValueType = @ValueType_2998e578,
  @IsArray = @IsArray_2998e578,
  @Description = @Description_2998e578,
  @IsRequired = @IsRequired_2998e578;

-- Save Action Params (core SP call only)
DECLARE @ID_7c3ad9cc UNIQUEIDENTIFIER,
@ActionID_7c3ad9cc UNIQUEIDENTIFIER,
@Name_7c3ad9cc NVARCHAR(255),
@DefaultValue_7c3ad9cc NVARCHAR(MAX),
@Type_7c3ad9cc NCHAR(10),
@ValueType_7c3ad9cc NVARCHAR(30),
@IsArray_7c3ad9cc BIT,
@Description_7c3ad9cc NVARCHAR(MAX),
@IsRequired_7c3ad9cc BIT
SET
  @ID_7c3ad9cc = '719017a9-5211-4b42-829a-2b94d38eda22'
SET
  @ActionID_7c3ad9cc = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_7c3ad9cc = N'LastModified'
SET
  @Type_7c3ad9cc = N'Output'
SET
  @ValueType_7c3ad9cc = N'Scalar'
SET
  @IsArray_7c3ad9cc = 0
SET
  @Description_7c3ad9cc = N'Last modified timestamp from GetMetadata operation'
SET
  @IsRequired_7c3ad9cc = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_7c3ad9cc,
  @ActionID = @ActionID_7c3ad9cc,
  @Name = @Name_7c3ad9cc,
  @DefaultValue = @DefaultValue_7c3ad9cc,
  @Type = @Type_7c3ad9cc,
  @ValueType = @ValueType_7c3ad9cc,
  @IsArray = @IsArray_7c3ad9cc,
  @Description = @Description_7c3ad9cc,
  @IsRequired = @IsRequired_7c3ad9cc;

-- Save Action Params (core SP call only)
DECLARE @ID_89901ec2 UNIQUEIDENTIFIER,
@ActionID_89901ec2 UNIQUEIDENTIFIER,
@Name_89901ec2 NVARCHAR(255),
@DefaultValue_89901ec2 NVARCHAR(MAX),
@Type_89901ec2 NCHAR(10),
@ValueType_89901ec2 NVARCHAR(30),
@IsArray_89901ec2 BIT,
@Description_89901ec2 NVARCHAR(MAX),
@IsRequired_89901ec2 BIT
SET
  @ID_89901ec2 = '47035822-38b8-468e-bc55-065bf3b7aa9e'
SET
  @ActionID_89901ec2 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_89901ec2 = N'IsDirectory'
SET
  @Type_89901ec2 = N'Output'
SET
  @ValueType_89901ec2 = N'Scalar'
SET
  @IsArray_89901ec2 = 0
SET
  @Description_89901ec2 = N'Boolean indicating if object is a directory from GetMetadata operation'
SET
  @IsRequired_89901ec2 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_89901ec2,
  @ActionID = @ActionID_89901ec2,
  @Name = @Name_89901ec2,
  @DefaultValue = @DefaultValue_89901ec2,
  @Type = @Type_89901ec2,
  @ValueType = @ValueType_89901ec2,
  @IsArray = @IsArray_89901ec2,
  @Description = @Description_89901ec2,
  @IsRequired = @IsRequired_89901ec2;

-- Save Action Params (core SP call only)
DECLARE @ID_fc6c37aa UNIQUEIDENTIFIER,
@ActionID_fc6c37aa UNIQUEIDENTIFIER,
@Name_fc6c37aa NVARCHAR(255),
@DefaultValue_fc6c37aa NVARCHAR(MAX),
@Type_fc6c37aa NCHAR(10),
@ValueType_fc6c37aa NVARCHAR(30),
@IsArray_fc6c37aa BIT,
@Description_fc6c37aa NVARCHAR(MAX),
@IsRequired_fc6c37aa BIT
SET
  @ID_fc6c37aa = '5484adf1-47da-4e69-81a5-67add4e365d9'
SET
  @ActionID_fc6c37aa = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_fc6c37aa = N'ETag'
SET
  @Type_fc6c37aa = N'Output'
SET
  @ValueType_fc6c37aa = N'Scalar'
SET
  @IsArray_fc6c37aa = 0
SET
  @Description_fc6c37aa = N'Entity tag from GetMetadata operation (if available)'
SET
  @IsRequired_fc6c37aa = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_fc6c37aa,
  @ActionID = @ActionID_fc6c37aa,
  @Name = @Name_fc6c37aa,
  @DefaultValue = @DefaultValue_fc6c37aa,
  @Type = @Type_fc6c37aa,
  @ValueType = @ValueType_fc6c37aa,
  @IsArray = @IsArray_fc6c37aa,
  @Description = @Description_fc6c37aa,
  @IsRequired = @IsRequired_fc6c37aa;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_e6e80908 UNIQUEIDENTIFIER,
@ActionID_e6e80908 UNIQUEIDENTIFIER,
@ResultCode_e6e80908 NVARCHAR(255),
@IsSuccess_e6e80908 BIT,
@Description_e6e80908 NVARCHAR(MAX)
SET
  @ID_e6e80908 = 'f3d8f60b-a036-4cb4-852e-6e5d0c94c4fe'
SET
  @ActionID_e6e80908 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_e6e80908 = N'SUCCESS'
SET
  @IsSuccess_e6e80908 = 1
SET
  @Description_e6e80908 = N'Operation completed successfully'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_e6e80908,
  @ActionID = @ActionID_e6e80908,
  @ResultCode = @ResultCode_e6e80908,
  @IsSuccess = @IsSuccess_e6e80908,
  @Description = @Description_e6e80908;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_555ee3ac UNIQUEIDENTIFIER,
@ActionID_555ee3ac UNIQUEIDENTIFIER,
@ResultCode_555ee3ac NVARCHAR(255),
@IsSuccess_555ee3ac BIT,
@Description_555ee3ac NVARCHAR(MAX)
SET
  @ID_555ee3ac = 'b735f41d-166a-4007-b074-1107b47ed707'
SET
  @ActionID_555ee3ac = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_555ee3ac = N'MISSING_OPERATION'
SET
  @IsSuccess_555ee3ac = 0
SET
  @Description_555ee3ac = N'Operation parameter is required'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_555ee3ac,
  @ActionID = @ActionID_555ee3ac,
  @ResultCode = @ResultCode_555ee3ac,
  @IsSuccess = @IsSuccess_555ee3ac,
  @Description = @Description_555ee3ac;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_2ff944e3 UNIQUEIDENTIFIER,
@ActionID_2ff944e3 UNIQUEIDENTIFIER,
@ResultCode_2ff944e3 NVARCHAR(255),
@IsSuccess_2ff944e3 BIT,
@Description_2ff944e3 NVARCHAR(MAX)
SET
  @ID_2ff944e3 = '2f91c94c-e71f-4541-b66c-87ca1943fd09'
SET
  @ActionID_2ff944e3 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_2ff944e3 = N'MISSING_PROVIDER'
SET
  @IsSuccess_2ff944e3 = 0
SET
  @Description_2ff944e3 = N'StorageProvider parameter is required'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_2ff944e3,
  @ActionID = @ActionID_2ff944e3,
  @ResultCode = @ResultCode_2ff944e3,
  @IsSuccess = @IsSuccess_2ff944e3,
  @Description = @Description_2ff944e3;

-- Save Action Params (core SP call only)
DECLARE @ID_22f86269 UNIQUEIDENTIFIER,
@ActionID_22f86269 UNIQUEIDENTIFIER,
@Name_22f86269 NVARCHAR(255),
@DefaultValue_22f86269 NVARCHAR(MAX),
@Type_22f86269 NCHAR(10),
@ValueType_22f86269 NVARCHAR(30),
@IsArray_22f86269 BIT,
@Description_22f86269 NVARCHAR(MAX),
@IsRequired_22f86269 BIT
SET
  @ID_22f86269 = '406a1e53-0b8d-4aa5-a971-34800ef5d797'
SET
  @ActionID_22f86269 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_22f86269 = N'CustomMetadata'
SET
  @Type_22f86269 = N'Output'
SET
  @ValueType_22f86269 = N'Simple Object'
SET
  @IsArray_22f86269 = 0
SET
  @Description_22f86269 = N'Custom metadata key-value pairs from GetMetadata operation (if available)'
SET
  @IsRequired_22f86269 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_22f86269,
  @ActionID = @ActionID_22f86269,
  @Name = @Name_22f86269,
  @DefaultValue = @DefaultValue_22f86269,
  @Type = @Type_22f86269,
  @ValueType = @ValueType_22f86269,
  @IsArray = @IsArray_22f86269,
  @Description = @Description_22f86269,
  @IsRequired = @IsRequired_22f86269;

-- Save Action Params (core SP call only)
DECLARE @ID_3acd88a1 UNIQUEIDENTIFIER,
@ActionID_3acd88a1 UNIQUEIDENTIFIER,
@Name_3acd88a1 NVARCHAR(255),
@DefaultValue_3acd88a1 NVARCHAR(MAX),
@Type_3acd88a1 NCHAR(10),
@ValueType_3acd88a1 NVARCHAR(30),
@IsArray_3acd88a1 BIT,
@Description_3acd88a1 NVARCHAR(MAX),
@IsRequired_3acd88a1 BIT
SET
  @ID_3acd88a1 = '69b0b335-7066-4b4a-9d8a-a866e45dd12a'
SET
  @ActionID_3acd88a1 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_3acd88a1 = N'Content'
SET
  @Type_3acd88a1 = N'Output'
SET
  @ValueType_3acd88a1 = N'Scalar'
SET
  @IsArray_3acd88a1 = 0
SET
  @Description_3acd88a1 = N'Base64-encoded file content from GetObject operation'
SET
  @IsRequired_3acd88a1 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_3acd88a1,
  @ActionID = @ActionID_3acd88a1,
  @Name = @Name_3acd88a1,
  @DefaultValue = @DefaultValue_3acd88a1,
  @Type = @Type_3acd88a1,
  @ValueType = @ValueType_3acd88a1,
  @IsArray = @IsArray_3acd88a1,
  @Description = @Description_3acd88a1,
  @IsRequired = @IsRequired_3acd88a1;

-- Save Action Params (core SP call only)
DECLARE @ID_a72c5f6f UNIQUEIDENTIFIER,
@ActionID_a72c5f6f UNIQUEIDENTIFIER,
@Name_a72c5f6f NVARCHAR(255),
@DefaultValue_a72c5f6f NVARCHAR(MAX),
@Type_a72c5f6f NCHAR(10),
@ValueType_a72c5f6f NVARCHAR(30),
@IsArray_a72c5f6f BIT,
@Description_a72c5f6f NVARCHAR(MAX),
@IsRequired_a72c5f6f BIT
SET
  @ID_a72c5f6f = '116729b5-5b83-4c23-930c-f07e0c1932ca'
SET
  @ActionID_a72c5f6f = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_a72c5f6f = N'DownloadUrl'
SET
  @Type_a72c5f6f = N'Output'
SET
  @ValueType_a72c5f6f = N'Scalar'
SET
  @IsArray_a72c5f6f = 0
SET
  @Description_a72c5f6f = N'Pre-authenticated download URL from GetDownloadUrl operation'
SET
  @IsRequired_a72c5f6f = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_a72c5f6f,
  @ActionID = @ActionID_a72c5f6f,
  @Name = @Name_a72c5f6f,
  @DefaultValue = @DefaultValue_a72c5f6f,
  @Type = @Type_a72c5f6f,
  @ValueType = @ValueType_a72c5f6f,
  @IsArray = @IsArray_a72c5f6f,
  @Description = @Description_a72c5f6f,
  @IsRequired = @IsRequired_a72c5f6f;

-- Save Action Params (core SP call only)
DECLARE @ID_c707d07b UNIQUEIDENTIFIER,
@ActionID_c707d07b UNIQUEIDENTIFIER,
@Name_c707d07b NVARCHAR(255),
@DefaultValue_c707d07b NVARCHAR(MAX),
@Type_c707d07b NCHAR(10),
@ValueType_c707d07b NVARCHAR(30),
@IsArray_c707d07b BIT,
@Description_c707d07b NVARCHAR(MAX),
@IsRequired_c707d07b BIT
SET
  @ID_c707d07b = '36ac27fc-3ae8-4dcb-ac52-30d1d3f7996c'
SET
  @ActionID_c707d07b = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_c707d07b = N'UploadUrl'
SET
  @Type_c707d07b = N'Output'
SET
  @ValueType_c707d07b = N'Scalar'
SET
  @IsArray_c707d07b = 0
SET
  @Description_c707d07b = N'Pre-authenticated upload URL from GetUploadUrl operation'
SET
  @IsRequired_c707d07b = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_c707d07b,
  @ActionID = @ActionID_c707d07b,
  @Name = @Name_c707d07b,
  @DefaultValue = @DefaultValue_c707d07b,
  @Type = @Type_c707d07b,
  @ValueType = @ValueType_c707d07b,
  @IsArray = @IsArray_c707d07b,
  @Description = @Description_c707d07b,
  @IsRequired = @IsRequired_c707d07b;

-- Save Action Params (core SP call only)
DECLARE @ID_ce9a8a48 UNIQUEIDENTIFIER,
@ActionID_ce9a8a48 UNIQUEIDENTIFIER,
@Name_ce9a8a48 NVARCHAR(255),
@DefaultValue_ce9a8a48 NVARCHAR(MAX),
@Type_ce9a8a48 NCHAR(10),
@ValueType_ce9a8a48 NVARCHAR(30),
@IsArray_ce9a8a48 BIT,
@Description_ce9a8a48 NVARCHAR(MAX),
@IsRequired_ce9a8a48 BIT
SET
  @ID_ce9a8a48 = '32a95595-5a68-45c6-9d11-c158a3d05653'
SET
  @ActionID_ce9a8a48 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_ce9a8a48 = N'ProviderKey'
SET
  @Type_ce9a8a48 = N'Output'
SET
  @ValueType_ce9a8a48 = N'Scalar'
SET
  @IsArray_ce9a8a48 = 0
SET
  @Description_ce9a8a48 = N'Provider-specific key from GetUploadUrl operation (if returned by provider)'
SET
  @IsRequired_ce9a8a48 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_ce9a8a48,
  @ActionID = @ActionID_ce9a8a48,
  @Name = @Name_ce9a8a48,
  @DefaultValue = @DefaultValue_ce9a8a48,
  @Type = @Type_ce9a8a48,
  @ValueType = @ValueType_ce9a8a48,
  @IsArray = @IsArray_ce9a8a48,
  @Description = @Description_ce9a8a48,
  @IsRequired = @IsRequired_ce9a8a48;

-- Save Action Params (core SP call only)
DECLARE @ID_d575d5cc UNIQUEIDENTIFIER,
@ActionID_d575d5cc UNIQUEIDENTIFIER,
@Name_d575d5cc NVARCHAR(255),
@DefaultValue_d575d5cc NVARCHAR(MAX),
@Type_d575d5cc NCHAR(10),
@ValueType_d575d5cc NVARCHAR(30),
@IsArray_d575d5cc BIT,
@Description_d575d5cc NVARCHAR(MAX),
@IsRequired_d575d5cc BIT
SET
  @ID_d575d5cc = '355f4125-e27f-4e56-95ba-2e1d7d834da7'
SET
  @ActionID_d575d5cc = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_d575d5cc = N'Exists'
SET
  @Type_d575d5cc = N'Output'
SET
  @ValueType_d575d5cc = N'Scalar'
SET
  @IsArray_d575d5cc = 0
SET
  @Description_d575d5cc = N'Boolean indicating if object or directory exists from ObjectExists or DirectoryExists operations'
SET
  @IsRequired_d575d5cc = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_d575d5cc,
  @ActionID = @ActionID_d575d5cc,
  @Name = @Name_d575d5cc,
  @DefaultValue = @DefaultValue_d575d5cc,
  @Type = @Type_d575d5cc,
  @ValueType = @ValueType_d575d5cc,
  @IsArray = @IsArray_d575d5cc,
  @Description = @Description_d575d5cc,
  @IsRequired = @IsRequired_d575d5cc;

-- Save Action Params (core SP call only)
DECLARE @ID_4d5a1e11 UNIQUEIDENTIFIER,
@ActionID_4d5a1e11 UNIQUEIDENTIFIER,
@Name_4d5a1e11 NVARCHAR(255),
@DefaultValue_4d5a1e11 NVARCHAR(MAX),
@Type_4d5a1e11 NCHAR(10),
@ValueType_4d5a1e11 NVARCHAR(30),
@IsArray_4d5a1e11 BIT,
@Description_4d5a1e11 NVARCHAR(MAX),
@IsRequired_4d5a1e11 BIT
SET
  @ID_4d5a1e11 = 'd0e20c2e-11b6-421f-88c5-62b181a75cf6'
SET
  @ActionID_4d5a1e11 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @Name_4d5a1e11 = N'Success'
SET
  @Type_4d5a1e11 = N'Output'
SET
  @ValueType_4d5a1e11 = N'Scalar'
SET
  @IsArray_4d5a1e11 = 0
SET
  @Description_4d5a1e11 = N'Boolean indicating success of CopyObject, MoveObject, DeleteObject, CreateDirectory, or DeleteDirectory operations'
SET
  @IsRequired_4d5a1e11 = 0
EXEC [${flyway:defaultSchema}].spCreateActionParam @ID = @ID_4d5a1e11,
  @ActionID = @ActionID_4d5a1e11,
  @Name = @Name_4d5a1e11,
  @DefaultValue = @DefaultValue_4d5a1e11,
  @Type = @Type_4d5a1e11,
  @ValueType = @ValueType_4d5a1e11,
  @IsArray = @IsArray_4d5a1e11,
  @Description = @Description_4d5a1e11,
  @IsRequired = @IsRequired_4d5a1e11;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_e39eccf6 UNIQUEIDENTIFIER,
@ActionID_e39eccf6 UNIQUEIDENTIFIER,
@ResultCode_e39eccf6 NVARCHAR(255),
@IsSuccess_e39eccf6 BIT,
@Description_e39eccf6 NVARCHAR(MAX)
SET
  @ID_e39eccf6 = 'bb703e53-e159-466d-a13a-e990af3d2120'
SET
  @ActionID_e39eccf6 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_e39eccf6 = N'PROVIDER_NOT_FOUND'
SET
  @IsSuccess_e39eccf6 = 0
SET
  @Description_e39eccf6 = N'Specified storage provider not found'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_e39eccf6,
  @ActionID = @ActionID_e39eccf6,
  @ResultCode = @ResultCode_e39eccf6,
  @IsSuccess = @IsSuccess_e39eccf6,
  @Description = @Description_e39eccf6;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_a866f033 UNIQUEIDENTIFIER,
@ActionID_a866f033 UNIQUEIDENTIFIER,
@ResultCode_a866f033 NVARCHAR(255),
@IsSuccess_a866f033 BIT,
@Description_a866f033 NVARCHAR(MAX)
SET
  @ID_a866f033 = 'a84a4830-b191-4e34-bd28-745800bd2eb7'
SET
  @ActionID_a866f033 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_a866f033 = N'INVALID_OPERATION'
SET
  @IsSuccess_a866f033 = 0
SET
  @Description_a866f033 = N'Unknown or invalid operation specified'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_a866f033,
  @ActionID = @ActionID_a866f033,
  @ResultCode = @ResultCode_a866f033,
  @IsSuccess = @IsSuccess_a866f033,
  @Description = @Description_a866f033;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_84e61928 UNIQUEIDENTIFIER,
@ActionID_84e61928 UNIQUEIDENTIFIER,
@ResultCode_84e61928 NVARCHAR(255),
@IsSuccess_84e61928 BIT,
@Description_84e61928 NVARCHAR(MAX)
SET
  @ID_84e61928 = 'f26db5ce-8ecf-4a21-af9d-a736ef014323'
SET
  @ActionID_84e61928 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_84e61928 = N'MISSING_OBJECTNAME'
SET
  @IsSuccess_84e61928 = 0
SET
  @Description_84e61928 = N'ObjectName parameter is required for this operation'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_84e61928,
  @ActionID = @ActionID_84e61928,
  @ResultCode = @ResultCode_84e61928,
  @IsSuccess = @IsSuccess_84e61928,
  @Description = @Description_84e61928;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_b2dd8071 UNIQUEIDENTIFIER,
@ActionID_b2dd8071 UNIQUEIDENTIFIER,
@ResultCode_b2dd8071 NVARCHAR(255),
@IsSuccess_b2dd8071 BIT,
@Description_b2dd8071 NVARCHAR(MAX)
SET
  @ID_b2dd8071 = '5cc97c27-0bef-40f7-88de-d88912d525cc'
SET
  @ActionID_b2dd8071 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_b2dd8071 = N'MISSING_DIRECTORYPATH'
SET
  @IsSuccess_b2dd8071 = 0
SET
  @Description_b2dd8071 = N'DirectoryPath parameter is required for this operation'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_b2dd8071,
  @ActionID = @ActionID_b2dd8071,
  @ResultCode = @ResultCode_b2dd8071,
  @IsSuccess = @IsSuccess_b2dd8071,
  @Description = @Description_b2dd8071;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_6a5dd434 UNIQUEIDENTIFIER,
@ActionID_6a5dd434 UNIQUEIDENTIFIER,
@ResultCode_6a5dd434 NVARCHAR(255),
@IsSuccess_6a5dd434 BIT,
@Description_6a5dd434 NVARCHAR(MAX)
SET
  @ID_6a5dd434 = '082264a7-4335-4c45-bc05-c6424b6eaa25'
SET
  @ActionID_6a5dd434 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_6a5dd434 = N'MISSING_SOURCE'
SET
  @IsSuccess_6a5dd434 = 0
SET
  @Description_6a5dd434 = N'SourceObjectName parameter is required for this operation'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_6a5dd434,
  @ActionID = @ActionID_6a5dd434,
  @ResultCode = @ResultCode_6a5dd434,
  @IsSuccess = @IsSuccess_6a5dd434,
  @Description = @Description_6a5dd434;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_6eff100a UNIQUEIDENTIFIER,
@ActionID_6eff100a UNIQUEIDENTIFIER,
@ResultCode_6eff100a NVARCHAR(255),
@IsSuccess_6eff100a BIT,
@Description_6eff100a NVARCHAR(MAX)
SET
  @ID_6eff100a = 'a9c8806f-ef73-485d-978a-f5f03e3a0909'
SET
  @ActionID_6eff100a = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_6eff100a = N'MISSING_DESTINATION'
SET
  @IsSuccess_6eff100a = 0
SET
  @Description_6eff100a = N'DestinationObjectName parameter is required for this operation'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_6eff100a,
  @ActionID = @ActionID_6eff100a,
  @ResultCode = @ResultCode_6eff100a,
  @IsSuccess = @IsSuccess_6eff100a,
  @Description = @Description_6eff100a;

-- Save Action Result Codes (core SP call only)
DECLARE @ID_f0e57382 UNIQUEIDENTIFIER,
@ActionID_f0e57382 UNIQUEIDENTIFIER,
@ResultCode_f0e57382 NVARCHAR(255),
@IsSuccess_f0e57382 BIT,
@Description_f0e57382 NVARCHAR(MAX)
SET
  @ID_f0e57382 = '115100c5-a26a-4ce0-96c0-4f77c616525e'
SET
  @ActionID_f0e57382 = '77D34B5A-F636-49E1-A20B-6446502BD65E'
SET
  @ResultCode_f0e57382 = N'OPERATION_FAILED'
SET
  @IsSuccess_f0e57382 = 0
SET
  @Description_f0e57382 = N'File storage operation failed'
EXEC [${flyway:defaultSchema}].spCreateActionResultCode @ID = @ID_f0e57382,
  @ActionID = @ActionID_f0e57382,
  @ResultCode = @ResultCode_f0e57382,
  @IsSuccess = @IsSuccess_f0e57382,
  @Description = @Description_f0e57382;

-- End of SQL Logging Session
-- Session ID: 16fea9ba-a70b-4d71-abb0-9d0b974f70b5
-- Completed: 2025-09-29T21:29:26.816Z
-- Duration: 7702ms
-- Total Statements: 39
