-- indexes here are custom, not fkey generations

CREATE INDEX IX_EntityField_Name
ON ${flyway:defaultSchema}.EntityField (Name);

-- Index on Name
CREATE INDEX IX_Entity_Name
ON ${flyway:defaultSchema}.Entity (Name);

-- Index on BaseTable
CREATE INDEX IX_Entity_BaseTable
ON ${flyway:defaultSchema}.Entity (BaseTable);

-- Index on BaseView
CREATE INDEX IX_Entity_BaseView
ON ${flyway:defaultSchema}.Entity (BaseView);

-- Index on SchemaName
CREATE INDEX IX_Entity_SchemaName
ON ${flyway:defaultSchema}.Entity (SchemaName);

CREATE INDEX IX_Entity_Name_BaseTable_SchemaName
ON ${flyway:defaultSchema}.Entity (Name, BaseTable, SchemaName);

CREATE INDEX IX_Entity_ID_SchemaName_BaseTable
ON [${flyway:defaultSchema}].Entity (ID, SchemaName, BaseTable);

CREATE INDEX IX_EntityField_EntityID_Name
ON [${flyway:defaultSchema}].EntityField (EntityID, Name);


 

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Actions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Action].IX_Action_CategoryID;
CREATE INDEX IX_Action_CategoryID ON [${flyway:defaultSchema}].[Action] ([CategoryID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Action].IX_Action_CodeApprovedByUserID;
CREATE INDEX IX_Action_CodeApprovedByUserID ON [${flyway:defaultSchema}].[Action] ([CodeApprovedByUserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Authorizations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionAuthorization].IX_ActionAuthorization_ActionID;
CREATE INDEX IX_ActionAuthorization_ActionID ON [${flyway:defaultSchema}].[ActionAuthorization] ([ActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionAuthorization].IX_ActionAuthorization_AuthorizationID;
CREATE INDEX IX_ActionAuthorization_AuthorizationID ON [${flyway:defaultSchema}].[ActionAuthorization] ([AuthorizationID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Categories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionCategory].IX_ActionCategory_ParentID;
CREATE INDEX IX_ActionCategory_ParentID ON [${flyway:defaultSchema}].[ActionCategory] ([ParentID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Contexts
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionContext].IX_ActionContext_ActionID;
CREATE INDEX IX_ActionContext_ActionID ON [${flyway:defaultSchema}].[ActionContext] ([ActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionContext].IX_ActionContext_ContextTypeID;
CREATE INDEX IX_ActionContext_ContextTypeID ON [${flyway:defaultSchema}].[ActionContext] ([ContextTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Context Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Execution Logs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionExecutionLog].IX_ActionExecutionLog_ActionID;
CREATE INDEX IX_ActionExecutionLog_ActionID ON [${flyway:defaultSchema}].[ActionExecutionLog] ([ActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionExecutionLog].IX_ActionExecutionLog_UserID;
CREATE INDEX IX_ActionExecutionLog_UserID ON [${flyway:defaultSchema}].[ActionExecutionLog] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Filters
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Libraries
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionLibrary].IX_ActionLibrary_ActionID;
CREATE INDEX IX_ActionLibrary_ActionID ON [${flyway:defaultSchema}].[ActionLibrary] ([ActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionLibrary].IX_ActionLibrary_LibraryID;
CREATE INDEX IX_ActionLibrary_LibraryID ON [${flyway:defaultSchema}].[ActionLibrary] ([LibraryID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Params
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionParam].IX_ActionParam_ActionID;
CREATE INDEX IX_ActionParam_ActionID ON [${flyway:defaultSchema}].[ActionParam] ([ActionID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Action Result Codes
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ActionResultCode].IX_ActionResultCode_ActionID;
CREATE INDEX IX_ActionResultCode_ActionID ON [${flyway:defaultSchema}].[ActionResultCode] ([ActionID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: AI Actions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIAction].IX_AIAction_DefaultModelID;
CREATE INDEX IX_AIAction_DefaultModelID ON [${flyway:defaultSchema}].[AIAction] ([DefaultModelID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: AI Models
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIModel].IX_AIModel_AIModelTypeID;
CREATE INDEX IX_AIModel_AIModelTypeID ON [${flyway:defaultSchema}].[AIModel] ([AIModelTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: AI Model Actions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIModelAction].IX_AIModelAction_AIModelID;
CREATE INDEX IX_AIModelAction_AIModelID ON [${flyway:defaultSchema}].[AIModelAction] ([AIModelID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIModelAction].IX_AIModelAction_AIActionID;
CREATE INDEX IX_AIModelAction_AIActionID ON [${flyway:defaultSchema}].[AIModelAction] ([AIActionID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: AI Model Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: AI Prompts
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIPrompt].IX_AIPrompt_TemplateID;
CREATE INDEX IX_AIPrompt_TemplateID ON [${flyway:defaultSchema}].[AIPrompt] ([TemplateID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIPrompt].IX_AIPrompt_CategoryID;
CREATE INDEX IX_AIPrompt_CategoryID ON [${flyway:defaultSchema}].[AIPrompt] ([CategoryID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIPrompt].IX_AIPrompt_TypeID;
CREATE INDEX IX_AIPrompt_TypeID ON [${flyway:defaultSchema}].[AIPrompt] ([TypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: AI Prompt Categories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIPromptCategory].IX_AIPromptCategory_ParentID;
CREATE INDEX IX_AIPromptCategory_ParentID ON [${flyway:defaultSchema}].[AIPromptCategory] ([ParentID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: AI Prompt Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: AI Result Cache
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIResultCache].IX_AIResultCache_AIPromptID;
CREATE INDEX IX_AIResultCache_AIPromptID ON [${flyway:defaultSchema}].[AIResultCache] ([AIPromptID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AIResultCache].IX_AIResultCache_AIModelID;
CREATE INDEX IX_AIResultCache_AIModelID ON [${flyway:defaultSchema}].[AIResultCache] ([AIModelID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Applications
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Application Entities
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ApplicationEntity].IX_ApplicationEntity_ApplicationID;
CREATE INDEX IX_ApplicationEntity_ApplicationID ON [${flyway:defaultSchema}].[ApplicationEntity] ([ApplicationID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ApplicationEntity].IX_ApplicationEntity_EntityID;
CREATE INDEX IX_ApplicationEntity_EntityID ON [${flyway:defaultSchema}].[ApplicationEntity] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Application Settings
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ApplicationSetting].IX_ApplicationSetting_ApplicationID;
CREATE INDEX IX_ApplicationSetting_ApplicationID ON [${flyway:defaultSchema}].[ApplicationSetting] ([ApplicationID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Audit Logs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AuditLog].IX_AuditLog_UserID;
CREATE INDEX IX_AuditLog_UserID ON [${flyway:defaultSchema}].[AuditLog] ([UserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AuditLog].IX_AuditLog_AuditLogTypeID;
CREATE INDEX IX_AuditLog_AuditLogTypeID ON [${flyway:defaultSchema}].[AuditLog] ([AuditLogTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AuditLog].IX_AuditLog_AuthorizationID;
CREATE INDEX IX_AuditLog_AuthorizationID ON [${flyway:defaultSchema}].[AuditLog] ([AuthorizationID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AuditLog].IX_AuditLog_EntityID;
CREATE INDEX IX_AuditLog_EntityID ON [${flyway:defaultSchema}].[AuditLog] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Audit Log Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AuditLogType].IX_AuditLogType_ParentID;
CREATE INDEX IX_AuditLogType_ParentID ON [${flyway:defaultSchema}].[AuditLogType] ([ParentID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AuditLogType].IX_AuditLogType_AuthorizationID;
CREATE INDEX IX_AuditLogType_AuthorizationID ON [${flyway:defaultSchema}].[AuditLogType] ([AuthorizationID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Authorizations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Authorization].IX_Authorization_ParentID;
CREATE INDEX IX_Authorization_ParentID ON [${flyway:defaultSchema}].[Authorization] ([ParentID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Authorization Roles
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AuthorizationRole].IX_AuthorizationRole_AuthorizationID;
CREATE INDEX IX_AuthorizationRole_AuthorizationID ON [${flyway:defaultSchema}].[AuthorizationRole] ([AuthorizationID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[AuthorizationRole].IX_AuthorizationRole_RoleID;
CREATE INDEX IX_AuthorizationRole_RoleID ON [${flyway:defaultSchema}].[AuthorizationRole] ([RoleID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Communication Base Message Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Communication Logs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CommunicationLog].IX_CommunicationLog_CommunicationProviderID;
CREATE INDEX IX_CommunicationLog_CommunicationProviderID ON [${flyway:defaultSchema}].[CommunicationLog] ([CommunicationProviderID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CommunicationLog].IX_CommunicationLog_CommunicationProviderMessageTypeID;
CREATE INDEX IX_CommunicationLog_CommunicationProviderMessageTypeID ON [${flyway:defaultSchema}].[CommunicationLog] ([CommunicationProviderMessageTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CommunicationLog].IX_CommunicationLog_CommunicationRunID;
CREATE INDEX IX_CommunicationLog_CommunicationRunID ON [${flyway:defaultSchema}].[CommunicationLog] ([CommunicationRunID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Communication Providers
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Communication Provider Message Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CommunicationProviderMessageType].IX_CommunicationProviderMessageType_CommunicationProviderID;
CREATE INDEX IX_CommunicationProviderMessageType_CommunicationProviderID ON [${flyway:defaultSchema}].[CommunicationProviderMessageType] ([CommunicationProviderID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CommunicationProviderMessageType].IX_CommunicationProviderMessageType_CommunicationBaseMessageTypeID;
CREATE INDEX IX_CommunicationProviderMessageType_CommunicationBaseMessageTypeID ON [${flyway:defaultSchema}].[CommunicationProviderMessageType] ([CommunicationBaseMessageTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Communication Runs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CommunicationRun].IX_CommunicationRun_UserID;
CREATE INDEX IX_CommunicationRun_UserID ON [${flyway:defaultSchema}].[CommunicationRun] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Companies
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Company Integrations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegration].IX_CompanyIntegration_CompanyID;
CREATE INDEX IX_CompanyIntegration_CompanyID ON [${flyway:defaultSchema}].[CompanyIntegration] ([CompanyID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegration].IX_CompanyIntegration_IntegrationID;
CREATE INDEX IX_CompanyIntegration_IntegrationID ON [${flyway:defaultSchema}].[CompanyIntegration] ([IntegrationID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Company Integration Record Maps
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegrationRecordMap].IX_CompanyIntegrationRecordMap_CompanyIntegrationID;
CREATE INDEX IX_CompanyIntegrationRecordMap_CompanyIntegrationID ON [${flyway:defaultSchema}].[CompanyIntegrationRecordMap] ([CompanyIntegrationID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegrationRecordMap].IX_CompanyIntegrationRecordMap_EntityID;
CREATE INDEX IX_CompanyIntegrationRecordMap_EntityID ON [${flyway:defaultSchema}].[CompanyIntegrationRecordMap] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Company Integration Runs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegrationRun].IX_CompanyIntegrationRun_CompanyIntegrationID;
CREATE INDEX IX_CompanyIntegrationRun_CompanyIntegrationID ON [${flyway:defaultSchema}].[CompanyIntegrationRun] ([CompanyIntegrationID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegrationRun].IX_CompanyIntegrationRun_RunByUserID;
CREATE INDEX IX_CompanyIntegrationRun_RunByUserID ON [${flyway:defaultSchema}].[CompanyIntegrationRun] ([RunByUserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Company Integration Run API Logs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegrationRunAPILog].IX_CompanyIntegrationRunAPILog_CompanyIntegrationRunID;
CREATE INDEX IX_CompanyIntegrationRunAPILog_CompanyIntegrationRunID ON [${flyway:defaultSchema}].[CompanyIntegrationRunAPILog] ([CompanyIntegrationRunID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Company Integration Run Details
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegrationRunDetail].IX_CompanyIntegrationRunDetail_CompanyIntegrationRunID;
CREATE INDEX IX_CompanyIntegrationRunDetail_CompanyIntegrationRunID ON [${flyway:defaultSchema}].[CompanyIntegrationRunDetail] ([CompanyIntegrationRunID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[CompanyIntegrationRunDetail].IX_CompanyIntegrationRunDetail_EntityID;
CREATE INDEX IX_CompanyIntegrationRunDetail_EntityID ON [${flyway:defaultSchema}].[CompanyIntegrationRunDetail] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content File Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Items
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentItem].IX_ContentItem_ContentSourceID;
CREATE INDEX IX_ContentItem_ContentSourceID ON [${flyway:defaultSchema}].[ContentItem] ([ContentSourceID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentItem].IX_ContentItem_ContentTypeID;
CREATE INDEX IX_ContentItem_ContentTypeID ON [${flyway:defaultSchema}].[ContentItem] ([ContentTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentItem].IX_ContentItem_ContentSourceTypeID;
CREATE INDEX IX_ContentItem_ContentSourceTypeID ON [${flyway:defaultSchema}].[ContentItem] ([ContentSourceTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentItem].IX_ContentItem_ContentFileTypeID;
CREATE INDEX IX_ContentItem_ContentFileTypeID ON [${flyway:defaultSchema}].[ContentItem] ([ContentFileTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Item Attributes
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentItemAttribute].IX_ContentItemAttribute_ContentItemID;
CREATE INDEX IX_ContentItemAttribute_ContentItemID ON [${flyway:defaultSchema}].[ContentItemAttribute] ([ContentItemID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Item Tags
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentItemTag].IX_ContentItemTag_ItemID;
CREATE INDEX IX_ContentItemTag_ItemID ON [${flyway:defaultSchema}].[ContentItemTag] ([ItemID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Process Runs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentProcessRun].IX_ContentProcessRun_SourceID;
CREATE INDEX IX_ContentProcessRun_SourceID ON [${flyway:defaultSchema}].[ContentProcessRun] ([SourceID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Sources
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentSource].IX_ContentSource_ContentTypeID;
CREATE INDEX IX_ContentSource_ContentTypeID ON [${flyway:defaultSchema}].[ContentSource] ([ContentTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentSource].IX_ContentSource_ContentSourceTypeID;
CREATE INDEX IX_ContentSource_ContentSourceTypeID ON [${flyway:defaultSchema}].[ContentSource] ([ContentSourceTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentSource].IX_ContentSource_ContentFileTypeID;
CREATE INDEX IX_ContentSource_ContentFileTypeID ON [${flyway:defaultSchema}].[ContentSource] ([ContentFileTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Source Params
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentSourceParam].IX_ContentSourceParam_ContentSourceID;
CREATE INDEX IX_ContentSourceParam_ContentSourceID ON [${flyway:defaultSchema}].[ContentSourceParam] ([ContentSourceID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Source Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Source Type Params
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ContentType].IX_ContentType_AIModelID;
CREATE INDEX IX_ContentType_AIModelID ON [${flyway:defaultSchema}].[ContentType] ([AIModelID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Content Type Attributes
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Conversations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Conversation].IX_Conversation_UserID;
CREATE INDEX IX_Conversation_UserID ON [${flyway:defaultSchema}].[Conversation] ([UserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Conversation].IX_Conversation_LinkedEntityID;
CREATE INDEX IX_Conversation_LinkedEntityID ON [${flyway:defaultSchema}].[Conversation] ([LinkedEntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Conversation].IX_Conversation_DataContextID;
CREATE INDEX IX_Conversation_DataContextID ON [${flyway:defaultSchema}].[Conversation] ([DataContextID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Conversation Details
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ConversationDetail].IX_ConversationDetail_ConversationID;
CREATE INDEX IX_ConversationDetail_ConversationID ON [${flyway:defaultSchema}].[ConversationDetail] ([ConversationID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Dashboards
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Dashboard].IX_Dashboard_UserID;
CREATE INDEX IX_Dashboard_UserID ON [${flyway:defaultSchema}].[Dashboard] ([UserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Dashboard].IX_Dashboard_CategoryID;
CREATE INDEX IX_Dashboard_CategoryID ON [${flyway:defaultSchema}].[Dashboard] ([CategoryID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Dashboard Categories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DashboardCategory].IX_DashboardCategory_ParentID;
CREATE INDEX IX_DashboardCategory_ParentID ON [${flyway:defaultSchema}].[DashboardCategory] ([ParentID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DashboardCategory].IX_DashboardCategory_UserID;
CREATE INDEX IX_DashboardCategory_UserID ON [${flyway:defaultSchema}].[DashboardCategory] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Data Contexts
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DataContext].IX_DataContext_UserID;
CREATE INDEX IX_DataContext_UserID ON [${flyway:defaultSchema}].[DataContext] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Data Context Items
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DataContextItem].IX_DataContextItem_DataContextID;
CREATE INDEX IX_DataContextItem_DataContextID ON [${flyway:defaultSchema}].[DataContextItem] ([DataContextID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DataContextItem].IX_DataContextItem_ViewID;
CREATE INDEX IX_DataContextItem_ViewID ON [${flyway:defaultSchema}].[DataContextItem] ([ViewID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DataContextItem].IX_DataContextItem_QueryID;
CREATE INDEX IX_DataContextItem_QueryID ON [${flyway:defaultSchema}].[DataContextItem] ([QueryID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DataContextItem].IX_DataContextItem_EntityID;
CREATE INDEX IX_DataContextItem_EntityID ON [${flyway:defaultSchema}].[DataContextItem] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Datasets
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Dataset Items
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DatasetItem].IX_DatasetItem_DatasetID;
CREATE INDEX IX_DatasetItem_DatasetID ON [${flyway:defaultSchema}].[DatasetItem] ([DatasetID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DatasetItem].IX_DatasetItem_EntityID;
CREATE INDEX IX_DatasetItem_EntityID ON [${flyway:defaultSchema}].[DatasetItem] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Duplicate Runs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DuplicateRun].IX_DuplicateRun_EntityID;
CREATE INDEX IX_DuplicateRun_EntityID ON [${flyway:defaultSchema}].[DuplicateRun] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DuplicateRun].IX_DuplicateRun_StartedByUserID;
CREATE INDEX IX_DuplicateRun_StartedByUserID ON [${flyway:defaultSchema}].[DuplicateRun] ([StartedByUserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DuplicateRun].IX_DuplicateRun_SourceListID;
CREATE INDEX IX_DuplicateRun_SourceListID ON [${flyway:defaultSchema}].[DuplicateRun] ([SourceListID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DuplicateRun].IX_DuplicateRun_ApprovedByUserID;
CREATE INDEX IX_DuplicateRun_ApprovedByUserID ON [${flyway:defaultSchema}].[DuplicateRun] ([ApprovedByUserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Duplicate Run Details
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DuplicateRunDetail].IX_DuplicateRunDetail_DuplicateRunID;
CREATE INDEX IX_DuplicateRunDetail_DuplicateRunID ON [${flyway:defaultSchema}].[DuplicateRunDetail] ([DuplicateRunID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Duplicate Run Detail Matches
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DuplicateRunDetailMatch].IX_DuplicateRunDetailMatch_DuplicateRunDetailID;
CREATE INDEX IX_DuplicateRunDetailMatch_DuplicateRunDetailID ON [${flyway:defaultSchema}].[DuplicateRunDetailMatch] ([DuplicateRunDetailID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[DuplicateRunDetailMatch].IX_DuplicateRunDetailMatch_RecordMergeLogID;
CREATE INDEX IX_DuplicateRunDetailMatch_RecordMergeLogID ON [${flyway:defaultSchema}].[DuplicateRunDetailMatch] ([RecordMergeLogID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Employees
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Employee].IX_Employee_CompanyID;
CREATE INDEX IX_Employee_CompanyID ON [${flyway:defaultSchema}].[Employee] ([CompanyID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Employee].IX_Employee_SupervisorID;
CREATE INDEX IX_Employee_SupervisorID ON [${flyway:defaultSchema}].[Employee] ([SupervisorID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Employee Company Integrations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EmployeeCompanyIntegration].IX_EmployeeCompanyIntegration_EmployeeID;
CREATE INDEX IX_EmployeeCompanyIntegration_EmployeeID ON [${flyway:defaultSchema}].[EmployeeCompanyIntegration] ([EmployeeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EmployeeCompanyIntegration].IX_EmployeeCompanyIntegration_CompanyIntegrationID;
CREATE INDEX IX_EmployeeCompanyIntegration_CompanyIntegrationID ON [${flyway:defaultSchema}].[EmployeeCompanyIntegration] ([CompanyIntegrationID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Employee Roles
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EmployeeRole].IX_EmployeeRole_EmployeeID;
CREATE INDEX IX_EmployeeRole_EmployeeID ON [${flyway:defaultSchema}].[EmployeeRole] ([EmployeeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EmployeeRole].IX_EmployeeRole_RoleID;
CREATE INDEX IX_EmployeeRole_RoleID ON [${flyway:defaultSchema}].[EmployeeRole] ([RoleID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Employee Skills
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EmployeeSkill].IX_EmployeeSkill_EmployeeID;
CREATE INDEX IX_EmployeeSkill_EmployeeID ON [${flyway:defaultSchema}].[EmployeeSkill] ([EmployeeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EmployeeSkill].IX_EmployeeSkill_SkillID;
CREATE INDEX IX_EmployeeSkill_SkillID ON [${flyway:defaultSchema}].[EmployeeSkill] ([SkillID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entities
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Entity].IX_Entity_ParentID;
CREATE INDEX IX_Entity_ParentID ON [${flyway:defaultSchema}].[Entity] ([ParentID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Actions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityAction].IX_EntityAction_EntityID;
CREATE INDEX IX_EntityAction_EntityID ON [${flyway:defaultSchema}].[EntityAction] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityAction].IX_EntityAction_ActionID;
CREATE INDEX IX_EntityAction_ActionID ON [${flyway:defaultSchema}].[EntityAction] ([ActionID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Action Filters
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityActionFilter].IX_EntityActionFilter_EntityActionID;
CREATE INDEX IX_EntityActionFilter_EntityActionID ON [${flyway:defaultSchema}].[EntityActionFilter] ([EntityActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityActionFilter].IX_EntityActionFilter_ActionFilterID;
CREATE INDEX IX_EntityActionFilter_ActionFilterID ON [${flyway:defaultSchema}].[EntityActionFilter] ([ActionFilterID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Action Invocations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityActionInvocation].IX_EntityActionInvocation_EntityActionID;
CREATE INDEX IX_EntityActionInvocation_EntityActionID ON [${flyway:defaultSchema}].[EntityActionInvocation] ([EntityActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityActionInvocation].IX_EntityActionInvocation_InvocationTypeID;
CREATE INDEX IX_EntityActionInvocation_InvocationTypeID ON [${flyway:defaultSchema}].[EntityActionInvocation] ([InvocationTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Action Invocation Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Action Params
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityActionParam].IX_EntityActionParam_EntityActionID;
CREATE INDEX IX_EntityActionParam_EntityActionID ON [${flyway:defaultSchema}].[EntityActionParam] ([EntityActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityActionParam].IX_EntityActionParam_ActionParamID;
CREATE INDEX IX_EntityActionParam_ActionParamID ON [${flyway:defaultSchema}].[EntityActionParam] ([ActionParamID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity AI Actions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityAIAction].IX_EntityAIAction_EntityID;
CREATE INDEX IX_EntityAIAction_EntityID ON [${flyway:defaultSchema}].[EntityAIAction] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityAIAction].IX_EntityAIAction_AIModelID;
CREATE INDEX IX_EntityAIAction_AIModelID ON [${flyway:defaultSchema}].[EntityAIAction] ([AIModelID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityAIAction].IX_EntityAIAction_AIActionID;
CREATE INDEX IX_EntityAIAction_AIActionID ON [${flyway:defaultSchema}].[EntityAIAction] ([AIActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityAIAction].IX_EntityAIAction_OutputEntityID;
CREATE INDEX IX_EntityAIAction_OutputEntityID ON [${flyway:defaultSchema}].[EntityAIAction] ([OutputEntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Communication Fields
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityCommunicationField].IX_EntityCommunicationField_EntityCommunicationMessageTypeID;
CREATE INDEX IX_EntityCommunicationField_EntityCommunicationMessageTypeID ON [${flyway:defaultSchema}].[EntityCommunicationField] ([EntityCommunicationMessageTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Communication Message Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityCommunicationMessageType].IX_EntityCommunicationMessageType_EntityID;
CREATE INDEX IX_EntityCommunicationMessageType_EntityID ON [${flyway:defaultSchema}].[EntityCommunicationMessageType] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityCommunicationMessageType].IX_EntityCommunicationMessageType_BaseMessageTypeID;
CREATE INDEX IX_EntityCommunicationMessageType_BaseMessageTypeID ON [${flyway:defaultSchema}].[EntityCommunicationMessageType] ([BaseMessageTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Documents
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityDocument].IX_EntityDocument_TypeID;
CREATE INDEX IX_EntityDocument_TypeID ON [${flyway:defaultSchema}].[EntityDocument] ([TypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityDocument].IX_EntityDocument_EntityID;
CREATE INDEX IX_EntityDocument_EntityID ON [${flyway:defaultSchema}].[EntityDocument] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityDocument].IX_EntityDocument_VectorDatabaseID;
CREATE INDEX IX_EntityDocument_VectorDatabaseID ON [${flyway:defaultSchema}].[EntityDocument] ([VectorDatabaseID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityDocument].IX_EntityDocument_TemplateID;
CREATE INDEX IX_EntityDocument_TemplateID ON [${flyway:defaultSchema}].[EntityDocument] ([TemplateID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityDocument].IX_EntityDocument_AIModelID;
CREATE INDEX IX_EntityDocument_AIModelID ON [${flyway:defaultSchema}].[EntityDocument] ([AIModelID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Document Runs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityDocumentRun].IX_EntityDocumentRun_EntityDocumentID;
CREATE INDEX IX_EntityDocumentRun_EntityDocumentID ON [${flyway:defaultSchema}].[EntityDocumentRun] ([EntityDocumentID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Document Settings
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityDocumentSetting].IX_EntityDocumentSetting_EntityDocumentID;
CREATE INDEX IX_EntityDocumentSetting_EntityDocumentID ON [${flyway:defaultSchema}].[EntityDocumentSetting] ([EntityDocumentID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Document Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Fields
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityField].IX_EntityField_EntityID;
CREATE INDEX IX_EntityField_EntityID ON [${flyway:defaultSchema}].[EntityField] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityField].IX_EntityField_RelatedEntityID;
CREATE INDEX IX_EntityField_RelatedEntityID ON [${flyway:defaultSchema}].[EntityField] ([RelatedEntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Field Values
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityFieldValue].IX_EntityFieldValue_EntityFieldID;
CREATE INDEX IX_EntityFieldValue_EntityFieldID ON [${flyway:defaultSchema}].[EntityFieldValue] ([EntityFieldID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Permissions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityPermission].IX_EntityPermission_EntityID;
CREATE INDEX IX_EntityPermission_EntityID ON [${flyway:defaultSchema}].[EntityPermission] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityPermission].IX_EntityPermission_RoleID;
CREATE INDEX IX_EntityPermission_RoleID ON [${flyway:defaultSchema}].[EntityPermission] ([RoleID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityPermission].IX_EntityPermission_ReadRLSFilterID;
CREATE INDEX IX_EntityPermission_ReadRLSFilterID ON [${flyway:defaultSchema}].[EntityPermission] ([ReadRLSFilterID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityPermission].IX_EntityPermission_CreateRLSFilterID;
CREATE INDEX IX_EntityPermission_CreateRLSFilterID ON [${flyway:defaultSchema}].[EntityPermission] ([CreateRLSFilterID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityPermission].IX_EntityPermission_UpdateRLSFilterID;
CREATE INDEX IX_EntityPermission_UpdateRLSFilterID ON [${flyway:defaultSchema}].[EntityPermission] ([UpdateRLSFilterID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityPermission].IX_EntityPermission_DeleteRLSFilterID;
CREATE INDEX IX_EntityPermission_DeleteRLSFilterID ON [${flyway:defaultSchema}].[EntityPermission] ([DeleteRLSFilterID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Record Documents
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityRecordDocument].IX_EntityRecordDocument_EntityID;
CREATE INDEX IX_EntityRecordDocument_EntityID ON [${flyway:defaultSchema}].[EntityRecordDocument] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityRecordDocument].IX_EntityRecordDocument_EntityDocumentID;
CREATE INDEX IX_EntityRecordDocument_EntityDocumentID ON [${flyway:defaultSchema}].[EntityRecordDocument] ([EntityDocumentID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityRecordDocument].IX_EntityRecordDocument_VectorIndexID;
CREATE INDEX IX_EntityRecordDocument_VectorIndexID ON [${flyway:defaultSchema}].[EntityRecordDocument] ([VectorIndexID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Relationships
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityRelationship].IX_EntityRelationship_EntityID;
CREATE INDEX IX_EntityRelationship_EntityID ON [${flyway:defaultSchema}].[EntityRelationship] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityRelationship].IX_EntityRelationship_RelatedEntityID;
CREATE INDEX IX_EntityRelationship_RelatedEntityID ON [${flyway:defaultSchema}].[EntityRelationship] ([RelatedEntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityRelationship].IX_EntityRelationship_DisplayUserViewID;
CREATE INDEX IX_EntityRelationship_DisplayUserViewID ON [${flyway:defaultSchema}].[EntityRelationship] ([DisplayUserViewID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntityRelationship].IX_EntityRelationship_DisplayComponentID;
CREATE INDEX IX_EntityRelationship_DisplayComponentID ON [${flyway:defaultSchema}].[EntityRelationship] ([DisplayComponentID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Relationship Display Components
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Entity Settings
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[EntitySetting].IX_EntitySetting_EntityID;
CREATE INDEX IX_EntitySetting_EntityID ON [${flyway:defaultSchema}].[EntitySetting] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Error Logs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ErrorLog].IX_ErrorLog_CompanyIntegrationRunID;
CREATE INDEX IX_ErrorLog_CompanyIntegrationRunID ON [${flyway:defaultSchema}].[ErrorLog] ([CompanyIntegrationRunID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ErrorLog].IX_ErrorLog_CompanyIntegrationRunDetailID;
CREATE INDEX IX_ErrorLog_CompanyIntegrationRunDetailID ON [${flyway:defaultSchema}].[ErrorLog] ([CompanyIntegrationRunDetailID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Explorer Navigation Items
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Files
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[File].IX_File_CategoryID;
CREATE INDEX IX_File_CategoryID ON [${flyway:defaultSchema}].[File] ([CategoryID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[File].IX_File_ProviderID;
CREATE INDEX IX_File_ProviderID ON [${flyway:defaultSchema}].[File] ([ProviderID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: File Categories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[FileCategory].IX_FileCategory_ParentID;
CREATE INDEX IX_FileCategory_ParentID ON [${flyway:defaultSchema}].[FileCategory] ([ParentID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: File Entity Record Links
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[FileEntityRecordLink].IX_FileEntityRecordLink_FileID;
CREATE INDEX IX_FileEntityRecordLink_FileID ON [${flyway:defaultSchema}].[FileEntityRecordLink] ([FileID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[FileEntityRecordLink].IX_FileEntityRecordLink_EntityID;
CREATE INDEX IX_FileEntityRecordLink_EntityID ON [${flyway:defaultSchema}].[FileEntityRecordLink] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: File Storage Providers
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: flyway _schema _histories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Integrations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Integration URL Formats
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[IntegrationURLFormat].IX_IntegrationURLFormat_IntegrationID;
CREATE INDEX IX_IntegrationURLFormat_IntegrationID ON [${flyway:defaultSchema}].[IntegrationURLFormat] ([IntegrationID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[IntegrationURLFormat].IX_IntegrationURLFormat_EntityID;
CREATE INDEX IX_IntegrationURLFormat_EntityID ON [${flyway:defaultSchema}].[IntegrationURLFormat] ([EntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Libraries
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Library Items
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[LibraryItem].IX_LibraryItem_LibraryID;
CREATE INDEX IX_LibraryItem_LibraryID ON [${flyway:defaultSchema}].[LibraryItem] ([LibraryID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Lists
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[List].IX_List_EntityID;
CREATE INDEX IX_List_EntityID ON [${flyway:defaultSchema}].[List] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[List].IX_List_UserID;
CREATE INDEX IX_List_UserID ON [${flyway:defaultSchema}].[List] ([UserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[List].IX_List_CategoryID;
CREATE INDEX IX_List_CategoryID ON [${flyway:defaultSchema}].[List] ([CategoryID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[List].IX_List_CompanyIntegrationID;
CREATE INDEX IX_List_CompanyIntegrationID ON [${flyway:defaultSchema}].[List] ([CompanyIntegrationID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: List Categories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ListCategory].IX_ListCategory_ParentID;
CREATE INDEX IX_ListCategory_ParentID ON [${flyway:defaultSchema}].[ListCategory] ([ParentID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ListCategory].IX_ListCategory_UserID;
CREATE INDEX IX_ListCategory_UserID ON [${flyway:defaultSchema}].[ListCategory] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: List Details
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ListDetail].IX_ListDetail_ListID;
CREATE INDEX IX_ListDetail_ListID ON [${flyway:defaultSchema}].[ListDetail] ([ListID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Output Delivery Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Output Format Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Output Trigger Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Queries
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Query].IX_Query_CategoryID;
CREATE INDEX IX_Query_CategoryID ON [${flyway:defaultSchema}].[Query] ([CategoryID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Query Categories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[QueryCategory].IX_QueryCategory_ParentID;
CREATE INDEX IX_QueryCategory_ParentID ON [${flyway:defaultSchema}].[QueryCategory] ([ParentID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[QueryCategory].IX_QueryCategory_UserID;
CREATE INDEX IX_QueryCategory_UserID ON [${flyway:defaultSchema}].[QueryCategory] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Query Fields
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[QueryField].IX_QueryField_QueryID;
CREATE INDEX IX_QueryField_QueryID ON [${flyway:defaultSchema}].[QueryField] ([QueryID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[QueryField].IX_QueryField_SourceEntityID;
CREATE INDEX IX_QueryField_SourceEntityID ON [${flyway:defaultSchema}].[QueryField] ([SourceEntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Query Permissions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[QueryPermission].IX_QueryPermission_QueryID;
CREATE INDEX IX_QueryPermission_QueryID ON [${flyway:defaultSchema}].[QueryPermission] ([QueryID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[QueryPermission].IX_QueryPermission_RoleID;
CREATE INDEX IX_QueryPermission_RoleID ON [${flyway:defaultSchema}].[QueryPermission] ([RoleID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Queues
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Queue].IX_Queue_QueueTypeID;
CREATE INDEX IX_Queue_QueueTypeID ON [${flyway:defaultSchema}].[Queue] ([QueueTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Queue Tasks
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[QueueTask].IX_QueueTask_QueueID;
CREATE INDEX IX_QueueTask_QueueID ON [${flyway:defaultSchema}].[QueueTask] ([QueueID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Queue Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Recommendations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Recommendation].IX_Recommendation_RecommendationRunID;
CREATE INDEX IX_Recommendation_RecommendationRunID ON [${flyway:defaultSchema}].[Recommendation] ([RecommendationRunID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Recommendation].IX_Recommendation_SourceEntityID;
CREATE INDEX IX_Recommendation_SourceEntityID ON [${flyway:defaultSchema}].[Recommendation] ([SourceEntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Recommendation Items
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecommendationItem].IX_RecommendationItem_RecommendationID;
CREATE INDEX IX_RecommendationItem_RecommendationID ON [${flyway:defaultSchema}].[RecommendationItem] ([RecommendationID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecommendationItem].IX_RecommendationItem_DestinationEntityID;
CREATE INDEX IX_RecommendationItem_DestinationEntityID ON [${flyway:defaultSchema}].[RecommendationItem] ([DestinationEntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Recommendation Providers
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Recommendation Runs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecommendationRun].IX_RecommendationRun_RecommendationProviderID;
CREATE INDEX IX_RecommendationRun_RecommendationProviderID ON [${flyway:defaultSchema}].[RecommendationRun] ([RecommendationProviderID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecommendationRun].IX_RecommendationRun_RunByUserID;
CREATE INDEX IX_RecommendationRun_RunByUserID ON [${flyway:defaultSchema}].[RecommendationRun] ([RunByUserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Record Changes
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordChange].IX_RecordChange_EntityID;
CREATE INDEX IX_RecordChange_EntityID ON [${flyway:defaultSchema}].[RecordChange] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordChange].IX_RecordChange_UserID;
CREATE INDEX IX_RecordChange_UserID ON [${flyway:defaultSchema}].[RecordChange] ([UserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordChange].IX_RecordChange_ReplayRunID;
CREATE INDEX IX_RecordChange_ReplayRunID ON [${flyway:defaultSchema}].[RecordChange] ([ReplayRunID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordChange].IX_RecordChange_IntegrationID;
CREATE INDEX IX_RecordChange_IntegrationID ON [${flyway:defaultSchema}].[RecordChange] ([IntegrationID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Record Change Replay Runs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordChangeReplayRun].IX_RecordChangeReplayRun_UserID;
CREATE INDEX IX_RecordChangeReplayRun_UserID ON [${flyway:defaultSchema}].[RecordChangeReplayRun] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Record Merge Deletion Logs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordMergeDeletionLog].IX_RecordMergeDeletionLog_RecordMergeLogID;
CREATE INDEX IX_RecordMergeDeletionLog_RecordMergeLogID ON [${flyway:defaultSchema}].[RecordMergeDeletionLog] ([RecordMergeLogID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Record Merge Logs
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordMergeLog].IX_RecordMergeLog_EntityID;
CREATE INDEX IX_RecordMergeLog_EntityID ON [${flyway:defaultSchema}].[RecordMergeLog] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordMergeLog].IX_RecordMergeLog_InitiatedByUserID;
CREATE INDEX IX_RecordMergeLog_InitiatedByUserID ON [${flyway:defaultSchema}].[RecordMergeLog] ([InitiatedByUserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[RecordMergeLog].IX_RecordMergeLog_ApprovedByUserID;
CREATE INDEX IX_RecordMergeLog_ApprovedByUserID ON [${flyway:defaultSchema}].[RecordMergeLog] ([ApprovedByUserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Reports
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_CategoryID;
CREATE INDEX IX_Report_CategoryID ON [${flyway:defaultSchema}].[Report] ([CategoryID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_UserID;
CREATE INDEX IX_Report_UserID ON [${flyway:defaultSchema}].[Report] ([UserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_ConversationID;
CREATE INDEX IX_Report_ConversationID ON [${flyway:defaultSchema}].[Report] ([ConversationID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_ConversationDetailID;
CREATE INDEX IX_Report_ConversationDetailID ON [${flyway:defaultSchema}].[Report] ([ConversationDetailID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_DataContextID;
CREATE INDEX IX_Report_DataContextID ON [${flyway:defaultSchema}].[Report] ([DataContextID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_OutputTriggerTypeID;
CREATE INDEX IX_Report_OutputTriggerTypeID ON [${flyway:defaultSchema}].[Report] ([OutputTriggerTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_OutputFormatTypeID;
CREATE INDEX IX_Report_OutputFormatTypeID ON [${flyway:defaultSchema}].[Report] ([OutputFormatTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_OutputDeliveryTypeID;
CREATE INDEX IX_Report_OutputDeliveryTypeID ON [${flyway:defaultSchema}].[Report] ([OutputDeliveryTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Report].IX_Report_OutputWorkflowID;
CREATE INDEX IX_Report_OutputWorkflowID ON [${flyway:defaultSchema}].[Report] ([OutputWorkflowID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Report Categories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ReportCategory].IX_ReportCategory_ParentID;
CREATE INDEX IX_ReportCategory_ParentID ON [${flyway:defaultSchema}].[ReportCategory] ([ParentID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ReportCategory].IX_ReportCategory_UserID;
CREATE INDEX IX_ReportCategory_UserID ON [${flyway:defaultSchema}].[ReportCategory] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Report Snapshots
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ReportSnapshot].IX_ReportSnapshot_ReportID;
CREATE INDEX IX_ReportSnapshot_ReportID ON [${flyway:defaultSchema}].[ReportSnapshot] ([ReportID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ReportSnapshot].IX_ReportSnapshot_UserID;
CREATE INDEX IX_ReportSnapshot_UserID ON [${flyway:defaultSchema}].[ReportSnapshot] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Resource Links
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ResourceLink].IX_ResourceLink_UserID;
CREATE INDEX IX_ResourceLink_UserID ON [${flyway:defaultSchema}].[ResourceLink] ([UserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ResourceLink].IX_ResourceLink_ResourceTypeID;
CREATE INDEX IX_ResourceLink_ResourceTypeID ON [${flyway:defaultSchema}].[ResourceLink] ([ResourceTypeID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Resource Permissions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ResourcePermission].IX_ResourcePermission_ResourceTypeID;
CREATE INDEX IX_ResourcePermission_ResourceTypeID ON [${flyway:defaultSchema}].[ResourcePermission] ([ResourceTypeID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ResourcePermission].IX_ResourcePermission_RoleID;
CREATE INDEX IX_ResourcePermission_RoleID ON [${flyway:defaultSchema}].[ResourcePermission] ([RoleID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ResourcePermission].IX_ResourcePermission_UserID;
CREATE INDEX IX_ResourcePermission_UserID ON [${flyway:defaultSchema}].[ResourcePermission] ([UserID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Resource Types
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ResourceType].IX_ResourceType_EntityID;
CREATE INDEX IX_ResourceType_EntityID ON [${flyway:defaultSchema}].[ResourceType] ([EntityID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ResourceType].IX_ResourceType_CategoryEntityID;
CREATE INDEX IX_ResourceType_CategoryEntityID ON [${flyway:defaultSchema}].[ResourceType] ([CategoryEntityID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Roles
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Row Level Security Filters
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Scheduled Actions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ScheduledAction].IX_ScheduledAction_CreatedByUserID;
CREATE INDEX IX_ScheduledAction_CreatedByUserID ON [${flyway:defaultSchema}].[ScheduledAction] ([CreatedByUserID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ScheduledAction].IX_ScheduledAction_ActionID;
CREATE INDEX IX_ScheduledAction_ActionID ON [${flyway:defaultSchema}].[ScheduledAction] ([ActionID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Scheduled Action Params
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ScheduledActionParam].IX_ScheduledActionParam_ScheduledActionID;
CREATE INDEX IX_ScheduledActionParam_ScheduledActionID ON [${flyway:defaultSchema}].[ScheduledActionParam] ([ScheduledActionID]);
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[ScheduledActionParam].IX_ScheduledActionParam_ActionParamID;
CREATE INDEX IX_ScheduledActionParam_ActionParamID ON [${flyway:defaultSchema}].[ScheduledActionParam] ([ActionParamID]);


-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Schema Info
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------



-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Skills
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
DROP INDEX IF EXISTS [${flyway:defaultSchema}].[Skill].IX_Skill_ParentID;
CREATE INDEX IX_Skill_ParentID ON [${flyway:defaultSchema}].[Skill] ([ParentID]);







GO
 



DROP PROC IF EXISTS [${flyway:defaultSchema}].[spUpdateExistingEntityFieldsFromSchema]
GO
CREATE PROC [${flyway:defaultSchema}].[spUpdateExistingEntityFieldsFromSchema]
    @ExcludedSchemaNames NVARCHAR(MAX)
AS
BEGIN
    -- Step 1: Parse the excluded schema names into a table
    DECLARE @ExcludedSchemas TABLE (SchemaName NVARCHAR(255));
    INSERT INTO @ExcludedSchemas(SchemaName)
    SELECT TRIM(value) FROM STRING_SPLIT(@ExcludedSchemaNames, ',');

    -- Step 2: Precompute the join results in a CTE
    WITH PrecomputedData AS (
        SELECT 
            ef.ID AS EntityFieldID,
            ef.AutoUpdateDescription,
            ef.Description AS ExistingDescription,
            fromSQL.Description AS SQLDescription,
            fromSQL.Type,
            fromSQL.Length,
            fromSQL.Precision,
            fromSQL.Scale,
            fromSQL.AllowsNull,
            fromSQL.DefaultValue,
            fromSQL.AutoIncrement,
            fromSQL.IsVirtual,
            fromSQL.Sequence,
            re.ID AS RelatedEntityID,
            fk.referenced_column AS RelatedEntityFieldName,
            CASE WHEN pk.ColumnName IS NOT NULL THEN 1 ELSE 0 END AS IsPrimaryKey,
            CASE 
                WHEN pk.ColumnName IS NOT NULL THEN 1 
                ELSE CASE WHEN uk.ColumnName IS NOT NULL THEN 1 ELSE 0 END
            END AS IsUnique,
            e.VirtualEntity,
            excludedSchemas.SchemaName AS ExcludedSchemaName
        FROM
            [${flyway:defaultSchema}].EntityField ef
        INNER JOIN
            vwSQLColumnsAndEntityFields fromSQL
        ON
            ef.EntityID = fromSQL.EntityID AND
            ef.Name = fromSQL.FieldName
        INNER JOIN
            [${flyway:defaultSchema}].Entity e 
        ON
            ef.EntityID = e.ID
        LEFT OUTER JOIN
            vwForeignKeys fk
        ON
            ef.Name = fk.[column] AND
            e.BaseTable = fk.[table] AND
            e.SchemaName = fk.[schema_name]
        LEFT OUTER JOIN 
            [${flyway:defaultSchema}].Entity re -- Related Entity
        ON
            re.BaseTable = fk.referenced_table AND
            re.SchemaName = fk.[referenced_schema]
        LEFT OUTER JOIN 
            [${flyway:defaultSchema}].vwTablePrimaryKeys pk
        ON
            e.BaseTable = pk.TableName AND
            ef.Name = pk.ColumnName AND
            e.SchemaName = pk.SchemaName
        LEFT OUTER JOIN 
            [${flyway:defaultSchema}].vwTableUniqueKeys uk
        ON
            e.BaseTable = uk.TableName AND
            ef.Name = uk.ColumnName AND
            e.SchemaName = uk.SchemaName
        LEFT OUTER JOIN
            @ExcludedSchemas excludedSchemas
        ON
            e.SchemaName = excludedSchemas.SchemaName
    )
    -- Step 3: Perform the update using the precomputed data
    UPDATE ef
    SET
        ef.Description = IIF(pd.AutoUpdateDescription=1, CONVERT(NVARCHAR(MAX), pd.SQLDescription), pd.ExistingDescription),
        ef.Type = pd.Type,
        ef.Length = pd.Length,
        ef.Precision = pd.Precision,
        ef.Scale = pd.Scale,
        ef.AllowsNull = pd.AllowsNull,
        ef.DefaultValue = pd.DefaultValue,
        ef.AutoIncrement = pd.AutoIncrement,
        ef.IsVirtual = pd.IsVirtual,
        ef.Sequence = pd.Sequence,
        ef.RelatedEntityID = pd.RelatedEntityID,
        ef.RelatedEntityFieldName = pd.RelatedEntityFieldName,
        ef.IsPrimaryKey = pd.IsPrimaryKey,
        ef.IsUnique = pd.IsUnique,
        ef.${flyway:defaultSchema}_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].EntityField ef
    INNER JOIN
        PrecomputedData pd
    ON
        ef.ID = pd.EntityFieldID
    WHERE
        pd.VirtualEntity = 0
        AND pd.EntityFieldID IS NOT NULL -- only where we HAVE ALREADY CREATED EntityField records
        AND pd.ExcludedSchemaName IS NULL; -- Only include non-excluded schemas
END
GO
 





DROP VIEW IF EXISTS [${flyway:defaultSchema}].[vwSQLColumnsAndEntityFields]
GO
CREATE VIEW [${flyway:defaultSchema}].[vwSQLColumnsAndEntityFields]
AS
WITH FilteredColumns AS (
    SELECT *
    FROM sys.all_columns
    WHERE default_object_id IS NOT NULL
)
SELECT 
	e.EntityID,
	e.EntityName Entity,
	e.SchemaName,
	e.TableName TableName,
	ef.ID EntityFieldID,
	ef.Sequence EntityFieldSequence,
	ef.Name EntityFieldName,
	c.column_id Sequence,
  basetable_columns.column_id BaseTableSequence,
	c.name FieldName,
	COALESCE(bt.name, t.name) Type, -- get the type from the base type (bt) if it exists, this is in the case of a user-defined type being used, t.name would be the UDT name.
	IIF(t.is_user_defined = 1, t.name, NULL) UserDefinedType, -- we have a user defined type, so pass that to the view caller too
	c.max_length Length,
	c.precision Precision,
	c.scale Scale,
	c.is_nullable AllowsNull,
	IIF(COALESCE(bt.name, t.name) IN ('timestamp', 'rowversion'), 1, IIF(basetable_columns.is_identity IS NULL, 0, basetable_columns.is_identity)) AutoIncrement,
	c.column_id,
	IIF(basetable_columns.column_id IS NULL OR cc.definition IS NOT NULL, 1, 0) IsVirtual, -- updated so that we take into account that computed columns are virtual always, previously only looked for existence of a column in table vs. a view
	basetable_columns.object_id,
	dc.name AS DefaultConstraintName,
    dc.definition AS DefaultValue,
	cc.definition ComputedColumnDefinition,
	COALESCE(EP_View.value, EP_Table.value) AS [Description], -- Dynamically choose description - first look at view level if a description was defined there (rare) and then go to table if it was defined there (often not there either)
	EP_View.value AS ViewColumnDescription,
	EP_Table.value AS TableColumnDescription
FROM
	FilteredColumns c
INNER JOIN
	[${flyway:defaultSchema}].vwSQLTablesAndEntities e
ON
  c.object_id = COALESCE(e.view_object_id, e.object_id)
INNER JOIN
	sys.types t 
ON
	c.user_type_id = t.user_type_id
LEFT OUTER JOIN
    sys.types bt
ON
    t.system_type_id = bt.user_type_id AND t.is_user_defined = 1 -- Join to fetch base type for UDTs
INNER JOIN
	sys.all_objects basetable 
ON
	e.object_id = basetable.object_id
LEFT OUTER JOIN 
    sys.computed_columns cc 
ON 
	e.object_id = cc.object_id AND 
	c.name = cc.name
LEFT OUTER JOIN
	sys.all_columns basetable_columns -- join in all columns from base table and line them up - that way we know if a field is a VIEW only field or a TABLE field (virtual vs. in table)
ON
	basetable.object_id = basetable_columns.object_id AND
	c.name = basetable_columns.name 
LEFT OUTER JOIN
	${flyway:defaultSchema}.EntityField ef 
ON
	e.EntityID = ef.EntityID AND
	c.name = ef.Name
LEFT OUTER JOIN 
    sys.default_constraints dc 
ON 
  e.object_id = dc.parent_object_id AND
	basetable_columns.column_id = dc.parent_column_id
LEFT OUTER JOIN 
    sys.extended_properties EP_Table 
ON 
	EP_Table.major_id = basetable_columns.object_id AND 
	EP_Table.minor_id = basetable_columns.column_id AND 
	EP_Table.name = 'MS_Description'
LEFT OUTER JOIN 
    sys.extended_properties EP_View 
ON 
	EP_View.major_id = c.object_id AND 
	EP_View.minor_id = c.column_id AND 
	EP_View.name = 'MS_Description'
GO
