-- SQL Logging Session
-- Session ID: 1b149578-d212-4afd-bc15-e4e49a1c3d68
-- Started: 2025-06-25T21:13:25.175Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction SQLServerDataProvider

-- Save Action Categories (core SP call only)
EXEC [${flyway:defaultSchema}].spUpdateActionCategory @Name = N'Communication',
@Description = N'Communication Actions',
@ParentID = NULL,
@Status = N'Active',
@ID = '65E048AA-5220-4E4D-920A-A3D9349902A7';

-- Save Action Categories (core SP call only)
EXEC [${flyway:defaultSchema}].spUpdateActionCategory @Name = N'Demo',
@Description = N'Demo Actions',
@ParentID = NULL,
@Status = N'Active',
@ID = 'B51957C7-990F-4CA7-BBFF-93ED507CE466';

-- Save Action Categories (core SP call only)
EXEC [${flyway:defaultSchema}].spUpdateActionCategory @Name = N'Utilities',
@Description = N'Utility Actions',
@ParentID = NULL,
@Status = N'Active',
@ID = 'E959A850-7842-456D-AB51-F232DF12E709';

-- Save Action Categories (core SP call only)
EXEC [${flyway:defaultSchema}].spUpdateActionCategory @Name = N'Web',
@Description = N'Web Actions',
@ParentID = NULL,
@Status = N'Active',
@ID = '095EC184-0AAB-4122-A9B9-B64F0215F7DA';


-- End of SQL Logging Session
-- Session ID: 1b149578-d212-4afd-bc15-e4e49a1c3d68
-- Completed: 2025-06-25T21:13:27.819Z
-- Duration: 2644ms
-- Total Statements: 4
