/**
 * Turns Index Advisor proposals into a dialect-specific, Flyway-style SQL migration.
 */

import type { AutoDocExportFile, AutoDocExporterOptions } from '../types.js';
import type { IndexAdvisorData, IndexProposal } from './IndexAdvisorTypes.js';

type Provider = AutoDocExporterOptions['Provider'];

/** Maximum identifier length per platform. */
const MAX_IDENTIFIER: Record<Provider, number> = { sqlserver: 128, postgresql: 63, mysql: 64 };

const BASE_NAME = 'dbautodoc_indexes';

export class IndexMigrationGenerator {
  /** Returns the migration file (plus a Flyway `.conf` when PostgreSQL CONCURRENTLY is on), or nothing when there are no proposals. */
  public Generate(data: IndexAdvisorData, options: AutoDocExporterOptions): AutoDocExportFile[] {
    if (data.Proposed.length === 0) {
      return [];
    }
    const concurrently = options.Provider === 'postgresql' && data.Options.Concurrently;
    const fileName = `${options.FileNamePrefix ?? `V${IndexMigrationGenerator.Timestamp(data.AnalyzedAt)}__`}${BASE_NAME}.sql`;
    const files: AutoDocExportFile[] = [{ FileName: fileName, Content: this.buildScript(data, options.Provider, concurrently) }];
    if (concurrently) {
      // CREATE INDEX CONCURRENTLY cannot run inside a transaction; tell Flyway to run this script without one.
      files.push({ FileName: `${fileName}.conf`, Content: 'executeInTransaction=false\n' });
    }
    return files;
  }

  /** Index name for a proposal: IX_<table>_<columns>, shortened with a hash suffix when too long. */
  public static IndexName(proposal: Pick<IndexProposal, 'TableName' | 'Columns'>, provider: Provider): string {
    const raw = `IX_${proposal.TableName}_${proposal.Columns.join('_')}`.replace(/[^A-Za-z0-9_]/g, '_');
    const max = MAX_IDENTIFIER[provider];
    if (raw.length <= max) {
      return raw;
    }
    return `${raw.slice(0, max - 9)}_${IndexMigrationGenerator.hash(raw)}`;
  }

  /** yyyyMMddHHmm (UTC) from an ISO timestamp. */
  public static Timestamp(iso: string): string {
    const d = new Date(iso);
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}`;
  }

  private buildScript(data: IndexAdvisorData, provider: Provider, concurrently: boolean): string {
    const header = [
      `-- Index migration generated by DBAutoDoc Index Advisor (${data.AnalyzedAt}).`,
      `-- Platform: ${provider}. ${data.Proposed.length} proposed index(es), highest priority first.`,
      '-- Review before applying. Each index is created only if it does not already exist.',
      provider === 'mysql' ? '-- MySQL has no CREATE INDEX IF NOT EXISTS; re-running this script fails on indexes that already exist.' : ''
    ].filter((l) => l.length > 0);
    const statements = data.Proposed.map((p) => `-- ${p.Source}: ${p.Reason}\n${this.statement(p, provider, concurrently)}`);
    return `${header.join('\n')}\n\n${statements.join('\n\n')}\n`;
  }

  private statement(p: IndexProposal, provider: Provider, concurrently: boolean): string {
    const name = IndexMigrationGenerator.IndexName(p, provider);
    const q = (id: string) => IndexMigrationGenerator.Quote(id, provider);
    const table = `${q(p.SchemaName)}.${q(p.TableName)}`;
    const columns = p.Columns.map(q).join(', ');
    const include = p.IncludeColumns.length && provider !== 'mysql' ? ` INCLUDE (${p.IncludeColumns.map(q).join(', ')})` : '';
    switch (provider) {
      case 'sqlserver':
        return [
          `IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'${name}' AND object_id = OBJECT_ID(N'${table.replace(/'/g, "''")}'))`,
          `    CREATE NONCLUSTERED INDEX ${q(name)} ON ${table} (${columns})${include};`
        ].join('\n');
      case 'postgresql':
        return `CREATE INDEX ${concurrently ? 'CONCURRENTLY ' : ''}IF NOT EXISTS ${q(name)} ON ${table} (${columns})${include};`;
      case 'mysql':
        return `CREATE INDEX ${q(name)} ON ${table} (${columns});`;
    }
  }

  /** Quotes an identifier for the platform, doubling any embedded quote character. */
  public static Quote(identifier: string, provider: Provider): string {
    switch (provider) {
      case 'sqlserver':
        return `[${identifier.replace(/]/g, ']]')}]`;
      case 'postgresql':
        return `"${identifier.replace(/"/g, '""')}"`;
      case 'mysql':
        return `\`${identifier.replace(/`/g, '``')}\``;
    }
  }

  /** 8-hex-digit FNV-1a hash, used to keep shortened index names unique. */
  private static hash(value: string): string {
    let h = 0x811c9dc5;
    for (let i = 0; i < value.length; i++) {
      h ^= value.charCodeAt(i);
      h = Math.imul(h, 0x01000193);
    }
    return (h >>> 0).toString(16).padStart(8, '0');
  }
}
