import { describe, it, expect } from 'vitest';
import { splitMigration, extractAffectedEntities } from '../MigrationSplitter.js';

/** Minimal reproduction of a CodeGen item header block. */
const codegenItem = (title: string, body: string) =>
  [
    `/* ${title} */`,
    '-----------------------------------------------------------------',
    '-- SQL Code Generation',
    '-- Item: ' + title,
    '--',
    '-- This was generated by the MemberJunction CodeGen tool.',
    '-- This file should NOT be edited by hand.',
    '-----------------------------------------------------------------',
    body,
  ].join('\n');

describe('splitMigration', () => {
  describe('boundary detection', () => {
    it('splits at the /* opener of the first banner-marked item (no run delimiter)', () => {
      const sql = [
        '-- hand-authored header',
        "ALTER TABLE __mj.Foo ADD Bar INT NULL;",
        '',
        codegenItem('Base View SQL for Foo', 'CREATE VIEW __mj.vwFoos AS SELECT 1;'),
      ].join('\n');

      const r = splitMigration(sql, 'feature.sql');
      expect(r.boundaryMethod).toBe('first-item-banner');
      // boundary points at the `/*` opener line (line 4)
      expect(r.codeGenBoundaryLine).toBe(4);
      expect(r.handAuthored).toContain('ALTER TABLE __mj.Foo');
      expect(r.handAuthored).not.toContain('CREATE VIEW');
      expect(r.codeGenBlock).toContain('/* Base View SQL for Foo */');
      expect(r.codeGenBlock).toContain('CREATE VIEW __mj.vwFoos');
    });

    it('prefers an explicit -- CODE GEN RUN delimiter when present', () => {
      const sql = [
        'CREATE TABLE __mj.Foo (ID INT);',
        '-- CODE GEN RUN (appended from CodeGen_Run_2026-05-22_21-31-40.sql)',
        codegenItem('spCreate SQL for Foo', 'CREATE PROCEDURE __mj.spCreateFoo AS BEGIN SELECT 1; END;'),
      ].join('\n');

      const r = splitMigration(sql);
      expect(r.boundaryMethod).toBe('code-gen-run-delimiter');
      expect(r.codeGenBoundaryLine).toBe(2);
      expect(r.handAuthored).toContain('CREATE TABLE __mj.Foo');
      // The generated spCreate must NOT leak into the hand region (so it isn't
      // misclassified as hand-procedural).
      expect(r.handAuthoredRegions.some((f) => f.kind === 'hand-procedural')).toBe(false);
      expect(r.routing).toBe('transpile-only');
    });

    it('reports no codegen block for a pure hand-authored file', () => {
      const sql = "CREATE TABLE __mj.Foo (ID INT);\nALTER TABLE __mj.Foo ADD Name NVARCHAR(50);";
      const r = splitMigration(sql);
      expect(r.boundaryMethod).toBe('no-codegen-block');
      expect(r.codeGenBoundaryLine).toBeNull();
      expect(r.codeGenBlock).toBe('');
      expect(r.handAuthored).toBe(sql);
    });
  });

  describe('hand-region classification & routing', () => {
    it('routes regular DDL as transpile-only', () => {
      const sql = [
        'CREATE TABLE __mj.Foo (ID UNIQUEIDENTIFIER NOT NULL);',
        'CREATE INDEX IX_Foo ON __mj.Foo(ID);',
        "INSERT INTO __mj.Bar (ID) VALUES ('x');",
      ].join('\n');
      const r = splitMigration(sql);
      expect(r.routing).toBe('transpile-only');
      expect(r.handAuthoredRegions.map((f) => f.kind)).toContain('schema-ddl');
    });

    it('flags hand-written procedural SQL as needs-hand-authoring', () => {
      const sql = [
        'CREATE TABLE __mj.Foo (ID INT);',
        'GO',
        'CREATE OR ALTER PROCEDURE __mj.spClaimNextJob AS',
        'BEGIN',
        '  UPDATE __mj.Job SET Claimed = 1;',
        'END;',
      ].join('\n');
      const r = splitMigration(sql, 'Scheduling_Engine_Atomic_Sprocs.sql');
      expect(r.routing).toBe('needs-hand-authoring');
      const proc = r.handAuthoredRegions.find((f) => f.kind === 'hand-procedural');
      expect(proc).toBeDefined();
      expect(proc!.line).toBe(3);
    });

    it('detects mj-sync metadata seed (hashed vars) as transpile-plus-reseed', () => {
      const sql = [
        'DECLARE @Name_da319a9d NVARCHAR(50),',
        '        @Description_da319a9d NVARCHAR(MAX);',
        "SET @Name_da319a9d = 'GPT';",
        'EXEC __mj.spCreateAIModel @Name = @Name_da319a9d;',
      ].join('\n');
      const r = splitMigration(sql, 'Metadata_Sync.sql');
      expect(r.routing).toBe('transpile-plus-reseed');
      expect(r.handAuthoredRegions.some((f) => f.kind === 'metadata-sync')).toBe(true);
    });

    it('detects mj-sync by the SQL Logging Session header (header lives in a comment)', () => {
      const sql = [
        '-- SQL Logging Session',
        '-- Description: MetadataSync push operation',
        '-- Generated by MemberJunction',
        '',
        'EXEC __mj.spUpdateTemplate @ID = 1;',
      ].join('\n');
      const r = splitMigration(sql, 'V_Metadata_Sync.sql');
      expect(r.routing).toBe('transpile-plus-reseed');
      const f = r.handAuthoredRegions.find((x) => x.kind === 'metadata-sync');
      expect(f?.evidence).toBe('MetadataSync push operation');
    });

    it('does NOT route an inline EXEC spCreate (no mj-sync fingerprints) to reseed', () => {
      // A feature migration that seeds a row by hand — no hashed vars, no session
      // header. This is plain DML the converter handles, not mj-sync-owned content.
      const sql = [
        'CREATE TABLE __mj.Widget (ID UNIQUEIDENTIFIER NOT NULL);',
        "EXEC __mj.spCreateWidget @Name = 'Gizmo';",
      ].join('\n');
      const r = splitMigration(sql, 'Feature.sql');
      expect(r.routing).toBe('transpile-only');
      expect(r.handAuthoredRegions.some((f) => f.kind === 'metadata-sync')).toBe(false);
    });
  });

  describe('comment / string awareness', () => {
    it('does not classify keywords that appear only inside comments', () => {
      const sql = [
        '-- This migration used to CREATE PROCEDURE but no longer does.',
        '/* CREATE TRIGGER example in a block comment */',
        'ALTER TABLE __mj.Foo ADD Note NVARCHAR(50);',
      ].join('\n');
      const r = splitMigration(sql);
      expect(r.routing).toBe('transpile-only');
      expect(r.handAuthoredRegions.some((f) => f.kind === 'hand-procedural')).toBe(false);
    });

    it('does not classify keywords inside string literals', () => {
      const sql = "INSERT INTO __mj.Doc (Body) VALUES ('You can CREATE FUNCTION here');";
      const r = splitMigration(sql);
      expect(r.handAuthoredRegions.some((f) => f.kind === 'hand-procedural')).toBe(false);
      expect(r.handAuthoredRegions.some((f) => f.kind === 'data-dml')).toBe(true);
    });

    it('does not classify keywords inside MULTI-LINE string literals', () => {
      // Regression: the in-string state reset per line, so continuation lines of a
      // prompt-template literal mentioning ALTER/CREATE TABLE were scanned as code
      // (live corpus hit: V202605021448 Metadata_Sync mis-routed to transpile).
      const sql = [
        "SET @Description = N'This template shows how to",
        'CREATE TABLE Foo and ALTER TABLE Bar in SQL.',
        "End of template';",
      ].join('\n');
      const r = splitMigration(sql);
      expect(r.handAuthoredRegions.some((f) => f.kind === 'schema-ddl')).toBe(false);
    });

    it("handles doubled-quote escapes across the multi-line literal", () => {
      const sql = [
        "SET @Description = N'It''s a template that says",
        "''CREATE TABLE'' is just text here';",
        'ALTER TABLE __mj.Foo ADD Note NVARCHAR(50);',
      ].join('\n');
      const r = splitMigration(sql);
      // The real ALTER TABLE after the literal IS classified; the quoted one is not.
      expect(r.handAuthoredRegions.filter((f) => f.kind === 'schema-ddl')).toHaveLength(1);
    });
  });
});

describe('extractAffectedEntities', () => {
  it('returns [] for an empty block', () => {
    expect(extractAffectedEntities('')).toEqual([]);
  });

  it('captures the entity from a newer SQL-Code-Generation sproc header (-- Entity: gated by -- Item:)', () => {
    const block = [
      '/* spCreate SQL for MJ: AI Agent Runs */',
      '-----------------------------------------------------------------',
      '-- SQL Code Generation',
      '-- Entity: MJ: AI Agent Runs',
      '-- Item: spCreateAIAgentRun',
      '--',
      '-- This was generated by the MemberJunction CodeGen tool.',
      '-----------------------------------------------------------------',
      'CREATE OR REPLACE FUNCTION __mj."spCreateAIAgentRun"() RETURNS SETOF __mj."vwAIAgentRuns" AS $$ $$;',
    ].join('\n');
    // present in BOTH the provenance comment and the Entity/Item header → de-duped to one.
    expect(extractAffectedEntities(block)).toEqual(['MJ: AI Agent Runs']);
  });

  it('captures the entity from the older base-view banner (no -- Entity: line present)', () => {
    const block = [
      '-- Item: vwAIAgentRuns',
      '--',
      '-- This was generated by the MemberJunction CodeGen tool.',
      '-----------------------------------------------------------------',
      '',
      '------------------------------------------------------------',
      '----- BASE VIEW FOR ENTITY:      MJ: AI Agent Runs',
      '-----               SCHEMA:      __mj',
      '------------------------------------------------------------',
      'CREATE VIEW __mj."vwAIAgentRuns" AS SELECT 1;',
    ].join('\n');
    expect(extractAffectedEntities(block)).toEqual(['MJ: AI Agent Runs']);
  });

  it('captures the entity from a provenance-only header (no -- Entity:, no banner)', () => {
    const block = '/* Base View SQL for MJ: AI Prompts */\nCREATE VIEW __mj."vwAIPrompts" AS SELECT 1;';
    expect(extractAffectedEntities(block)).toEqual(['MJ: AI Prompts']);
  });

  it('captures cascade spDelete-only entities, in first-appearance order, de-duplicated', () => {
    // Mirrors a real "add columns to AIPromptRun" block: the primary entity gets the
    // full object set; FK-cascade dependents get spDelete only — all must be in E(M).
    const block = [
      '/* spCreate SQL for MJ: AI Prompt Runs */',
      '-- SQL Code Generation',
      '-- Entity: MJ: AI Prompt Runs',
      '-- Item: spCreateAIPromptRun',
      'CREATE OR REPLACE FUNCTION __mj."spCreateAIPromptRun"() RETURNS void AS $$ $$;',
      '/* spDelete SQL for MJ: AI Prompt Runs */',
      '-- SQL Code Generation',
      '-- Entity: MJ: AI Prompt Runs',
      '-- Item: spDeleteAIPromptRun',
      'CREATE OR REPLACE FUNCTION __mj."spDeleteAIPromptRun"() RETURNS void AS $$ $$;',
      '/* spDelete SQL for MJ: AI Agents */',
      '-- SQL Code Generation',
      '-- Entity: MJ: AI Agents',
      '-- Item: spDeleteAIAgent',
      'CREATE OR REPLACE FUNCTION __mj."spDeleteAIAgent"() RETURNS void AS $$ $$;',
      '/* spDelete SQL for MJ: AI Configurations */',
      '-- Entity: MJ: AI Configurations',
      '-- Item: spDeleteAIConfiguration',
      'CREATE OR REPLACE FUNCTION __mj."spDeleteAIConfiguration"() RETURNS void AS $$ $$;',
    ].join('\n');
    expect(extractAffectedEntities(block)).toEqual([
      'MJ: AI Prompt Runs',
      'MJ: AI Agents',
      'MJ: AI Configurations',
    ]);
  });

  it('uses the DISPLAY name for an FK-index item, not the bare table name', () => {
    const block = ['-- Entity: MJ: AI Agent Runs', '-- Item: Index for Foreign Keys', 'CREATE INDEX i ON __mj."AIAgentRun" ("AgentID");'].join('\n');
    expect(extractAffectedEntities(block)).toEqual(['MJ: AI Agent Runs']);
  });

  it('excludes the table-name `Index for Foreign Keys for <Table>` provenance form', () => {
    const block = '/* Index for Foreign Keys for AIAgentRun */\nCREATE INDEX i ON __mj."AIAgentRun" ("AgentID");';
    expect(extractAffectedEntities(block)).toEqual([]);
  });

  it('excludes entities merely mentioned in metadata DML / inline registration comments', () => {
    const block = [
      '/* SQL text to insert new entity field */',
      'IF NOT EXISTS (SELECT 1 FROM __mj."EntityField" ...) BEGIN',
      '  INSERT INTO __mj."EntityField" ("ID","EntityID") VALUES (',
      "    'ae864635-13fe-474c-bcd9-2238a8cdd682', -- Entity: MJ: AI Agent Runs",
      '  );',
      'END;',
      '/* Set field properties for entity */',
      'UPDATE __mj."EntityField" SET "DefaultInView" = TRUE WHERE "ID" = \'x\';',
    ].join('\n');
    // The inline `-- Entity:` is not line-anchored and not a generated-item header → excluded.
    expect(extractAffectedEntities(block)).toEqual([]);
  });

  it('does not capture a line-anchored `-- Entity:` that does not head a generated item', () => {
    const block = ['-- Entity: MJ: Should Not Count', 'SELECT 1;'].join('\n');
    expect(extractAffectedEntities(block)).toEqual([]);
  });

  it('is wired into splitMigration (affectedEntities populated from the codegen block; [] for hand-only)', () => {
    const sql = [
      '-- hand-authored header',
      'ALTER TABLE __mj.AIAgentRun ADD LastHeartbeatAt TIMESTAMPTZ NULL;',
      '',
      '/* Base View SQL for MJ: AI Agent Runs */',
      '-----------------------------------------------------------------',
      '-- This was generated by the MemberJunction CodeGen tool.',
      '-----------------------------------------------------------------',
      'CREATE VIEW __mj."vwAIAgentRuns" AS SELECT 1;',
    ].join('\n');
    expect(splitMigration(sql, 'feature.sql').affectedEntities).toEqual(['MJ: AI Agent Runs']);

    const handOnly = 'CREATE TABLE __mj.Foo (ID INT);\nALTER TABLE __mj.Foo ADD Name NVARCHAR(50);';
    expect(splitMigration(handOnly).affectedEntities).toEqual([]);
  });
});
