import { describe, it, expect } from 'vitest';
import { splitMigration } from '../MigrationSplitter.js';

/** Minimal reproduction of a CodeGen item header block. */
const codegenItem = (title: string, body: string) =>
  [
    `/* ${title} */`,
    '-----------------------------------------------------------------',
    '-- SQL Code Generation',
    '-- Item: ' + title,
    '--',
    '-- This was generated by the MemberJunction CodeGen tool.',
    '-- This file should NOT be edited by hand.',
    '-----------------------------------------------------------------',
    body,
  ].join('\n');

describe('splitMigration', () => {
  describe('boundary detection', () => {
    it('splits at the /* opener of the first banner-marked item (no run delimiter)', () => {
      const sql = [
        '-- hand-authored header',
        "ALTER TABLE __mj.Foo ADD Bar INT NULL;",
        '',
        codegenItem('Base View SQL for Foo', 'CREATE VIEW __mj.vwFoos AS SELECT 1;'),
      ].join('\n');

      const r = splitMigration(sql, 'feature.sql');
      expect(r.boundaryMethod).toBe('first-item-banner');
      // boundary points at the `/*` opener line (line 4)
      expect(r.codeGenBoundaryLine).toBe(4);
      expect(r.handAuthored).toContain('ALTER TABLE __mj.Foo');
      expect(r.handAuthored).not.toContain('CREATE VIEW');
      expect(r.codeGenBlock).toContain('/* Base View SQL for Foo */');
      expect(r.codeGenBlock).toContain('CREATE VIEW __mj.vwFoos');
    });

    it('prefers an explicit -- CODE GEN RUN delimiter when present', () => {
      const sql = [
        'CREATE TABLE __mj.Foo (ID INT);',
        '-- CODE GEN RUN (appended from CodeGen_Run_2026-05-22_21-31-40.sql)',
        codegenItem('spCreate SQL for Foo', 'CREATE PROCEDURE __mj.spCreateFoo AS BEGIN SELECT 1; END;'),
      ].join('\n');

      const r = splitMigration(sql);
      expect(r.boundaryMethod).toBe('code-gen-run-delimiter');
      expect(r.codeGenBoundaryLine).toBe(2);
      expect(r.handAuthored).toContain('CREATE TABLE __mj.Foo');
      // The generated spCreate must NOT leak into the hand region (so it isn't
      // misclassified as hand-procedural).
      expect(r.handAuthoredRegions.some((f) => f.kind === 'hand-procedural')).toBe(false);
      expect(r.routing).toBe('transpile-only');
    });

    it('reports no codegen block for a pure hand-authored file', () => {
      const sql = "CREATE TABLE __mj.Foo (ID INT);\nALTER TABLE __mj.Foo ADD Name NVARCHAR(50);";
      const r = splitMigration(sql);
      expect(r.boundaryMethod).toBe('no-codegen-block');
      expect(r.codeGenBoundaryLine).toBeNull();
      expect(r.codeGenBlock).toBe('');
      expect(r.handAuthored).toBe(sql);
    });
  });

  describe('hand-region classification & routing', () => {
    it('routes regular DDL as transpile-only', () => {
      const sql = [
        'CREATE TABLE __mj.Foo (ID UNIQUEIDENTIFIER NOT NULL);',
        'CREATE INDEX IX_Foo ON __mj.Foo(ID);',
        "INSERT INTO __mj.Bar (ID) VALUES ('x');",
      ].join('\n');
      const r = splitMigration(sql);
      expect(r.routing).toBe('transpile-only');
      expect(r.handAuthoredRegions.map((f) => f.kind)).toContain('schema-ddl');
    });

    it('flags hand-written procedural SQL as needs-hand-authoring', () => {
      const sql = [
        'CREATE TABLE __mj.Foo (ID INT);',
        'GO',
        'CREATE OR ALTER PROCEDURE __mj.spClaimNextJob AS',
        'BEGIN',
        '  UPDATE __mj.Job SET Claimed = 1;',
        'END;',
      ].join('\n');
      const r = splitMigration(sql, 'Scheduling_Engine_Atomic_Sprocs.sql');
      expect(r.routing).toBe('needs-hand-authoring');
      const proc = r.handAuthoredRegions.find((f) => f.kind === 'hand-procedural');
      expect(proc).toBeDefined();
      expect(proc!.line).toBe(3);
    });

    it('detects mj-sync metadata seed (hashed vars) as transpile-plus-reseed', () => {
      const sql = [
        'DECLARE @Name_da319a9d NVARCHAR(50),',
        '        @Description_da319a9d NVARCHAR(MAX);',
        "SET @Name_da319a9d = 'GPT';",
        'EXEC __mj.spCreateAIModel @Name = @Name_da319a9d;',
      ].join('\n');
      const r = splitMigration(sql, 'Metadata_Sync.sql');
      expect(r.routing).toBe('transpile-plus-reseed');
      expect(r.handAuthoredRegions.some((f) => f.kind === 'metadata-sync')).toBe(true);
    });

    it('detects mj-sync by the SQL Logging Session header (header lives in a comment)', () => {
      const sql = [
        '-- SQL Logging Session',
        '-- Description: MetadataSync push operation',
        '-- Generated by MemberJunction',
        '',
        'EXEC __mj.spUpdateTemplate @ID = 1;',
      ].join('\n');
      const r = splitMigration(sql, 'V_Metadata_Sync.sql');
      expect(r.routing).toBe('transpile-plus-reseed');
      const f = r.handAuthoredRegions.find((x) => x.kind === 'metadata-sync');
      expect(f?.evidence).toBe('MetadataSync push operation');
    });

    it('does NOT route an inline EXEC spCreate (no mj-sync fingerprints) to reseed', () => {
      // A feature migration that seeds a row by hand — no hashed vars, no session
      // header. This is plain DML the converter handles, not mj-sync-owned content.
      const sql = [
        'CREATE TABLE __mj.Widget (ID UNIQUEIDENTIFIER NOT NULL);',
        "EXEC __mj.spCreateWidget @Name = 'Gizmo';",
      ].join('\n');
      const r = splitMigration(sql, 'Feature.sql');
      expect(r.routing).toBe('transpile-only');
      expect(r.handAuthoredRegions.some((f) => f.kind === 'metadata-sync')).toBe(false);
    });
  });

  describe('comment / string awareness', () => {
    it('does not classify keywords that appear only inside comments', () => {
      const sql = [
        '-- This migration used to CREATE PROCEDURE but no longer does.',
        '/* CREATE TRIGGER example in a block comment */',
        'ALTER TABLE __mj.Foo ADD Note NVARCHAR(50);',
      ].join('\n');
      const r = splitMigration(sql);
      expect(r.routing).toBe('transpile-only');
      expect(r.handAuthoredRegions.some((f) => f.kind === 'hand-procedural')).toBe(false);
    });

    it('does not classify keywords inside string literals', () => {
      const sql = "INSERT INTO __mj.Doc (Body) VALUES ('You can CREATE FUNCTION here');";
      const r = splitMigration(sql);
      expect(r.handAuthoredRegions.some((f) => f.kind === 'hand-procedural')).toBe(false);
      expect(r.handAuthoredRegions.some((f) => f.kind === 'data-dml')).toBe(true);
    });

    it('does not classify keywords inside MULTI-LINE string literals', () => {
      // Regression: the in-string state reset per line, so continuation lines of a
      // prompt-template literal mentioning ALTER/CREATE TABLE were scanned as code
      // (live corpus hit: V202605021448 Metadata_Sync mis-routed to transpile).
      const sql = [
        "SET @Description = N'This template shows how to",
        'CREATE TABLE Foo and ALTER TABLE Bar in SQL.',
        "End of template';",
      ].join('\n');
      const r = splitMigration(sql);
      expect(r.handAuthoredRegions.some((f) => f.kind === 'schema-ddl')).toBe(false);
    });

    it("handles doubled-quote escapes across the multi-line literal", () => {
      const sql = [
        "SET @Description = N'It''s a template that says",
        "''CREATE TABLE'' is just text here';",
        'ALTER TABLE __mj.Foo ADD Note NVARCHAR(50);',
      ].join('\n');
      const r = splitMigration(sql);
      // The real ALTER TABLE after the literal IS classified; the quoted one is not.
      expect(r.handAuthoredRegions.filter((f) => f.kind === 'schema-ddl')).toHaveLength(1);
    });
  });
});
