import { describe, it, expect } from 'vitest';
import { convertMigration, extractKeptTSQL, type TSQLToPGTranspiler } from '../MigrationConverter.js';

const codegenItem = (title: string, body: string) =>
  [
    `/* ${title} */`,
    '-----------------------------------------------------------------',
    '-- This was generated by the MemberJunction CodeGen tool.',
    '-----------------------------------------------------------------',
    body,
  ].join('\n');

/**
 * Passthrough stub — returns the kept T-SQL verbatim so tests can assert on what
 * classification fed the transpiler, without a Python runtime. The real
 * implementation is MJPostgresTranspiler in @memberjunction/sqlglot-ts.
 */
const passthrough: TSQLToPGTranspiler = {
  transpile: async (tsql) => ({ sql: tsql.split(/\nGO\n/), unhandled: [] }),
};

describe('convertMigration — reconciliation (issue #3252 Phase 3)', () => {
  it('flags suspiciousEmptyOutput when substantive kept T-SQL vanishes (no output, no gaps)', async () => {
    // A "vanishing" transpiler simulates the RC1 failure mode at the conversion layer: the
    // classifier fed real DDL to the dialect, but nothing came out and nothing was reported.
    // The dialect's own EMPTY-EMISSION guard should prevent this, but convertMigration must
    // catch it as belt-and-suspenders — never a clean result over content that disappeared.
    const vanishing: TSQLToPGTranspiler = { transpile: async () => ({ sql: [], unhandled: [] }) };
    const sql = 'CREATE TABLE [__mj].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );';
    const r = await convertMigration(sql, 'V_Widget.sql', { transpiler: vanishing });
    expect(r.reconciliation.suspiciousEmptyOutput).toBe(true);
    // …and it is surfaced as a gap so the CLI fails the run rather than shipping an empty file.
    expect(r.unhandled.some((u) => u.kind === 'RECONCILIATION-EMPTY-OUTPUT')).toBe(true);
  });

  it('does NOT flag a normal conversion; reports source/emitted counts', async () => {
    const sql = 'CREATE TABLE [__mj].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );';
    const r = await convertMigration(sql, 'V_Widget.sql', { transpiler: passthrough });
    expect(r.reconciliation.suspiciousEmptyOutput).toBe(false);
    expect(r.reconciliation.sourceStatements).toBeGreaterThan(0);
    expect(r.reconciliation.emittedStatements).toBeGreaterThan(0);
  });

  it('does NOT flag a legitimate reseed/regen marker (classifier found nothing translatable)', async () => {
    // A pure mj-sync metadata file legitimately produces an empty marker — trust the
    // classifier, do not second-guess it at the reconciliation layer.
    const sql = [
      '-- MetadataSync push operation',
      "DECLARE @Name_da319a9d NVARCHAR(100) = N'X';",
      "INSERT INTO [__mj].[AIModel] ([ID],[Name]) VALUES ('aaaa', @Name_da319a9d);",
    ].join('\n');
    const r = await convertMigration(sql, 'V_Metadata_Sync.sql', { transpiler: passthrough });
    expect(r.status).toBe('reseed-or-regen-only');
    expect(r.reconciliation.suspiciousEmptyOutput).toBe(false);
    expect(r.reconciliation.emittedStatements).toBe(0);
  });

  it('does NOT flag suspiciousEmptyOutput when the dialect intentionally DROPPED the content', async () => {
    // An all-dropped file (e.g. kept T-SQL is only an actionless ALTER that PG discards) emits
    // nothing and reports nothing, but the content did not VANISH — it was accounted as dropped.
    // The guard must look at `dropped` too, or it false-positives on a legitimate empty output.
    const allDropped: TSQLToPGTranspiler = {
      transpile: async () => ({ sql: [], unhandled: [], dropped: [{ kind: 'ALTER-ACTIONLESS', snippet: 'ALTER TABLE x' }] }),
    };
    const sql = 'ALTER TABLE [__mj].[Widget] ADD CONSTRAINT CK CHECK (ISJSON([X]) = 1);';
    const r = await convertMigration(sql, 'V_Widget.sql', { transpiler: allDropped });
    expect(r.reconciliation.suspiciousEmptyOutput).toBe(false);
    expect(r.unhandled.some((u) => u.kind === 'RECONCILIATION-EMPTY-OUTPUT')).toBe(false);
  });

  it('flags a hand-authored object silently dropped to a clean marker (issue #3252 Phase 4)', async () => {
    // A hand-authored VIEW whose name does NOT match a CodeGen convention (so `mj codegen` will
    // NOT regenerate it) can be routed to an empty marker by the classifier. Returning a clean
    // reseed/regen marker there is exactly the RC1 silent-drop class — the marker path must
    // reconcile source statements against what was kept/reported before trusting the emptiness.
    const sql = 'CREATE VIEW [__mj].[CustomerSummary] AS SELECT [ID], [Total] FROM [__mj].[Orders];';
    const r = await convertMigration(sql, 'V_CustomerSummary.sql', { transpiler: passthrough });
    expect(r.reconciliation.suspiciousEmptyOutput).toBe(true);
    expect(r.unhandled.some((u) => u.kind === 'RECONCILIATION-EMPTY-OUTPUT')).toBe(true);
  });

  it('substitutes ${mjSchema} independently of ${flyway:defaultSchema} (issue #3838)', async () => {
    // An Open App migration names its OWN schema with ${flyway:defaultSchema} and MJ CORE with
    // ${mjSchema}; for every app those are different values. Only the first was substituted, so
    // `${mjSchema}` survived into the emitted file AND into the SQL --bake-codegen executes,
    // failing with: relation "${mjSchema}.Entity" does not exist.
    const sql = [
      'CREATE TABLE [${flyway:defaultSchema}].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );',
      'GO',
      "UPDATE [${mjSchema}].[Entity] SET [Name] = 'W' WHERE [ID] = '1';",
    ].join('\n');
    const r = await convertMigration(sql, 'V_Widget.sql', {
      transpiler: passthrough,
      schema: '__mj_bizappscommon',
      coreSchema: '__mj',
    });
    expect(r.pgSQL).not.toContain('${mjSchema}');
    expect(r.pgSQL).not.toContain('${flyway:defaultSchema}');
    // The app's own object resolves to the app schema…
    expect(r.pgSQL).toContain('__mj_bizappscommon');
    // …and core resolves to core, NOT to the app schema.
    expect(r.pgSQL).not.toContain('__mj_bizappscommon"."Entity"');
    expect(r.pgSQL).toMatch(/__mj["\].]*\.?\[?"?Entity/);
  });

  it('defaults ${mjSchema} to __mj when no coreSchema is supplied', async () => {
    const sql = "UPDATE [${mjSchema}].[Entity] SET [Name] = 'W' WHERE [ID] = '1';\nGO\nCREATE TABLE [x].[Y] ( [ID] INT );";
    const r = await convertMigration(sql, 'V_Widget.sql', { transpiler: passthrough, schema: '__mj_app' });
    expect(r.pgSQL).not.toContain('${mjSchema}');
    // The app schema is deliberately '__mj_app', which CONTAINS '__mj' as a substring — so
    // `toContain('__mj')` cannot tell the default apart from the bug this PR fixes, where the
    // core placeholder falls back to the app schema. pgHeader() emits
    // `CREATE SCHEMA IF NOT EXISTS __mj;` besides, which satisfies that assertion on its own
    // whether or not the token was substituted at all. Assert on the qualified reference:
    // negative on the wrong schema, positive on the right one.
    expect(r.pgSQL).not.toContain('[__mj_app].[Entity]');
    expect(r.pgSQL).toContain('[__mj].[Entity]');
  });

  it('reflects a dialect ACCOUNTING-LEAK in reconciliation', async () => {
    const leaky: TSQLToPGTranspiler = {
      transpile: async (t) => ({ sql: [t], unhandled: [{ kind: 'ACCOUNTING-LEAK', snippet: 'parsed=3 but …' }] }),
    };
    const sql = 'CREATE TABLE [__mj].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );';
    const r = await convertMigration(sql, 'V_Widget.sql', { transpiler: leaky });
    expect(r.reconciliation.accountingLeak).toBe(true);
  });
});

describe('convertMigration', () => {
  it('transpiles regular DDL and drops the CodeGen block', async () => {
    const sql = [
      'CREATE TABLE [__mj].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );',
      codegenItem('spCreate SQL for Widget', 'CREATE PROCEDURE [__mj].[spCreateWidget] AS BEGIN SELECT 1 END'),
    ].join('\n');

    const r = await convertMigration(sql, 'V_Widget.sql', { transpiler: passthrough });
    expect(r.status).toBe('converted');
    // CodeGen sproc must not appear in the PG output — it is regenerated, not translated.
    expect(r.pgSQL).not.toContain('spCreateWidget');
    expect(r.droppedCodeGenLines).toBeGreaterThan(0);
    // Regular DDL was fed to the transpiler.
    expect(r.pgSQL).toContain('Widget');
    expect(r.notes.some((n) => n.includes('regenerated natively'))).toBe(true);
  });

  it('throws when kept T-SQL exists but no transpiler was provided (content is never dropped)', async () => {
    const sql = 'CREATE TABLE [__mj].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );';
    await expect(convertMigration(sql, 'V_Widget.sql')).rejects.toThrow(/transpiler/);
  });

  it('emits transpiled DDL AND flags the file when hand-written procedural SQL is present', async () => {
    // Regression (ClusterAnalysisCluster lesson): a needs-hand file must still emit its
    // schema DDL — only the routines are gaps, not the whole file.
    const sql = [
      'CREATE TABLE __mj.Job (ID INT);',
      'GO',
      'CREATE OR ALTER PROCEDURE __mj.spClaimJob AS BEGIN UPDATE __mj.Job SET X=1; END;',
    ].join('\n');
    const r = await convertMigration(sql, 'Scheduling_Engine_Atomic_Sprocs.sql', { transpiler: passthrough });
    expect(r.status).toBe('needs-hand-authoring');
    expect(r.pgSQL).toContain('NEEDS HAND-AUTHORING');
    expect(r.handProcedural.length).toBeGreaterThan(0);
    // The CREATE TABLE was NOT discarded along with the routine.
    expect(r.pgSQL).toContain('CREATE TABLE');
  });

  it('treats a pure mj-sync Metadata_Sync file as reseed-or-regen-only (no DDL emitted)', async () => {
    const sql = [
      '-- SQL Logging Session',
      '-- Description: MetadataSync push operation',
      'DECLARE @Name_da319a9d NVARCHAR(50);',
      "SET @Name_da319a9d = 'GPT';",
      'EXEC __mj.spCreateAIModel @Name = @Name_da319a9d;',
    ].join('\n');
    const r = await convertMigration(sql, 'V_Metadata_Sync.sql', { transpiler: passthrough });
    expect(r.status).toBe('reseed-or-regen-only');
    expect(r.pgSQL).toContain('mj sync push');
    // No spCreate call carried into the PG output — it is re-seeded, not transpiled.
    expect(r.pgSQL).not.toContain('spCreateAIModel');
  });

  it('keeps an mj-sync file as reseed even when it contains incidental data DML (not schema DDL)', async () => {
    // Regression: a 964k-line Metadata_Sync file was mis-routed to "converted"
    // because an INSERT/UPDATE matched the DDL regex. Data DML in an mj-sync file
    // is the metadata seed itself — reproduced by `mj sync push`, never transpiled.
    const sql = [
      '-- SQL Logging Session',
      '-- Description: MetadataSync push operation',
      'DECLARE @Name_da319a9d NVARCHAR(50);',
      'UPDATE __mj.AIModel SET Name = @Name_da319a9d WHERE ID = 1;',
      'EXEC __mj.spCreateAIModel @Name = @Name_da319a9d;',
    ].join('\n');
    const r = await convertMigration(sql, 'V202604271430__Metadata_Sync.sql', { transpiler: passthrough });
    expect(r.status).toBe('reseed-or-regen-only');
    expect(r.pgSQL).not.toContain('spCreateAIModel');
  });

  it('keeps an mj-sync file as reseed when a multi-line string literal contains DDL-looking text', async () => {
    // Regression: stripCommentsPreservingLines reset its in-string state per line, so a
    // prompt-template literal spanning lines whose content mentions "ALTER TABLE" was
    // scanned as code → schema-ddl finding → the whole metadata seed was mis-routed to
    // the transpiler (live corpus hit: V202605021448 Metadata_Sync, 14k lines).
    const sql = [
      '-- SQL Logging Session',
      '-- Description: MetadataSync push operation',
      "SET @Description_da319a9d = N'This template shows how to",
      'CREATE TABLE Foo and ALTER TABLE Bar in SQL.',
      "End of template';",
      'EXEC __mj.spUpdateAIPrompt @Description = @Description_da319a9d;',
    ].join('\n');
    const r = await convertMigration(sql, 'V202605021448__Metadata_Sync.sql', { transpiler: passthrough });
    expect(r.status).toBe('reseed-or-regen-only');
    expect(r.pgSQL).not.toContain('spUpdateAIPrompt');
  });

  it('transpiles a Backfill_* data migration (data DML, no mj-sync fingerprints)', async () => {
    const sql = "UPDATE __mj.UserView SET ViewTypeID = 'x' WHERE ViewTypeID IS NULL;";
    const r = await convertMigration(sql, 'V_Backfill_UserView_ViewTypeID.sql', { transpiler: passthrough });
    expect(r.status).toBe('converted');
  });

  it('treats a pure CodeGen-only file as reseed-or-regen-only', async () => {
    const sql = [
      '-- regen only',
      codegenItem('spDelete SQL for Foo', 'CREATE PROCEDURE __mj.spDeleteFoo AS BEGIN DELETE FROM __mj.Foo END'),
    ].join('\n');
    const r = await convertMigration(sql, 'spDelete_Force_Regen.sql', { transpiler: passthrough });
    expect(r.status).toBe('reseed-or-regen-only');
    expect(r.pgSQL).not.toContain('spDeleteFoo');
    expect(r.pgSQL).toContain('mj codegen');
  });

  it('recovers entity-registration INSERTs through the convertMigration path (not just extractKeptTSQL)', async () => {
    // Regression: the registration-recovery fix originally landed only in extractKeptTSQL;
    // the CLI path (convertMigration) had a copy-pasted routing that skipped it, so new
    // entities (KnowledgeHub) never registered on PG. Single classification path now.
    const sql = [
      'CREATE TABLE [${flyway:defaultSchema}].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );',
      'GO',
      '-- CODE GEN RUN',
      '/* SQL generated to create new entity MJ: Widgets */',
      "INSERT INTO [${flyway:defaultSchema}].[Entity] ([ID],[Name]) VALUES ('aaaa', 'MJ: Widgets');",
    ].join('\n');
    const r = await convertMigration(sql, 'V_Widgets_Feature.sql', { transpiler: passthrough });
    expect(r.status).toBe('converted');
    expect(r.pgSQL).toContain("'MJ: Widgets'");
  });

  it('substitutes the flyway schema macro in the final output', async () => {
    const sql = 'CREATE TABLE [${flyway:defaultSchema}].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );';
    const r = await convertMigration(sql, 'V_Widget.sql', { transpiler: passthrough });
    expect(r.pgSQL).not.toContain('${flyway:defaultSchema}');
    expect(r.pgSQL).toContain('__mj');
  });

  it('embeds transpiler-unhandled statements as gap comments and reports them', async () => {
    const reporting: TSQLToPGTranspiler = {
      transpile: async () => ({
        sql: ['CREATE TABLE __mj."T" ("ID" UUID NOT NULL)'],
        unhandled: [{ kind: 'Command', snippet: 'EXEC sp_rename ...' }],
      }),
    };
    const sql = 'CREATE TABLE [__mj].[T] ([ID] UNIQUEIDENTIFIER NOT NULL);\nGO\nEXEC sp_rename ...;';
    const r = await convertMigration(sql, 'V_Rename.sql', { transpiler: reporting });
    expect(r.unhandled).toHaveLength(1);
    expect(r.pgSQL).toContain('UNHANDLED BY THE AST TRANSPILER');
    expect(r.pgSQL).toContain('sp_rename');
  });
});

describe('extractKeptTSQL — statement mode (unbannered snapshots)', () => {
  const snapshot = (...batches: string[]) => batches.join('\nGO\n');

  it('keeps unknown batches so the transpiler decides (never silently dropped)', () => {
    const sql = snapshot(
      'CREATE TABLE [__mj].[T] ([ID] INT);',
      'CREATE VIEW [__mj].[vwTs] AS SELECT * FROM [__mj].[T];', // codegen-object → triggers statement mode
      "EXEC sp_rename '__mj.T.Old', 'New', 'COLUMN';", // unknown
    );
    const kept = extractKeptTSQL(sql, 'B_Baseline.sql');
    expect(kept.tsql).toContain('sp_rename');
    expect(kept.tsql).not.toContain('vwTs');
    expect(kept.droppedObjects.some((o) => o.includes('vwTs'))).toBe(true);
  });

  it('keeps DECLARE-led batches (real seed statements, not noise)', () => {
    const sql = snapshot(
      'CREATE TABLE [__mj].[T] ([ID] INT);',
      'CREATE VIEW [__mj].[vwTs] AS SELECT * FROM [__mj].[T];',
      "DECLARE @ID UNIQUEIDENTIFIER = 'aaaa'; INSERT INTO [__mj].[CustomThing] ([ID]) VALUES (@ID);",
    );
    const kept = extractKeptTSQL(sql, 'B_Baseline.sql');
    expect(kept.tsql).toContain('CustomThing');
  });

  it('keeps allowlisted hand-written views despite the codegen vw* naming convention', () => {
    const sql = snapshot(
      'CREATE TABLE [__mj].[T] ([ID] INT);',
      'CREATE VIEW [__mj].[vwTs] AS SELECT * FROM [__mj].[T];',
      'CREATE VIEW [__mj].[vwEntitiesWithExternalChangeTracking] AS SELECT 1 AS X;',
    );
    const kept = extractKeptTSQL(sql, 'B_Baseline.sql');
    expect(kept.tsql).toContain('vwEntitiesWithExternalChangeTracking');
    expect(kept.tsql).not.toContain('[vwTs]');
  });

  it('keeps hand-procedural batches in the stream and flags the file', () => {
    const sql = snapshot(
      'CREATE TABLE [__mj].[T] ([ID] INT);',
      'CREATE VIEW [__mj].[vwTs] AS SELECT * FROM [__mj].[T];',
      'CREATE PROCEDURE [__mj].[GetWeirdStuff] AS BEGIN SELECT 1 END;',
    );
    const kept = extractKeptTSQL(sql, 'B_Baseline.sql');
    expect(kept.status).toBe('needs-hand-authoring');
    expect(kept.handProcedural.some((h) => h.includes('GetWeirdStuff'))).toBe(true);
    expect(kept.tsql).toContain('GetWeirdStuff');
  });

  it('reports dropped metadata DML in the notes for NON-baseline snapshots (audit trail)', () => {
    const sql = snapshot(
      'CREATE TABLE [__mj].[T] ([ID] INT);',
      'CREATE VIEW [__mj].[vwTs] AS SELECT * FROM [__mj].[T];',
      "INSERT INTO [__mj].[Entity] ([ID],[Name]) VALUES ('aaaa','T');",
    );
    const kept = extractKeptTSQL(sql, 'V_Old_Unbannered_Snapshot.sql');
    expect(kept.notes[0]).toMatch(/1 metadata DML/);
    expect(kept.tsql).not.toContain('INSERT INTO [__mj].[Entity]');
  });

  it('BASELINES keep their metadata DML (the point-in-time seed codegen boots from)', () => {
    // A fresh PG install seeds metadata from the baseline itself — codegen cannot run
    // on empty Entity/EntityField, and `mj sync push` only owns the curated subset.
    const sql = snapshot(
      'CREATE TABLE [__mj].[T] ([ID] INT);',
      'CREATE VIEW [__mj].[vwTs] AS SELECT * FROM [__mj].[T];',
      "INSERT INTO [__mj].[Entity] ([ID],[Name]) VALUES ('aaaa','T');",
    );
    const kept = extractKeptTSQL(sql, 'B202605291452__v5.38.x__Baseline.sql');
    expect(kept.tsql).toContain('INSERT INTO [__mj].[Entity]');
    expect(kept.tsql).not.toContain('vwTs');
  });

  it('drops auto-generated FK indexes (IDX_AUTO_MJ_FKEY_*) — regenerated collision-safe by codegen', () => {
    // Two long SS FK-index names truncate to the same 63-char PG identifier → collision. They are
    // CodeGen output, so drop them here and let native PG codegen re-emit (truncation + hash).
    const sql = snapshot(
      'CREATE TABLE [__mj].[T] ([ID] INT);',
      'CREATE VIEW [__mj].[vwTs] AS SELECT * FROM [__mj].[T];',
      'CREATE INDEX [IDX_AUTO_MJ_FKEY_CommunicationProviderMessageType_CommunicationBaseMessageTypeID] ON [__mj].[CommunicationProviderMessageType] ([CommunicationBaseMessageTypeID]);',
      'CREATE INDEX [IDX_Custom_HandAuthored] ON [__mj].[T] ([ID]);', // hand-authored → kept
    );
    const kept = extractKeptTSQL(sql, 'B202605291452__v5.38.x__Baseline.sql');
    expect(kept.tsql).not.toContain('IDX_AUTO_MJ_FKEY_');
    expect(kept.tsql).toContain('IDX_Custom_HandAuthored');
    expect(kept.droppedObjects.some((o) => o.includes('auto FK'))).toBe(true);
  });
});

describe('extractKeptTSQL — hand-written trigger not misclassified (issue #3252 RC2)', () => {
  // The bare `trg` alternative in CODEGEN_NAME classified EVERY trigger as a CodeGen object,
  // flipping this hand-written-trigger file into statement-mode where the trigger was DROPPED
  // and the file reported a clean 'converted' with empty T-SQL. It must be needs-hand-authoring.
  const handTrigger = [
    '-- Fix: concurrent same-conversation inserts deadlock (hand-authored PG port required)',
    'GO',
    'CREATE OR ALTER TRIGGER [${flyway:defaultSchema}].[trgConversationDetail_AssignSequence]',
    'ON [${flyway:defaultSchema}].[ConversationDetail]',
    'AFTER INSERT AS',
    'BEGIN',
    '    SET NOCOUNT ON;',
    '    UPDATE [${flyway:defaultSchema}].[ConversationDetail] SET [Sequence] = 1;',
    'END',
    'GO',
  ].join('\n');

  it('routes a hand trigger to needs-hand-authoring, never silently dropped', () => {
    const kept = extractKeptTSQL(handTrigger, 'V202607202110__v5.49.x__Fix_ConversationDetail_Sequence_Deadlock.sql');
    expect(kept.status).toBe('needs-hand-authoring');
    // The file is flagged as carrying a hand-written routine (banner-mode evidence is the
    // matched CREATE … TRIGGER keyword), and the trigger body survives into the kept T-SQL
    // so a human can author the PG port — NOT dropped with an empty 'converted' stub.
    expect(kept.handProcedural.length).toBeGreaterThan(0);
    expect(kept.handProcedural.some((h) => /TRIGGER/i.test(h))).toBe(true);
    expect(kept.tsql).toContain('trgConversationDetail_AssignSequence');
  });

  it('still classifies a CodeGen trgUpdate* trigger as a regenerated codegen object', () => {
    // A genuine snapshot (has a vw* codegen object) with a trgUpdate trigger stays in
    // statement-mode and the trgUpdate trigger is dropped (regenerated by mj codegen).
    const snapshot = [
      'CREATE TABLE [__mj].[T] ([ID] INT);',
      'CREATE VIEW [__mj].[vwT] AS SELECT * FROM [__mj].[T];',
      'CREATE TRIGGER [__mj].[trgUpdateT] ON [__mj].[T] AFTER UPDATE AS BEGIN SET NOCOUNT ON; END;',
    ].join('\nGO\n');
    const kept = extractKeptTSQL(snapshot, 'B202605291452__v5.38.x__Baseline.sql');
    expect(kept.droppedObjects.some((o) => o.includes('trgUpdateT'))).toBe(true);
    expect(kept.tsql).not.toContain('trgUpdateT');
  });

  it('a lone codegen trigger (no vw/sp) does NOT flip an unbannered file into statement-mode', () => {
    // Defense-in-depth (2b): only a vw*/sp* codegen-object marks a genuine squashed snapshot.
    // A file whose only "codegen object" is a trigger (or index) must stay banner-mode, where
    // its hand ALTER is transpiled and the trigger is flagged — NOT statement-mode, where a
    // lone false-positive could drop OTHER batches. Without 2b this file flips to statement
    // mode (the trigger is a codegen-object) and reports a clean 'converted'.
    const sql = [
      'ALTER TABLE [__mj].[Foo] ADD [Bar] INT NULL;',
      'CREATE TRIGGER [__mj].[trgUpdateFoo] ON [__mj].[Foo] AFTER UPDATE AS BEGIN SET NOCOUNT ON; END;',
    ].join('\nGO\n');
    const kept = extractKeptTSQL(sql, 'V_Some_Hand_File.sql');
    expect(kept.status).toBe('needs-hand-authoring');
    expect(kept.tsql).toContain('[Bar]'); // the hand ALTER survives, not dropped by a bad flip
  });
});

describe('extractKeptTSQL — entity-registration recovery from the CodeGen block', () => {
  // A feature migration whose CodeGen output sits below an explicit `-- CODE GEN RUN` banner.
  // The whole post-banner block is routed to codeGenBlock and dropped — but the entity
  // REGISTRATION rows (Entity / EntityField / …) have no schema-introspection source on PG,
  // so they must be recovered. Base-table seed rows and generated views/sprocs/grants stay dropped.
  const bannered = [
    'CREATE TABLE [${flyway:defaultSchema}].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );',
    'GO',
    '-- CODE GEN RUN',
    '/* SQL generated to create new entity MJ: Widgets */',
    "INSERT INTO [${flyway:defaultSchema}].[Entity] ([ID],[Name],[BaseView],[SchemaName]) " +
      "VALUES ('aaaa', 'MJ: Widgets', 'vwWidgets', '${flyway:defaultSchema}');",
    'GO',
    '/* SQL generated to add new entity MJ: Widgets to application */',
    "INSERT INTO [${flyway:defaultSchema}].[ApplicationEntity] ([ID],[EntityID]) VALUES ('bbbb','aaaa');",
    'GO',
    '/* SQL text to insert new entity field */',
    "IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[EntityField] WHERE ID = 'cccc') BEGIN " +
      "INSERT INTO [${flyway:defaultSchema}].[EntityField] ([ID],[EntityID],[Name]) VALUES ('cccc','aaaa','ID'); END",
    'GO',
    '/* base-table seed row — NOT a registration row, must stay dropped */',
    "INSERT INTO [${flyway:defaultSchema}].[Widget] ([ID]) VALUES ('dddd');",
    'GO',
    '/* generated view — regenerated by mj codegen, must stay dropped */',
    'CREATE VIEW [${flyway:defaultSchema}].[vwWidgets] AS SELECT * FROM [${flyway:defaultSchema}].[Widget];',
    'GO',
    'GRANT SELECT ON [${flyway:defaultSchema}].[vwWidgets] TO [cdp_UI];',
  ].join('\n');

  it('recovers Entity / ApplicationEntity / EntityField registration rows', () => {
    const kept = extractKeptTSQL(bannered, 'V_Widgets_Feature.sql');
    expect(kept.status).toBe('converted');
    expect(kept.tsql).toContain("'MJ: Widgets'");
    expect(kept.tsql).toContain('[ApplicationEntity]');
    expect(kept.tsql).toContain('[EntityField]');
  });

  it('does NOT recover base-table seed rows, generated views, or grants', () => {
    const kept = extractKeptTSQL(bannered, 'V_Widgets_Feature.sql');
    // The base-table seed INSERT (INSERT INTO Widget (...)) must not be recovered.
    expect(kept.tsql).not.toMatch(/INSERT\s+INTO\s+\[\$\{flyway:defaultSchema\}\]\.\[Widget\]\s*\(/i);
    expect(kept.tsql).not.toContain('CREATE VIEW');
    expect(kept.tsql).not.toContain('GRANT SELECT');
  });

  it('recovers the AdvancedGeneration curation tail (category UPDATEs + EntitySetting INSERTs)', () => {
    // AdvancedGeneration emits EntityField.Category / Entity.Icon UPDATEs and
    // EntitySetting INSERTs as ONE un-GO\'d batch headed by an UPDATE. PG codegen runs
    // without AdvancedGeneration, so this curation has no other source (live hit:
    // 12 eSignature FieldCategoryIcons/Info settings + field categories).
    const sql = [
      'CREATE TABLE [${flyway:defaultSchema}].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );',
      'GO',
      '-- CODE GEN RUN',
      '/* categorize fields */',
      "UPDATE [${flyway:defaultSchema}].[EntityField] SET Category = 'System Metadata' WHERE ID = 'aaaa';",
      "UPDATE [${flyway:defaultSchema}].[Entity] SET [Icon] = 'fa fa-cog' WHERE [ID] = 'bbbb';",
      "INSERT INTO [${flyway:defaultSchema}].[EntitySetting] ([ID],[EntityID],[Name],[Value]) VALUES ('cccc','bbbb','FieldCategoryInfo','{}');",
      'GO',
      'CREATE VIEW [${flyway:defaultSchema}].[vwWidgets] AS SELECT * FROM [${flyway:defaultSchema}].[Widget];',
    ].join('\n');
    const kept = extractKeptTSQL(sql, 'V_Widgets_Feature.sql');
    expect(kept.tsql).toContain("Category = 'System Metadata'");
    expect(kept.tsql).toContain('[EntitySetting]');
    expect(kept.tsql).not.toContain('CREATE VIEW');
  });

  it('recovers special-date-field statements (__mj_CreatedAt/__mj_UpdatedAt) for new entities', () => {
    // PG codegen does not reliably re-add the special date columns when the recovered
    // EntityField metadata already lists them (live hit: ClusterAnalysisCluster lost
    // __mj_UpdatedAt). The ADD/backfill/DEFAULT statements carry an exact provenance
    // comment and must survive the split.
    const sql = [
      'CREATE TABLE [${flyway:defaultSchema}].[Widget] ( [ID] UNIQUEIDENTIFIER NOT NULL );',
      'GO',
      '-- CODE GEN RUN',
      '/* SQL text to add special date field __mj_UpdatedAt to entity ${flyway:defaultSchema}.Widget */',
      'ALTER TABLE [${flyway:defaultSchema}].[Widget] ADD [__mj_UpdatedAt] DATETIMEOFFSET NULL;',
      'GO',
      '/* SQL text to add special date field __mj_UpdatedAt to entity ${flyway:defaultSchema}.Widget */',
      'ALTER TABLE [${flyway:defaultSchema}].[Widget] ADD CONSTRAINT [DF___mj_Widget___mj_UpdatedAt] DEFAULT GETUTCDATE() FOR [__mj_UpdatedAt];',
      'GO',
      '/* generated view — must stay dropped */',
      'CREATE VIEW [${flyway:defaultSchema}].[vwWidgets] AS SELECT * FROM [${flyway:defaultSchema}].[Widget];',
    ].join('\n');
    const kept = extractKeptTSQL(sql, 'V_Widgets_Feature.sql');
    expect(kept.tsql).toContain('[__mj_UpdatedAt] DATETIMEOFFSET');
    expect(kept.tsql).toContain('DF___mj_Widget___mj_UpdatedAt');
    expect(kept.tsql).not.toContain('CREATE VIEW');
  });

  it('recovers registration rows in a needs-hand file too (not skipped by the early return)', () => {
    // Regression: the needs-hand path returned before recovery ran, silently excluding
    // registration rows below the banner (live hit: IsComputed_To_EntityField).
    const sql = [
      'CREATE OR ALTER PROCEDURE [${flyway:defaultSchema}].[DoCustomMaintenance] AS BEGIN SELECT 1 END;',
      'GO',
      '-- CODE GEN RUN',
      '/* SQL text to insert new entity field */',
      "IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[EntityField] WHERE ID = 'cccc') BEGIN " +
        "INSERT INTO [${flyway:defaultSchema}].[EntityField] ([ID],[Name]) VALUES ('cccc','IsComputed'); END",
    ].join('\n');
    const kept = extractKeptTSQL(sql, 'V_Add_IsComputed.sql');
    expect(kept.status).toBe('needs-hand-authoring');
    expect(kept.tsql).toContain('IsComputed');
  });

  it('truncates a registration batch that bundles a view regeneration without a GO separator', () => {
    // CodeGen emits the EntityField inserts and the `----- BASE VIEW FOR ENTITY …` /
    // `IF OBJECT_ID(...,'V') DROP VIEW … CREATE VIEW …` block back-to-back in ONE GO-batch.
    // The registration prefix must be kept; the trailing generated view (which `mj codegen`
    // rebuilds, and whose DROP VIEW would fail on PG when dependents exist) must be dropped.
    const sql = [
      'CREATE TABLE [${flyway:defaultSchema}].[Thing] ( [ID] UNIQUEIDENTIFIER NOT NULL );',
      'GO',
      '-- CODE GEN RUN',
      '/* SQL text to insert new entity field */',
      "IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[EntityField] WHERE ID = 'ffff') BEGIN " +
        "INSERT INTO [${flyway:defaultSchema}].[EntityField] ([ID],[Name]) VALUES ('ffff','Title'); END",
      '------------------------------------------------------------',
      '----- BASE VIEW FOR ENTITY:      MJ: Things',
      '------------------------------------------------------------',
      "IF OBJECT_ID('[${flyway:defaultSchema}].[vwThings]', 'V') IS NOT NULL",
      'DROP VIEW [${flyway:defaultSchema}].[vwThings];',
      'GO',
      'CREATE VIEW [${flyway:defaultSchema}].[vwThings] AS SELECT * FROM [${flyway:defaultSchema}].[Thing];',
    ].join('\n');
    const kept = extractKeptTSQL(sql, 'V_Things_Feature.sql');
    expect(kept.tsql).toContain('[EntityField]');
    expect(kept.tsql).not.toMatch(/DROP\s+VIEW/i);
    expect(kept.tsql).not.toMatch(/CREATE\s+VIEW/i);
    expect(kept.tsql).not.toContain('OBJECT_ID');
  });

  it('leaves a no-banner feature file (registration rows already inline) unchanged in spirit', () => {
    // No `-- CODE GEN RUN` banner: the splitter keeps the registration INSERTs inline, so the
    // recovery is a no-op (codeGenBlock is empty) but the rows still survive.
    const noBanner = [
      'CREATE TABLE [${flyway:defaultSchema}].[Gadget] ( [ID] UNIQUEIDENTIFIER NOT NULL );',
      'GO',
      "INSERT INTO [${flyway:defaultSchema}].[Entity] ([ID],[Name]) VALUES ('eeee','MJ: Gadgets');",
    ].join('\n');
    const kept = extractKeptTSQL(noBanner, 'V_Gadgets_Feature.sql');
    expect(kept.tsql).toContain("'MJ: Gadgets'");
  });
});
