SELECT 
    t.TABLE_SCHEMA, 
    t.TABLE_NAME, 
    c.COLUMN_NAME
FROM 
    INFORMATION_SCHEMA.TABLES t
INNER JOIN 
    INFORMATION_SCHEMA.COLUMNS c ON c.TABLE_SCHEMA = t.TABLE_SCHEMA AND c.TABLE_NAME = t.TABLE_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON ccu.TABLE_SCHEMA = c.TABLE_SCHEMA AND ccu.TABLE_NAME = c.TABLE_NAME AND ccu.COLUMN_NAME = c.COLUMN_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc ON rc.CONSTRAINT_SCHEMA = ccu.CONSTRAINT_SCHEMA AND rc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ON tc.CONSTRAINT_SCHEMA = rc.UNIQUE_CONSTRAINT_SCHEMA AND tc.CONSTRAINT_NAME = rc.UNIQUE_CONSTRAINT_NAME AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
WHERE 
    c.COLUMN_NAME LIKE '%EntityID%' 
    AND t.TABLE_TYPE = 'BASE TABLE'
    AND tc.TABLE_NAME IS NULL
    AND t.TABLE_SCHEMA NOT IN ('sys', 'information_schema')
ORDER BY 
    t.TABLE_SCHEMA, 
    t.TABLE_NAME, 
    c.COLUMN_NAME;
