/**
 * Remove-flow tests for the migrations-model teardown (HandleTeardown).
 *
 * A connector's seed migration writes rows into the SHARED core schema (Integration/IO/IOF/Action
 * rows in __mj); dropping the app's OWN schema cannot reach them. On `mj app remove` the engine runs
 * the app's `migrations.teardownDirectory` scripts (inverse DELETEs, generated by the publisher's
 * build) against the live DB. These tests stub every external collaborator and assert teardown:
 *   1. downloads the teardown dir at the persisted version + subpath and runs each script via the
 *      provider, substituting ${mjSchema},
 *   2. is platform-aware (PostgreSQL → `<teardownDirectory>-pg/`),
 *   3. no-ops when the manifest declares no teardownDirectory,
 *   4. is skipped under --keep-data (teardown is data removal), and
 *   5. fails the remove loudly when a teardown script errors (never a silent partial remove).
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

vi.mock('../github/github-client.js', () => ({
    FetchManifestFromGitHub: vi.fn(),
    DownloadMigrations: vi.fn(),
    GetLatestVersion: vi.fn(),
    ValidateGitHubTag: vi.fn(),
    ParseGitHubUrl: (u: string) => {
        const m = u.match(/github\.com\/([^/?#]+)\/([^/?#]+)((?:\/[^?#]+)*)/);
        if (!m) return null;
        const sub = (m[3] ?? '').replace(/^\/+|\/+$/g, '');
        return { Owner: m[1], Repo: m[2].replace(/\.git$/, ''), Subpath: sub.length ? sub : undefined };
    },
}));
vi.mock('../install/schema-manager.js', () => ({
    CreateAppSchema: vi.fn(),
    DropAppSchema: vi.fn(),
    SchemaExists: vi.fn(),
    EscapeSqlString: (s: string) => s,
}));
vi.mock('../install/migration-runner.js', () => ({ RunAppMigrations: vi.fn() }));
vi.mock('../install/package-manager.js', () => ({
    AddAppPackages: vi.fn(),
    RemoveAppPackages: vi.fn(),
    RunPackageInstall: vi.fn(),
    BumpPrefixedDependencies: vi.fn(),
}));
vi.mock('../install/config-manager.js', () => ({
    AddServerDynamicPackages: vi.fn(),
    RemoveServerDynamicPackages: vi.fn(),
    ToggleServerDynamicPackages: vi.fn(),
    AddEntityPackageMapping: vi.fn(),
    RemoveEntityPackageMapping: vi.fn(),
    AddExcludeSchema: vi.fn(() => ({ Success: true })),
    RemoveExcludeSchema: vi.fn(() => ({ Success: true })),
    AddIncludeSchema: vi.fn(() => ({ Success: true })),
    RemoveIncludeSchema: vi.fn(() => ({ Success: true })),
}));
vi.mock('../install/client-bootstrap-gen.js', () => ({ RegenerateClientBootstrap: vi.fn() }));
vi.mock('../install/history-recorder.js', () => ({
    RecordAppInstallation: vi.fn(),
    RecordInstallHistoryEntry: vi.fn(),
    RecordAppDependencies: vi.fn(),
    DeleteAppDependencies: vi.fn(),
    SetAppStatus: vi.fn(),
    SetAppStep: vi.fn(),
    FindInstalledApp: vi.fn(),
    FindDependentApps: vi.fn(),
    CheckSchemaSharedByOtherApps: vi.fn(),
    ListInstalledApps: vi.fn(),
    UpdateAppRecord: vi.fn(),
}));
vi.mock('@memberjunction/core', () => ({
    Metadata: class { async CreateTransactionGroup() { return { Submit: async () => true }; } },
    // Enough shape for RemoveAppEntityMetadata, which runs for real (it lives in the orchestrator,
    // not a mockable module) whenever the removed app owns a schema no one else shares.
    RunView: class { async RunView() { return { Success: true, Results: [] }; } },
    BaseEntity: class {},
    DatabaseProviderBase: class {},
}));

import { RemoveApp } from '../install/install-orchestrator.js';
import type { OrchestratorContext } from '../install/install-orchestrator.js';
import { DownloadMigrations } from '../github/github-client.js';
import { RunPackageInstall } from '../install/package-manager.js';
import {
    FindInstalledApp,
    CheckSchemaSharedByOtherApps,
    FindDependentApps,
    ListInstalledApps,
    SetAppStatus,
    RecordInstallHistoryEntry,
    UpdateAppRecord,
} from '../install/history-recorder.js';
import { RemoveExcludeSchema } from '../install/config-manager.js';

/** A full Open App manifest (schema + migrations) whose migrations declare a teardownDirectory. */
function connectorManifest(withTeardown = true): string {
    return JSON.stringify({
        manifestVersion: 1,
        name: 'acme-connector',
        displayName: 'Acme Connector',
        description: 'Acme connector full Open App for teardown tests.',
        version: '1.2.0',
        publisher: { name: 'Acme' },
        repository: 'https://github.com/acme/mj-apps',
        mjVersionRange: '>=5.43.0 <6.0.0',
        schema: { name: 'mj_connector_acme', createIfNotExists: true },
        migrations: { directory: 'migrations', engine: 'skyway', ...(withTeardown ? { teardownDirectory: 'migrations-teardown' } : {}) },
        metadata: { directory: 'metadata' },
    });
}

/** SchemaName=null so the entity-metadata removal + schema drop are skipped — isolating teardown. */
function installedConnector(withTeardown = true): unknown {
    return {
        ID: 'app-1',
        Name: 'acme-connector',
        Version: '1.2.0',
        RepositoryURL: 'https://github.com/acme/mj-apps',
        Subpath: 'CRM/Acme',
        SchemaName: null,
        ManifestJSON: connectorManifest(withTeardown),
        Status: 'Active',
    };
}

const TEARDOWN_SQL = "DELETE FROM [${mjSchema}].[Integration] WHERE ID = 'int-1';";

/** Builds a context whose provider reports the given platform and captures ExecuteSQL calls. */
function ctxFor(platformKey: string, executeSQL = vi.fn(async () => [])): OrchestratorContext {
    return {
        ContextUser: {},
        DatabaseProvider: { Dialect: { PlatformKey: platformKey }, ExecuteSQL: executeSQL, BeginTransaction: vi.fn(async () => {}), CommitTransaction: vi.fn(async () => {}), RollbackTransaction: vi.fn(async () => {}) },
        DatabaseConfig: {},
        GitHubOptions: {},
        RepoRoot: '/tmp/test-repo',
        MJVersion: '5.43.0',
    } as unknown as OrchestratorContext;
}

describe('RemoveApp — migrations-model teardown (HandleTeardown)', () => {
    beforeEach(() => {
        vi.clearAllMocks();
        vi.mocked(FindDependentApps).mockResolvedValue([]);
        vi.mocked(ListInstalledApps).mockResolvedValue([]);
        vi.mocked(CheckSchemaSharedByOtherApps).mockResolvedValue({ Shared: false, CheckFailed: false });
        vi.mocked(SetAppStatus).mockResolvedValue(undefined);
        vi.mocked(RecordInstallHistoryEntry).mockResolvedValue(undefined);
        vi.mocked(UpdateAppRecord).mockResolvedValue(undefined);
        vi.mocked(RunPackageInstall).mockReturnValue({ Success: true });
        vi.mocked(FindInstalledApp).mockResolvedValue(
            installedConnector() as unknown as Awaited<ReturnType<typeof FindInstalledApp>>,
        );
        // Serve a real teardown script into the engine's temp dir so HandleTeardown can read it.
        vi.mocked(DownloadMigrations).mockImplementation(
            async (_repo, _ver, _dir, localDir: string) => {
                writeFileSync(join(localDir, 'V1__teardown.sql'), TEARDOWN_SQL);
                return { Success: true, LocalPath: localDir, Files: ['V1__teardown.sql'] };
            },
        );
    });

    it('downloads the teardown dir + runs each script with ${mjSchema} resolved', async () => {
        const executeSQL = vi.fn(async () => []);
        const result = await RemoveApp({ AppName: 'acme-connector' }, ctxFor('sqlserver', executeSQL));

        expect(result.Success).toBe(true);
        // SQL Server → the plain teardown dir, at the persisted version + subpath.
        expect(DownloadMigrations).toHaveBeenCalledWith(
            'https://github.com/acme/mj-apps', '1.2.0', 'migrations-teardown', expect.any(String), expect.anything(), 'CRM/Acme',
        );
        // ${mjSchema} resolved to the core schema default (__mj) and executed via the provider.
        expect(executeSQL).toHaveBeenCalledTimes(1);
        expect(executeSQL).toHaveBeenCalledWith("DELETE FROM [__mj].[Integration] WHERE ID = 'int-1';");
    });

    it('reads the -pg teardown dir on PostgreSQL', async () => {
        await RemoveApp({ AppName: 'acme-connector' }, ctxFor('postgresql'));
        expect(DownloadMigrations).toHaveBeenCalledWith(
            'https://github.com/acme/mj-apps', '1.2.0', 'migrations-teardown-pg', expect.any(String), expect.anything(), 'CRM/Acme',
        );
    });

    it('no-ops when the manifest declares no teardownDirectory', async () => {
        vi.mocked(FindInstalledApp).mockResolvedValue(
            installedConnector(false) as unknown as Awaited<ReturnType<typeof FindInstalledApp>>,
        );
        const executeSQL = vi.fn(async () => []);
        const result = await RemoveApp({ AppName: 'acme-connector' }, ctxFor('sqlserver', executeSQL));

        expect(result.Success).toBe(true);
        expect(DownloadMigrations).not.toHaveBeenCalled();
        expect(executeSQL).not.toHaveBeenCalled();
    });

    it('skips teardown under --keep-data (teardown is data removal)', async () => {
        const executeSQL = vi.fn(async () => []);
        const result = await RemoveApp({ AppName: 'acme-connector', KeepData: true }, ctxFor('sqlserver', executeSQL));

        expect(result.Success).toBe(true);
        expect(DownloadMigrations).not.toHaveBeenCalled();
        expect(executeSQL).not.toHaveBeenCalled();
    });

    it('fails the remove loudly when a teardown script errors (no silent partial remove)', async () => {
        const executeSQL = vi.fn(async () => { throw new Error('FK violation: rows still referenced'); });
        const result = await RemoveApp({ AppName: 'acme-connector' }, ctxFor('sqlserver', executeSQL));

        expect(result.Success).toBe(false);
        expect(result.ErrorMessage).toMatch(/Teardown failed/i);
        // App is NOT marked Removed when teardown fails.
        expect(vi.mocked(UpdateAppRecord)).not.toHaveBeenCalledWith(expect.anything(), 'app-1', { Status: 'Removed' });
    });
});

/**
 * Uninstall must respect a co-owner's exclusion (the mirror of AnotherInstalledAppSelfManages).
 *
 * `schemaShared` is already computed for the metadata-removal and schema-drop decisions, but the
 * config cleanup ran unconditionally. So with app A (host-managed) and app B (self-managed) sharing
 * a schema, removing A stripped the exclusion and B's schema silently became CodeGen-owned —
 * entity registration plus base views and CRUD procs over a schema whose owner opted out. Same
 * install-order hazard this feature closes on the install path, arriving on removal instead.
 * `HandleAngularPrebundleExcludeRemoval`, in the same `Promise.all`, is already shared-aware.
 */
describe('RemoveApp — excludeSchemas cleanup respects a co-owning app', () => {
    const SHARED_SCHEMA = 'mj_shared_schema';

    function appOnSharedSchema() {
        return {
            ID: 'app-1',
            Name: 'acme-connector',
            Version: '1.2.0',
            RepositoryURL: 'https://github.com/acme/mj-apps',
            SchemaName: SHARED_SCHEMA,
            Status: 'Active',
            ManifestJSON: JSON.stringify({
                manifestVersion: 1,
                name: 'acme-connector',
                displayName: 'Acme Connector',
                description: 'Acme connector sharing a schema with another app.',
                version: '1.2.0',
                publisher: { name: 'Acme' },
                repository: 'https://github.com/acme/mj-apps',
                mjVersionRange: '>=5.43.0 <7.0.0',
                schema: { name: SHARED_SCHEMA },
                packages: {},
            }),
        };
    }

    beforeEach(() => {
        vi.mocked(FindInstalledApp).mockResolvedValue(
            appOnSharedSchema() as unknown as Awaited<ReturnType<typeof FindInstalledApp>>,
        );
        vi.mocked(CheckSchemaSharedByOtherApps).mockResolvedValue({ Shared: true, CheckFailed: false });
    });

    it('keeps the exclusion when the schema is still owned by another installed app', async () => {
        await RemoveApp({ AppName: 'acme-connector', KeepData: true }, ctxFor('sqlserver'));

        expect(RemoveExcludeSchema).not.toHaveBeenCalled();
    });

    it('still cleans up the exclusion when no other app owns the schema', async () => {
        // The stock fixture: no co-owner, so the exclusion is this app's to remove. Uses the
        // SchemaName-less installed record so the entity-metadata path stays out of the way —
        // the config cleanup keys on manifest.schema, not on the persisted SchemaName.
        vi.mocked(FindInstalledApp).mockResolvedValue(
            installedConnector() as unknown as Awaited<ReturnType<typeof FindInstalledApp>>,
        );
        vi.mocked(CheckSchemaSharedByOtherApps).mockResolvedValue({ Shared: false, CheckFailed: false });

        const result = await RemoveApp({ AppName: 'acme-connector' }, ctxFor('sqlserver'));

        expect(result.Success).toBe(true);
        expect(RemoveExcludeSchema).toHaveBeenCalledWith('/tmp/test-repo', 'mj_connector_acme', undefined);
    });
});
