import { describe, it, expect, beforeEach } from 'vitest';
import {
    TelemetryManager,
    TelemetryRunViewsBatchParams,
    TelemetryRunViewParams
} from '../generic/telemetryManager';

/**
 * Regression coverage for the filter-blind batch RunViews fingerprint (Issue #4).
 *
 * Before the fix, TelemetryRunViewsBatchParams carried only BatchSize + Entities, so two
 * genuinely-different RunViews batches over the SAME entity set (different per-view ExtraFilter)
 * produced the SAME fingerprint and were falsely flagged "Duplicate RunView … same filter/orderBy".
 *
 * GenerateFingerprintForTest exposes the otherwise-private fingerprint generator so these tests
 * can assert on fingerprint identity/distinctness directly.
 */
describe('TelemetryManager — batch RunViews fingerprint (filter-aware)', () => {
    let tm: TelemetryManager;

    // The fingerprint generator is private; access it through an index signature without `any`.
    const fingerprintOf = (params: TelemetryRunViewsBatchParams | TelemetryRunViewParams): string => {
        const generate = (tm as unknown as {
            generateFingerprint(category: 'RunView', params: TelemetryRunViewsBatchParams | TelemetryRunViewParams): string;
        }).generateFingerprint.bind(tm);
        return generate('RunView', params);
    };

    beforeEach(() => {
        tm = TelemetryManager.Instance;
        tm.Reset();
        tm.SetEnabled(true);
    });

    const sameEntities = ['MJ: AI Agent Notes', 'MJ: AI Agent Examples'];

    it('gives DISTINCT fingerprints to two batches over the same entities but different filters', () => {
        // The exact real-world collision: expiry sweep vs. decay sweep, both over the same entity set.
        const expirySweep: TelemetryRunViewsBatchParams = {
            BatchSize: 2,
            Entities: sameEntities,
            Filters: [`ExpiresAt < '2026-06-15'`, `ExpiresAt < '2026-06-15'`],
            OrderBys: [undefined, undefined]
        };
        const decaySweep: TelemetryRunViewsBatchParams = {
            BatchSize: 2,
            Entities: sameEntities,
            Filters: [`IsAutoGenerated = 1 AND Status = 'Active'`, `IsAutoGenerated = 1 AND Status = 'Active' AND SuccessScore < 50`],
            OrderBys: [undefined, undefined]
        };

        expect(fingerprintOf(expirySweep)).not.toBe(fingerprintOf(decaySweep));
    });

    it('gives IDENTICAL fingerprints to two batches over the same entities AND same filters', () => {
        const batchA: TelemetryRunViewsBatchParams = {
            BatchSize: 2,
            Entities: sameEntities,
            Filters: [`Status = 'Active'`, `Status = 'Active'`],
            OrderBys: ['Name', undefined]
        };
        const batchB: TelemetryRunViewsBatchParams = {
            BatchSize: 2,
            Entities: [...sameEntities],
            Filters: [`Status = 'Active'`, `Status = 'Active'`],
            OrderBys: ['Name', undefined]
        };

        expect(fingerprintOf(batchA)).toBe(fingerprintOf(batchB));
    });

    it('is case-insensitive and whitespace-tolerant on filters (still collides on equivalent filters)', () => {
        const batchA: TelemetryRunViewsBatchParams = {
            BatchSize: 1,
            Entities: ['MJ: AI Agent Notes'],
            Filters: [`Status = 'Active'`]
        };
        const batchB: TelemetryRunViewsBatchParams = {
            BatchSize: 1,
            Entities: ['mj: ai agent notes'],
            Filters: [`  STATUS = 'Active'  `]
        };

        expect(fingerprintOf(batchA)).toBe(fingerprintOf(batchB));
    });

    it('distinguishes batches that differ only by OrderBy', () => {
        const ordered: TelemetryRunViewsBatchParams = {
            BatchSize: 1,
            Entities: ['MJ: Actions'],
            Filters: [undefined],
            OrderBys: ['Name ASC']
        };
        const unordered: TelemetryRunViewsBatchParams = {
            BatchSize: 1,
            Entities: ['MJ: Actions'],
            Filters: [undefined],
            OrderBys: [undefined]
        };

        expect(fingerprintOf(ordered)).not.toBe(fingerprintOf(unordered));
    });

    it('is order-independent: reordering the views in a batch yields the same fingerprint', () => {
        const forward: TelemetryRunViewsBatchParams = {
            BatchSize: 2,
            Entities: ['MJ: AI Agent Notes', 'MJ: AI Agent Examples'],
            Filters: [`A = 1`, `B = 2`]
        };
        const reversed: TelemetryRunViewsBatchParams = {
            BatchSize: 2,
            Entities: ['MJ: AI Agent Examples', 'MJ: AI Agent Notes'],
            Filters: [`B = 2`, `A = 1`]
        };

        expect(fingerprintOf(forward)).toBe(fingerprintOf(reversed));
    });

    it('still distinguishes a single RunView from a batch (single-view fingerprint unchanged)', () => {
        const single: TelemetryRunViewParams = {
            EntityName: 'MJ: AI Agent Notes',
            ExtraFilter: `Status = 'Active'`,
            OrderBy: 'Name',
            ResultType: 'simple'
        };
        const batch: TelemetryRunViewsBatchParams = {
            BatchSize: 1,
            Entities: ['MJ: AI Agent Notes'],
            Filters: [`Status = 'Active'`],
            OrderBys: ['Name']
        };

        expect(fingerprintOf(single)).not.toBe(fingerprintOf(batch));
    });

    it('falls back gracefully when Filters/OrderBys are absent (legacy callers)', () => {
        // A batch recorded by an old code path with no Filters/OrderBys should still produce a
        // stable fingerprint, and two such filterless batches over the same entities collide.
        const legacyA: TelemetryRunViewsBatchParams = {
            BatchSize: 2,
            Entities: sameEntities
        };
        const legacyB: TelemetryRunViewsBatchParams = {
            BatchSize: 2,
            Entities: [...sameEntities]
        };

        expect(fingerprintOf(legacyA)).toBe(fingerprintOf(legacyB));
    });
});
