-- =============================================================================
-- FileStorageProvider.Configuration — Extensible provider-level configuration (JSONType)
-- including IconClass and BrandColor for UI display and provider branding.
-- =============================================================================
--
-- WHAT THIS ENABLES:
--   1. Stores UI branding (IconClass, BrandColor) directly in metadata rather than
--      hardcoding icon mappings in client components.
--   2. Future-proofs FileStorageProvider with an extensible JSON configuration bag
--      (shape = IFileStorageProviderConfiguration) for provider-specific driver options,
--      upload chunking policies, and feature flags without requiring table alterations.
--
-- METADATA SEEDING:
--   Seeds initial IconClass and BrandColor for all built-in storage providers.
-- =============================================================================

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[${flyway:defaultSchema}].[FileStorageProvider]') 
      AND name = N'Configuration'
)
BEGIN
    ALTER TABLE [${flyway:defaultSchema}].[FileStorageProvider]
        ADD [Configuration] NVARCHAR(MAX) NULL;
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.extended_properties
    WHERE major_id = OBJECT_ID(N'[${flyway:defaultSchema}].[FileStorageProvider]')
      AND minor_id = (SELECT column_id FROM sys.columns WHERE object_id = OBJECT_ID(N'[${flyway:defaultSchema}].[FileStorageProvider]') AND name = N'Configuration')
      AND name = N'MS_Description'
)
BEGIN
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Optional JSON configuration bag defining provider-level metadata and settings (shape = IFileStorageProviderConfiguration). Includes IconClass and BrandColor for UI representation.',
        @level0type = N'SCHEMA',  @level0name = N'${flyway:defaultSchema}',
        @level1type = N'TABLE',   @level1name = N'FileStorageProvider',
        @level2type = N'COLUMN',  @level2name = N'Configuration';
END
GO

-- Seed initial Configuration for existing storage providers
UPDATE [${flyway:defaultSchema}].[FileStorageProvider]
SET [Configuration] = N'{"IconClass":"fa-solid fa-box","BrandColor":"#0061D5"}'
WHERE [Name] = N'Box.com' OR [ServerDriverKey] LIKE N'%Box%';

UPDATE [${flyway:defaultSchema}].[FileStorageProvider]
SET [Configuration] = N'{"IconClass":"fa-brands fa-aws","BrandColor":"#FF9900"}'
WHERE [Name] LIKE N'%AWS%' OR [Name] LIKE N'%S3%' OR [ServerDriverKey] LIKE N'%S3%';

UPDATE [${flyway:defaultSchema}].[FileStorageProvider]
SET [Configuration] = N'{"IconClass":"fa-brands fa-microsoft","BrandColor":"#0078D4"}'
WHERE [Name] LIKE N'%Azure%' OR [ServerDriverKey] LIKE N'%Azure%';

UPDATE [${flyway:defaultSchema}].[FileStorageProvider]
SET [Configuration] = N'{"IconClass":"fa-brands fa-google-drive","BrandColor":"#0F9D58"}'
WHERE [Name] = N'Google Drive' OR [ServerDriverKey] LIKE N'%Google Drive%';

UPDATE [${flyway:defaultSchema}].[FileStorageProvider]
SET [Configuration] = N'{"IconClass":"fa-brands fa-google","BrandColor":"#4285F4"}'
WHERE [Name] = N'Google Cloud Storage' OR [ServerDriverKey] LIKE N'%Google Cloud%';

UPDATE [${flyway:defaultSchema}].[FileStorageProvider]
SET [Configuration] = N'{"IconClass":"fa-brands fa-dropbox","BrandColor":"#0061FF"}'
WHERE [Name] = N'Dropbox' OR [ServerDriverKey] LIKE N'%Dropbox%';

UPDATE [${flyway:defaultSchema}].[FileStorageProvider]
SET [Configuration] = N'{"IconClass":"fa-brands fa-microsoft","BrandColor":"#038387"}'
WHERE [Name] LIKE N'%SharePoint%' OR [ServerDriverKey] LIKE N'%SharePoint%';
GO

















































-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================
-- Everything below this block was produced by CodeGen after
-- the hand-written ALTER TABLE above. It contains:
--   * EntityField INSERT for FileStorageProvider.Configuration (apply-time Sequence)
--   * Regenerated vwFileStorageProviders, spCreate/spUpdate/spDelete, and
--     trgUpdateFileStorageProvider
-- =============================================================================

/* SQL text to insert new entity field */
IF NOT EXISTS (
    SELECT 1 FROM [${flyway:defaultSchema}].[EntityField] 
    WHERE ID = 'A54EAB65-B002-498E-A4B9-F28D21A9698D' 
       OR (EntityID = '28248F34-2837-EF11-86D4-6045BDEE16E6' AND Name = 'Configuration')
) BEGIN
    INSERT INTO [${flyway:defaultSchema}].[EntityField]
    (
        [ID],
        [EntityID],
        [Sequence],
        [Name],
        [DisplayName],
        [Description],
        [Type],
        [Length],
        [Precision],
        [Scale],
        [AllowsNull],
        [DefaultValue],
        [AutoIncrement],
        [AllowUpdateAPI],
        [IsVirtual],
        [IsComputed],
        [RelatedEntityID],
        [RelatedEntityFieldName],
        [IsNameField],
        [IncludeInUserSearchAPI],
        [IncludeRelatedEntityNameFieldInBaseView],
        [DefaultInView],
        [IsPrimaryKey],
        [IsUnique],
        [RelatedEntityDisplayType],
        [JSONType],
        [JSONTypeIsArray],
        [JSONTypeDefinition],
        [__mj_CreatedAt],
        [__mj_UpdatedAt]
    )
    VALUES
    (
        'A54EAB65-B002-498E-A4B9-F28D21A9698D',
        '28248F34-2837-EF11-86D4-6045BDEE16E6', -- Entity: MJ: File Storage Providers
        (SELECT COALESCE(MAX([Sequence]), 0) FROM [${flyway:defaultSchema}].[EntityField] WHERE [EntityID] = '28248F34-2837-EF11-86D4-6045BDEE16E6') + 1,
        'Configuration',
        'Configuration',
        'Optional JSON configuration bag defining provider-level metadata and settings (shape = IFileStorageProviderConfiguration). Includes IconClass and BrandColor for UI representation.',
        'nvarchar',
        -1,
        0,
        0,
        1,
        NULL,
        0,
        1,
        0,
        0,
        NULL,
        NULL,
        0,
        0,
        0,
        0,
        0,
        0,
        'Search',
        'IFileStorageProviderConfiguration',
        0,
        '@file:JSONType-interfaces/IFileStorageProviderConfiguration.ts',
        GETUTCDATE(),
        GETUTCDATE()
    );
END
GO

/* Base View SQL for MJ: File Storage Providers */
IF OBJECT_ID('[${flyway:defaultSchema}].[vwFileStorageProviders]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwFileStorageProviders];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwFileStorageProviders]
AS
SELECT
    f.*
FROM
    [${flyway:defaultSchema}].[FileStorageProvider] AS f
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwFileStorageProviders] TO [cdp_UI], [cdp_Integration], [cdp_Developer];
GO

/* spCreate SQL for MJ: File Storage Providers */
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateFileStorageProvider]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateFileStorageProvider];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateFileStorageProvider]
    @ID uniqueidentifier = NULL,
    @Name nvarchar(50),
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @ServerDriverKey nvarchar(100),
    @ClientDriverKey nvarchar(100),
    @Priority int = NULL,
    @IsActive bit = NULL,
    @Configuration_Clear bit = 0,
    @Configuration nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        INSERT INTO [${flyway:defaultSchema}].[FileStorageProvider]
            (
                [ID],
                [Name],
                [Description],
                [ServerDriverKey],
                [ClientDriverKey],
                [Priority],
                [IsActive],
                [Configuration]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @ServerDriverKey,
                @ClientDriverKey,
                ISNULL(@Priority, 0),
                ISNULL(@IsActive, 1),
                CASE WHEN @Configuration_Clear = 1 THEN NULL ELSE ISNULL(@Configuration, NULL) END
            )
    END
    ELSE
    BEGIN
        INSERT INTO [${flyway:defaultSchema}].[FileStorageProvider]
            (
                [Name],
                [Description],
                [ServerDriverKey],
                [ClientDriverKey],
                [Priority],
                [IsActive],
                [Configuration]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @ServerDriverKey,
                @ClientDriverKey,
                ISNULL(@Priority, 0),
                ISNULL(@IsActive, 1),
                CASE WHEN @Configuration_Clear = 1 THEN NULL ELSE ISNULL(@Configuration, NULL) END
            )
    END
    SELECT * FROM [${flyway:defaultSchema}].[vwFileStorageProviders] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateFileStorageProvider] TO [cdp_Integration], [cdp_Developer];
GO

/* spUpdate SQL for MJ: File Storage Providers */
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateFileStorageProvider]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateFileStorageProvider];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateFileStorageProvider]
    @ID uniqueidentifier,
    @Name nvarchar(50) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @ServerDriverKey nvarchar(100) = NULL,
    @ClientDriverKey nvarchar(100) = NULL,
    @Priority int = NULL,
    @IsActive bit = NULL,
    @Configuration_Clear bit = 0,
    @Configuration nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[FileStorageProvider]
    SET
        [Name] = ISNULL(@Name, [Name]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [ServerDriverKey] = ISNULL(@ServerDriverKey, [ServerDriverKey]),
        [ClientDriverKey] = ISNULL(@ClientDriverKey, [ClientDriverKey]),
        [Priority] = ISNULL(@Priority, [Priority]),
        [IsActive] = ISNULL(@IsActive, [IsActive]),
        [Configuration] = CASE WHEN @Configuration_Clear = 1 THEN NULL ELSE ISNULL(@Configuration, [Configuration]) END
    WHERE
        [ID] = @ID

    SELECT * FROM [${flyway:defaultSchema}].[vwFileStorageProviders] WHERE [ID] = @ID
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateFileStorageProvider] TO [cdp_Integration], [cdp_Developer];
GO

/* spDelete SQL for MJ: File Storage Providers */
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteFileStorageProvider]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteFileStorageProvider];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteFileStorageProvider]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM
        [${flyway:defaultSchema}].[FileStorageProvider]
    WHERE
        [ID] = @ID

    SELECT @ID AS [ID]
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteFileStorageProvider] TO [cdp_Integration], [cdp_Developer];
GO

/* Trigger for FileStorageProvider */
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateFileStorageProvider]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateFileStorageProvider];
GO

CREATE TRIGGER [${flyway:defaultSchema}].[trgUpdateFileStorageProvider]
ON [${flyway:defaultSchema}].[FileStorageProvider]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[FileStorageProvider]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[FileStorageProvider] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
