-- Corrects the GPT 5.5 Instant model's APIName from the non-existent `gpt-5.5-instant` to
-- `gpt-5.5`, the id OpenAI actually exposes (verified against /v1/models). The bad value
-- shipped in v5.49.0, so every prompt bound to this model 404s at inference:
--   404 The model `gpt-5.5-instant` does not exist or you do not have access to it.
-- It is absent from the consolidated V202608051834 sync migration because it was unchanged
-- relative to the last release; this migration carries the correction additively rather than
-- rewriting that ledger file. Generated by `mj sync push --include=ai-models`.


-- Save MJ: AI Models (core SP call only)
DECLARE @Name_fe9a1c65 NVARCHAR(50),
@Description_fe9a1c65 NVARCHAR(MAX),
@AIModelTypeID_fe9a1c65 UNIQUEIDENTIFIER,
@PowerRank_fe9a1c65 INT,
@IsActive_fe9a1c65 BIT,
@SpeedRank_fe9a1c65 INT,
@CostRank_fe9a1c65 INT,
@ModelSelectionInsights_fe9a1c65 NVARCHAR(MAX),
@InheritTypeModalities_fe9a1c65 BIT,
@PriorVersionID_fe9a1c65 UNIQUEIDENTIFIER,
@SupportsPrefill_fe9a1c65 BIT,
@PrefillFallbackText_fe9a1c65 NVARCHAR(MAX),
@ID_fe9a1c65 UNIQUEIDENTIFIER
SET
  @Name_fe9a1c65 = N'GPT 5.5 Instant'
SET
  @Description_fe9a1c65 = N'OpenAI''s latest low-latency default ChatGPT model (May 5, 2026). Replaces GPT-5.3 Instant as the default in ChatGPT. API NOTE: there is no `gpt-5.5-instant` or `gpt-5.5-chat-latest` model id — OpenAI exposes this family as `gpt-5.5` (verified against /v1/models), which is what this record''s APIName uses. Headline metric: 52.5% fewer hallucinated claims than GPT-5.3 Instant on high-stakes prompts (legal, medical, financial). Inherits the GPT-5.5 family context: 1,050,000 input tokens, 128,000 output. Supports configurable reasoning_effort. PRICING NOTE: provisional rate uses the GPT-5.5 standard $5/$30 per 1M tokens; Instant SKU may carry a lower rate once OpenAI''s pricing page differentiates it.'
SET
  @AIModelTypeID_fe9a1c65 = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @PowerRank_fe9a1c65 = 13
SET
  @IsActive_fe9a1c65 = 1
SET
  @SpeedRank_fe9a1c65 = 9
SET
  @CostRank_fe9a1c65 = 10
SET
  @InheritTypeModalities_fe9a1c65 = 1
SET
  @PriorVersionID_fe9a1c65 = '87C9417E-45E6-4C97-95B1-EC0482C7FE4D'
SET
  @ID_fe9a1c65 = '7E91F18E-52CC-48C9-8457-74C810899B41' EXEC [${flyway:defaultSchema}].spUpdateAIModel @Name = @Name_fe9a1c65,
  @Description = @Description_fe9a1c65,
  @AIModelTypeID = @AIModelTypeID_fe9a1c65,
  @PowerRank = @PowerRank_fe9a1c65,
  @IsActive = @IsActive_fe9a1c65,
  @SpeedRank = @SpeedRank_fe9a1c65,
  @CostRank = @CostRank_fe9a1c65,
  @ModelSelectionInsights = @ModelSelectionInsights_fe9a1c65,
  @ModelSelectionInsights_Clear = 1,
  @InheritTypeModalities = @InheritTypeModalities_fe9a1c65,
  @PriorVersionID = @PriorVersionID_fe9a1c65,
  @SupportsPrefill = @SupportsPrefill_fe9a1c65,
  @SupportsPrefill_Clear = 1,
  @PrefillFallbackText = @PrefillFallbackText_fe9a1c65,
  @PrefillFallbackText_Clear = 1,
  @ID = @ID_fe9a1c65;

GO

-- Save MJ: AI Model Vendors (core SP call only)
DECLARE @ModelID_443912ff UNIQUEIDENTIFIER,
@VendorID_443912ff UNIQUEIDENTIFIER,
@Priority_443912ff INT,
@Status_443912ff NVARCHAR(20),
@DriverClass_443912ff NVARCHAR(100),
@DriverImportPath_443912ff NVARCHAR(255),
@APIName_443912ff NVARCHAR(100),
@MaxInputTokens_443912ff INT,
@MaxOutputTokens_443912ff INT,
@SupportedResponseFormats_443912ff NVARCHAR(100),
@SupportsEffortLevel_443912ff BIT,
@SupportsStreaming_443912ff BIT,
@TypeID_443912ff UNIQUEIDENTIFIER,
@SupportsPrefill_443912ff BIT,
@PrefillFallbackText_443912ff NVARCHAR(MAX),
@ID_443912ff UNIQUEIDENTIFIER
SET
  @ModelID_443912ff = '7E91F18E-52CC-48C9-8457-74C810899B41'
SET
  @VendorID_443912ff = 'D8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @Priority_443912ff = 1
SET
  @Status_443912ff = N'Active'
SET
  @DriverClass_443912ff = N'OpenAILLM'
SET
  @APIName_443912ff = N'gpt-5.5'
SET
  @MaxInputTokens_443912ff = 1050000
SET
  @MaxOutputTokens_443912ff = 128000
SET
  @SupportedResponseFormats_443912ff = N'Any, JSON'
SET
  @SupportsEffortLevel_443912ff = 1
SET
  @SupportsStreaming_443912ff = 1
SET
  @TypeID_443912ff = '5B043EC3-1FF2-4730-B5D2-7CFDA50979B3'
SET
  @ID_443912ff = 'B12DF96C-C415-4D00-A634-2EBCA428E78C' EXEC [${flyway:defaultSchema}].spUpdateAIModelVendor @ModelID = @ModelID_443912ff,
  @VendorID = @VendorID_443912ff,
  @Priority = @Priority_443912ff,
  @Status = @Status_443912ff,
  @DriverClass = @DriverClass_443912ff,
  @DriverImportPath = @DriverImportPath_443912ff,
  @DriverImportPath_Clear = 1,
  @APIName = @APIName_443912ff,
  @MaxInputTokens = @MaxInputTokens_443912ff,
  @MaxOutputTokens = @MaxOutputTokens_443912ff,
  @SupportedResponseFormats = @SupportedResponseFormats_443912ff,
  @SupportsEffortLevel = @SupportsEffortLevel_443912ff,
  @SupportsStreaming = @SupportsStreaming_443912ff,
  @TypeID = @TypeID_443912ff,
  @SupportsPrefill = @SupportsPrefill_443912ff,
  @SupportsPrefill_Clear = 1,
  @PrefillFallbackText = @PrefillFallbackText_443912ff,
  @PrefillFallbackText_Clear = 1,
  @ID = @ID_443912ff;

GO


-- End of SQL Logging Session
-- Session ID: 8d94d259-1163-4dfa-8ec3-2204617236e8
-- Completed: 2026-08-05T21:12:14.554Z
-- Duration: 2501ms
-- Total Statements: 2
