import { BaseModel } from "./baseModel";

/**
 * Minimal shape for a UserInfo-like context user.
 *
 * The `@memberjunction/ai` package is intentionally insulated — it depends only on
 * `@memberjunction/global` (see package.json description: "usable anywhere without ANY
 * other MJ dependencies past @memberjunction/global"). We therefore cannot import the
 * full `UserInfo` class from `@memberjunction/core` here. Consumers in higher-level
 * packages will pass a real `UserInfo` instance, which satisfies this structural type.
 */
export interface UserInfoLike {
    ID: string;
    Email?: string;
    Name?: string;
}

/**
 * Minimal shape for an AIVoiceProfileEntity-like record.
 *
 * Placeholder until `AIVoiceProfileEntity` is generated by CodeGen against the
 * upcoming voice-profile migration. Once that exists in `@memberjunction/core-entities`,
 * higher-level packages can pass full entity instances which satisfy this structural type.
 * AI/Core itself cannot import from `@memberjunction/core-entities` due to the package
 * isolation contract documented above.
 */
export interface VoiceProfileLike {
    Name?: string;
    LanguageCode?: string;
    StyleHint?: string;
    SampleAudioURL?: string;
    /** Provider-specific JSON config (voice IDs, model knobs, etc.) */
    ProviderOverridesJSON?: string;
}

/**
 * A single tool/function the realtime model is allowed to call mid-conversation.
 *
 * Kept local to AI/Core because the only existing `ToolDefinition` in the repo
 * (`@memberjunction/ai-computer-use`) is narrowly scoped to that package's controller
 * loop. The realtime/agent layers need a more generic, JSON-schema-shaped contract.
 */
export interface ToolDefinition {
    /** Tool name as exposed to the model. */
    Name: string;
    /** Human-readable description used by the model to decide when to call. */
    Description: string;
    /** JSON Schema describing the tool's input arguments. */
    ParametersSchema: Record<string, unknown>;
}

/**
 * A tool invocation emitted by the realtime model.
 */
export interface ToolCall {
    /** Tool name being invoked (matches a `ToolDefinition.Name`). */
    Name: string;
    /** Arguments parsed from the model's tool call. */
    Arguments: Record<string, unknown>;
    /** Provider-specific call identifier, used to correlate the response. */
    CallID: string;
}

/**
 * Result of executing a `ToolCall`, returned to the realtime session so the model
 * can incorporate it into the ongoing response.
 */
export interface ToolResult {
    /** Must match the originating `ToolCall.CallID`. */
    CallID: string;
    /**
     * Tool output payload. Typed as `unknown` because tool results are heterogeneous
     * (strings, structured objects, binary handles) and the caller knows the schema.
     */
    Result?: unknown;
    /** Error message if the tool failed; mutually exclusive with `Result`. */
    Error?: string;
}

/**
 * A single audio frame moving across a realtime/streaming channel.
 *
 * `mediaType` examples: `'audio/pcm'`, `'audio/opus'`, `'audio/mulaw'`. PCM frames
 * are little-endian 16-bit signed unless the provider documents otherwise.
 */
export interface AudioFrame {
    data: Uint8Array;
    sampleRateHz: number;
    channelCount: number;
    mediaType: string;
}

/**
 * Options accepted by `BaseRealtimeSpeech.Connect()`.
 *
 * `Credentials` is a generic key/value bag so we can support cloud providers,
 * on-prem WebSocket endpoints, and PersonaPlex-style deployments through a single
 * contract.
 */
export interface RealtimeSpeechConnectOptions {
    SystemPrompt: string;
    /** Voice configuration. Swap to `AIVoiceProfileEntity` once CodeGen emits it. */
    VoiceProfile?: VoiceProfileLike;
    /** Tools the model may call. Empty for tool-less S2S like PersonaPlex. */
    Tools?: ToolDefinition[];
    Language?: string;
    ContextUser: UserInfoLike;
    /** Pluggable credentials bag — supports cloud + on-prem providers. */
    Credentials?: Record<string, string>;
}

/**
 * A live bidirectional speech-to-speech session returned by `BaseRealtimeSpeech.Connect()`.
 */
export interface RealtimeSpeechSession {
    /** Send a single audio frame to the model. */
    SendAudio(chunk: AudioFrame): void;
    /** Subscribe to audio frames coming back from the model. */
    OnAudio(cb: (chunk: AudioFrame) => void): void;
    /** Subscribe to transcript fragments (user or assistant, partial or final). */
    OnTranscript(cb: (text: string, role: 'user' | 'assistant', isFinal: boolean) => void): void;
    /** Subscribe to tool calls; the callback resolves the tool result. */
    OnToolCall(cb: (call: ToolCall) => Promise<ToolResult>): void;
    /** Cancel the in-flight assistant response — used for barge-in. */
    CancelCurrentResponse(): void;
    /** Close the session and release resources. */
    Close(): Promise<void>;
}

/**
 * Streaming STT input options. The `AudioStream` is consumed as it yields frames.
 */
export interface StreamingSTTOptions {
    AudioStream: AsyncIterable<AudioFrame>;
    Language?: string;
    /** When true, callers receive interim (non-final) transcripts as well. */
    IncludePartials?: boolean;
    ContextUser: UserInfoLike;
}

/**
 * Streaming TTS input options. The `TextStream` is consumed incrementally so the
 * provider can begin emitting audio before the full text is known.
 */
export interface StreamingTTSOptions {
    TextStream: AsyncIterable<string>;
    /** Voice configuration. Swap to `AIVoiceProfileEntity` once CodeGen emits it. */
    VoiceProfile?: VoiceProfileLike;
    SampleRateHz?: number;
    /** Output container/codec; e.g. `'audio/pcm'`, `'audio/opus'`, `'audio/mulaw'`. */
    MediaType?: string;
    ContextUser: UserInfoLike;
}

/**
 * Transcript fragment emitted by `BaseAudioGenerator.TranscribeStream()`.
 */
export interface TranscriptEvent {
    Text: string;
    IsFinal: boolean;
    Role?: 'user' | 'assistant';
    ConfidenceScore?: number;
}

/**
 * Bidirectional speech-to-speech (S2S) contract.
 *
 * Implementations connect to a realtime model — cloud (OpenAI, Gemini Live) or
 * on-prem (PersonaPlex, self-hosted Whisper+TTS bridges) — and expose a duplex
 * audio session with optional tool calling. Tool execution itself lives above the
 * engine: even when the provider supports native tool calling, the channel
 * runtime routes calls back through `BaseAgent` for consistent audit/permission
 * behavior. See `plans/audio-agent-architecture.md` section 3.3.
 */
export abstract class BaseRealtimeSpeech extends BaseModel {
    public abstract Connect(opts: RealtimeSpeechConnectOptions): Promise<RealtimeSpeechSession>;
}
