-- RSU Migration: Integration: higherlogic-thrive — higherlogic_thrive.Announcements, higherlogic_thrive.Answers, higherlogic_thrive.AutomationRuleContactData, higherlogic_thrive.AutomationRuleSchedules, higherlogic_thrive.BlogComments, higherlogic_thrive.Blogs, higherlogic_thrive.Comments, higherlogic_thrive.Communities, higherlogic_thrive.CommunityInvitations, higherlogic_thrive.CommunityMembers, higherlogic_thrive.Contacts, higherlogic_thrive.DataFeed, higherlogic_thrive.DemographicChoices, higherlogic_thrive.DemographicTypes, higherlogic_thrive.DiscussionPosts, higherlogic_thrive.Discussions, higherlogic_thrive.DiscussionThreads, higherlogic_thrive.DocumentAttachments, higherlogic_thrive.EventRegistrants, higherlogic_thrive.Events, higherlogic_thrive.EventSessions, higherlogic_thrive.EventTypes, higherlogic_thrive.ExternalActivity, higherlogic_thrive.IdeaCategories, higherlogic_thrive.Ideas, higherlogic_thrive.IdeaStatuses, higherlogic_thrive.Questions, higherlogic_thrive.ResourceLibraryDocuments, higherlogic_thrive.ResourceLibraryLibraries, higherlogic_thrive.Tags, higherlogic_thrive.VolunteerOpportunities, higherlogic_thrive.VolunteerOpportunityTypes, higherlogic_thrive.Volunteers
-- Generated: 2026-07-11T17:22:06.817Z
-- Affected tables: higherlogic_thrive.Announcements, higherlogic_thrive.Answers, higherlogic_thrive.AutomationRuleContactData, higherlogic_thrive.AutomationRuleSchedules, higherlogic_thrive.BlogComments, higherlogic_thrive.Blogs, higherlogic_thrive.Comments, higherlogic_thrive.Communities, higherlogic_thrive.CommunityInvitations, higherlogic_thrive.CommunityMembers, higherlogic_thrive.Contacts, higherlogic_thrive.DataFeed, higherlogic_thrive.DemographicChoices, higherlogic_thrive.DemographicTypes, higherlogic_thrive.DiscussionPosts, higherlogic_thrive.Discussions, higherlogic_thrive.DiscussionThreads, higherlogic_thrive.DocumentAttachments, higherlogic_thrive.EventRegistrants, higherlogic_thrive.Events, higherlogic_thrive.EventSessions, higherlogic_thrive.EventTypes, higherlogic_thrive.ExternalActivity, higherlogic_thrive.IdeaCategories, higherlogic_thrive.Ideas, higherlogic_thrive.IdeaStatuses, higherlogic_thrive.Questions, higherlogic_thrive.ResourceLibraryDocuments, higherlogic_thrive.ResourceLibraryLibraries, higherlogic_thrive.Tags, higherlogic_thrive.VolunteerOpportunities, higherlogic_thrive.VolunteerOpportunityTypes, higherlogic_thrive.Volunteers
-- ============================================================
-- Auto-generated by MJ SchemaEngine
-- Consumer: higherlogic-thrive | Object: Announcements, Answers, AutomationRuleContactData, AutomationRuleSchedules, BlogComments, Blogs, Comments, Communities, CommunityInvitations, CommunityMembers, Contacts, DataFeed, DemographicChoices, DemographicTypes, DiscussionPosts, Discussions, DiscussionThreads, DocumentAttachments, EventRegistrants, Events, EventSessions, EventTypes, ExternalActivity, IdeaCategories, Ideas, IdeaStatuses, Questions, ResourceLibraryDocuments, ResourceLibraryLibraries, Tags, VolunteerOpportunities, VolunteerOpportunityTypes, Volunteers
-- Action: AlterTables
-- Generated: 2026-07-11T17:22:06.814Z
-- Generated By: MJ Integration Schema Builder (via SchemaEngine)
-- ============================================================
-- NOTE: __mj_CreatedAt, __mj_UpdatedAt, FK indexes, views, and SPs
--       are created by CodeGen — do NOT add them here.
-- NOTE: Soft foreign keys are defined in additionalSchemaInfo,
--       applied by CodeGen — no FK constraints needed in this migration.
-- ============================================================
-- DEPRECATED: Column [RootParentCommunityKey] no longer exists in source. Consider removing after grace period.

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[higherlogic_thrive].[CommunityMembers]') AND name = N'mj_e2e_custom_attr')
ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ADD [mj_e2e_custom_attr] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [CommunityMemberRoles] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [LinkToProfile] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [LegacyContactKey] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [IsCompany] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [AcceptedOn] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [AgreedToTermsDateTime] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [InvitedOn] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [ContactStatusCode] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [IsActive] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [HLContactMeOptOut] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [IsAdmin] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [InvitedByContactKey] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [InformalName] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [RemovedOn] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [DisplayName] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [AMSDirectoryOptOut] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [EmailAddress] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [HLDirectoryOptOut] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [PictureUrl] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [StartDate] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [CompanyTitle] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [UpdatedByContactKey] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [LargePictureUrl] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [CompanyLegacyContactKey] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [EndDate] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [UpdatedOn] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [CompanyName] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [FirstName] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [PrefixCode] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [Designation] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [MiddleName] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [LastName] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[CommunityMembers]
    ALTER COLUMN [SuffixCode] NVARCHAR(812) NULL;

-- DEPRECATED: Column [RootUpdatedByContactKey] no longer exists in source. Consider removing after grace period.

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[higherlogic_thrive].[DataFeed]') AND name = N'mj_e2e_custom_attr')
ALTER TABLE [higherlogic_thrive].[DataFeed]
    ADD [mj_e2e_custom_attr] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [PublishedDate] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Date01] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [HasRecommended] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Marker] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [PublicationStatus] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Text04] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Title] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [FeaturedImageUrl] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Bool02] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [LinkToViewItem] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [RecommendationCount] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [HasReplied] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Bool01] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [ResponseCount] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Date02] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [ActionText] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [ItemType] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [CreateDate] NVARCHAR(MAX) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Text03] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Text01] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Text02] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [ThreadKey] NVARCHAR(812) NULL;

ALTER TABLE [higherlogic_thrive].[DataFeed]
    ALTER COLUMN [Body] NVARCHAR(812) NULL;

-- DEPRECATED: Column [RootParentDiscussionPostKey] no longer exists in source. Consider removing after grace period.

