/**
 * cross-server-signatures.test.ts — pins the classifier the cross-server rig uses to tell the #3777
 * poisoned-engine failure apart from an ordinary query failure.
 *
 * XS5–XS7 and the probe picker only run nightly against two live MJAPI processes, so a classifier
 * that stopped matching would not show up as a red test there: every poisoned run would be reported
 * as "failed for an unrelated reason", or a fully poisoned server as a missing fixture. The positive
 * case below is generated by V8 itself, the same way the defect produced it, so a change in Node's
 * TypeError wording fails here.
 */
import { describe, expect, it } from 'vitest';
import { LooksLikePoisonedEngine } from '../../rigs/lib/cross-server-signatures';

/** The #3777 mechanism: a row that went through JSON keeps its fields and loses its prototype. */
class FakeQueryEntity {
    public Name = 'Probe';
    public UserCanRun(): boolean {
        return true;
    }
}

function messageFromCallingAMethodOnDeserializedRow(): string {
    const row = JSON.parse(JSON.stringify(new FakeQueryEntity())) as FakeQueryEntity;
    try {
        row.UserCanRun();
    } catch (e) {
        return e instanceof Error ? e.message : String(e);
    }
    throw new Error('calling a method on a deserialized row did not throw');
}

describe('LooksLikePoisonedEngine', () => {
    it('matches the TypeError V8 raises when a deserialized row has lost its methods', () => {
        const message = messageFromCallingAMethodOnDeserializedRow();
        expect(message).toContain('UserCanRun');
        expect(LooksLikePoisonedEngine(message)).toBe(true);
    });

    it('matches the production message as it arrives through RunQuery, prefix and case aside', () => {
        expect(LooksLikePoisonedEngine('TypeError: query.UserCanRun is not a function')).toBe(true);
        expect(LooksLikePoisonedEngine('Error running query: QUERY.USERCANRUN IS NOT A FUNCTION')).toBe(true);
    });

    it.each([
        ['an empty error', ''],
        ['a missing parameter', "Missing required parameter 'StartDate'"],
        ['a SQL error', "Invalid column name 'Revenue'."],
        ['a missing query', "Query 'Monthly Revenue' not found"],
        ['a permission failure', 'User does not have permission to run this query'],
        ['a function that exists but failed', 'function GetRevenue returned an error'],
    ])('does not match %s', (_label, error) => {
        expect(LooksLikePoisonedEngine(error)).toBe(false);
    });
});
