{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Communication Preferences Subscriptions",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-03",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "STARTER",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Batch"
  }, {
    "name" : "Definitions"
  }, {
    "name" : "Status"
  } ],
  "paths" : {
    "/communication-preferences/2026-03/definitions" : {
      "get" : {
        "tags" : [ "Definitions" ],
        "summary" : "Retrieve all subscription status definitions",
        "description" : "Get a list of subscription status definitions from the account.",
        "operationId" : "get-/communication-preferences/2026-03/definitions",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "oauth2" : [ "communication_preferences.read" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/links/generate" : {
      "post" : {
        "tags" : [ "Status" ],
        "summary" : "Generate subscription links",
        "description" : "Generate communication preference links for a subscriber. This endpoint allows you to create URLs for managing preferences and unsubscribing, tailored to a specific subscriber. It is useful for integrating communication preference management into your applications.",
        "operationId" : "post-/communication-preferences/2026-03/links/generate_/communication-preferences/v4/links/generate",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read", "communication_preferences.write" ]
        }, {
          "oauth2" : [ "communication_preferences.read_write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch retrieve subscription statuses",
        "description" : "Batch retrieve subscription statuses for a set of contacts.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/batch/read",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.read" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/batch/unsubscribe-all" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch unsubscribe contacts from all subscriptions",
        "description" : "Unsubscribe a set of contacts from all email subscriptions.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/batch/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/batch/unsubscribe-all/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch retrieve contacts who have opted out of all communications",
        "description" : "Checks whether a set of contacts have opted out of all communications.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/batch/unsubscribe-all/read",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.read" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/batch/write" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch update subscription status",
        "description" : "Update the subscription status for a set of contacts.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/batch/write",
        "security" : [ {
          "oauth2" : [ "communication_preferences.statuses.batch.write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/{subscriberIdString}" : {
      "get" : {
        "tags" : [ "Status" ],
        "summary" : "Get subscription preferences for a specific contact",
        "description" : "Retrieve a contact's current email subscription preferences.",
        "operationId" : "get-/communication-preferences/2026-03/statuses/{subscriberIdString}",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "oauth2" : [ "communication_preferences.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Status" ],
        "summary" : "Update a contact's subscription status",
        "description" : "Set the subscription status of a specific contact.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/{subscriberIdString}",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "oauth2" : [ "communication_preferences.write" ]
        } ]
      }
    },
    "/communication-preferences/2026-03/statuses/{subscriberIdString}/unsubscribe-all" : {
      "get" : {
        "tags" : [ "Status" ],
        "summary" : "Retrieve a contact's unsubscribed status",
        "description" : "Check whether a contact has unsubscribed from all email subscriptions. If a contact has not opted out of all communications, the response `results` array will be empty.",
        "operationId" : "get-/communication-preferences/2026-03/statuses/{subscriberIdString}/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "oauth2" : [ "communication_preferences.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Definitions" ],
        "summary" : "Unsubscribe a contact from all subscriptions",
        "description" : "Unsubscribe a contact from all email subscriptions.",
        "operationId" : "post-/communication-preferences/2026-03/statuses/{subscriberIdString}/unsubscribe-all",
        "security" : [ {
          "oauth2" : [ "communication_preferences.read_write" ]
        }, {
          "oauth2" : [ "communication_preferences.write" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "communication_preferences.read_write" : "",
              "communication_preferences.statuses.batch.read" : "",
              "communication_preferences.statuses.batch.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "STARTER",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}