{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Conversations Inbox & Messages",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-related-documentation" : [ {
      "name" : "Inbox & Messages Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/conversations/inbox-and-messages"
    } ]
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Actors"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Channel accounts"
  }, {
    "name" : "Channels"
  }, {
    "name" : "Inboxes"
  }, {
    "name" : "Messages"
  }, {
    "name" : "Threads"
  } ],
  "paths" : {
    "/conversations/conversations/v3/threads/{threadId}/assignee" : {
      "put" : {
        "tags" : [ "Basic" ],
        "operationId" : "put-/conversations/conversations/v3/threads/{threadId}/assignee_/conversations/conversations/v3/threads/{threadId}/assignee",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "operationId" : "delete-/conversations/conversations/v3/threads/{threadId}/assignee_/conversations/conversations/v3/threads/{threadId}/assignee",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ]
      }
    },
    "/conversations/v3/conversations/actors/batch/read" : {
      "post" : {
        "tags" : [ "Actors" ],
        "summary" : "Get a group of actors",
        "description" : "Resolve a set of `ActorId`s to the underlying actors/participants.",
        "operationId" : "post-/conversations/v3/conversations/actors/batch/read",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/actors/{actorId}" : {
      "get" : {
        "tags" : [ "Actors" ],
        "summary" : "Get a single actor",
        "description" : "Retrieve details of a single actor using the actor ID.",
        "operationId" : "get-/conversations/v3/conversations/actors/{actorId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channel-accounts" : {
      "get" : {
        "tags" : [ "Channel accounts" ],
        "summary" : "Get channel accounts",
        "description" : "Retrieve a list of channel accounts, with optional filters and sorting.",
        "operationId" : "get-/conversations/v3/conversations/channel-accounts",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channel-accounts/{channelAccountId}" : {
      "get" : {
        "tags" : [ "Channel accounts" ],
        "summary" : "Get a single channel account",
        "description" : "Retrieve details of a single channel account using the channel account ID.",
        "operationId" : "get-/conversations/v3/conversations/channel-accounts/{channelAccountId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channels" : {
      "get" : {
        "tags" : [ "Channels" ],
        "summary" : "Get channels",
        "description" : "Retrieve a list of channels, with optional filters and sorting.",
        "operationId" : "get-/conversations/v3/conversations/channels",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/channels/{channelId}" : {
      "get" : {
        "tags" : [ "Channels" ],
        "summary" : "Get a single channel",
        "description" : "Retrieve details of a single channel using the channel ID.",
        "operationId" : "get-/conversations/v3/conversations/channels/{channelId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/inboxes" : {
      "get" : {
        "tags" : [ "Inboxes" ],
        "summary" : "Get conversations inboxes",
        "description" : "Retrieve a list of conversations inboxes, with optional filters and sorting.",
        "operationId" : "get-/conversations/v3/conversations/inboxes",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/inboxes/{inboxId}" : {
      "get" : {
        "tags" : [ "Inboxes" ],
        "summary" : "Get a single conversations inbox",
        "description" : "Retrieve details of a single conversations inbox using the inbox ID.",
        "operationId" : "get-/conversations/v3/conversations/inboxes/{inboxId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads" : {
      "get" : {
        "tags" : [ "Threads" ],
        "summary" : "Get threads",
        "description" : "Retrieve a list of threads, with optional filters and sorting.",
        "operationId" : "get-/conversations/v3/conversations/threads",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}" : {
      "get" : {
        "tags" : [ "Threads" ],
        "summary" : "Get a single thread",
        "description" : "Retrieve a single thread by its ID",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Threads" ],
        "summary" : "Archives a thread",
        "description" : "Archives a single thread. The thread will be permanently deleted 30 days after placed in an archived state.",
        "operationId" : "delete-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Threads" ],
        "summary" : "Update a thread",
        "description" : "Updates a single thread. Either a thread's status can be updated, or the thread can be restored.",
        "operationId" : "patch-/conversations/v3/conversations/threads/{threadId}",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages" : {
      "get" : {
        "tags" : [ "Threads" ],
        "summary" : "Get message history for a thread",
        "description" : "Retrieve the message history for a specific thread.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Threads" ],
        "summary" : "Send a message to a thread",
        "description" : "Send a new message on a thread at the current timestamp.",
        "operationId" : "post-/conversations/v3/conversations/threads/{threadId}/messages",
        "security" : [ {
          "oauth2" : [ "conversations.write" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}" : {
      "get" : {
        "tags" : [ "Messages" ],
        "summary" : "Get a single message",
        "description" : "Retrieve a single message from a thread using the message ID.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content" : {
      "get" : {
        "tags" : [ "Messages" ],
        "summary" : "Get the original content of a single message",
        "description" : "Returns the complete original text and rich text bodies of a message. This will be different from the text and rich text in the message itself if the message's `truncationStatus` is anything other than `NOT_TRUNCATED`.",
        "operationId" : "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content",
        "security" : [ {
          "oauth2" : [ "conversations.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "conversations.read" : "",
              "conversations.write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}