import { Command, Flags } from '@oclif/core';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  convertFile,
  getRulesForDialects,
  createConversionStats,
  deduplicateEntityFieldSequences,
  convertMigration,
  IncrementalBaker,
} from '@memberjunction/sql-converter';
import type {
  BatchConverterConfig,
  BatchConverterResult,
  ConversionStats,
  MigrationConversionResult,
  BakerWorkingDB,
} from '@memberjunction/sql-converter';
import { MJPostgresTranspiler } from '@memberjunction/sqlglot-ts';
// Type-only import: erased at runtime, so the heavy codegen-lib value graph is NOT loaded
// by a plain `convert --split` — only the dynamic import() inside buildBaker() loads it.
import type { DataSourceResult } from '@memberjunction/codegen-lib';

/** The fields runSplit consumes from a per-migration conversion, shared by the
 *  transpile-only path (convertMigration) and the inline-baking path (IncrementalBaker). */
type ConvertedShape = Pick<MigrationConversionResult, 'status' | 'pgSQL' | 'unhandled' | 'handProcedural'>;

/**
 * CLI command to discover and convert T-SQL migrations to PostgreSQL.
 *
 * Scans the SQL Server migrations directory, identifies files that don't
 * have a corresponding .pg.sql counterpart in the PG migrations directory,
 * and converts them.
 *
 * Two strategies:
 * - `--split` (split-and-regenerate, the standard path): classify content by the
 *   generator that produced it, transpile only hand-written DDL via the AST dialect
 *   (sqlglot `mj_postgres.py`), drop CodeGen objects (regenerated by `mj codegen`)
 *   and mj-sync metadata (re-seeded by `mj sync push`), and surface every gap loudly.
 *   Requires Python 3 with sqlglot (`pip install sqlglot`; set MJ_SQLGLOT_PYTHON if
 *   not `python3` on PATH).
 * - default (legacy): the regex-based BatchConverter rule pipeline, which converts
 *   everything including appended CodeGen output. Retained for compatibility.
 *
 * Usage:
 *   mj migrate convert --split                       # Standard split-and-regenerate conversion
 *   mj migrate convert --split --file V20260401__foo.sql
 *   mj migrate convert --split --dry-run
 *   mj migrate convert                               # Legacy regex pipeline
 */
export default class MigrateConvert extends Command {
  static description = 'Convert T-SQL migrations to PostgreSQL';

  static examples = [
    '<%= config.bin %> migrate convert --split',
    '<%= config.bin %> migrate convert --split --dry-run',
    '<%= config.bin %> migrate convert --split --file V202604060452__v5.24.x__KnowledgeHub.sql',
    '<%= config.bin %> migrate convert --source-dir ./migrations/v5 --output-dir ./migrations-pg/v5',
    '<%= config.bin %> migrate convert --verbose',
  ];

  static flags = {
    'source-dir': Flags.string({
      description: 'Source T-SQL migrations directory',
      default: './migrations/v5',
    }),
    'output-dir': Flags.string({
      description: 'Output PG migrations directory',
      default: './migrations-pg/v5',
    }),
    file: Flags.string({
      description: 'Convert a specific file (filename only, looked up in source-dir)',
    }),
    schema: Flags.string({
      description: 'Target schema name',
      default: '__mj',
    }),
    'dry-run': Flags.boolean({
      description: 'Show what would be converted without writing files',
      default: false,
    }),
    'no-header': Flags.boolean({
      description: 'Skip PG header (extensions, schema, implicit cast)',
      default: false,
    }),
    verbose: Flags.boolean({
      char: 'v',
      description: 'Show per-statement progress',
      default: false,
    }),
    split: Flags.boolean({
      description:
        'Split-and-regenerate (the standard path): transpile only hand-written DDL via the AST ' +
        'dialect; CodeGen objects are regenerated by `mj codegen` and mj-sync metadata re-seeded ' +
        'by `mj sync push`; every conversion gap is surfaced and fails the run unless --allow-gaps.',
      default: false,
    }),
    'allow-gaps': Flags.boolean({
      description:
        'With --split: exit 0 even when migrations have conversion gaps (hand-authoring needed ' +
        'or unhandled statements). Gaps are still embedded as comments and listed in the summary.',
      default: false,
    }),
    'bake-codegen': Flags.boolean({
      description:
        'With --split: bake native PG CodeGen objects inline per migration (Path C), so the set ' +
        'deploys with `mj migrate` alone — no `mj codegen` step. Requires a LIVE working PG database ' +
        '(DB_PLATFORM=postgresql + PG_* env, same as `mj codegen`) seeded to the state just BEFORE ' +
        'the migrations being converted (typically the latest baseline); the converter brings it ' +
        'forward in committed order as it bakes. Not compatible with --dry-run.',
      default: false,
    }),
  };

  async run(): Promise<void> {
    const { flags } = await this.parse(MigrateConvert);

    if (flags['bake-codegen']) {
      if (!flags.split) this.error('--bake-codegen requires --split.');
      if (flags['dry-run']) this.error('--bake-codegen mutates a live working DB and is incompatible with --dry-run.');
    }

    if (flags.split) {
      await this.runSplit(flags);
      return;
    }

    const sourceDir = path.resolve(flags['source-dir']);
    const outputDir = path.resolve(flags['output-dir']);

    // Verify directories exist
    if (!fs.existsSync(sourceDir)) {
      this.error(`Source directory not found: ${sourceDir}`);
    }
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
      this.log(`Created output directory: ${outputDir}`);
    }

    // Load conversion rules
    const rules = getRulesForDialects('tsql', 'postgres');
    if (rules.length === 0) {
      this.error('No conversion rules found for tsql -> postgres');
    }

    // Discover migrations
    const unconverted = this.discoverUnconverted(sourceDir, outputDir, flags.file);

    if (unconverted.length === 0) {
      this.log('All migrations are already converted. Nothing to do.');
      return;
    }

    this.log(`Found ${unconverted.length} migration(s) to convert:\n`);
    for (const m of unconverted) {
      this.log(`  ${m.SourceFile} → ${m.OutputFile}`);
    }

    if (flags['dry-run']) {
      this.log('\nDry run — no files written.');
      return;
    }

    this.log('');

    // Convert each file
    let successCount = 0;
    let errorCount = 0;
    const totalStats: ConversionStats = createConversionStats();

    for (const migration of unconverted) {
      this.log(`Converting: ${migration.SourceFile}`);

      const config: BatchConverterConfig = {
        Source: path.join(sourceDir, migration.SourceFile),
        SourceIsFile: true,
        OutputFile: path.join(outputDir, migration.OutputFile),
        Rules: rules,
        Schema: flags.schema,
        SourceDialect: 'tsql',
        TargetDialect: 'postgres',
        IncludeHeader: !flags['no-header'],
        EnablePostProcess: true,
        OnProgress: flags.verbose ? (msg: string) => this.log(`  ${msg}`) : undefined,
      };

      const result: BatchConverterResult = convertFile(config);
      this.mergeStats(totalStats, result.Stats);

      if (result.Stats.Errors > 0) {
        errorCount++;
        this.logToStderr(`  ERRORS: ${result.Stats.Errors} in ${migration.SourceFile}`);
        for (const err of result.Stats.ErrorBatches) {
          this.logToStderr(`    ${err.substring(0, 200)}`);
        }
      } else {
        successCount++;
        this.log(`  OK (${result.Stats.Converted} batches, ${result.Stats.TotalBatches - result.Stats.Converted} skipped)`);
      }
    }

    // Print summary
    this.log('');
    this.log('=== Conversion Summary ===');
    this.log(`  Files:       ${unconverted.length} (${successCount} OK, ${errorCount} errors)`);
    this.log(`  Batches:     ${totalStats.TotalBatches} total, ${totalStats.Converted} converted, ${totalStats.Skipped} skipped, ${totalStats.Errors} errors`);
    this.log(`  Tables:      ${totalStats.TablesCreated}`);
    this.log(`  Views:       ${totalStats.ViewsCreated}`);
    this.log(`  Procedures:  ${totalStats.ProceduresConverted}`);
    this.log(`  Functions:   ${totalStats.FunctionsConverted}`);
    this.log(`  Triggers:    ${totalStats.TriggersConverted}`);
    this.log(`  Indexes:     ${totalStats.IndexesCreated}`);
    this.log(`  Inserts:     ${totalStats.InsertsConverted}`);
    this.log(`  Grants:      ${totalStats.GrantsConverted}`);

    if (errorCount > 0) {
      this.error(`Conversion completed with errors in ${errorCount} file(s)`);
    }

    // Post-conversion: deduplicate EntityField Sequence values across files
    // to prevent UQ_EntityField_EntityID_Sequence violations on PG
    this.log('\nRunning EntityField Sequence deduplication...');
    const dedupResult = deduplicateEntityFieldSequences(outputDir);
    if (dedupResult.totalCollisions > 0) {
      this.log(`  Fixed ${dedupResult.totalCollisions} sequence collision(s) across ${dedupResult.fixes.length} INSERT(s):`);
      for (const fix of dedupResult.fixes) {
        this.log(`    ${fix.file} line ${fix.line}: ${fix.originalSequence} → ${fix.newSequence}`);
      }
    } else {
      this.log(`  No collisions found (${dedupResult.totalInserts} EntityField INSERTs scanned).`);
    }
  }

  /**
   * Split-and-regenerate conversion (the standard path). Classification routes
   * content by the generator that produced it; the AST dialect transpiles what's
   * kept. Contract: nothing is dropped silently —
   * - needs-hand migrations are written as `<name>.pg.sql.needs-hand` (NOT a
   *   discoverable `.pg.sql`, so the migration stays visibly unconverted until a
   *   human finishes it) and fail the run;
   * - statements the dialect couldn't emit are embedded as gap comments in the
   *   output, listed in the summary, and fail the run unless --allow-gaps.
   *
   * See plans/pg-migration-architecture/SPLIT_AND_REGENERATE_PROPOSAL.md.
   */
  private async runSplit(flags: {
    'source-dir': string;
    'output-dir': string;
    file?: string;
    schema: string;
    'dry-run': boolean;
    'no-header': boolean;
    'allow-gaps': boolean;
    'bake-codegen': boolean;
  }): Promise<void> {
    const sourceDir = path.resolve(flags['source-dir']);
    const outputDir = path.resolve(flags['output-dir']);
    if (!fs.existsSync(sourceDir)) this.error(`Source directory not found: ${sourceDir}`);
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

    const unconverted = this.discoverUnconverted(sourceDir, outputDir, flags.file);
    if (unconverted.length === 0) {
      this.log('All migrations are already converted. Nothing to do.');
      return;
    }

    const transpiler = await this.buildTranspiler(sourceDir);

    // Select the per-migration conversion: inline-baking (live DB, CodeGen baked natively) or
    // the default transpile-only path (CodeGen regenerated by `mj codegen` at deploy).
    const bakeCodegen = flags['bake-codegen'];
    const baker = bakeCodegen ? await this.buildBaker(transpiler, flags.schema) : null;
    const convertOne = (sql: string, fileName: string): Promise<ConvertedShape> =>
      baker
        ? baker.bakeMigration(sql, fileName)
        : convertMigration(sql, fileName, { schema: flags.schema, includeHeader: !flags['no-header'], transpiler });
    if (bakeCodegen) this.log(`\nInline CodeGen baking ENABLED — bringing the working DB forward as each migration bakes.`);

    const converted: string[] = [];
    const regenReseed: string[] = [];
    const needsHand: { file: string; routines: string[] }[] = [];
    const withUnhandled: { file: string; count: number }[] = [];
    const gapReport: {
      sourceFile: string;
      outputFile: string;
      status: string;
      handProcedural: string[];
      unhandled: { kind: string; snippet: string }[];
    }[] = [];

    for (const m of unconverted) {
      const sql = fs.readFileSync(path.join(sourceDir, m.SourceFile), 'utf8');
      let result: ConvertedShape;
      try {
        result = await convertOne(sql, m.SourceFile);
      } catch (err) {
        this.error(`Conversion failed for ${m.SourceFile}: ${err instanceof Error ? err.message : String(err)}`);
      }

      // A needs-hand migration is NEVER written as a discoverable .pg.sql — that
      // would mark it converted forever and let Flyway apply an incomplete file.
      // The .needs-hand artifact carries the transpiled DDL + gap comments for the
      // human (or LLM last-mile pass) to finish, then rename to .pg.sql.
      const isNeedsHand = result.status === 'needs-hand-authoring';
      const outName = isNeedsHand ? `${m.OutputFile}.needs-hand` : m.OutputFile;
      const outPath = path.join(outputDir, outName);
      if (!flags['dry-run']) {
        if (isNeedsHand && fs.existsSync(outPath)) {
          // Someone may be mid-edit on the artifact — never clobber it on a re-run.
          this.warn(`${outName} already exists — not overwritten (delete it to regenerate).`);
        } else {
          fs.writeFileSync(outPath, result.pgSQL);
        }
      }

      if (result.status === 'needs-hand-authoring') {
        needsHand.push({ file: m.SourceFile, routines: result.handProcedural });
      } else if (result.status === 'reseed-or-regen-only') {
        regenReseed.push(m.SourceFile);
      } else {
        converted.push(m.SourceFile);
      }
      if (result.unhandled.length > 0) {
        withUnhandled.push({ file: m.SourceFile, count: result.unhandled.length });
      }
      if (result.status === 'needs-hand-authoring' || result.unhandled.length > 0) {
        gapReport.push({
          sourceFile: m.SourceFile,
          outputFile: outName,
          status: result.status,
          handProcedural: result.handProcedural,
          unhandled: result.unhandled,
        });
      }
    }

    // The consolidated gap artifact — everything a build engineer (or an LLM pass they
    // drive) needs to finish the conversion, in one machine-readable file.
    if (!flags['dry-run']) {
      const reportPath = path.join(outputDir, 'conversion-gaps.report.json');
      if (gapReport.length > 0) {
        fs.writeFileSync(
          reportPath,
          JSON.stringify({ generatedAt: new Date().toISOString(), sourceDir, gaps: gapReport }, null, 2),
        );
        this.log(`\nGap report written: ${reportPath}`);
      } else if (fs.existsSync(reportPath)) {
        fs.unlinkSync(reportPath); // clean run — stale report would misreport state
      }
    }

    this.printSplitSummary(converted, regenReseed, needsHand, withUnhandled, flags['dry-run'], bakeCodegen);

    const gapCount = needsHand.length + withUnhandled.length;
    if (gapCount > 0 && !flags['allow-gaps']) {
      // In bake mode the working DB pools are open; this.error → oclif force-exits anyway.
      this.error(
        `${needsHand.length} migration(s) need hand-authoring and ${withUnhandled.length} have ` +
          'unhandled statements. Resolve the gaps (conversion-gaps.report.json + comments in the ' +
          'output files), or pass --allow-gaps to accept them for now.',
      );
    }

    // setupDataSource() opened pg pools that keep the event loop alive, and CodeGenConnection
    // exposes no close(). Mirror the `mj codegen` command (runCodeGen.ts) and exit explicitly so
    // the CLI terminates after a clean bake.
    if (bakeCodegen) process.exit(0);
  }

  /**
   * Construct the AST transpiler with the cross-file BIT/BOOLEAN column registry
   * collected from the baselines (they declare the core tables, e.g. User.IsActive),
   * so per-file transpiles can coerce 1/0 → TRUE/FALSE in seed INSERTs that target
   * tables defined outside the migration being converted. Fails fast with install
   * guidance when Python/sqlglot is unavailable.
   */
  private async buildTranspiler(sourceDir: string): Promise<MJPostgresTranspiler> {
    const probe = new MJPostgresTranspiler();
    try {
      await probe.preflight();
    } catch (err) {
      this.error(err instanceof Error ? err.message : String(err));
    }

    const baselines = fs
      .readdirSync(sourceDir)
      .filter((f) => /^B\d.*\.sql$/.test(f) && !f.endsWith('.pg.sql') && !f.endsWith('.pg-only.sql'))
      .sort();
    const bitColumns: string[] = [];
    for (const b of baselines) {
      try {
        const cols = await probe.collectBitColumns(fs.readFileSync(path.join(sourceDir, b), 'utf8'));
        bitColumns.push(...cols);
      } catch (err) {
        // A baseline that fails bit-column collection degrades 1/0→TRUE/FALSE
        // coercion for tables it declares — warn loudly, don't proceed silently.
        this.warn(`Bit-column collection failed for ${b}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }
    return new MJPostgresTranspiler({ extraBitColumns: bitColumns });
  }

  /**
   * Build the inline-baking driver: connect to the live working PG database (the same
   * config/env `mj codegen` uses) and wire its apply / metadata-refresh / per-entity capture
   * into an IncrementalBaker.
   *
   * The codegen engine + data-provider stack is heavy and only this opt-in path needs it, so
   * the value graph is loaded with a dynamic import here (Rule 8 case 3 — bundle-size deferral;
   * codegen-lib + core are declared MJCLI deps) to keep a plain `convert --split` light. The
   * matching `import type` at the top is erased at runtime, so it does not defeat the deferral.
   */
  private async buildBaker(transpiler: MJPostgresTranspiler, schema: string): Promise<IncrementalBaker> {
    const { RunCodeGenBase, SQLCodeGenBase, initializeConfig, dbPlatform } = await import('@memberjunction/codegen-lib');
    const { Metadata } = await import('@memberjunction/core');

    if (dbPlatform() !== 'postgresql') {
      this.error('--bake-codegen requires DB_PLATFORM=postgresql with PG_* connection env (the working DB CodeGen objects are captured from).');
    }
    initializeConfig(process.cwd());

    let ds: DataSourceResult;
    try {
      ds = await new RunCodeGenBase().setupDataSource();
    } catch (err) {
      this.error(
        `--bake-codegen could not connect/load metadata from the working PG database: ${err instanceof Error ? err.message : String(err)}. ` +
          'Seed the working DB to the baseline (its __mj views + metadata must exist) before baking.',
      );
    }

    const sqlGen = new SQLCodeGenBase();
    const md = new Metadata();
    const db: BakerWorkingDB = {
      apply: async (sql: string) => {
        await ds.connection.query(sql);
      },
      refreshMetadata: async () => {
        await ds.provider.Refresh();
      },
      captureEntity: async (name: string) => {
        const entity = md.EntityByName(name);
        if (!entity) throw new Error(`--bake-codegen: entity not found in working-DB metadata: ${name}`);
        const r = await sqlGen.generateSingleEntitySQLToSeparateFiles({
          pool: ds.connection,
          entity,
          directory: os.tmpdir(), // inert — writeFiles is false
          onlyPermissions: false,
          writeFiles: false,
          skipExecution: false, // execute → keep the working DB current for later migrations
        });
        return { sql: r.sql ?? '', permissionsSQL: r.permissionsSQL ?? '' };
      },
    };
    return new IncrementalBaker({ transpiler, db, schema });
  }

  /** Print the split-and-regenerate run summary and the mandatory next steps. */
  private printSplitSummary(
    converted: string[],
    regenReseed: string[],
    needsHand: { file: string; routines: string[] }[],
    withUnhandled: { file: string; count: number }[],
    dryRun: boolean,
    bakeCodegen = false,
  ): void {
    this.log(`\n=== Split-and-Regenerate Summary${bakeCodegen ? ' (inline CodeGen baking)' : ''} ===`);
    this.log(`  transpiled (DDL):        ${converted.length}`);
    const regenNote = bakeCodegen ? 'CodeGen baked inline; metadata via mj sync push' : 'handled by mj codegen + mj sync push';
    this.log(`  regen/reseed only:       ${regenReseed.length}  (${regenNote})`);
    this.log(`  needs hand-authoring:    ${needsHand.length}`);
    this.log(`  with unhandled stmts:    ${withUnhandled.length}`);
    if (dryRun) this.log('  (dry run — no files written)');

    if (needsHand.length > 0) {
      this.logToStderr('\n  ⚠ Hand-written procedural SQL — written as .needs-hand files; finish and rename to .pg.sql:');
      for (const h of needsHand) this.logToStderr(`    ${h.file} — ${h.routines.slice(0, 5).join(', ')}`);
    }
    if (withUnhandled.length > 0) {
      this.logToStderr('\n  ⚠ Statements the AST transpiler could not emit (embedded as comments in the output):');
      for (const u of withUnhandled) this.logToStderr(`    ${u.file} — ${u.count} statement(s)`);
    }

    this.log('\nNext steps to complete the PG migration set (run against a fresh PG database):');
    if (bakeCodegen) {
      this.log('  1. resolve any gaps above (hand-author or LLM last-mile, then rename .needs-hand)');
      this.log('  2. mj migrate                  # apply DDL + inline-baked CodeGen objects (no codegen step)');
      this.log('  3. mj sync push                # re-seed mj-sync metadata');
      this.log('  4. schema/row-count diff vs a fresh SQL Server build to confirm parity');
    } else {
      this.log('  1. resolve any gaps above (hand-author or LLM last-mile, then rename .needs-hand)');
      this.log('  2. mj migrate                  # apply the transpiled DDL (.pg.sql)');
      this.log('  3. mj codegen                  # regenerate CodeGen SQL objects natively (DB_PLATFORM=postgresql)');
      this.log('  4. mj sync push                # re-seed mj-sync metadata');
      this.log('  5. schema/row-count diff vs a fresh SQL Server build to confirm parity');
    }
  }

  /**
   * Discovers T-SQL migrations that don't have a corresponding PG counterpart.
   *
   * A T-SQL file like `V202604060452__v5.24.x__Foo.sql` maps to
   * `V202604060452__v5.24.x__Foo.pg.sql` in the output directory; a `.pg-only.sql`
   * variant also counts as a counterpart (manual PG-specific override). Counterpart
   * presence is the only filter — baselines (B__) convert like any other file when
   * their `.pg.sql` is missing (statement-mode classification handles them).
   * `.needs-hand` artifacts are deliberately NOT counterparts: a migration stays
   * unconverted until its gaps are resolved and the file is renamed to `.pg.sql`.
   */
  private discoverUnconverted(
    sourceDir: string,
    outputDir: string,
    specificFile: string | undefined,
  ): Array<{ SourceFile: string; OutputFile: string }> {
    const sourceFiles = fs.readdirSync(sourceDir)
      .filter((f: string) => f.endsWith('.sql') && !f.endsWith('.pg.sql') && !f.endsWith('.pg-only.sql'))
      .sort();

    if (specificFile && !sourceFiles.includes(specificFile)) {
      this.error(`--file ${specificFile} not found in ${sourceDir}`);
    }

    const outputFiles = new Set(
      fs.readdirSync(outputDir)
        .filter((f: string) => f.endsWith('.pg.sql') || f.endsWith('.pg-only.sql'))
    );

    const unconverted: Array<{ SourceFile: string; OutputFile: string }> = [];

    for (const sourceFile of sourceFiles) {
      // If a specific file was requested, only convert that one
      if (specificFile && sourceFile !== specificFile) {
        continue;
      }

      // Generate expected PG filename: replace .sql with .pg.sql
      const pgFileName = sourceFile.replace(/\.sql$/, '.pg.sql');

      // Check if PG version already exists
      if (!outputFiles.has(pgFileName)) {
        // Also check if a .pg-only.sql variant exists (manual PG-specific override)
        const pgOnlyFileName = sourceFile.replace(/\.sql$/, '.pg-only.sql');
        if (!outputFiles.has(pgOnlyFileName)) {
          unconverted.push({
            SourceFile: sourceFile,
            OutputFile: pgFileName,
          });
        }
      }
    }

    return unconverted;
  }

  private mergeStats(target: ConversionStats, source: ConversionStats): void {
    target.TotalBatches += source.TotalBatches;
    target.Converted += source.Converted;
    target.Skipped += source.Skipped;
    target.Errors += source.Errors;
    target.TablesCreated += source.TablesCreated;
    target.ViewsCreated += source.ViewsCreated;
    target.ProceduresConverted += source.ProceduresConverted;
    target.FunctionsConverted += source.FunctionsConverted;
    target.TriggersConverted += source.TriggersConverted;
    target.IndexesCreated += source.IndexesCreated;
    target.InsertsConverted += source.InsertsConverted;
    target.GrantsConverted += source.GrantsConverted;
    target.FKConstraints += source.FKConstraints;
    target.CheckConstraints += source.CheckConstraints;
    target.CommentsConverted += source.CommentsConverted;
    target.ErrorBatches.push(...source.ErrorBatches);
    target.SkippedBatches.push(...source.SkippedBatches);
  }
}
