/**
 * @fileoverview Protected Resource Metadata per RFC 9728.
 *
 * Implements the OAuth 2.0 Protected Resource Metadata endpoint
 * as required by the MCP Authorization specification.
 *
 * The metadata endpoint at /.well-known/oauth-protected-resource
 * allows MCP clients to discover:
 * - The resource identifier (for audience validation)
 * - Authorization servers that can issue tokens
 * - Supported scopes and token delivery methods
 *
 * @module @memberjunction/ai-mcp-server/auth/ProtectedResourceMetadata
 */

import type { ProtectedResourceMetadata } from './types.js';
import { getResourceIdentifier, getScopes } from './OAuthConfig.js';

/**
 * Auth provider info needed for scope auto-generation.
 * Uses properties available from IAuthProvider interface.
 */
interface AuthProviderInfo {
  /** Provider name (e.g., 'azure', 'auth0') */
  name?: string;
  /** Issuer URL - used to detect provider type */
  issuer?: string;
  /** Audience - for Azure AD, this is the clientId (WEB_CLIENT_ID) */
  audience?: string;
}

/**
 * Options for building Protected Resource Metadata.
 */
export interface ProtectedResourceMetadataOptions {
  /** Override the resource identifier (defaults to configured value) */
  resourceIdentifier?: string;
  /** Authorization server issuer URLs (from configured auth providers) */
  authorizationServers: string[];
  /** Human-readable name for the resource */
  resourceName?: string;
  /** URL to resource documentation */
  resourceDocumentation?: string;
  /** Auth providers for automatic scope generation (optional) */
  providers?: AuthProviderInfo[];
  /**
   * When true, use the OAuth proxy as the authorization server.
   * This enables dynamic client registration for MCP clients.
   */
  useOAuthProxy?: boolean;
  /** Base URL for the OAuth proxy (e.g., http://localhost:3100) */
  oauthProxyBaseUrl?: string;
}

/**
 * Builds the Protected Resource Metadata response per RFC 9728.
 *
 * This metadata is served at `/.well-known/oauth-protected-resource`
 * and helps MCP clients discover how to authenticate.
 *
 * @param options - Configuration options for the metadata
 * @returns The Protected Resource Metadata object
 *
 * @example
 * const metadata = buildProtectedResourceMetadata({
 *   authorizationServers: ['https://login.microsoftonline.com/tenant/v2.0'],
 *   resourceName: 'My MCP Server',
 * });
 * // Returns:
 * // {
 * //   resource: "http://localhost:3100",
 * //   authorization_servers: ["https://login.microsoftonline.com/tenant/v2.0"],
 * //   scopes_supported: ["openid", "profile", "email"],
 * //   bearer_methods_supported: ["header"],
 * //   resource_name: "My MCP Server"
 * // }
 */
export function buildProtectedResourceMetadata(
  options: ProtectedResourceMetadataOptions
): ProtectedResourceMetadata {
  const resourceIdentifier = options.resourceIdentifier ?? getResourceIdentifier();

  // Determine authorization servers based on mode
  let authorizationServers: string[];
  let scopes: string[];

  if (options.useOAuthProxy && options.oauthProxyBaseUrl) {
    // OAuth Proxy mode: Point to our own authorization server
    // This enables dynamic client registration for MCP clients
    authorizationServers = [options.oauthProxyBaseUrl];

    // Use standard OIDC scopes - the proxy will handle Azure AD scopes internally
    scopes = ['openid', 'profile', 'email'];
  } else {
    // Direct mode: Point to upstream providers
    authorizationServers = options.authorizationServers;

    // Get scopes - use configured scopes, or auto-generate from providers
    const configuredScopes = getScopes();
    const useAutoGeneratedScopes = configuredScopes.length === 3 &&
      configuredScopes.includes('openid') &&
      configuredScopes.includes('profile') &&
      configuredScopes.includes('email');

    // If using default scopes and we have providers, auto-generate provider-specific scopes
    scopes = configuredScopes;
    if (useAutoGeneratedScopes && options.providers && options.providers.length > 0) {
      scopes = generateScopesFromProviders(options.providers);
    }
  }

  const metadata: ProtectedResourceMetadata = {
    // Required: The protected resource identifier
    resource: resourceIdentifier,

    // Required: Authorization servers that can issue tokens for this resource
    authorization_servers: authorizationServers,

    // Recommended: Scopes supported by this resource
    // Auto-generated from providers if not explicitly configured
    scopes_supported: scopes,

    // Recommended: Token delivery methods
    // MCP Server only accepts tokens in the Authorization header
    bearer_methods_supported: ['header'],

    // Optional: Human-readable name
    resource_name: options.resourceName ?? 'MemberJunction MCP Server',
  };

  // Add documentation URL if provided
  if (options.resourceDocumentation) {
    metadata.resource_documentation = options.resourceDocumentation;
  }

  return metadata;
}

/**
 * Extracts authorization server issuer URLs from auth providers.
 *
 * This helper function retrieves the issuer URLs from all configured
 * auth providers to include in the Protected Resource Metadata.
 *
 * @param providers - Array of auth provider configurations
 * @returns Array of unique issuer URLs
 */
export function extractAuthorizationServers(
  providers: Array<{ issuer?: string }>
): string[] {
  const issuers = providers
    .map(p => p.issuer)
    .filter((issuer): issuer is string => typeof issuer === 'string' && issuer.length > 0);

  // Return unique issuers
  return [...new Set(issuers)];
}

/**
 * Generates OAuth scopes from configured auth providers.
 *
 * This function auto-generates the appropriate scopes based on the provider:
 * - Azure AD (detected by issuer URL): api://{audience}/.default
 * - Auth0: Standard OIDC scopes
 * - Other providers: Standard OIDC scopes
 *
 * The generated scopes are used in Protected Resource Metadata to tell
 * MCP clients what scopes to request from the authorization server.
 *
 * @param providers - Array of auth provider configurations
 * @returns Array of scope strings
 */
function generateScopesFromProviders(providers: AuthProviderInfo[]): string[] {
  const scopes = new Set<string>();

  for (const provider of providers) {
    // Detect Azure AD by issuer URL pattern
    // Azure AD issuers are like: https://login.microsoftonline.com/{tenant}/v2.0
    const isAzureAD = provider.issuer?.includes('microsoftonline.com') ||
                      provider.issuer?.includes('sts.windows.net');

    if (isAzureAD && provider.audience) {
      // For Azure AD, audience is the clientId (WEB_CLIENT_ID)
      // Scope format: api://{clientId}/.default
      scopes.add(`api://${provider.audience}/.default`);
    }

    // Auth0 and other providers use standard OIDC scopes
    // The MCP client will request these scopes from the authorization server
  }

  // Always include standard OIDC scopes as fallback
  if (scopes.size === 0) {
    scopes.add('openid');
    scopes.add('profile');
    scopes.add('email');
  }

  return [...scopes];
}
