import { RegisterClass } from '@memberjunction/global';
import { Metadata, type IMetadataProvider, type UserInfo } from '@memberjunction/core';
import type { MJCompanyIntegrationEntity, MJCredentialEntity, MJIntegrationObjectEntity } from '@memberjunction/core-entities';
import {
    BaseIntegrationConnector,
    BaseRESTIntegrationConnector,
    type RESTAuthContext,
    type RESTResponse,
    type PaginationState,
    type PaginationType,
    type ConnectionTestResult,
    type ExternalObjectSchema,
    type ExternalFieldSchema,
    type FetchContext,
    type FetchBatchResult,
    type ExternalRecord,
    type CreateRecordContext,
    type UpdateRecordContext,
    type DeleteRecordContext,
    type CRUDResult,
    type DefaultFieldMapping,
    type DefaultIntegrationConfig,
    type IntegrationObjectInfo,
    type ActionGeneratorConfig,
    type SourceSchemaInfo,
    type SourceObjectInfo,
    type SourceFieldInfo,
    type SourceRelationshipInfo,
    type IntrospectSchemaOptions,
} from '@memberjunction/integration-engine';

// ─── Types ────────────────────────────────────────────────────────────

/**
 * Connection configuration for the Reach360 connector.
 * Reach 360 uses a single static Bearer token generated in the admin UI.
 */
export interface Reach360ConnectionConfig {
    /** Reach 360 API token (Bearer). Generated by an admin user in the Reach 360 UI. */
    apiKey: string;

    // ── Optional performance overrides ──────────────────────────────
    /** Maximum retries for rate-limited or failed requests. Default: 3 */
    MaxRetries?: number;
    /** HTTP request timeout in milliseconds. Default: 30000 */
    RequestTimeoutMs?: number;
    /** Minimum milliseconds between requests to avoid rate limiting. Default: 250 */
    MinRequestIntervalMs?: number;
}

/** Extended auth context with Reach360-specific config reference. */
interface Reach360AuthContext extends RESTAuthContext {
    Config: Reach360ConnectionConfig;
}

/** Shape of the cursor-paginated response envelope used by all Reach 360 list endpoints. */
interface Reach360PagedResponse {
    nextUrl?: string | null;
    [dataKey: string]: unknown;
}

// ─── Constants ────────────────────────────────────────────────────────

const REACH360_BASE_URL = 'https://api.reach360.com';

/** Default max retries when a request fails with a retryable error. */
const DEFAULT_MAX_RETRIES = 3;

/** Default HTTP request timeout (ms). */
const DEFAULT_REQUEST_TIMEOUT_MS = 30000;

/** Minimum interval between outbound requests (ms) — Reach 360 rate limits are undocumented. */
const DEFAULT_MIN_REQUEST_INTERVAL_MS = 250;

/** Default page size when the caller does not specify one — Reach 360 uses 50. Max 100. */
const DEFAULT_PAGE_SIZE = 50;

/** Absolute ceiling for requested page size per the documented API. */
const MAX_PAGE_SIZE = 100;

// ─── Static Action Metadata ───────────────────────────────────────────

/**
 * Objects exposed through the action generator. Mirrors the runtime metadata
 * defined in `metadata/integrations/.reach360.json` but is maintained here so
 * action generation does not require a live connection.
 */
const REACH360_OBJECTS: IntegrationObjectInfo[] = [
    {
        Name: 'Courses', DisplayName: 'Courses',
        Description: 'Courses authored in Articulate Rise/Storyline/Microlearning or imported SCORM/xAPI content.',
        SupportsWrite: false,
        Fields: [
            { Name: 'id', DisplayName: 'ID', Type: 'string', IsRequired: true, IsReadOnly: true, IsPrimaryKey: true, Description: 'Unique identifier of the course' },
            { Name: 'title', DisplayName: 'Title', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Course title' },
            { Name: 'contentType', DisplayName: 'Content Type', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Content source (rise/storyline/microlearning/imported)' },
            { Name: 'coverImageUrl', DisplayName: 'Cover Image URL', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'URL for course cover image' },
            { Name: 'authorUrl', DisplayName: 'Author URL', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'HATEOAS URL for course author' },
            { Name: 'url', DisplayName: 'URL', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Canonical URL for this course' },
        ],
    },
    {
        Name: 'Users', DisplayName: 'Users',
        Description: 'Reach 360 users — created via invitation or SSO provisioning.',
        SupportsWrite: false,
        Fields: [
            { Name: 'id', DisplayName: 'ID', Type: 'string', IsRequired: true, IsReadOnly: true, IsPrimaryKey: true, Description: 'Unique identifier of the user' },
            { Name: 'email', DisplayName: 'Email', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'User email — natural key' },
            { Name: 'role', DisplayName: 'Role', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'learner | author | admin' },
            { Name: 'firstName', DisplayName: 'First Name', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'User first name' },
            { Name: 'lastName', DisplayName: 'Last Name', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'User last name' },
            { Name: 'lastActiveAt', DisplayName: 'Last Active At', Type: 'datetime', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Last platform activity timestamp' },
            { Name: 'articulate360User', DisplayName: 'Articulate 360 User', Type: 'boolean', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Managed by Articulate 360 Teams subscription' },
        ],
    },
    {
        Name: 'Groups', DisplayName: 'Groups',
        Description: 'Groups used for user tagging/categorization and course assignment. UI-created; API supports membership mutations.',
        SupportsWrite: false,
        Fields: [
            { Name: 'id', DisplayName: 'ID', Type: 'string', IsRequired: true, IsReadOnly: true, IsPrimaryKey: true, Description: 'Unique identifier of the group' },
            { Name: 'name', DisplayName: 'Name', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Group name' },
            { Name: 'description', DisplayName: 'Description', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Group description' },
            { Name: 'usersUrl', DisplayName: 'Users URL', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'HATEOAS URL for group members' },
            { Name: 'coursesUrl', DisplayName: 'Courses URL', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'HATEOAS URL for group courses' },
        ],
    },
    {
        Name: 'LearningPaths', DisplayName: 'Learning Paths',
        Description: 'Ordered sequences of courses — created in the UI; enrollments manageable via API.',
        SupportsWrite: false,
        Fields: [
            { Name: 'id', DisplayName: 'ID', Type: 'string', IsRequired: true, IsReadOnly: true, IsPrimaryKey: true, Description: 'Unique identifier of the learning path' },
            { Name: 'title', DisplayName: 'Title', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Learning path title' },
            { Name: 'description', DisplayName: 'Description', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Learning path description' },
        ],
    },
    {
        Name: 'ActivityReport', DisplayName: 'Activity Report',
        Description: 'Account-wide session activity feed — primary source for incremental engagement data.',
        SupportsWrite: false,
        Fields: [
            { Name: 'courseId', DisplayName: 'Course ID', Type: 'string', IsRequired: true, IsReadOnly: true, IsPrimaryKey: true, Description: 'Course identifier' },
            { Name: 'userId', DisplayName: 'User ID', Type: 'string', IsRequired: true, IsReadOnly: true, IsPrimaryKey: true, Description: 'User identifier' },
            { Name: 'status', DisplayName: 'Status', Type: 'string', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Session status' },
            { Name: 'startedAt', DisplayName: 'Started At', Type: 'datetime', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Session start timestamp' },
            { Name: 'completedAt', DisplayName: 'Completed At', Type: 'datetime', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Session completion timestamp (watermark field)' },
            { Name: 'durationSeconds', DisplayName: 'Duration', Type: 'integer', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Session active duration in seconds' },
            { Name: 'quizScore', DisplayName: 'Quiz Score', Type: 'decimal', IsRequired: false, IsReadOnly: true, IsPrimaryKey: false, Description: 'Quiz score when applicable' },
        ],
    },
];

/**
 * Maps lowercase object names to the top-level response key that holds the
 * record array for list endpoints. Reach 360 wraps every list response under
 * a plural key (`courses`, `users`, `sessions`, etc.) alongside `nextUrl`.
 */
const REACH360_RESPONSE_DATA_KEYS: Record<string, string> = {
    courses: 'courses',
    users: 'users',
    groups: 'groups',
    learningpaths: 'learningPaths',
    activityreport: 'sessions',
};

/** Maps lowercase object names to their list API paths (relative to base URL). */
const REACH360_API_PATHS: Record<string, string> = {
    courses: '/courses',
    users: '/users',
    groups: '/groups',
    learningpaths: '/learning-paths',
    activityreport: '/reports/activity',
};

/**
 * Provable implicit foreign keys, keyed by lowercase object name → (field name →
 * referenced object's external name). Each entry is proven by a `<Sibling>Id`
 * field whose `<Sibling>` resolves (singular/plural-aware) to ANOTHER object
 * declared in REACH360_OBJECTS:
 *   - ActivityReport.courseId → Courses (composite-PK part; also the FK)
 *   - ActivityReport.userId   → Users   (composite-PK part; also the FK)
 * Both are part of ActivityReport's composite {courseId, userId} primary key —
 * the association/junction pattern — so each is simultaneously PK and FK.
 */
const REACH360_FOREIGN_KEYS: Record<string, Record<string, string>> = {
    activityreport: {
        courseId: 'Courses',
        userId: 'Users',
    },
};

/**
 * Promotes each object's OWN declared "last changed" timestamp into the
 * IncrementalWatermarkField slot. These are the exact fields the connector
 * already filters on client-side in `watermarkFieldFor()` / `applyClientWatermark()`:
 *   - ActivityReport → completedAt  (declared "Session completion timestamp (watermark field)")
 *   - Users          → lastActiveAt (declared "Last platform activity timestamp")
 * Objects with no declared change-timestamp are intentionally absent (honest gap).
 */
const REACH360_WATERMARK_FIELDS: Record<string, string> = {
    activityreport: 'completedAt',
    users: 'lastActiveAt',
};

// ─── Connector Implementation ─────────────────────────────────────────

/**
 * Connector for the Reach 360 LMS REST API.
 *
 * Reach 360 is Articulate's lightweight cloud LMS. The API is documented only
 * as HTML articles (no OpenAPI spec) and exposes ~25 endpoints across Courses,
 * Users, Groups, Learning Paths, Reports, Invitations and Completions.
 *
 * Auth: a single static Bearer token generated in the Reach 360 admin UI. No
 * OAuth flow, no refresh tokens. The token is sent on every request as
 * `Authorization: Bearer {apiKey}`.
 *
 * Pagination: cursor-based. List responses include a `nextUrl` pointer that
 * encodes the next cursor; follow until null.
 *
 * Incremental sync: Reach 360 has no CDC endpoint and no server-side date
 * filtering on list endpoints. Instead, `/reports/activity` acts as a
 * session-level change stream; callers filter client-side by `completedAt`.
 */
@RegisterClass(BaseIntegrationConnector, 'Reach360Connector')
export class Reach360Connector extends BaseRESTIntegrationConnector {

    /** Timestamp of the last HTTP request — used for throttling. */
    private lastRequestTime = 0;

    // ── Capability getters ────────────────────────────────────────────

    public override get SupportsCreate(): boolean { return true; }   // Invitations, Completions
    public override get SupportsUpdate(): boolean { return true; }   // Groups update via PUT /groups/{groupId}; other primary resources still return 400 in UpdateRecord
    public override get SupportsDelete(): boolean { return true; }   // User delete, group membership removal

    public override get IntegrationName(): string { return 'Reach360'; }

    // ── Action generation ─────────────────────────────────────────────

    /**
     * Returns the static object catalog for action generation. Derived from
     * Articulate's documented endpoint catalog (no OpenAPI spec exists).
     */
    public override GetIntegrationObjects(): IntegrationObjectInfo[] {
        return REACH360_OBJECTS;
    }

    public override GetActionGeneratorConfig(): ActionGeneratorConfig | null {
        const objects = this.GetIntegrationObjects();
        if (objects.length === 0) return null;
        return {
            IntegrationName: 'Reach360',
            CategoryName: 'Reach360',
            IconClass: 'fa-solid fa-graduation-cap',
            Objects: objects,
            IncludeSearch: false,
            IncludeList: false,
            CategoryDescription: 'Reach 360 LMS integration actions',
            ParentCategoryName: 'Learning',
        };
    }

    public override GetDefaultConfiguration(): DefaultIntegrationConfig | null {
        return {
            DefaultSchemaName: 'Reach360',
            DefaultObjects: [
                {
                    SourceObjectName: 'Users',
                    TargetTableName: 'Reach360_User',
                    TargetEntityName: 'Reach360 Users',
                    SyncEnabled: true,
                    FieldMappings: this.GetDefaultFieldMappings('Users', 'Contacts'),
                },
                {
                    SourceObjectName: 'Courses',
                    TargetTableName: 'Reach360_Course',
                    TargetEntityName: 'Reach360 Courses',
                    SyncEnabled: true,
                    FieldMappings: this.GetDefaultFieldMappings('Courses', 'Courses'),
                },
                {
                    SourceObjectName: 'ActivityReport',
                    TargetTableName: 'Reach360_Activity',
                    TargetEntityName: 'Reach360 Activity',
                    SyncEnabled: true,
                    FieldMappings: [],
                },
            ],
        };
    }

    public override GetDefaultFieldMappings(objectName: string, _entityName: string): DefaultFieldMapping[] {
        switch (objectName) {
            case 'Users':
                return [
                    { SourceFieldName: 'id', DestinationFieldName: 'ExternalID', IsKeyField: true },
                    { SourceFieldName: 'email', DestinationFieldName: 'Email' },
                    { SourceFieldName: 'firstName', DestinationFieldName: 'FirstName' },
                    { SourceFieldName: 'lastName', DestinationFieldName: 'LastName' },
                ];
            case 'Courses':
                return [
                    { SourceFieldName: 'id', DestinationFieldName: 'ExternalID', IsKeyField: true },
                    { SourceFieldName: 'title', DestinationFieldName: 'Title' },
                ];
            default:
                return [];
        }
    }

    // ─── TestConnection ──────────────────────────────────────────────

    /**
     * Verifies connectivity by hitting GET /users?limit=1. A 2xx response with
     * a recognizable envelope confirms both credentials and rate-limit posture.
     */
    public async TestConnection(
        companyIntegration: MJCompanyIntegrationEntity,
        contextUser: UserInfo
    ): Promise<ConnectionTestResult> {
        try {
            const auth = await this.Authenticate(companyIntegration, contextUser) as Reach360AuthContext;
            const url = `${REACH360_BASE_URL}/users?limit=1`;
            const headers = this.BuildHeaders(auth);
            const resp = await this.MakeHTTPRequest(auth, url, 'GET', headers);
            if (resp.Status < 200 || resp.Status >= 300) {
                return { Success: false, Message: `Reach360 TestConnection failed: HTTP ${resp.Status}` };
            }
            return {
                Success: true,
                Message: 'Successfully connected to Reach 360',
                ServerVersion: 'Reach 360 REST API v1',
            };
        } catch (err: unknown) {
            const message = err instanceof Error ? err.message : String(err);
            return { Success: false, Message: `Connection failed: ${message}` };
        }
    }

    // ─── Discovery ────────────────────────────────────────────────────

    /**
     * Overrides the base cache-driven discovery so the connector is usable
     * before the integration metadata has been seeded into the DB (e.g. at
     * first setup). Returns the static REACH360_OBJECTS catalog.
     */
    public override async DiscoverObjects(
        _companyIntegration: MJCompanyIntegrationEntity,
        _contextUser: UserInfo
    ): Promise<ExternalObjectSchema[]> {
        return REACH360_OBJECTS.map(obj => ({
            Name: obj.Name,
            Label: obj.DisplayName,
            Description: obj.Description,
            SupportsIncrementalSync: obj.Name === 'ActivityReport' || obj.Name === 'Users',
            SupportsWrite: obj.SupportsWrite,
        }));
    }

    /**
     * Returns the static field list for the named object. Reach 360 has no
     * custom-field system, so there is no runtime enrichment to perform.
     */
    public override async DiscoverFields(
        _companyIntegration: MJCompanyIntegrationEntity,
        objectName: string,
        _contextUser: UserInfo
    ): Promise<ExternalFieldSchema[]> {
        const obj = REACH360_OBJECTS.find(o => o.Name.toLowerCase() === objectName.toLowerCase());
        if (!obj) return [];
        const fkMap = REACH360_FOREIGN_KEYS[objectName.toLowerCase()] ?? {};
        return obj.Fields.map(f => {
            const fkTarget = fkMap[f.Name];
            return {
                Name: f.Name,
                Label: f.DisplayName,
                Description: f.Description,
                DataType: f.Type,
                IsRequired: f.IsRequired,
                IsPrimaryKey: f.IsPrimaryKey,
                IsUniqueKey: f.IsPrimaryKey,
                IsReadOnly: f.IsReadOnly,
                IsForeignKey: fkTarget != null,
                ForeignKeyTarget: fkTarget ?? null,
            };
        });
    }

    /**
     * Builds the source-schema introspection result from the static
     * REACH360_OBJECTS catalog. Overrides the base implementation purely to
     * additionally surface each object's IncrementalWatermarkField — the base
     * IntrospectSchema derives PK/FK from DiscoverFields() but does not emit a
     * watermark. All PK/FK/watermark values here are promoted from this
     * connector's OWN declared metadata (composite-PK association fields and the
     * declared change-timestamps); nothing is inferred from a live API.
     */
    public override async IntrospectSchema(
        companyIntegration: MJCompanyIntegrationEntity,
        contextUser: UserInfo,
        options?: IntrospectSchemaOptions
    ): Promise<SourceSchemaInfo> {
        const wanted = options?.ObjectNames && options.ObjectNames.length > 0
            ? new Set(options.ObjectNames.map(n => n.toLowerCase()))
            : null;
        const objects = wanted
            ? REACH360_OBJECTS.filter(o => wanted.has(o.Name.toLowerCase()))
            : REACH360_OBJECTS;

        const result: SourceSchemaInfo = { Objects: [] };
        for (const obj of objects) {
            const fields = await this.DiscoverFields(companyIntegration, obj.Name, contextUser);
            const sourceFields: SourceFieldInfo[] = fields.map(f => ({
                Name: f.Name,
                Label: f.Label,
                Description: f.Description,
                SourceType: f.DataType,
                IsRequired: f.IsRequired,
                AllowsNull: f.AllowsNull,
                MaxLength: f.MaxLength ?? null,
                Precision: f.Precision ?? null,
                Scale: f.Scale ?? null,
                DefaultValue: f.DefaultValue ?? null,
                IsPrimaryKey: f.IsPrimaryKey ?? false,
                IsUniqueKey: f.IsUniqueKey,
                IsReadOnly: f.IsReadOnly,
                IsForeignKey: f.IsForeignKey ?? false,
                ForeignKeyTarget: f.ForeignKeyTarget ?? null,
            }));
            const relationships: SourceRelationshipInfo[] = sourceFields
                .filter(f => f.IsForeignKey && f.ForeignKeyTarget)
                .map(f => ({ FieldName: f.Name, TargetObject: f.ForeignKeyTarget!, TargetField: 'ID' }));
            result.Objects.push({
                ExternalName: obj.Name,
                ExternalLabel: obj.DisplayName,
                Description: obj.Description,
                Fields: sourceFields,
                PrimaryKeyFields: sourceFields.filter(f => f.IsPrimaryKey).map(f => f.Name),
                Relationships: relationships,
                IncrementalWatermarkField: REACH360_WATERMARK_FIELDS[obj.Name.toLowerCase()],
            });
        }
        return result;
    }

    // ─── FetchChanges (cursor pagination) ────────────────────────────

    /**
     * Reach 360 uses cursor pagination via `nextUrl`. Fetches the configured
     * page size, follows the cursor chain until either `nextUrl` is null or
     * `BatchSize` is reached.
     *
     * For `ActivityReport` and `Users` objects the caller's watermark is
     * applied client-side against `completedAt` / `lastActiveAt` respectively.
     */
    public override async FetchChanges(ctx: FetchContext): Promise<FetchBatchResult> {
        const auth = await this.Authenticate(ctx.CompanyIntegration, ctx.ContextUser) as Reach360AuthContext;
        const objLower = ctx.ObjectName.toLowerCase();
        const path = REACH360_API_PATHS[objLower];
        if (!path) {
            console.warn(`[Reach360] No API path mapped for object "${ctx.ObjectName}"`);
            return { Records: [], HasMore: false };
        }
        const dataKey = REACH360_RESPONSE_DATA_KEYS[objLower] ?? objLower;

        const pageSize = Math.min(ctx.BatchSize ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE);
        const initialUrl = ctx.CurrentCursor
            ? this.DecodeCursor(ctx.CurrentCursor)
            : `${REACH360_BASE_URL}${path}?limit=${pageSize}`;

        const { records, nextCursor } = await this.fetchCursorBatch(auth, initialUrl, dataKey, ctx.BatchSize);
        const { filtered, newWatermark } = this.applyClientWatermark(records, objLower, ctx.WatermarkValue);

        const externalRecords = filtered.map(r => this.toExternalRecord(r, ctx.ObjectName));
        return {
            Records: externalRecords,
            HasMore: nextCursor != null,
            NextCursor: nextCursor ?? undefined,
            NewWatermarkValue: !nextCursor && newWatermark ? newWatermark : undefined,
        };
    }

    /**
     * Walks the `nextUrl` chain starting from `startUrl` and accumulates up to
     * `batchSize` records. Returns the raw record array and the final cursor
     * (base64-encoded `nextUrl` when more remain, or null).
     */
    private async fetchCursorBatch(
        auth: Reach360AuthContext,
        startUrl: string,
        dataKey: string,
        batchSize: number
    ): Promise<{ records: Record<string, unknown>[]; nextCursor: string | null }> {
        const all: Record<string, unknown>[] = [];
        let url: string | null = startUrl;
        const limit = batchSize > 0 ? batchSize : Number.MAX_SAFE_INTEGER;

        while (url && all.length < limit) {
            const headers = this.BuildHeaders(auth);
            const resp = await this.MakeHTTPRequest(auth, url, 'GET', headers);
            if (resp.Status < 200 || resp.Status >= 300) {
                throw new Error(`Reach360 GET ${url} returned HTTP ${resp.Status}`);
            }
            const body = (resp.Body ?? {}) as Reach360PagedResponse;
            const arr = body[dataKey];
            if (Array.isArray(arr)) {
                all.push(...(arr as Record<string, unknown>[]));
            }
            const next = typeof body.nextUrl === 'string' && body.nextUrl.length > 0 ? body.nextUrl : null;
            if (!next || all.length >= limit) {
                return { records: all.slice(0, limit), nextCursor: all.length >= limit && next ? this.EncodeCursor(next) : null };
            }
            url = next;
        }

        return { records: all, nextCursor: null };
    }

    /**
     * Applies a client-side watermark filter against the appropriate date
     * field for the given object. Returns records newer than the watermark
     * plus the latest observed timestamp (to update the watermark after the
     * final page).
     */
    private applyClientWatermark(
        records: Record<string, unknown>[],
        objLower: string,
        watermark: string | null
    ): { filtered: Record<string, unknown>[]; newWatermark: string | null } {
        const dateField = this.watermarkFieldFor(objLower);
        if (!dateField) return { filtered: records, newWatermark: null };

        const watermarkDate = watermark ? new Date(watermark) : null;
        let latest: Date | null = null;
        const filtered: Record<string, unknown>[] = [];

        for (const rec of records) {
            const raw = rec[dateField];
            if (typeof raw !== 'string' || raw.length === 0) {
                filtered.push(rec);
                continue;
            }
            const parsed = new Date(raw);
            if (isNaN(parsed.getTime())) {
                filtered.push(rec);
                continue;
            }
            if (!latest || parsed > latest) latest = parsed;
            if (!watermarkDate || parsed > watermarkDate) filtered.push(rec);
        }
        return { filtered, newWatermark: latest ? latest.toISOString() : null };
    }

    /** Returns the date field used for incremental filtering, if any. */
    private watermarkFieldFor(objLower: string): string | null {
        if (objLower === 'activityreport') return 'completedAt';
        if (objLower === 'users') return 'lastActiveAt';
        return null;
    }

    /**
     * Converts a raw Reach 360 record into an ExternalRecord. ActivityReport
     * uses a composite {courseId, userId} key.
     */
    private toExternalRecord(raw: Record<string, unknown>, objectType: string): ExternalRecord {
        const externalID = this.extractExternalID(raw, objectType);
        return { ExternalID: externalID, ObjectType: objectType, Fields: raw };
    }

    private extractExternalID(raw: Record<string, unknown>, objectType: string): string {
        if (objectType.toLowerCase() === 'activityreport') {
            const cid = raw['courseId'] != null ? String(raw['courseId']) : '';
            const uid = raw['userId'] != null ? String(raw['userId']) : '';
            return `${cid}|${uid}`;
        }
        return raw['id'] != null ? String(raw['id']) : '';
    }

    // ─── CRUD Operations ─────────────────────────────────────────────

    /**
     * Supported creates:
     *   - Invitations → POST /invitations
     *   - Completions → POST /courses/{courseId}/users/{userId}/completions
     *                   (requires `courseId` + `userId` on Attributes)
     *   - Group membership → POST /groups/{groupId}/users
     *                         (requires `groupId` on Attributes)
     */
    public override async CreateRecord(ctx: CreateRecordContext): Promise<CRUDResult> {
        const companyIntegration = ctx.CompanyIntegration as MJCompanyIntegrationEntity;
        const contextUser = ctx.ContextUser as UserInfo;
        try {
            const auth = await this.Authenticate(companyIntegration, contextUser) as Reach360AuthContext;
            const headers = this.BuildHeaders(auth);
            const route = this.resolveCreateRoute(ctx.ObjectName, ctx.Attributes);
            if (!route) {
                return { Success: false, ErrorMessage: `Reach360 CreateRecord not supported for "${ctx.ObjectName}"`, StatusCode: 400 };
            }
            const url = `${REACH360_BASE_URL}${route.path}`;
            const resp = await this.MakeHTTPRequest(auth, url, 'POST', headers, route.body);
            if (resp.Status < 200 || resp.Status >= 300) {
                return this.buildCRUDError(resp, 'CreateRecord', ctx.ObjectName);
            }
            const body = (resp.Body ?? {}) as Record<string, unknown>;
            const id = body['id'] != null ? String(body['id']) : (route.fallbackID ?? '');
            return { Success: true, ExternalID: id, StatusCode: resp.Status };
        } catch (err: unknown) {
            const message = err instanceof Error ? err.message : String(err);
            return { Success: false, ErrorMessage: `Reach360 CreateRecord failed: ${message}`, StatusCode: 500 };
        }
    }

    /**
     * Resolves which REST route a CreateRecord call maps to. Drives the router
     * from object name + payload fields so no hardcoded switch on individual
     * object behavior leaks into the HTTP code.
     */
    private resolveCreateRoute(
        objectName: string,
        attrs: Record<string, unknown>
    ): { path: string; body: Record<string, unknown>; fallbackID?: string } | null {
        const obj = objectName.toLowerCase();
        if (obj === 'invitations') {
            return { path: '/invitations', body: attrs };
        }
        if (obj === 'completions') {
            const courseId = attrs['courseId'];
            const userId = attrs['userId'];
            if (typeof courseId !== 'string' || typeof userId !== 'string') return null;
            const { courseId: _c, userId: _u, ...body } = attrs;
            return {
                path: `/courses/${encodeURIComponent(courseId)}/users/${encodeURIComponent(userId)}/completions`,
                body,
                fallbackID: `${courseId}|${userId}`,
            };
        }
        if (obj === 'groupmembers' || obj === 'groupmembership' || obj === 'groupusers') {
            const groupId = attrs['groupId'];
            if (typeof groupId !== 'string') return null;
            const { groupId: _g, ...body } = attrs;
            return { path: `/groups/${encodeURIComponent(groupId)}/users`, body };
        }
        return null;
    }

    /**
     * Reach 360 update endpoints (per vendor docs as of audit):
     *   - Groups        → PUT /groups/{groupId}     — name, description, tag updates
     *   - Users         → not supported (no PUT/PATCH on /users/{id})
     *   - Courses       → not supported (no PUT/PATCH on /courses/{id})
     *   - Learning Paths → not supported
     *   - Reports       → not supported
     */
    public override async UpdateRecord(ctx: UpdateRecordContext): Promise<CRUDResult> {
        const objectLower = ctx.ObjectName.toLowerCase();
        if (objectLower === 'groups') {
            const companyIntegration = ctx.CompanyIntegration as MJCompanyIntegrationEntity;
            const contextUser = ctx.ContextUser as UserInfo;
            try {
                const auth = await this.Authenticate(companyIntegration, contextUser) as Reach360AuthContext;
                const headers = this.BuildHeaders(auth);
                const url = `${REACH360_BASE_URL}/groups/${encodeURIComponent(ctx.ExternalID)}`;
                const resp = await this.MakeHTTPRequest(auth, url, 'PUT', headers, ctx.Attributes);
                if (resp.Status >= 200 && resp.Status < 300) {
                    return { Success: true, ExternalID: ctx.ExternalID, StatusCode: resp.Status };
                }
                return this.buildCRUDError(resp, 'UpdateRecord', ctx.ObjectName);
            } catch (err: unknown) {
                const message = err instanceof Error ? err.message : String(err);
                return { Success: false, ErrorMessage: `Reach360 UpdateRecord failed: ${message}`, StatusCode: 500 };
            }
        }
        return {
            Success: false,
            ErrorMessage: `Reach360 UpdateRecord not supported for "${ctx.ObjectName}" — only Groups supports PUT in the vendor API.`,
            StatusCode: 400,
        };
    }

    /**
     * Supported deletes:
     *   - Users → DELETE /users/{userId}
     *   - Group membership → DELETE /groups/{groupId}/users/{userId}
     *                         (requires `groupId` to be supplied via ExternalID
     *                          as `{groupId}|{userId}`)
     */
    public override async DeleteRecord(ctx: DeleteRecordContext): Promise<CRUDResult> {
        const companyIntegration = ctx.CompanyIntegration as MJCompanyIntegrationEntity;
        const contextUser = ctx.ContextUser as UserInfo;
        try {
            const auth = await this.Authenticate(companyIntegration, contextUser) as Reach360AuthContext;
            const headers = this.BuildHeaders(auth);
            const path = this.resolveDeletePath(ctx.ObjectName, ctx.ExternalID);
            if (!path) {
                return { Success: false, ErrorMessage: `Reach360 DeleteRecord not supported for "${ctx.ObjectName}"`, StatusCode: 400 };
            }
            const url = `${REACH360_BASE_URL}${path}`;
            const resp = await this.MakeHTTPRequest(auth, url, 'DELETE', headers);
            if (resp.Status < 200 || resp.Status >= 300) {
                return this.buildCRUDError(resp, 'DeleteRecord', ctx.ObjectName);
            }
            return { Success: true, ExternalID: ctx.ExternalID, StatusCode: resp.Status };
        } catch (err: unknown) {
            const message = err instanceof Error ? err.message : String(err);
            return { Success: false, ErrorMessage: `Reach360 DeleteRecord failed: ${message}`, StatusCode: 500 };
        }
    }

    private resolveDeletePath(objectName: string, externalID: string): string | null {
        const obj = objectName.toLowerCase();
        if (obj === 'users') {
            return `/users/${encodeURIComponent(externalID)}`;
        }
        if (obj === 'groupmembers' || obj === 'groupmembership' || obj === 'groupusers') {
            const [groupId, userId] = externalID.split('|');
            if (!groupId || !userId) return null;
            return `/groups/${encodeURIComponent(groupId)}/users/${encodeURIComponent(userId)}`;
        }
        return null;
    }

    private buildCRUDError(resp: RESTResponse, op: string, objectName: string): CRUDResult {
        const body = resp.Body as Record<string, unknown> | undefined;
        const rawMessage = typeof body?.['message'] === 'string' ? (body['message'] as string) : undefined;
        return {
            Success: false,
            ErrorMessage: rawMessage ?? `Reach360 ${op} on ${objectName} failed (HTTP ${resp.Status})`,
            StatusCode: resp.Status,
        };
    }

    // ─── Abstract REST hooks (BaseRESTIntegrationConnector) ───────────

    protected async Authenticate(
        companyIntegration: MJCompanyIntegrationEntity,
        contextUser: UserInfo
    ): Promise<RESTAuthContext> {
        const config = await this.parseConfig(companyIntegration, contextUser);
        return { Token: config.apiKey, Config: config } as Reach360AuthContext;
    }

    protected BuildHeaders(auth: RESTAuthContext): Record<string, string> {
        const token = auth.Token ?? '';
        return {
            'Authorization': `Bearer ${token}`,
            'Accept': 'application/json',
        };
    }

    /**
     * Not used by this connector — FetchChanges walks `nextUrl` directly and
     * bypasses the base pagination engine. Still required to satisfy the
     * abstract contract.
     */
    protected NormalizeResponse(rawBody: unknown, responseDataKey: string | null): Record<string, unknown>[] {
        if (!responseDataKey) return Array.isArray(rawBody) ? rawBody as Record<string, unknown>[] : [];
        const body = rawBody as Record<string, unknown>;
        const arr = body[responseDataKey];
        return Array.isArray(arr) ? arr as Record<string, unknown>[] : [];
    }

    /**
     * Pagination info is expressed through Reach 360's `nextUrl` pointer which
     * the cursor path already consumes directly. This hook is retained for API
     * compliance and simply reports "no more pages" to anyone calling through
     * the base pipeline.
     */
    protected ExtractPaginationInfo(
        rawBody: unknown,
        _paginationType: PaginationType,
        _currentPage: number,
        _currentOffset: number,
        _pageSize: number
    ): PaginationState {
        const body = rawBody as Reach360PagedResponse | undefined;
        const next = typeof body?.nextUrl === 'string' && body.nextUrl.length > 0 ? body.nextUrl : null;
        return { HasMore: next != null, NextCursor: next ?? undefined };
    }

    protected GetBaseURL(
        _companyIntegration: MJCompanyIntegrationEntity,
        _auth: RESTAuthContext
    ): string {
        return REACH360_BASE_URL;
    }

    // ─── HTTP transport with retry + throttling ───────────────────────

    protected async MakeHTTPRequest(
        auth: RESTAuthContext,
        url: string,
        method: string,
        headers: Record<string, string>,
        body?: unknown
    ): Promise<RESTResponse> {
        const r360 = auth as Reach360AuthContext;
        const cfg = r360.Config;
        const maxRetries = cfg.MaxRetries ?? DEFAULT_MAX_RETRIES;
        const timeoutMs = cfg.RequestTimeoutMs ?? DEFAULT_REQUEST_TIMEOUT_MS;
        const minInterval = cfg.MinRequestIntervalMs ?? DEFAULT_MIN_REQUEST_INTERVAL_MS;

        for (let attempt = 0; attempt <= maxRetries; attempt++) {
            await this.throttle(minInterval);
            try {
                const resp = await this.doFetch(url, method, headers, body, timeoutMs);
                this.lastRequestTime = Date.now();
                if (resp.Status === 429 || resp.Status === 503) {
                    if (attempt === maxRetries) return resp;
                    await this.sleep(this.backoffMs(attempt));
                    continue;
                }
                return resp;
            } catch (err: unknown) {
                if (attempt === maxRetries) throw err;
                const retryable = this.isRetryableError(err);
                if (!retryable) throw err;
                await this.sleep(this.backoffMs(attempt));
            }
        }
        throw new Error(`Reach360 request to ${url} exhausted ${maxRetries + 1} attempts`);
    }

    /** Executes a single fetch() with an AbortController-backed timeout. */
    private async doFetch(
        url: string,
        method: string,
        headers: Record<string, string>,
        body: unknown,
        timeoutMs: number
    ): Promise<RESTResponse> {
        const controller = new AbortController();
        const handle = setTimeout(() => controller.abort(), timeoutMs);
        const finalHeaders: Record<string, string> = { ...headers };
        if (body !== undefined && !finalHeaders['Content-Type']) {
            finalHeaders['Content-Type'] = 'application/json';
        }
        try {
            const resp = await fetch(url, {
                method,
                headers: finalHeaders,
                body: body !== undefined ? JSON.stringify(body) : undefined,
                signal: controller.signal,
            });
            const respHeaders: Record<string, string> = {};
            resp.headers.forEach((value, key) => { respHeaders[key.toLowerCase()] = value; });
            const text = await resp.text();
            const parsed = text.length > 0 ? this.safeParseJSON(text) : null;
            return { Status: resp.status, Body: parsed, Headers: respHeaders };
        } finally {
            clearTimeout(handle);
        }
    }

    private safeParseJSON(text: string): unknown {
        try { return JSON.parse(text) as unknown; } catch { return text; }
    }

    private isRetryableError(err: unknown): boolean {
        const msg = err instanceof Error ? err.message : String(err);
        return /abort|timeout|ECONNRESET|ENOTFOUND|ETIMEDOUT|network/i.test(msg);
    }

    private backoffMs(attempt: number): number {
        const base = Math.min(1000 * Math.pow(2, attempt), 15000);
        const jitter = Math.floor(Math.random() * 250);
        return base + jitter;
    }

    private async throttle(minIntervalMs: number): Promise<void> {
        const elapsed = Date.now() - this.lastRequestTime;
        if (elapsed < minIntervalMs) {
            await this.sleep(minIntervalMs - elapsed);
        }
    }

    private sleep(ms: number): Promise<void> {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    // ─── Cursor helpers ──────────────────────────────────────────────

    /** Encodes a full `nextUrl` into an opaque cursor string. */
    private EncodeCursor(nextUrl: string): string {
        return Buffer.from(nextUrl, 'utf-8').toString('base64url');
    }

    /** Decodes a previously encoded cursor back to its `nextUrl`. */
    private DecodeCursor(cursor: string): string {
        return Buffer.from(cursor, 'base64url').toString('utf-8');
    }

    // ─── Config parsing ───────────────────────────────────────────────

    private async parseConfig(
        companyIntegration: MJCompanyIntegrationEntity,
        contextUser: UserInfo
    ): Promise<Reach360ConnectionConfig> {
        const credentialID = companyIntegration.CredentialID;
        if (credentialID) {
            const fromCred = await this.loadFromCredential(credentialID, contextUser);
            if (fromCred) return fromCred;
        }
        const raw = companyIntegration.Configuration;
        if (!raw) {
            throw new Error('Reach360Connector: No credential or Configuration JSON found on CompanyIntegration');
        }
        const parsed = JSON.parse(raw) as Partial<Reach360ConnectionConfig>;
        return this.validateConfig(parsed);
    }

    private async loadFromCredential(
        credentialID: string,
        contextUser: UserInfo,
        provider?: IMetadataProvider
    ): Promise<Reach360ConnectionConfig | null> {
        const md = provider ?? new Metadata();
        const credential = await md.GetEntityObject<MJCredentialEntity>('MJ: Credentials', contextUser);
        const loaded = await credential.Load(credentialID);
        if (!loaded || !credential.Values) return null;
        try {
            const parsed = JSON.parse(credential.Values) as Partial<Reach360ConnectionConfig>;
            return this.validateConfig(parsed);
        } catch {
            return null;
        }
    }

    private validateConfig(raw: Partial<Reach360ConnectionConfig>): Reach360ConnectionConfig {
        if (!raw.apiKey || typeof raw.apiKey !== 'string') {
            throw new Error('Reach360Connector: apiKey is required');
        }
        return {
            apiKey: raw.apiKey,
            MaxRetries: raw.MaxRetries ?? DEFAULT_MAX_RETRIES,
            RequestTimeoutMs: raw.RequestTimeoutMs ?? DEFAULT_REQUEST_TIMEOUT_MS,
            MinRequestIntervalMs: raw.MinRequestIntervalMs ?? DEFAULT_MIN_REQUEST_INTERVAL_MS,
        };
    }
}

/** Tree-shaking prevention function — import and call from module entry point. */
export function LoadReach360Connector(): void { /* no-op */ }
