/**
 * Type definitions for QueryGen package
 */

import { EntityInfo, EntityRelationshipInfo } from '@memberjunction/core';

/**
 * Represents a group of related entities for query generation
 */
export interface EntityGroup {
  entities: EntityInfo[];
  relationships: EntityRelationshipInfo[];
  primaryEntity: EntityInfo;
  relationshipType: 'single' | 'parent-child' | 'many-to-many';

  // LLM-generated semantic metadata
  businessDomain: string;           // e.g., "Sales Pipeline", "Inventory Management"
  businessRationale: string;        // Why this grouping makes business sense
  expectedQuestionTypes: string[];  // e.g., ["trend_analysis", "aggregation", "comparison"]
}

/**
 * Entity metadata formatted for AI prompts
 */
export interface EntityMetadataForPrompt {
  entityName: string;
  description: string;
  schemaName: string;
  baseTable: string;
  baseView: string;
  fields: EntityFieldMetadata[];
  relationships: EntityRelationshipMetadata[];
}

/**
 * Entity field metadata for prompts
 */
export interface EntityFieldMetadata {
  name: string;
  displayName: string;
  type: string;
  sqlFullType: string;
  description: string;
  isPrimaryKey: boolean;
  isForeignKey: boolean;
  isVirtual: boolean;
  allowsNull: boolean;
  relatedEntity?: string;
  isRequired: boolean;
  defaultValue?: string;
  possibleValues?: string[];
}

/**
 * Entity relationship metadata for prompts
 */
export interface EntityRelationshipMetadata {
  type: 'one-to-many' | 'many-to-one' | 'many-to-many';
  relatedEntity: string;
  relatedEntityView: string;
  relatedEntitySchema: string;
  foreignKeyField: string;
  description: string;
}

/**
 * Business question generated by AI
 */
export interface BusinessQuestion {
  userQuestion: string;
  description: string;
  technicalDescription: string;
  complexity: 'simple' | 'medium' | 'complex';
  requiresAggregation: boolean;
  requiresJoins: boolean;
  entities: string[];
}

/**
 * SQL query generated by AI
 * Note: selectClause removed - MJQueryEntity automatically creates MJQueryFieldEntity records from SQL
 */
export interface GeneratedQuery {
  queryName: string;
  sql: string;
  parameters: QueryParameter[];
}

/**
 * Query output field definition
 */
export interface QueryOutputField {
  name: string;
  description: string;
  type: string;
  optional: boolean;
}

/**
 * Query parameter definition
 */
export interface QueryParameter {
  name: string;
  type: string;
  isRequired: boolean;
  description: string;
  usage: string[];
  defaultValue: string | null;
  sampleValue: string;
}

/**
 * Golden query for few-shot learning
 */
export interface GoldenQuery {
  name: string;
  userQuestion: string;
  description: string;
  technicalDescription: string;
  sql: string;
  parameters: QueryParameter[];
  selectClause: QueryOutputField[];
}

/**
 * Similarity search result
 * Note: nameSim excluded since queries don't have names until after generation
 */
export interface SimilarQuery {
  query: GoldenQuery;
  similarity: number;
  fieldScores: {
    userQuestionSim: number;
    descSim: number;
    techDescSim: number;
  };
}

/**
 * Query test result
 */
export interface QueryTestResult {
  success: boolean;
  renderedSQL?: string;
  rowCount?: number;
  sampleRows?: unknown[];
  attempts?: number;
  error?: string;
}

/**
 * Query evaluation result
 */
export interface QueryEvaluation {
  answersQuestion: boolean;
  confidence: number;
  reasoning: string;
  suggestions: string[];
  needsRefinement: boolean;
}

/**
 * Refined query result
 */
export interface RefinedQuery {
  query: GeneratedQuery;
  testResult: QueryTestResult;
  evaluation: QueryEvaluation;
  refinementCount: number;
  reachedMaxRefinements?: boolean;
}

/**
 * Query category information for metadata export and database write
 */
export interface QueryCategoryInfo {
  /** Name of the category */
  name: string;
  /** Parent category name (null for root categories) */
  parentName: string | null;
  /** Category description */
  description: string;
  /** Full category path (e.g., "Golden-Queries/Members") */
  path: string;
}

/**
 * Validated query ready for export
 */
export interface ValidatedQuery {
  businessQuestion: BusinessQuestion;
  query: GeneratedQuery;
  testResult: QueryTestResult;
  evaluation: QueryEvaluation;
  entityGroup: EntityGroup;
  category: QueryCategoryInfo;
}

/**
 * Metadata export result
 */
export interface ExportResult {
  success: boolean;
  outputPath: string;
  queryCount: number;
}

/**
 * Database write result
 */
export interface WriteResult {
  success: boolean;
  results: string[];
}

/**
 * Query metadata record for MJ metadata format
 *
 * Note: QueryFields and QueryParameters are not included here.
 * They are automatically extracted by MJQueryEntity.server.ts using
 * AI analysis of the SQL template during the Save() operation.
 */
export interface QueryMetadataRecord {
  fields: {
    Name: string;
    CategoryID: string;
    UserQuestion: string;
    Description: string;
    TechnicalDescription: string;
    SQL: string;
    UsesTemplate: boolean;
    Status: string;
  };
}

/**
 * Embeddings for a query or golden query
 * Note: name is excluded since queries don't have names until after generation
 */
export interface QueryEmbeddings {
  userQuestion: number[];
  description: number[];
  technicalDescription: number[];
}

/**
 * Golden query with embeddings
 */
export interface EmbeddedGoldenQuery {
  query: GoldenQuery;
  embeddings: QueryEmbeddings;
}
