-- ============================================================================
-- MemberJunction PostgreSQL Migration — V202607071500__v5.46.x__OpenApp_LastCompletedStep.sql
-- Additive DDL + EntityField metadata only (no baked view/sproc regen). The base view
-- (vwOpenApps) and CRUD routines (spCreateOpenApp/spUpdateOpenApp/spDeleteOpenApp) that
-- expose these two columns are regenerated by a normal `mj codegen` pass after this
-- migration applies — same as the SQL Server side, which relies on deploy-time CodeGen
-- rather than hand-baking sproc/view SQL into the migration file.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE SCHEMA IF NOT EXISTS __mj;
SET search_path TO __mj, public;
SET standard_conforming_strings = on;

ALTER TABLE __mj."OpenApp"
    ADD COLUMN "LastCompletedStep" VARCHAR(50) NULL,
    ADD COLUMN "LastCompletedStepTargetVersion" VARCHAR(20) NULL;

ALTER TABLE __mj."OpenApp"
    ADD CONSTRAINT "CK_OpenApp_LastCompletedStep"
    CHECK ("LastCompletedStep" IS NULL OR "LastCompletedStep" IN (
        'RecordCreated', 'PackagesInstalled', 'ConfigUpdated', 'AngularExcludesUpdated', 'Finalized', 'HooksRun',
        'MigrationsApplied', 'RecordUpdated', 'DependenciesReplaced',
        'DbCleanupDone', 'FilesRemoved'
    ));

COMMENT ON COLUMN __mj."OpenApp"."LastCompletedStep" IS 'The last install/upgrade/remove step that completed successfully for this app while Status is Installing, Upgrading, or Removing. Used to resume a crashed or failed operation from the correct point instead of restarting it entirely. Cleared (NULL) once the operation reaches a terminal state (Active/Disabled/Removed/Error).';
COMMENT ON COLUMN __mj."OpenApp"."LastCompletedStepTargetVersion" IS 'The version this app was being upgraded TO when LastCompletedStep was last written, for Upgrade only. A resume only trusts LastCompletedStep when this matches the version currently being requested — otherwise a checkpoint from an interrupted upgrade to a different version could wrongly skip steps for the new target. Cleared alongside LastCompletedStep.';

-- ---------------------------------------------------------------------------------------------------
-- EntityField metadata for the two new columns. On SQL Server, deploy-time CodeGen introspects the
-- new columns and creates these rows; under PG (no deploy codegen assumed) they are inserted inline
-- so a subsequent `mj codegen` pass has metadata to regenerate the base view/sprocs against.
-- ---------------------------------------------------------------------------------------------------
DO $mj_ef$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM __mj."EntityField"
                 WHERE "ID" = 'c2a8b40a-272c-40e1-875d-71b59df51ffe'
                    OR ("EntityID" = 'ac4a2799-454b-4395-aa56-a42241f32c12' AND "Name" = 'LastCompletedStep')) THEN
    INSERT INTO __mj."EntityField" (
      "ID","EntityID","Sequence","Name","DisplayName","Description","Type","Length",
      "Precision","Scale","AllowsNull","DefaultValue","AutoIncrement","AllowUpdateAPI",
      "IsVirtual","IsComputed","RelatedEntityID","RelatedEntityFieldName","IsNameField",
      "IncludeInUserSearchAPI","IncludeRelatedEntityNameFieldInBaseView","DefaultInView",
      "IsPrimaryKey","IsUnique","RelatedEntityDisplayType"
    ) VALUES (
      'c2a8b40a-272c-40e1-875d-71b59df51ffe', 'ac4a2799-454b-4395-aa56-a42241f32c12' /* Entity: MJ: Open Apps */,
      23, 'LastCompletedStep', 'Last Completed Step',
      'The last install/upgrade/remove step that completed successfully for this app while Status is Installing, Upgrading, or Removing. Used to resume a crashed or failed operation from the correct point instead of restarting it entirely. Cleared (NULL) once the operation reaches a terminal state (Active/Disabled/Removed/Error).',
      'nvarchar', 100, 0, 0, TRUE, NULL, FALSE, TRUE, FALSE, FALSE, NULL, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Search'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM __mj."EntityField"
                 WHERE "ID" = '431567e4-23e6-4738-8071-fb784da946f5'
                    OR ("EntityID" = 'ac4a2799-454b-4395-aa56-a42241f32c12' AND "Name" = 'LastCompletedStepTargetVersion')) THEN
    INSERT INTO __mj."EntityField" (
      "ID","EntityID","Sequence","Name","DisplayName","Description","Type","Length",
      "Precision","Scale","AllowsNull","DefaultValue","AutoIncrement","AllowUpdateAPI",
      "IsVirtual","IsComputed","RelatedEntityID","RelatedEntityFieldName","IsNameField",
      "IncludeInUserSearchAPI","IncludeRelatedEntityNameFieldInBaseView","DefaultInView",
      "IsPrimaryKey","IsUnique","RelatedEntityDisplayType"
    ) VALUES (
      '431567e4-23e6-4738-8071-fb784da946f5', 'ac4a2799-454b-4395-aa56-a42241f32c12' /* Entity: MJ: Open Apps */,
      24, 'LastCompletedStepTargetVersion', 'Last Completed Step Target Version',
      'The version this app was being upgraded TO when LastCompletedStep was last written, for Upgrade only. A resume only trusts LastCompletedStep when this matches the version currently being requested — otherwise a checkpoint from an interrupted upgrade to a different version could wrongly skip steps for the new target. Cleared alongside LastCompletedStep.',
      'nvarchar', 40, 0, 0, TRUE, NULL, FALSE, TRUE, FALSE, FALSE, NULL, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Search'
    );
  END IF;
END $mj_ef$;

-- NOTE: the base view (vwOpenApps) and spCreateOpenApp/spUpdateOpenApp/spDeleteOpenApp are NOT
-- regenerated inline here — run `mj codegen` after this migration to pick up the two new columns
-- in the view + CRUD routines. A future revision of this file should bake the CodeGen output
-- natively (matching the pattern in V202606260000__v5.43.x__OpenApp_Subpath.pg.sql) if this
-- migration needs to apply in a deployment path that does not run CodeGen after migrate.
