-- ============================================================================
-- MemberJunction PostgreSQL Migration — V202606171325__v5.41.x__Normalize_EntityField_CodeType_Casing.sql
-- Generated by the split-and-regenerate pipeline (AST dialect transpile of
-- hand-written DDL; CodeGen objects regenerated natively; metadata re-seeded).
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE SCHEMA IF NOT EXISTS __mj;
SET search_path TO __mj, public;
SET standard_conforming_strings = on;

-- ============================================================================
-- Normalize EntityField.CodeType to the canonical casing allowed by
-- CK_EntityField_CodeType ('Other','JavaScript','CSS','HTML','SQL','TypeScript').
--
-- SQL Server's default case-insensitive collation accepts mis-cased values
-- (e.g. 'Typescript'), so they slip past the CHECK and are carried into the
-- generated baselines. PostgreSQL's CHECK is case-sensitive and rejects them on
-- ANY update of the row, which breaks `mj codegen` on a fresh PostgreSQL
-- install. Correcting the canonical data here keeps future baseline
-- regenerations clean on both platforms.
--
-- PG translation of the SQL Server original: the source used a case-INsensitive
-- `CodeType = 'X'` predicate (default SS collation) combined with a
-- case-SENSITIVE `CodeType COLLATE Latin1_General_BIN2 <> 'X'` guard to match
-- only the mis-cased rows. PostgreSQL has no Latin1_General_BIN2 collation and
-- is case-sensitive by default, so the faithful equivalent is
-- `LOWER("CodeType") = '<lowercase>'` (case-insensitive match) AND
-- `"CodeType" <> 'X'` (case-sensitive guard). Correctly-cased rows are left
-- untouched (no spurious __mj_UpdatedAt churn or record-change rows).
-- ============================================================================
UPDATE __mj."EntityField" SET "CodeType" = 'TypeScript'
  WHERE LOWER("CodeType") = 'typescript' AND "CodeType" <> 'TypeScript';
UPDATE __mj."EntityField" SET "CodeType" = 'JavaScript'
  WHERE LOWER("CodeType") = 'javascript' AND "CodeType" <> 'JavaScript';
UPDATE __mj."EntityField" SET "CodeType" = 'HTML'
  WHERE LOWER("CodeType") = 'html' AND "CodeType" <> 'HTML';
UPDATE __mj."EntityField" SET "CodeType" = 'CSS'
  WHERE LOWER("CodeType") = 'css' AND "CodeType" <> 'CSS';
UPDATE __mj."EntityField" SET "CodeType" = 'SQL'
  WHERE LOWER("CodeType") = 'sql' AND "CodeType" <> 'SQL';
UPDATE __mj."EntityField" SET "CodeType" = 'Other'
  WHERE LOWER("CodeType") = 'other' AND "CodeType" <> 'Other';
