-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj;
SET search_path TO __mj, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- Implicit INTEGER -> BOOLEAN cast (SQL Server BIT columns accept 0/1 in INSERTs)
-- PostgreSQL has a built-in explicit-only INTEGER->bool cast. We upgrade it to implicit
-- so INSERT VALUES with 0/1 for BOOLEAN columns work like SQL Server BIT.
UPDATE pg_cast SET castcontext = 'i'
WHERE castsource = 'integer'::regtype AND casttarget = 'boolean'::regtype;


-- ===================== DDL: Tables, PKs, Indexes =====================


-- ===================== Helper Functions (fn*) =====================


-- ===================== Views =====================


-- ===================== Stored Procedures (sp*) =====================


-- ===================== Triggers =====================


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- SQL Logging Session
-- Session ID: 57747897-7fed-4131-b27b-eeaafd755a46
-- Started: 2026-02-27T20:00:51.595Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction SQLServerDataProvider

-- Save MJ: AI Vendors (core SP call only)
DO $$
DECLARE
  p_ID_6e9ea39b UUID;
  p_Name_6e9ea39b VARCHAR(50);
  p_Description_6e9ea39b TEXT;
  p_CredentialTypeID_6e9ea39b UUID;
BEGIN
  p_ID_6e9ea39b := '5c070719-85b1-4c3b-9c9e-3be8b6b64d7e';
  p_Name_6e9ea39b := 'MiniMax';
  p_Description_6e9ea39b := 'MiniMax is a Chinese AI company developing large language models including the M-series. Known for the MiniMax-M2.5 MoE model (230B total / 10B active parameters) with state-of-the-art coding and agentic capabilities, competing with frontier models at significantly lower cost. MIT licensed open-weights models.';
  p_CredentialTypeID_6e9ea39b := '3F0C13AB-EF5F-4260-A50A-D66DDEC25270';
  PERFORM __mj."spCreateAIVendor"(p_ID := p_ID_6e9ea39b, p_Name := p_Name_6e9ea39b, p_Description := p_Description_6e9ea39b, p_CredentialTypeID := p_CredentialTypeID_6e9ea39b);
END $$;

-- Save MJ: AI Models (core SP call only)
DO $$
DECLARE
  p_ID_d8266e0f UUID;
  p_Name_d8266e0f VARCHAR(50);
  p_Description_d8266e0f TEXT;
  p_AIModelTypeID_d8266e0f UUID;
  p_PowerRank_d8266e0f INTEGER;
  p_IsActive_d8266e0f BOOLEAN;
  p_SpeedRank_d8266e0f INTEGER;
  p_CostRank_d8266e0f INTEGER;
  p_ModelSelectionInsights_d8266e0f TEXT;
  p_InheritTypeModalities_d8266e0f BOOLEAN;
  p_PriorVersionID_d8266e0f UUID;
BEGIN
  p_ID_d8266e0f := '4e731caa-9765-41dd-a6cb-f68945561753';
  p_Name_d8266e0f := 'MiniMax-M2.5';
  p_Description_d8266e0f := 'MiniMax''s frontier MoE model released February 12, 2026. 230B total parameters (10B active) with 204K token context window and 128K output capacity. Achieves 80.2% on SWE-bench Verified, comparable to Claude Opus on coding benchmarks. Features built-in chain-of-thought reasoning (<think> tags), function calling, and agentic tool use. Extensively trained with RL across hundreds of thousands of real-world environments. Open-weights under MIT license.';
  p_AIModelTypeID_d8266e0f := 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E';
  p_PowerRank_d8266e0f := 20;
  p_IsActive_d8266e0f := 1;
  p_SpeedRank_d8266e0f := 8;
  p_CostRank_d8266e0f := 3;
  p_InheritTypeModalities_d8266e0f := 1;
  PERFORM __mj."spCreateAIModel"(p_ID := p_ID_d8266e0f, p_Name := p_Name_d8266e0f, p_Description := p_Description_d8266e0f, p_AIModelTypeID := p_AIModelTypeID_d8266e0f, p_PowerRank := p_PowerRank_d8266e0f, p_IsActive := p_IsActive_d8266e0f, p_SpeedRank := p_SpeedRank_d8266e0f, p_CostRank := p_CostRank_d8266e0f, p_ModelSelectionInsights := p_ModelSelectionInsights_d8266e0f, p_InheritTypeModalities := p_InheritTypeModalities_d8266e0f, p_PriorVersionID := p_PriorVersionID_d8266e0f);
END $$;

-- Save MJ: AI Models (core SP call only)
DO $$
DECLARE
  p_ID_c4075929 UUID;
  p_Name_c4075929 VARCHAR(50);
  p_Description_c4075929 TEXT;
  p_AIModelTypeID_c4075929 UUID;
  p_PowerRank_c4075929 INTEGER;
  p_IsActive_c4075929 BOOLEAN;
  p_SpeedRank_c4075929 INTEGER;
  p_CostRank_c4075929 INTEGER;
  p_ModelSelectionInsights_c4075929 TEXT;
  p_InheritTypeModalities_c4075929 BOOLEAN;
  p_PriorVersionID_c4075929 UUID;
BEGIN
  p_ID_c4075929 := '6d185cab-a4c0-4b5f-ac34-6c922ce6f1a8';
  p_Name_c4075929 := 'MiniMax-M2.5-highspeed';
  p_Description_c4075929 := 'MiniMax''s high-speed variant of M2.5, identical in capability but optimized for ~100 tokens/sec output (vs ~60 tps for standard M2.5). Same 230B MoE architecture (10B active) with 204K context and 128K output. Ideal for latency-sensitive agentic workflows where rapid iteration matters. 2x the price of standard M2.5 but still very cost-effective for frontier-class performance.';
  p_AIModelTypeID_c4075929 := 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E';
  p_PowerRank_c4075929 := 20;
  p_IsActive_c4075929 := 1;
  p_SpeedRank_c4075929 := 10;
  p_CostRank_c4075929 := 4;
  p_InheritTypeModalities_c4075929 := 1;
  PERFORM __mj."spCreateAIModel"(p_ID := p_ID_c4075929, p_Name := p_Name_c4075929, p_Description := p_Description_c4075929, p_AIModelTypeID := p_AIModelTypeID_c4075929, p_PowerRank := p_PowerRank_c4075929, p_IsActive := p_IsActive_c4075929, p_SpeedRank := p_SpeedRank_c4075929, p_CostRank := p_CostRank_c4075929, p_ModelSelectionInsights := p_ModelSelectionInsights_c4075929, p_InheritTypeModalities := p_InheritTypeModalities_c4075929, p_PriorVersionID := p_PriorVersionID_c4075929);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_2c47c898 UUID;
  p_ModelID_2c47c898 UUID;
  p_VendorID_2c47c898 UUID;
  p_Priority_2c47c898 INTEGER;
  p_Status_2c47c898 VARCHAR(20);
  p_DriverClass_2c47c898 VARCHAR(100);
  p_DriverImportPath_2c47c898 VARCHAR(255);
  p_APIName_2c47c898 VARCHAR(100);
  p_MaxInputTokens_2c47c898 INTEGER;
  p_MaxOutputTokens_2c47c898 INTEGER;
  p_SupportedResponseFormats_2c47c898 VARCHAR(100);
  p_SupportsEffortLevel_2c47c898 BOOLEAN;
  p_SupportsStreaming_2c47c898 BOOLEAN;
  p_TypeID_2c47c898 UUID;
BEGIN
  p_ID_2c47c898 := 'eb300db7-354a-4f4a-9154-818aeb6b46e0';
  p_ModelID_2c47c898 := '4E731CAA-9765-41DD-A6CB-F68945561753';
  p_VendorID_2c47c898 := '5C070719-85B1-4C3B-9C9E-3BE8B6B64D7E';
  p_Priority_2c47c898 := 0;
  p_Status_2c47c898 := 'Active';
  p_SupportedResponseFormats_2c47c898 := 'Any';
  p_SupportsEffortLevel_2c47c898 := 1;
  p_SupportsStreaming_2c47c898 := 0;
  p_TypeID_2c47c898 := '10DB468E-F2CE-475D-9F39-2DF2DE75D257';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_2c47c898, p_ModelID := p_ModelID_2c47c898, p_VendorID := p_VendorID_2c47c898, p_Priority := p_Priority_2c47c898, p_Status := p_Status_2c47c898, p_DriverClass := p_DriverClass_2c47c898, p_DriverImportPath := p_DriverImportPath_2c47c898, p_APIName := p_APIName_2c47c898, p_MaxInputTokens := p_MaxInputTokens_2c47c898, p_MaxOutputTokens := p_MaxOutputTokens_2c47c898, p_SupportedResponseFormats := p_SupportedResponseFormats_2c47c898, p_SupportsEffortLevel := p_SupportsEffortLevel_2c47c898, p_SupportsStreaming := p_SupportsStreaming_2c47c898, p_TypeID := p_TypeID_2c47c898);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_0ba823e0 UUID;
  p_ModelID_0ba823e0 UUID;
  p_VendorID_0ba823e0 UUID;
  p_Priority_0ba823e0 INTEGER;
  p_Status_0ba823e0 VARCHAR(20);
  p_DriverClass_0ba823e0 VARCHAR(100);
  p_DriverImportPath_0ba823e0 VARCHAR(255);
  p_APIName_0ba823e0 VARCHAR(100);
  p_MaxInputTokens_0ba823e0 INTEGER;
  p_MaxOutputTokens_0ba823e0 INTEGER;
  p_SupportedResponseFormats_0ba823e0 VARCHAR(100);
  p_SupportsEffortLevel_0ba823e0 BOOLEAN;
  p_SupportsStreaming_0ba823e0 BOOLEAN;
  p_TypeID_0ba823e0 UUID;
BEGIN
  p_ID_0ba823e0 := 'd064c8b1-a247-4728-9e00-140820612acd';
  p_ModelID_0ba823e0 := '4E731CAA-9765-41DD-A6CB-F68945561753';
  p_VendorID_0ba823e0 := '5C070719-85B1-4C3B-9C9E-3BE8B6B64D7E';
  p_Priority_0ba823e0 := 0;
  p_Status_0ba823e0 := 'Active';
  p_DriverClass_0ba823e0 := 'MiniMaxLLM';
  p_APIName_0ba823e0 := 'MiniMax-M2.5';
  p_MaxInputTokens_0ba823e0 := 204800;
  p_MaxOutputTokens_0ba823e0 := 131072;
  p_SupportedResponseFormats_0ba823e0 := 'Any, JSON';
  p_SupportsEffortLevel_0ba823e0 := 1;
  p_SupportsStreaming_0ba823e0 := 1;
  p_TypeID_0ba823e0 := '5B043EC3-1FF2-4730-B5D2-7CFDA50979B3';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_0ba823e0, p_ModelID := p_ModelID_0ba823e0, p_VendorID := p_VendorID_0ba823e0, p_Priority := p_Priority_0ba823e0, p_Status := p_Status_0ba823e0, p_DriverClass := p_DriverClass_0ba823e0, p_DriverImportPath := p_DriverImportPath_0ba823e0, p_APIName := p_APIName_0ba823e0, p_MaxInputTokens := p_MaxInputTokens_0ba823e0, p_MaxOutputTokens := p_MaxOutputTokens_0ba823e0, p_SupportedResponseFormats := p_SupportedResponseFormats_0ba823e0, p_SupportsEffortLevel := p_SupportsEffortLevel_0ba823e0, p_SupportsStreaming := p_SupportsStreaming_0ba823e0, p_TypeID := p_TypeID_0ba823e0);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_2f4a8040 UUID;
  p_ModelID_2f4a8040 UUID;
  p_VendorID_2f4a8040 UUID;
  p_Priority_2f4a8040 INTEGER;
  p_Status_2f4a8040 VARCHAR(20);
  p_DriverClass_2f4a8040 VARCHAR(100);
  p_DriverImportPath_2f4a8040 VARCHAR(255);
  p_APIName_2f4a8040 VARCHAR(100);
  p_MaxInputTokens_2f4a8040 INTEGER;
  p_MaxOutputTokens_2f4a8040 INTEGER;
  p_SupportedResponseFormats_2f4a8040 VARCHAR(100);
  p_SupportsEffortLevel_2f4a8040 BOOLEAN;
  p_SupportsStreaming_2f4a8040 BOOLEAN;
  p_TypeID_2f4a8040 UUID;
BEGIN
  p_ID_2f4a8040 := '03538687-3297-4f7f-99ef-dfcc79858d37';
  p_ModelID_2f4a8040 := '4E731CAA-9765-41DD-A6CB-F68945561753';
  p_VendorID_2f4a8040 := '5AD8786B-2D00-45D5-AFBE-DAEC48963FFC';
  p_Priority_2f4a8040 := 1;
  p_Status_2f4a8040 := 'Active';
  p_DriverClass_2f4a8040 := 'OpenRouterLLM';
  p_APIName_2f4a8040 := 'minimax/minimax-m2.5';
  p_MaxInputTokens_2f4a8040 := 196608;
  p_MaxOutputTokens_2f4a8040 := 131072;
  p_SupportedResponseFormats_2f4a8040 := 'Any, JSON';
  p_SupportsEffortLevel_2f4a8040 := 1;
  p_SupportsStreaming_2f4a8040 := 1;
  p_TypeID_2f4a8040 := '5B043EC3-1FF2-4730-B5D2-7CFDA50979B3';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_2f4a8040, p_ModelID := p_ModelID_2f4a8040, p_VendorID := p_VendorID_2f4a8040, p_Priority := p_Priority_2f4a8040, p_Status := p_Status_2f4a8040, p_DriverClass := p_DriverClass_2f4a8040, p_DriverImportPath := p_DriverImportPath_2f4a8040, p_APIName := p_APIName_2f4a8040, p_MaxInputTokens := p_MaxInputTokens_2f4a8040, p_MaxOutputTokens := p_MaxOutputTokens_2f4a8040, p_SupportedResponseFormats := p_SupportedResponseFormats_2f4a8040, p_SupportsEffortLevel := p_SupportsEffortLevel_2f4a8040, p_SupportsStreaming := p_SupportsStreaming_2f4a8040, p_TypeID := p_TypeID_2f4a8040);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_ff15fc8c UUID;
  p_ModelID_ff15fc8c UUID;
  p_VendorID_ff15fc8c UUID;
  p_Priority_ff15fc8c INTEGER;
  p_Status_ff15fc8c VARCHAR(20);
  p_DriverClass_ff15fc8c VARCHAR(100);
  p_DriverImportPath_ff15fc8c VARCHAR(255);
  p_APIName_ff15fc8c VARCHAR(100);
  p_MaxInputTokens_ff15fc8c INTEGER;
  p_MaxOutputTokens_ff15fc8c INTEGER;
  p_SupportedResponseFormats_ff15fc8c VARCHAR(100);
  p_SupportsEffortLevel_ff15fc8c BOOLEAN;
  p_SupportsStreaming_ff15fc8c BOOLEAN;
  p_TypeID_ff15fc8c UUID;
BEGIN
  p_ID_ff15fc8c := '04f3c004-bda4-40e2-8a0d-5148c7be1ace';
  p_ModelID_ff15fc8c := '4E731CAA-9765-41DD-A6CB-F68945561753';
  p_VendorID_ff15fc8c := '66B67DA3-D048-43CD-AF25-BF683AB8DB74';
  p_Priority_ff15fc8c := 1;
  p_Status_ff15fc8c := 'Active';
  p_DriverClass_ff15fc8c := 'FireworksLLM';
  p_APIName_ff15fc8c := 'accounts/fireworks/models/minimax-m2p5';
  p_MaxInputTokens_ff15fc8c := 196608;
  p_MaxOutputTokens_ff15fc8c := 131072;
  p_SupportedResponseFormats_ff15fc8c := 'Any, JSON';
  p_SupportsEffortLevel_ff15fc8c := 1;
  p_SupportsStreaming_ff15fc8c := 1;
  p_TypeID_ff15fc8c := '5B043EC3-1FF2-4730-B5D2-7CFDA50979B3';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_ff15fc8c, p_ModelID := p_ModelID_ff15fc8c, p_VendorID := p_VendorID_ff15fc8c, p_Priority := p_Priority_ff15fc8c, p_Status := p_Status_ff15fc8c, p_DriverClass := p_DriverClass_ff15fc8c, p_DriverImportPath := p_DriverImportPath_ff15fc8c, p_APIName := p_APIName_ff15fc8c, p_MaxInputTokens := p_MaxInputTokens_ff15fc8c, p_MaxOutputTokens := p_MaxOutputTokens_ff15fc8c, p_SupportedResponseFormats := p_SupportedResponseFormats_ff15fc8c, p_SupportsEffortLevel := p_SupportsEffortLevel_ff15fc8c, p_SupportsStreaming := p_SupportsStreaming_ff15fc8c, p_TypeID := p_TypeID_ff15fc8c);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_75da4262 UUID;
  p_ModelID_75da4262 UUID;
  p_VendorID_75da4262 UUID;
  p_Priority_75da4262 INTEGER;
  p_Status_75da4262 VARCHAR(20);
  p_DriverClass_75da4262 VARCHAR(100);
  p_DriverImportPath_75da4262 VARCHAR(255);
  p_APIName_75da4262 VARCHAR(100);
  p_MaxInputTokens_75da4262 INTEGER;
  p_MaxOutputTokens_75da4262 INTEGER;
  p_SupportedResponseFormats_75da4262 VARCHAR(100);
  p_SupportsEffortLevel_75da4262 BOOLEAN;
  p_SupportsStreaming_75da4262 BOOLEAN;
  p_TypeID_75da4262 UUID;
BEGIN
  p_ID_75da4262 := '7583ab09-ecc1-492d-b2ac-6d41295de57f';
  p_ModelID_75da4262 := '6D185CAB-A4C0-4B5F-AC34-6C922CE6F1A8';
  p_VendorID_75da4262 := '5C070719-85B1-4C3B-9C9E-3BE8B6B64D7E';
  p_Priority_75da4262 := 0;
  p_Status_75da4262 := 'Active';
  p_SupportedResponseFormats_75da4262 := 'Any';
  p_SupportsEffortLevel_75da4262 := 1;
  p_SupportsStreaming_75da4262 := 0;
  p_TypeID_75da4262 := '10DB468E-F2CE-475D-9F39-2DF2DE75D257';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_75da4262, p_ModelID := p_ModelID_75da4262, p_VendorID := p_VendorID_75da4262, p_Priority := p_Priority_75da4262, p_Status := p_Status_75da4262, p_DriverClass := p_DriverClass_75da4262, p_DriverImportPath := p_DriverImportPath_75da4262, p_APIName := p_APIName_75da4262, p_MaxInputTokens := p_MaxInputTokens_75da4262, p_MaxOutputTokens := p_MaxOutputTokens_75da4262, p_SupportedResponseFormats := p_SupportedResponseFormats_75da4262, p_SupportsEffortLevel := p_SupportsEffortLevel_75da4262, p_SupportsStreaming := p_SupportsStreaming_75da4262, p_TypeID := p_TypeID_75da4262);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_2833a9aa UUID;
  p_ModelID_2833a9aa UUID;
  p_VendorID_2833a9aa UUID;
  p_Priority_2833a9aa INTEGER;
  p_Status_2833a9aa VARCHAR(20);
  p_DriverClass_2833a9aa VARCHAR(100);
  p_DriverImportPath_2833a9aa VARCHAR(255);
  p_APIName_2833a9aa VARCHAR(100);
  p_MaxInputTokens_2833a9aa INTEGER;
  p_MaxOutputTokens_2833a9aa INTEGER;
  p_SupportedResponseFormats_2833a9aa VARCHAR(100);
  p_SupportsEffortLevel_2833a9aa BOOLEAN;
  p_SupportsStreaming_2833a9aa BOOLEAN;
  p_TypeID_2833a9aa UUID;
BEGIN
  p_ID_2833a9aa := 'f0d3da50-89b7-47aa-8b7b-58820fb3bbbd';
  p_ModelID_2833a9aa := '6D185CAB-A4C0-4B5F-AC34-6C922CE6F1A8';
  p_VendorID_2833a9aa := '5C070719-85B1-4C3B-9C9E-3BE8B6B64D7E';
  p_Priority_2833a9aa := 0;
  p_Status_2833a9aa := 'Active';
  p_DriverClass_2833a9aa := 'MiniMaxLLM';
  p_APIName_2833a9aa := 'MiniMax-M2.5-highspeed';
  p_MaxInputTokens_2833a9aa := 204800;
  p_MaxOutputTokens_2833a9aa := 131072;
  p_SupportedResponseFormats_2833a9aa := 'Any, JSON';
  p_SupportsEffortLevel_2833a9aa := 1;
  p_SupportsStreaming_2833a9aa := 1;
  p_TypeID_2833a9aa := '5B043EC3-1FF2-4730-B5D2-7CFDA50979B3';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_2833a9aa, p_ModelID := p_ModelID_2833a9aa, p_VendorID := p_VendorID_2833a9aa, p_Priority := p_Priority_2833a9aa, p_Status := p_Status_2833a9aa, p_DriverClass := p_DriverClass_2833a9aa, p_DriverImportPath := p_DriverImportPath_2833a9aa, p_APIName := p_APIName_2833a9aa, p_MaxInputTokens := p_MaxInputTokens_2833a9aa, p_MaxOutputTokens := p_MaxOutputTokens_2833a9aa, p_SupportedResponseFormats := p_SupportedResponseFormats_2833a9aa, p_SupportsEffortLevel := p_SupportsEffortLevel_2833a9aa, p_SupportsStreaming := p_SupportsStreaming_2833a9aa, p_TypeID := p_TypeID_2833a9aa);
END $$;

-- Save MJ: AI Model Costs (core SP call only)
DO $$
DECLARE
  p_ID_81346334 UUID;
  p_ModelID_81346334 UUID;
  p_VendorID_81346334 UUID;
  p_StartedAt_81346334 TIMESTAMPTZ;
  p_EndedAt_81346334 TIMESTAMPTZ;
  p_Status_81346334 VARCHAR(20);
  p_Currency_81346334 CHAR(3);
  p_PriceTypeID_81346334 UUID;
  p_InputPricePerUnit_81346334 NUMERIC(18,8);
  p_OutputPricePerUnit_81346334 NUMERIC(18,8);
  p_UnitTypeID_81346334 UUID;
  p_ProcessingType_81346334 VARCHAR(20);
  p_Comments_81346334 TEXT;
BEGIN
  p_ID_81346334 := '0441c917-dd13-4978-893a-ba0aa82eb1fb';
  p_ModelID_81346334 := '4E731CAA-9765-41DD-A6CB-F68945561753';
  p_VendorID_81346334 := '5C070719-85B1-4C3B-9C9E-3BE8B6B64D7E';
  p_StartedAt_81346334 := '2026-02-12T00:00:00.000Z';
  p_Status_81346334 := 'Active';
  p_Currency_81346334 := 'USD';
  p_PriceTypeID_81346334 := 'ECE2BCB7-C854-4BF7-A517-D72793A40652';
  p_InputPricePerUnit_81346334 := 0.3;
  p_OutputPricePerUnit_81346334 := 1.2;
  p_UnitTypeID_81346334 := '54208F7D-331C-40AB-84E8-163338EE9EA1';
  p_ProcessingType_81346334 := 'Realtime';
  p_Comments_81346334 := 'MiniMax-M2.5 pricing on MiniMax as of February 2026. 230B MoE model (10B active) with 204K context and 128K output. Cached input available at $0.03/1M tokens.';
  PERFORM __mj."spCreateAIModelCost"(p_ID := p_ID_81346334, p_ModelID := p_ModelID_81346334, p_VendorID := p_VendorID_81346334, p_StartedAt := p_StartedAt_81346334, p_EndedAt := p_EndedAt_81346334, p_Status := p_Status_81346334, p_Currency := p_Currency_81346334, p_PriceTypeID := p_PriceTypeID_81346334, p_InputPricePerUnit := p_InputPricePerUnit_81346334, p_OutputPricePerUnit := p_OutputPricePerUnit_81346334, p_UnitTypeID := p_UnitTypeID_81346334, p_ProcessingType := p_ProcessingType_81346334, p_Comments := p_Comments_81346334);
END $$;

-- Save MJ: AI Model Costs (core SP call only)
DO $$
DECLARE
  p_ID_014caa29 UUID;
  p_ModelID_014caa29 UUID;
  p_VendorID_014caa29 UUID;
  p_StartedAt_014caa29 TIMESTAMPTZ;
  p_EndedAt_014caa29 TIMESTAMPTZ;
  p_Status_014caa29 VARCHAR(20);
  p_Currency_014caa29 CHAR(3);
  p_PriceTypeID_014caa29 UUID;
  p_InputPricePerUnit_014caa29 NUMERIC(18,8);
  p_OutputPricePerUnit_014caa29 NUMERIC(18,8);
  p_UnitTypeID_014caa29 UUID;
  p_ProcessingType_014caa29 VARCHAR(20);
  p_Comments_014caa29 TEXT;
BEGIN
  p_ID_014caa29 := '4d535607-2673-459c-8caf-170bbfac7d08';
  p_ModelID_014caa29 := '4E731CAA-9765-41DD-A6CB-F68945561753';
  p_VendorID_014caa29 := '5AD8786B-2D00-45D5-AFBE-DAEC48963FFC';
  p_StartedAt_014caa29 := '2026-02-12T00:00:00.000Z';
  p_Status_014caa29 := 'Active';
  p_Currency_014caa29 := 'USD';
  p_PriceTypeID_014caa29 := 'ECE2BCB7-C854-4BF7-A517-D72793A40652';
  p_InputPricePerUnit_014caa29 := 0.295;
  p_OutputPricePerUnit_014caa29 := 1.2;
  p_UnitTypeID_014caa29 := '54208F7D-331C-40AB-84E8-163338EE9EA1';
  p_ProcessingType_014caa29 := 'Realtime';
  p_Comments_014caa29 := 'MiniMax-M2.5 pricing on OpenRouter as of February 2026. Routed inference - provider may vary.';
  PERFORM __mj."spCreateAIModelCost"(p_ID := p_ID_014caa29, p_ModelID := p_ModelID_014caa29, p_VendorID := p_VendorID_014caa29, p_StartedAt := p_StartedAt_014caa29, p_EndedAt := p_EndedAt_014caa29, p_Status := p_Status_014caa29, p_Currency := p_Currency_014caa29, p_PriceTypeID := p_PriceTypeID_014caa29, p_InputPricePerUnit := p_InputPricePerUnit_014caa29, p_OutputPricePerUnit := p_OutputPricePerUnit_014caa29, p_UnitTypeID := p_UnitTypeID_014caa29, p_ProcessingType := p_ProcessingType_014caa29, p_Comments := p_Comments_014caa29);
END $$;

-- Save MJ: AI Model Costs (core SP call only)
DO $$
DECLARE
  p_ID_3072777f UUID;
  p_ModelID_3072777f UUID;
  p_VendorID_3072777f UUID;
  p_StartedAt_3072777f TIMESTAMPTZ;
  p_EndedAt_3072777f TIMESTAMPTZ;
  p_Status_3072777f VARCHAR(20);
  p_Currency_3072777f CHAR(3);
  p_PriceTypeID_3072777f UUID;
  p_InputPricePerUnit_3072777f NUMERIC(18,8);
  p_OutputPricePerUnit_3072777f NUMERIC(18,8);
  p_UnitTypeID_3072777f UUID;
  p_ProcessingType_3072777f VARCHAR(20);
  p_Comments_3072777f TEXT;
BEGIN
  p_ID_3072777f := 'f740c7c6-8b3e-48ac-9897-0565909ab3ed';
  p_ModelID_3072777f := '4E731CAA-9765-41DD-A6CB-F68945561753';
  p_VendorID_3072777f := '66B67DA3-D048-43CD-AF25-BF683AB8DB74';
  p_StartedAt_3072777f := '2026-02-12T00:00:00.000Z';
  p_Status_3072777f := 'Active';
  p_Currency_3072777f := 'USD';
  p_PriceTypeID_3072777f := 'ECE2BCB7-C854-4BF7-A517-D72793A40652';
  p_InputPricePerUnit_3072777f := 0.3;
  p_OutputPricePerUnit_3072777f := 1.2;
  p_UnitTypeID_3072777f := '54208F7D-331C-40AB-84E8-163338EE9EA1';
  p_ProcessingType_3072777f := 'Realtime';
  p_Comments_3072777f := 'MiniMax-M2.5 pricing on Fireworks.ai as of February 2026. Serverless deployment with cached input at $0.03/1M tokens.';
  PERFORM __mj."spCreateAIModelCost"(p_ID := p_ID_3072777f, p_ModelID := p_ModelID_3072777f, p_VendorID := p_VendorID_3072777f, p_StartedAt := p_StartedAt_3072777f, p_EndedAt := p_EndedAt_3072777f, p_Status := p_Status_3072777f, p_Currency := p_Currency_3072777f, p_PriceTypeID := p_PriceTypeID_3072777f, p_InputPricePerUnit := p_InputPricePerUnit_3072777f, p_OutputPricePerUnit := p_OutputPricePerUnit_3072777f, p_UnitTypeID := p_UnitTypeID_3072777f, p_ProcessingType := p_ProcessingType_3072777f, p_Comments := p_Comments_3072777f);
END $$;

-- Save MJ: AI Model Costs (core SP call only)
DO $$
DECLARE
  p_ID_5fc958a2 UUID;
  p_ModelID_5fc958a2 UUID;
  p_VendorID_5fc958a2 UUID;
  p_StartedAt_5fc958a2 TIMESTAMPTZ;
  p_EndedAt_5fc958a2 TIMESTAMPTZ;
  p_Status_5fc958a2 VARCHAR(20);
  p_Currency_5fc958a2 CHAR(3);
  p_PriceTypeID_5fc958a2 UUID;
  p_InputPricePerUnit_5fc958a2 NUMERIC(18,8);
  p_OutputPricePerUnit_5fc958a2 NUMERIC(18,8);
  p_UnitTypeID_5fc958a2 UUID;
  p_ProcessingType_5fc958a2 VARCHAR(20);
  p_Comments_5fc958a2 TEXT;
BEGIN
  p_ID_5fc958a2 := '66d273f8-bdb7-44c5-9986-be4e36a68e53';
  p_ModelID_5fc958a2 := '6D185CAB-A4C0-4B5F-AC34-6C922CE6F1A8';
  p_VendorID_5fc958a2 := '5C070719-85B1-4C3B-9C9E-3BE8B6B64D7E';
  p_StartedAt_5fc958a2 := '2026-02-12T00:00:00.000Z';
  p_Status_5fc958a2 := 'Active';
  p_Currency_5fc958a2 := 'USD';
  p_PriceTypeID_5fc958a2 := 'ECE2BCB7-C854-4BF7-A517-D72793A40652';
  p_InputPricePerUnit_5fc958a2 := 0.6;
  p_OutputPricePerUnit_5fc958a2 := 2.4;
  p_UnitTypeID_5fc958a2 := '54208F7D-331C-40AB-84E8-163338EE9EA1';
  p_ProcessingType_5fc958a2 := 'Realtime';
  p_Comments_5fc958a2 := 'MiniMax-M2.5-highspeed pricing on MiniMax as of February 2026. 2x standard M2.5 pricing for ~100 tps output speed (vs ~60 tps standard). Same model capability, optimized for low-latency inference.';
  PERFORM __mj."spCreateAIModelCost"(p_ID := p_ID_5fc958a2, p_ModelID := p_ModelID_5fc958a2, p_VendorID := p_VendorID_5fc958a2, p_StartedAt := p_StartedAt_5fc958a2, p_EndedAt := p_EndedAt_5fc958a2, p_Status := p_Status_5fc958a2, p_Currency := p_Currency_5fc958a2, p_PriceTypeID := p_PriceTypeID_5fc958a2, p_InputPricePerUnit := p_InputPricePerUnit_5fc958a2, p_OutputPricePerUnit := p_OutputPricePerUnit_5fc958a2, p_UnitTypeID := p_UnitTypeID_5fc958a2, p_ProcessingType := p_ProcessingType_5fc958a2, p_Comments := p_Comments_5fc958a2);
END $$;

-- Save MJ: AI Models (core SP call only)
DO $$
DECLARE
  p_ID_f30610e9 UUID;
  p_Name_f30610e9 VARCHAR(50);
  p_Description_f30610e9 TEXT;
  p_AIModelTypeID_f30610e9 UUID;
  p_PowerRank_f30610e9 INTEGER;
  p_IsActive_f30610e9 BOOLEAN;
  p_SpeedRank_f30610e9 INTEGER;
  p_CostRank_f30610e9 INTEGER;
  p_ModelSelectionInsights_f30610e9 TEXT;
  p_InheritTypeModalities_f30610e9 BOOLEAN;
  p_PriorVersionID_f30610e9 UUID;
BEGIN
  p_ID_f30610e9 := '93b65e90-49f3-40f6-8c75-f18c7a80ac3b';
  p_Name_f30610e9 := 'Gemini 3.1 Pro';
  p_Description_f30610e9 := 'Google''s most advanced reasoning model, released February 19, 2026. Built on Gemini 3 Pro architecture with improved software engineering behavior and expanded thinking levels (including new MEDIUM setting). Features 1M token context window and 64K output capacity. Ranked #1 of 115 models on Artificial Analysis Intelligence Index. Achieves 80.6% SWE-bench Verified, 94.3% GPQA Diamond, 77.1% ARC-AGI-2, and 51.4% Humanity''s Last Exam (with tools). Supports Deep Think mode, function calling, code execution, and grounding. Knowledge cutoff January 2025.';
  p_AIModelTypeID_f30610e9 := 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E';
  p_PowerRank_f30610e9 := 26;
  p_IsActive_f30610e9 := 1;
  p_SpeedRank_f30610e9 := 9;
  p_CostRank_f30610e9 := 10;
  p_InheritTypeModalities_f30610e9 := 1;
  p_PriorVersionID_f30610e9 := 'B7267218-302B-4C09-9875-8DF06AAA1695';
  PERFORM __mj."spCreateAIModel"(p_ID := p_ID_f30610e9, p_Name := p_Name_f30610e9, p_Description := p_Description_f30610e9, p_AIModelTypeID := p_AIModelTypeID_f30610e9, p_PowerRank := p_PowerRank_f30610e9, p_IsActive := p_IsActive_f30610e9, p_SpeedRank := p_SpeedRank_f30610e9, p_CostRank := p_CostRank_f30610e9, p_ModelSelectionInsights := p_ModelSelectionInsights_f30610e9, p_InheritTypeModalities := p_InheritTypeModalities_f30610e9, p_PriorVersionID := p_PriorVersionID_f30610e9);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_1d3c9ef8 UUID;
  p_ModelID_1d3c9ef8 UUID;
  p_VendorID_1d3c9ef8 UUID;
  p_Priority_1d3c9ef8 INTEGER;
  p_Status_1d3c9ef8 VARCHAR(20);
  p_DriverClass_1d3c9ef8 VARCHAR(100);
  p_DriverImportPath_1d3c9ef8 VARCHAR(255);
  p_APIName_1d3c9ef8 VARCHAR(100);
  p_MaxInputTokens_1d3c9ef8 INTEGER;
  p_MaxOutputTokens_1d3c9ef8 INTEGER;
  p_SupportedResponseFormats_1d3c9ef8 VARCHAR(100);
  p_SupportsEffortLevel_1d3c9ef8 BOOLEAN;
  p_SupportsStreaming_1d3c9ef8 BOOLEAN;
  p_TypeID_1d3c9ef8 UUID;
BEGIN
  p_ID_1d3c9ef8 := '59535ed3-7553-4800-baca-3d5aadc1725b';
  p_ModelID_1d3c9ef8 := '93B65E90-49F3-40F6-8C75-F18C7A80AC3B';
  p_VendorID_1d3c9ef8 := 'E4A5CCEC-6A37-EF11-86D4-000D3A4E707E';
  p_Priority_1d3c9ef8 := 0;
  p_Status_1d3c9ef8 := 'Active';
  p_SupportedResponseFormats_1d3c9ef8 := 'Any';
  p_SupportsEffortLevel_1d3c9ef8 := 1;
  p_SupportsStreaming_1d3c9ef8 := 0;
  p_TypeID_1d3c9ef8 := '10DB468E-F2CE-475D-9F39-2DF2DE75D257';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_1d3c9ef8, p_ModelID := p_ModelID_1d3c9ef8, p_VendorID := p_VendorID_1d3c9ef8, p_Priority := p_Priority_1d3c9ef8, p_Status := p_Status_1d3c9ef8, p_DriverClass := p_DriverClass_1d3c9ef8, p_DriverImportPath := p_DriverImportPath_1d3c9ef8, p_APIName := p_APIName_1d3c9ef8, p_MaxInputTokens := p_MaxInputTokens_1d3c9ef8, p_MaxOutputTokens := p_MaxOutputTokens_1d3c9ef8, p_SupportedResponseFormats := p_SupportedResponseFormats_1d3c9ef8, p_SupportsEffortLevel := p_SupportsEffortLevel_1d3c9ef8, p_SupportsStreaming := p_SupportsStreaming_1d3c9ef8, p_TypeID := p_TypeID_1d3c9ef8);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_0c1af1e9 UUID;
  p_ModelID_0c1af1e9 UUID;
  p_VendorID_0c1af1e9 UUID;
  p_Priority_0c1af1e9 INTEGER;
  p_Status_0c1af1e9 VARCHAR(20);
  p_DriverClass_0c1af1e9 VARCHAR(100);
  p_DriverImportPath_0c1af1e9 VARCHAR(255);
  p_APIName_0c1af1e9 VARCHAR(100);
  p_MaxInputTokens_0c1af1e9 INTEGER;
  p_MaxOutputTokens_0c1af1e9 INTEGER;
  p_SupportedResponseFormats_0c1af1e9 VARCHAR(100);
  p_SupportsEffortLevel_0c1af1e9 BOOLEAN;
  p_SupportsStreaming_0c1af1e9 BOOLEAN;
  p_TypeID_0c1af1e9 UUID;
BEGIN
  p_ID_0c1af1e9 := 'd4db6984-85e3-4a61-8e71-62932da9149b';
  p_ModelID_0c1af1e9 := '93B65E90-49F3-40F6-8C75-F18C7A80AC3B';
  p_VendorID_0c1af1e9 := 'E4A5CCEC-6A37-EF11-86D4-000D3A4E707E';
  p_Priority_0c1af1e9 := 0;
  p_Status_0c1af1e9 := 'Active';
  p_DriverClass_0c1af1e9 := 'GeminiLLM';
  p_APIName_0c1af1e9 := 'gemini-3.1-pro-preview';
  p_MaxInputTokens_0c1af1e9 := 1048576;
  p_MaxOutputTokens_0c1af1e9 := 65536;
  p_SupportedResponseFormats_0c1af1e9 := 'Any, JSON';
  p_SupportsEffortLevel_0c1af1e9 := 1;
  p_SupportsStreaming_0c1af1e9 := 1;
  p_TypeID_0c1af1e9 := '5B043EC3-1FF2-4730-B5D2-7CFDA50979B3';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_0c1af1e9, p_ModelID := p_ModelID_0c1af1e9, p_VendorID := p_VendorID_0c1af1e9, p_Priority := p_Priority_0c1af1e9, p_Status := p_Status_0c1af1e9, p_DriverClass := p_DriverClass_0c1af1e9, p_DriverImportPath := p_DriverImportPath_0c1af1e9, p_APIName := p_APIName_0c1af1e9, p_MaxInputTokens := p_MaxInputTokens_0c1af1e9, p_MaxOutputTokens := p_MaxOutputTokens_0c1af1e9, p_SupportedResponseFormats := p_SupportedResponseFormats_0c1af1e9, p_SupportsEffortLevel := p_SupportsEffortLevel_0c1af1e9, p_SupportsStreaming := p_SupportsStreaming_0c1af1e9, p_TypeID := p_TypeID_0c1af1e9);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_48ba3f26 UUID;
  p_ModelID_48ba3f26 UUID;
  p_VendorID_48ba3f26 UUID;
  p_Priority_48ba3f26 INTEGER;
  p_Status_48ba3f26 VARCHAR(20);
  p_DriverClass_48ba3f26 VARCHAR(100);
  p_DriverImportPath_48ba3f26 VARCHAR(255);
  p_APIName_48ba3f26 VARCHAR(100);
  p_MaxInputTokens_48ba3f26 INTEGER;
  p_MaxOutputTokens_48ba3f26 INTEGER;
  p_SupportedResponseFormats_48ba3f26 VARCHAR(100);
  p_SupportsEffortLevel_48ba3f26 BOOLEAN;
  p_SupportsStreaming_48ba3f26 BOOLEAN;
  p_TypeID_48ba3f26 UUID;
BEGIN
  p_ID_48ba3f26 := 'b8eaef05-6504-421d-8b2c-79db5ef65699';
  p_ModelID_48ba3f26 := '93B65E90-49F3-40F6-8C75-F18C7A80AC3B';
  p_VendorID_48ba3f26 := 'E41E970D-7D38-45D9-BBFC-4013FF7C5860';
  p_Priority_48ba3f26 := 1;
  p_Status_48ba3f26 := 'Active';
  p_SupportedResponseFormats_48ba3f26 := 'Any';
  p_SupportsEffortLevel_48ba3f26 := 1;
  p_SupportsStreaming_48ba3f26 := 1;
  p_TypeID_48ba3f26 := '10DB468E-F2CE-475D-9F39-2DF2DE75D257';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_48ba3f26, p_ModelID := p_ModelID_48ba3f26, p_VendorID := p_VendorID_48ba3f26, p_Priority := p_Priority_48ba3f26, p_Status := p_Status_48ba3f26, p_DriverClass := p_DriverClass_48ba3f26, p_DriverImportPath := p_DriverImportPath_48ba3f26, p_APIName := p_APIName_48ba3f26, p_MaxInputTokens := p_MaxInputTokens_48ba3f26, p_MaxOutputTokens := p_MaxOutputTokens_48ba3f26, p_SupportedResponseFormats := p_SupportedResponseFormats_48ba3f26, p_SupportsEffortLevel := p_SupportsEffortLevel_48ba3f26, p_SupportsStreaming := p_SupportsStreaming_48ba3f26, p_TypeID := p_TypeID_48ba3f26);
END $$;

-- Save MJ: AI Model Vendors (core SP call only)
DO $$
DECLARE
  p_ID_3fa54575 UUID;
  p_ModelID_3fa54575 UUID;
  p_VendorID_3fa54575 UUID;
  p_Priority_3fa54575 INTEGER;
  p_Status_3fa54575 VARCHAR(20);
  p_DriverClass_3fa54575 VARCHAR(100);
  p_DriverImportPath_3fa54575 VARCHAR(255);
  p_APIName_3fa54575 VARCHAR(100);
  p_MaxInputTokens_3fa54575 INTEGER;
  p_MaxOutputTokens_3fa54575 INTEGER;
  p_SupportedResponseFormats_3fa54575 VARCHAR(100);
  p_SupportsEffortLevel_3fa54575 BOOLEAN;
  p_SupportsStreaming_3fa54575 BOOLEAN;
  p_TypeID_3fa54575 UUID;
BEGIN
  p_ID_3fa54575 := '5a6f5907-c3f9-4f59-94f8-f2dd6debb2c7';
  p_ModelID_3fa54575 := '93B65E90-49F3-40F6-8C75-F18C7A80AC3B';
  p_VendorID_3fa54575 := 'E41E970D-7D38-45D9-BBFC-4013FF7C5860';
  p_Priority_3fa54575 := 1;
  p_Status_3fa54575 := 'Active';
  p_DriverClass_3fa54575 := 'VertexLLM';
  p_APIName_3fa54575 := 'gemini-3.1-pro-preview';
  p_MaxInputTokens_3fa54575 := 1048576;
  p_MaxOutputTokens_3fa54575 := 65536;
  p_SupportedResponseFormats_3fa54575 := 'Any, JSON';
  p_SupportsEffortLevel_3fa54575 := 1;
  p_SupportsStreaming_3fa54575 := 1;
  p_TypeID_3fa54575 := '5B043EC3-1FF2-4730-B5D2-7CFDA50979B3';
  PERFORM __mj."spCreateAIModelVendor"(p_ID := p_ID_3fa54575, p_ModelID := p_ModelID_3fa54575, p_VendorID := p_VendorID_3fa54575, p_Priority := p_Priority_3fa54575, p_Status := p_Status_3fa54575, p_DriverClass := p_DriverClass_3fa54575, p_DriverImportPath := p_DriverImportPath_3fa54575, p_APIName := p_APIName_3fa54575, p_MaxInputTokens := p_MaxInputTokens_3fa54575, p_MaxOutputTokens := p_MaxOutputTokens_3fa54575, p_SupportedResponseFormats := p_SupportedResponseFormats_3fa54575, p_SupportsEffortLevel := p_SupportsEffortLevel_3fa54575, p_SupportsStreaming := p_SupportsStreaming_3fa54575, p_TypeID := p_TypeID_3fa54575);
END $$;

-- Save MJ: AI Model Costs (core SP call only)
DO $$
DECLARE
  p_ID_efbbe415 UUID;
  p_ModelID_efbbe415 UUID;
  p_VendorID_efbbe415 UUID;
  p_StartedAt_efbbe415 TIMESTAMPTZ;
  p_EndedAt_efbbe415 TIMESTAMPTZ;
  p_Status_efbbe415 VARCHAR(20);
  p_Currency_efbbe415 CHAR(3);
  p_PriceTypeID_efbbe415 UUID;
  p_InputPricePerUnit_efbbe415 NUMERIC(18,8);
  p_OutputPricePerUnit_efbbe415 NUMERIC(18,8);
  p_UnitTypeID_efbbe415 UUID;
  p_ProcessingType_efbbe415 VARCHAR(20);
  p_Comments_efbbe415 TEXT;
BEGIN
  p_ID_efbbe415 := 'be29f384-c9d6-4386-9ff6-aa0dbca84640';
  p_ModelID_efbbe415 := '93B65E90-49F3-40F6-8C75-F18C7A80AC3B';
  p_VendorID_efbbe415 := 'E4A5CCEC-6A37-EF11-86D4-000D3A4E707E';
  p_StartedAt_efbbe415 := '2026-02-19T00:00:00.000Z';
  p_Status_efbbe415 := 'Active';
  p_Currency_efbbe415 := 'USD';
  p_PriceTypeID_efbbe415 := 'ECE2BCB7-C854-4BF7-A517-D72793A40652';
  p_InputPricePerUnit_efbbe415 := 2;
  p_OutputPricePerUnit_efbbe415 := 12;
  p_UnitTypeID_efbbe415 := '54208F7D-331C-40AB-84E8-163338EE9EA1';
  p_ProcessingType_efbbe415 := 'Realtime';
  p_Comments_efbbe415 := 'Gemini 3.1 Pro Preview pricing on Google AI Studio as of February 2026. Prompts <=200K: $2.00/$12.00 per 1M tokens. Prompts >200K: $4.00/$18.00 per 1M tokens. Cached input: $0.20/1M (<=200K), $0.40/1M (>200K). Base tier pricing shown.';
  PERFORM __mj."spCreateAIModelCost"(p_ID := p_ID_efbbe415, p_ModelID := p_ModelID_efbbe415, p_VendorID := p_VendorID_efbbe415, p_StartedAt := p_StartedAt_efbbe415, p_EndedAt := p_EndedAt_efbbe415, p_Status := p_Status_efbbe415, p_Currency := p_Currency_efbbe415, p_PriceTypeID := p_PriceTypeID_efbbe415, p_InputPricePerUnit := p_InputPricePerUnit_efbbe415, p_OutputPricePerUnit := p_OutputPricePerUnit_efbbe415, p_UnitTypeID := p_UnitTypeID_efbbe415, p_ProcessingType := p_ProcessingType_efbbe415, p_Comments := p_Comments_efbbe415);
END $$;

-- Save MJ: AI Model Costs (core SP call only)
DO $$
DECLARE
  p_ID_80592c5c UUID;
  p_ModelID_80592c5c UUID;
  p_VendorID_80592c5c UUID;
  p_StartedAt_80592c5c TIMESTAMPTZ;
  p_EndedAt_80592c5c TIMESTAMPTZ;
  p_Status_80592c5c VARCHAR(20);
  p_Currency_80592c5c CHAR(3);
  p_PriceTypeID_80592c5c UUID;
  p_InputPricePerUnit_80592c5c NUMERIC(18,8);
  p_OutputPricePerUnit_80592c5c NUMERIC(18,8);
  p_UnitTypeID_80592c5c UUID;
  p_ProcessingType_80592c5c VARCHAR(20);
  p_Comments_80592c5c TEXT;
BEGIN
  p_ID_80592c5c := 'ed052bc7-82bc-44d9-8937-5b6d1b7ae85b';
  p_ModelID_80592c5c := '93B65E90-49F3-40F6-8C75-F18C7A80AC3B';
  p_VendorID_80592c5c := 'E41E970D-7D38-45D9-BBFC-4013FF7C5860';
  p_StartedAt_80592c5c := '2026-02-19T00:00:00.000Z';
  p_Status_80592c5c := 'Active';
  p_Currency_80592c5c := 'USD';
  p_PriceTypeID_80592c5c := 'ECE2BCB7-C854-4BF7-A517-D72793A40652';
  p_InputPricePerUnit_80592c5c := 2;
  p_OutputPricePerUnit_80592c5c := 12;
  p_UnitTypeID_80592c5c := '54208F7D-331C-40AB-84E8-163338EE9EA1';
  p_ProcessingType_80592c5c := 'Realtime';
  p_Comments_80592c5c := 'Gemini 3.1 Pro Preview pricing on Vertex AI as of February 2026. Standard tier: $2.00/$12.00 per 1M tokens (<=200K), $4.00/$18.00 (>200K). Priority tier: $3.60/$21.60 (<=200K). Flex/Batch: $1.00/$6.00 (<=200K). Cached input: $0.20/1M. Base standard tier pricing shown.';
  PERFORM __mj."spCreateAIModelCost"(p_ID := p_ID_80592c5c, p_ModelID := p_ModelID_80592c5c, p_VendorID := p_VendorID_80592c5c, p_StartedAt := p_StartedAt_80592c5c, p_EndedAt := p_EndedAt_80592c5c, p_Status := p_Status_80592c5c, p_Currency := p_Currency_80592c5c, p_PriceTypeID := p_PriceTypeID_80592c5c, p_InputPricePerUnit := p_InputPricePerUnit_80592c5c, p_OutputPricePerUnit := p_OutputPricePerUnit_80592c5c, p_UnitTypeID := p_UnitTypeID_80592c5c, p_ProcessingType := p_ProcessingType_80592c5c, p_Comments := p_Comments_80592c5c);
END $$;


-- ===================== FK & CHECK Constraints =====================


-- ===================== Grants =====================


-- ===================== Comments =====================
