import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { AutoQuotePostgreSQLIdentifiers, PostgreSQLStructuralKeywords, PostgreSQLQuotingKeywords } from '../postgresqlAutoQuote.js';

/**
 * Derives the keyword/column collision set from the shipped PostgreSQL baseline DDL at test
 * time, instead of enumerating it by hand.
 *
 * SCOPE, so this is not over-trusted: the derivation reads the newest `*__Baseline.pg.sql` ONLY.
 * The incremental `migrations-pg/v*` files that sit on top of it are not parsed, and per
 * `migrations/CLAUDE.md` those are regenerated by the build engineer at release time — so a
 * colliding column introduced in the current era will not trip this test until the next baseline
 * is cut. That is the gap between this derivation and a live-database one (which is what found
 * `AIAgentRun.Verbose`). A green run here means "no collision in the last baseline", not "no
 * collision".
 *
 * The original defect was structural: the keyword set and the set of MJ column names overlap,
 * and every name in the intersection shipped broken. A hand-written list of the eleven known
 * colliders would go stale the moment a new column joins the intersection — which is exactly
 * how the defect got here. This test recomputes the intersection from the real schema on every
 * run, so a newly added colliding column fails CI rather than shipping.
 *
 * Note on caching: turbo's `test` task inputs are `src/**`, so editing a baseline SQL file does
 * not by itself invalidate this test's cache. Baseline changes are release events that run full
 * CI anyway; a targeted `pnpm test` in this package always re-reads the file.
 */
describe('PostgreSQL auto-quoting vs. the shipped baseline schema', () => {
    const thisDir = dirname(fileURLToPath(import.meta.url));
    const repoRoot = join(thisDir, '..', '..', '..', '..');
    const migrationsRoot = join(repoRoot, 'migrations-pg');

    /** Newest `B*__Baseline.pg.sql` across all `migrations-pg/v*` folders. */
    function findNewestBaseline(): string {
        expect(existsSync(migrationsRoot), `migrations-pg not found at ${migrationsRoot}`).toBe(true);
        const candidates: string[] = [];
        for (const folder of readdirSync(migrationsRoot, { withFileTypes: true })) {
            if (!folder.isDirectory()) continue;
            const folderPath = join(migrationsRoot, folder.name);
            for (const file of readdirSync(folderPath)) {
                if (/__Baseline\.pg\.sql$/.test(file)) candidates.push(join(folderPath, file));
            }
        }
        expect(candidates.length, `no *__Baseline.pg.sql found under ${migrationsRoot}`).toBeGreaterThan(0);
        // Sort on BASENAME. Sorting full paths ranks the `v5`/`v6` folder segment ahead of the
        // timestamp, which happens to give the right answer today and stops doing so the moment a
        // v6 baseline carries an older timestamp than the v5 one — the version lives in the
        // filename, which is also how Flyway orders these.
        return candidates.sort((a, b) => basename(a).localeCompare(basename(b)))[candidates.length - 1];
    }

    interface ColumnDefinition {
        Table: string;
        Column: string;
    }

    /**
     * Extracts column definitions from `CREATE TABLE __mj."X" (...)` blocks.
     *
     * Block-scoped on purpose: a file-wide scan for indented quoted identifiers also matches
     * view column aliases and function-body fragments (~1,500 of them), which are not columns.
     */
    function extractColumnDefinitions(sql: string): ColumnDefinition[] {
        const columns: ColumnDefinition[] = [];
        let currentTable: string | null = null;

        for (const line of sql.split('\n')) {
            if (currentTable === null) {
                const open = /^CREATE TABLE __mj\."([^"]+)" \(/.exec(line);
                if (open) currentTable = open[1];
                continue;
            }
            if (/^\);/.test(line)) {
                currentTable = null;
                continue;
            }
            if (/^\s+CONSTRAINT\b/.test(line)) continue;
            const column = /^\s+"([^"]+)"\s/.exec(line);
            if (column) columns.push({ Table: currentTable, Column: column[1] });
        }
        return columns;
    }

    const baselinePath = findNewestBaseline();
    const baselineSQL = readFileSync(baselinePath, 'utf8');
    const definitions = extractColumnDefinitions(baselineSQL);
    const distinctTables = new Set(definitions.map((d) => d.Table));

    const distinctColumns = [...new Set(definitions.map((d) => d.Column))].sort();

    /**
     * Columns this module is responsible for: uppercase-first names, which is every MJ column
     * except the handful of camelCase ones below and the `__mj_` internals the tokenizer skips
     * by design. This is the population where a keyword collision can occur.
     */
    const pascalCaseColumns = distinctColumns.filter((c) => /^[A-Z]/.test(c));

    /**
     * Known camelCase columns, which the tokenizer leaves bare unless they are dot-qualified.
     *
     * This is a separate, pre-existing gap — not a keyword collision. A bare `SELECT spCreate`
     * folds to `spcreate` on PG, while the normal `e.spCreate` form quotes correctly via the
     * dot rule. Quoting camelCase unconditionally is not a safe fix here: it would also quote
     * camelCase result aliases (`SELECT count(*) AS myCount`), changing the casing of result
     * keys that existing consumers read. Recorded rather than fixed, and asserted exactly so
     * that a NEW camelCase column trips this test instead of joining the gap silently.
     */
    const KNOWN_CAMEL_CASE_COLUMNS = [
        'spCreate', 'spCreateGenerated', 'spDelete', 'spDeleteGenerated',
        'spMatch', 'spUpdate', 'spUpdateGenerated',
    ];

    describe('baseline extraction', () => {
        it('found a baseline file', () => {
            expect(baselinePath).toMatch(/__Baseline\.pg\.sql$/);
        });

        it('parsed a plausible number of tables', () => {
            expect(distinctTables.size).toBeGreaterThanOrEqual(300);
        });

        it('parsed a plausible number of column definitions', () => {
            expect(definitions.length).toBeGreaterThanOrEqual(4000);
        });

        it('found the known keyword-colliding columns, proving the extractor sees real columns', () => {
            const found = new Set(definitions.map((d) => d.Column));
            for (const col of ['Name', 'Type', 'Values', 'Log', 'Precision', 'Length', 'Rank']) {
                expect(found.has(col), `expected a "${col}" column in ${baselinePath}`).toBe(true);
            }
        });
    });

    describe('every real column survives auto-quoting', () => {
        it('quotes each PascalCase column name in a SELECT', () => {
            const unquoted = pascalCaseColumns.filter(
                (col) => !AutoQuotePostgreSQLIdentifiers(`SELECT ${col} FROM t`).includes(`"${col}"`)
            );
            const detail = unquoted
                .map((col) => {
                    const tables = definitions.filter((d) => d.Column === col).map((d) => d.Table);
                    return `  - ${col} (on ${tables.slice(0, 3).join(', ')}${tables.length > 3 ? ', …' : ''})`;
                })
                .join('\n');

            expect(
                unquoted,
                unquoted.length === 0
                    ? ''
                    : `These baseline columns are NOT quoted by the shared PostgreSQL tokenizer:\n${detail}\n\n` +
                          `Unquoted identifiers fold to lowercase on PostgreSQL, so any SQL referencing such a ` +
                          `column without quotes fails with 'column "..." does not exist'. This happens when a ` +
                          `column name is spelled exactly like an ALL-CAPS entry in PostgreSQLQuotingKeywords ` +
                          `(e.g. a column literally named TYPE), or is all-lowercase-ambiguous.\n\n` +
                          `Fix by renaming the column, or by changing the rule in postgresqlAutoQuote.ts. Do NOT ` +
                          `"fix" this by adding the word to PostgreSQLQuotingKeywords — that is what caused the ` +
                          `original defect (MJ #3604, #3590, #3691).`
            ).toEqual([]);
        });

        /**
         * THE REVERSE GUARD — the mirror of the column derivation above.
         *
         * The column direction is exhaustively derived; without this the keyword direction is a
         * hand-curated denylist tested only by whichever examples someone thought to write down.
         *
         * The oracle here is DELIBERATELY INDEPENDENT of `PostgreSQLQuotingKeywords`. An earlier
         * version of this test derived its candidates by filtering the baseline's ALL-CAPS words
         * through that same set — which is circular: deleting a word removed it from the
         * population as well as from the set, so the test passed either way and could never catch
         * the thing it exists to catch. (Verified by mutation: dropping eight keywords left it
         * green.) This list comes from PostgreSQL's own reserved-word table instead, so a word
         * missing from our set fails here.
         *
         * Note the asymmetry with the column test, which is the whole design of the rule: a word
         * only ever survives in its ALL-CAPS spelling. Its mixed-case form is still quoted as a
         * column, so adding a word to the set can never re-break a column.
         */
        it('leaves PostgreSQL reserved words bare in their ALL-CAPS form', () => {
            const PG_RESERVED = [
                'ALL', 'AND', 'ANY', 'AS', 'ASC', 'BOTH', 'CASE', 'CAST', 'CHECK', 'COLLATE',
                'COLUMN', 'CONSTRAINT', 'CREATE', 'CURRENT_USER', 'DEFAULT', 'DEFERRABLE', 'DESC',
                'DISTINCT', 'DO', 'ELSE', 'END', 'EXCEPT', 'EXTENSION', 'FALSE', 'FOR', 'FROM',
                'GROUP', 'HAVING', 'IN', 'INITIALLY', 'INTERSECT', 'INTO', 'LIMIT', 'NOT', 'NULL',
                'OFFSET', 'ON', 'ONLY', 'OR', 'ORDER', 'PRIMARY', 'REFERENCES', 'RETURNING',
                'SELECT', 'SESSION_USER', 'SOME', 'SYSTEM', 'TABLE', 'THEN', 'TO', 'TRUE', 'UNION',
                'UNIQUE', 'UPDATE', 'USING', 'VALID', 'WHEN', 'WHERE', 'WITH',
            ];

            const quoted = PG_RESERVED.filter((kw) =>
                AutoQuotePostgreSQLIdentifiers(`SELECT ${kw} FROM t`).includes(`"${kw}"`));

            expect(
                quoted,
                `These PostgreSQL reserved words are quoted by the tokenizer, which produces SQL ` +
                    `PostgreSQL rejects. Add them to PostgreSQLQuotingKeywords — doing so is safe ` +
                    `even when the word is also an MJ column name, because only the ALL-CAPS ` +
                    `spelling is affected and the mixed-case column form still quotes.`
            ).toEqual([]);
        });

        it('still quotes the mixed-case column form of those same words', () => {
            // The other half of the contract, and the reason adding keywords is cheap: `VALID` the
            // reserved word and `Valid` the column are textually distinct under a case-sensitive
            // rule, so the reverse guard above can never be satisfied at a column's expense.
            for (const col of ['Valid', 'System', 'Both', 'Extension', 'Order', 'Table']) {
                expect(AutoQuotePostgreSQLIdentifiers(`SELECT ${col} FROM t`)).toContain(`"${col}"`);
            }
        });

        it('quotes every column, PascalCase or camelCase, when it is dot-qualified', () => {
            // No `__mj_` exemption. The five mixed-case framework columns (__mj_CreatedAt,
            // __mj_UpdatedAt, __mj_Latitude, __mj_Longitude, __mj_UDT) are real columns and fold
            // to lowercase exactly like any other; filtering them out of this assertion is what
            // let the carve-out that broke them survive under a heading claiming every real
            // column is covered.
            const unquoted = distinctColumns
                .filter((col) => !AutoQuotePostgreSQLIdentifiers(`SELECT e.${col} FROM t e`).includes(`"${col}"`));
            expect(unquoted).toEqual([]);
        });

        it('leaves exactly the known camelCase columns bare when they are not dot-qualified', () => {
            const bare = distinctColumns
                .filter((col) => !AutoQuotePostgreSQLIdentifiers(`SELECT ${col} FROM t`).includes(`"${col}"`));

            expect(
                bare,
                `The set of columns left bare by the tokenizer changed. Expected only the known ` +
                    `camelCase columns (${KNOWN_CAMEL_CASE_COLUMNS.join(', ')}), which are safe in practice ` +
                    `because MJ SQL references columns as \`alias.Column\`. A NEW name here means either a new ` +
                    `camelCase column was added — reference it dot-qualified, or rename it PascalCase — or the ` +
                    `quoting rule regressed.`
            ).toEqual(KNOWN_CAMEL_CASE_COLUMNS);
        });
    });

    describe('structural compatibility tier stays disjoint from real columns', () => {
        it('matches no baseline column, in any casing', () => {
            const colliding = [...new Set(definitions.map((d) => d.Column))].filter((col) =>
                PostgreSQLStructuralKeywords.has(col.toUpperCase())
            );

            expect(
                colliding,
                colliding.length === 0
                    ? ''
                    : `These baseline columns collide with PostgreSQLStructuralKeywords: ${colliding.join(', ')}.\n\n` +
                          `That tier is matched case-INsensitively, so such a column would be emitted unquoted and ` +
                          `fold to lowercase on PostgreSQL — recreating the exact defect this module fixes. Either ` +
                          `rename the column, or remove the word from PostgreSQLStructuralKeywords and accept that ` +
                          `externally authored SQL fragments using its mixed-case form will need updating.`
            ).toEqual([]);
        });
    });
});
