-- RSU Migration: Integration: re:Members AMS — re_members_ams.Individuals, re_members_ams.Organizations, re_members_ams.Memberships, re_members_ams.Events, re_members_ams.EventRegistrations, re_members_ams.EventCancellations, re_members_ams.CourseAttendees, re_members_ams.Orders, re_members_ams.AbandonedCheckouts, re_members_ams.Committees, re_members_ams.CommitteeMembers, re_members_ams.CommitteePositions, re_members_ams.CommitteeNominees, re_members_ams.Awards, re_members_ams.AwardIndividualRecipients, re_members_ams.AwardOrganizationRecipients, re_members_ams.Certifications, re_members_ams.Licenses, re_members_ams.Exams, re_members_ams.Subscriptions, re_members_ams.UserTasks, re_members_ams.CustomerRequests, re_members_ams.Exhibits, re_members_ams.Countries, re_members_ams.States, re_members_ams.RelationshipTypes, re_members_ams.OrganizationServices, re_members_ams.CustomFieldDefinitions, re_members_ams.CustomFieldValues, re_members_ams.Addresses, re_members_ams.AwardNominations, re_members_ams.Categories, re_members_ams.Emails, re_members_ams.ExamScores, re_members_ams.Phones, re_members_ams.Tasks
-- Generated: 2026-07-13T20:11:41.019Z
-- Affected tables: re_members_ams.Individuals, re_members_ams.Organizations, re_members_ams.Memberships, re_members_ams.Events, re_members_ams.EventRegistrations, re_members_ams.EventCancellations, re_members_ams.CourseAttendees, re_members_ams.Orders, re_members_ams.AbandonedCheckouts, re_members_ams.Committees, re_members_ams.CommitteeMembers, re_members_ams.CommitteePositions, re_members_ams.CommitteeNominees, re_members_ams.Awards, re_members_ams.AwardIndividualRecipients, re_members_ams.AwardOrganizationRecipients, re_members_ams.Certifications, re_members_ams.Licenses, re_members_ams.Exams, re_members_ams.Subscriptions, re_members_ams.UserTasks, re_members_ams.CustomerRequests, re_members_ams.Exhibits, re_members_ams.Countries, re_members_ams.States, re_members_ams.RelationshipTypes, re_members_ams.OrganizationServices, re_members_ams.CustomFieldDefinitions, re_members_ams.CustomFieldValues, re_members_ams.Addresses, re_members_ams.AwardNominations, re_members_ams.Categories, re_members_ams.Emails, re_members_ams.ExamScores, re_members_ams.Phones, re_members_ams.Tasks
-- ============================================================
-- Auto-generated by MJ SchemaEngine
-- Consumer: re:Members AMS | Object: Individuals, Organizations, Memberships, Events, EventRegistrations, EventCancellations, CourseAttendees, Orders, AbandonedCheckouts, Committees, CommitteeMembers, CommitteePositions, CommitteeNominees, Awards, AwardIndividualRecipients, AwardOrganizationRecipients, Certifications, Licenses, Exams, Subscriptions, UserTasks, CustomerRequests, Exhibits, Countries, States, RelationshipTypes, OrganizationServices, CustomFieldDefinitions, CustomFieldValues, Addresses, AwardNominations, Categories, Emails, ExamScores, Phones, Tasks
-- Action: AlterTables
-- Generated: 2026-07-13T20:11:41.012Z
-- Generated By: MJ Integration Schema Builder (via SchemaEngine)
-- ============================================================
-- NOTE: __mj_CreatedAt, __mj_UpdatedAt, FK indexes, views, and SPs
--       are created by CodeGen — do NOT add them here.
-- NOTE: Soft foreign keys are defined in additionalSchemaInfo,
--       applied by CodeGen — no FK constraints needed in this migration.
-- ============================================================
-- DEPRECATED: Column [RootparentCompanyId] no longer exists in source. Consider removing after grace period.

ALTER TABLE [re_members_ams].[Memberships]
    ALTER COLUMN [inheritedMembershipBenefits] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Memberships]
    ALTER COLUMN [expireDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Memberships]
    ALTER COLUMN [effectiveDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Memberships]
    ALTER COLUMN [graceExpireDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Memberships]
    ALTER COLUMN [joinDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Memberships]
    ALTER COLUMN [terminateDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[EventRegistrations]
    ALTER COLUMN [attendedDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[EventRegistrations]
    ALTER COLUMN [showInDirectory] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[EventCancellations]
    ALTER COLUMN [eventCancellationDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[EventCancellations]
    ALTER COLUMN [showInDirectory] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[CourseAttendees]
    ALTER COLUMN [attendedDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[CourseAttendees]
    ALTER COLUMN [showInDirectory] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[CourseAttendees]
    ALTER COLUMN [registeredDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Orders]
    ALTER COLUMN [date] NVARCHAR(MAX) NULL;

-- DEPRECATED: Column [RootparentCommitteeId] no longer exists in source. Consider removing after grace period.

ALTER TABLE [re_members_ams].[CommitteeMembers]
    ALTER COLUMN [endDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[CommitteeMembers]
    ALTER COLUMN [startDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[CommitteePositions]
    ALTER COLUMN [isAdmin] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[CommitteeNominees]
    ALTER COLUMN [startDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[CommitteeNominees]
    ALTER COLUMN [endDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[AwardIndividualRecipients]
    ALTER COLUMN [showInDirectory] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[AwardIndividualRecipients]
    ALTER COLUMN [awardedDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[AwardOrganizationRecipients]
    ALTER COLUMN [showInDirectory] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[AwardOrganizationRecipients]
    ALTER COLUMN [awardedDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Certifications]
    ALTER COLUMN [expireDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Licenses]
    ALTER COLUMN [expirationDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Licenses]
    ALTER COLUMN [startDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Subscriptions]
    ALTER COLUMN [expireDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[UserTasks]
    ALTER COLUMN [startDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[UserTasks]
    ALTER COLUMN [dueDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[UserTasks]
    ALTER COLUMN [completedDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Addresses]
    ALTER COLUMN [isPreferredShipping] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Addresses]
    ALTER COLUMN [isBadAddress] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Addresses]
    ALTER COLUMN [primary] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Addresses]
    ALTER COLUMN [showInDirectory] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Addresses]
    ALTER COLUMN [isPreferredBilling] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[AwardNominations]
    ALTER COLUMN [awardedDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[AwardNominations]
    ALTER COLUMN [nominationDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Categories]
    ALTER COLUMN [isPrimary] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Emails]
    ALTER COLUMN [primary] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Emails]
    ALTER COLUMN [showInDirectory] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Phones]
    ALTER COLUMN [showInDirectory] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Phones]
    ALTER COLUMN [primary] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Tasks]
    ALTER COLUMN [dueDate] NVARCHAR(MAX) NULL;

ALTER TABLE [re_members_ams].[Tasks]
    ALTER COLUMN [startDate] NVARCHAR(MAX) NULL;

