export { ConversionPipeline } from './ConversionPipeline.js';
export { SQLFileSplitter } from './SQLFileSplitter.js';
export { DatabaseAuditRunner } from './DatabaseAuditor.js';
export { NoOpLLMFallback } from './LLMFallback.js';
export type {
  ConversionPipelineConfig,
  ConversionResult,
  StatementResult,
  AuditReport,
  DatabaseInventory,
  RowCountMismatch,
  ILLMFallback,
  IDatabaseVerifier,
  IDatabaseAuditor,
  SQLDialect,
} from './types.js';

// Rule-based conversion system
export {
  classifyBatch,
  subSplitCompoundBatch,
  getTSQLToPostgresRules,
  getRulesForDialects,
  RuleRegistry,
  PostgreSQLHeaderBuilder,
  getHeaderBuilder,
  registerHeaderBuilder,
  convertFile,
  printReport,
  postProcess,
  convertIdentifiers,
  convertDateFunctions,
  convertCharIndex,
  convertStuff,
  convertStringConcat,
  convertIIF,
  convertTopToLimit,
  convertCastTypes,
  convertConvertFunction,
  removeNPrefix,
  removeCollate,
  convertCommonFunctions,
  createConversionContext,
  createConversionStats,
  createOutputGroups,
  CreateTableRule,
  ViewRule,
  ProcedureToFunctionRule,
  FunctionRule,
  TriggerRule,
  InsertRule,
  AlterTableRule,
  CreateIndexRule,
  GrantRule,
  ExtendedPropertyRule,
  resolveType,
  resolveInlineType,
  parseTypeString,
} from './rules/index.js';
export type {
  IConversionRule,
  ConversionContext,
  ConversionStats,
  OutputGroups,
  StatementType,
  BatchConverterConfig,
  BatchConverterResult,
  DialectCombination,
  DialectHeaderBuilder,
  ParsedType,
} from './rules/index.js';
