-- Record Set Processing: make RecordProcess.WorkType pluggable (drop the closed CHECK).
--
-- The record-set-processor substrate resolves a Record Process's WorkType to a processor via the
-- pluggable RecordProcessorRegistry (packages/RecordSetProcessor/base/src/registry.ts, where the
-- build context types `WorkType: string`). That registry is the extension seam for work types
-- contributed OUTSIDE the substrate package — e.g. Predictive Studio's 'ML Model' scorer, which the
-- server registers at startup via registerMLScoringProcessor(). The substrate's own unit tests
-- register ad-hoc work types like 'Custom Type' / 'ml model', confirming the column is meant to be open.
--
-- The original CHECK constraint hard-coded WorkType to the four BUILT-IN values
-- ('Action','Agent','Infer','FieldRules'), which made it impossible to SAVE a Record Process for any
-- registered extension work type: the INSERT failed on CK_RecordProcess_WorkType before the registry
-- ever got a chance to resolve a processor. That directly contradicts the pluggable design and blocks
-- the entire "add a work type without forking the substrate" capability.
--
-- Fix: drop the closed CHECK. Work-type VALIDITY is enforced where it belongs — at EXECUTION time, by
-- RecordProcessExecutor.buildProcessor() -> RecordProcessorRegistry.Resolve(), which throws for an
-- unregistered work type. The built-in values remain documented through the entity field's value list
-- (which drives the generated TypeScript union + the UI dropdown) — i.e. they stay first-class
-- suggestions, just not a hard database constraint that a registered extension can never satisfy.
--
-- Idempotent (DROP ... IF EXISTS), so it is safe to re-run and safe if the constraint was already
-- removed out-of-band. No CodeGen is required: a CHECK constraint is not part of CodeGen output, and
-- the WorkType value list (the source of the generated union) is unchanged by this migration.

ALTER TABLE ${flyway:defaultSchema}.RecordProcess DROP CONSTRAINT IF EXISTS CK_RecordProcess_WorkType;
