-- Add KeyPrefix column to APIKey table
-- Stores the configured prefix + first 4 characters of the random body
-- (e.g., "mj_sk_a1b2") so administrators can visually identify keys
-- without exposing the full key. NULL for keys created before this migration
-- since the raw key was never stored.

ALTER TABLE ${flyway:defaultSchema}.APIKey
ADD KeyPrefix NVARCHAR(20) NULL;

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'A short preview of the key shown at creation time (e.g. mj_sk_a1b2). Stores the configured prefix plus the first 4 characters of the random body for visual identification. NULL for keys created before this column was added.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}',
    @level1type = N'TABLE',  @level1name = N'APIKey',
    @level2type = N'COLUMN', @level2name = N'KeyPrefix';

-- After running this migration, run CodeGen to generate:
--   - Updated entity class with KeyPrefix getter/setter
--   - Updated stored procedures (spCreateAPIKey, spUpdateAPIKey)
--   - Updated database view

/* SQL text to insert new entity field */

      IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[EntityField] WHERE ID = '08336b23-33f3-49c1-8739-58528d8156ca' OR (EntityID = 'B56DB373-2982-4E91-AACB-075CB8BECBBB' AND Name = 'KeyPrefix')) BEGIN
         INSERT INTO [${flyway:defaultSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '08336b23-33f3-49c1-8739-58528d8156ca',
            'B56DB373-2982-4E91-AACB-075CB8BECBBB', -- Entity: MJ: API Keys
            100026,
            'KeyPrefix',
            'Key Prefix',
            'A short preview of the key shown at creation time (e.g. mj_sk_a1b2). Stores the configured prefix plus the first 4 characters of the random body for visual identification. NULL for keys created before this column was added.',
            'nvarchar',
            40,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* Index for Foreign Keys for APIKey */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key UserID in table APIKey
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_APIKey_UserID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[APIKey]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_APIKey_UserID ON [${flyway:defaultSchema}].[APIKey] ([UserID]);

-- Index for foreign key CreatedByUserID in table APIKey
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_APIKey_CreatedByUserID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[APIKey]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_APIKey_CreatedByUserID ON [${flyway:defaultSchema}].[APIKey] ([CreatedByUserID]);

/* Base View SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: vwAPIKeys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: API Keys
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  APIKey
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwAPIKeys]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwAPIKeys];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwAPIKeys]
AS
SELECT
    a.*,
    MJUser_UserID.[Name] AS [User],
    MJUser_CreatedByUserID.[Name] AS [CreatedByUser]
FROM
    [${flyway:defaultSchema}].[APIKey] AS a
INNER JOIN
    [${flyway:defaultSchema}].[User] AS MJUser_UserID
  ON
    [a].[UserID] = MJUser_UserID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[User] AS MJUser_CreatedByUserID
  ON
    [a].[CreatedByUserID] = MJUser_CreatedByUserID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwAPIKeys] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: Permissions for vwAPIKeys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwAPIKeys] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: spCreateAPIKey
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR APIKey
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateAPIKey]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateAPIKey];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateAPIKey]
    @ID uniqueidentifier = NULL,
    @Hash nvarchar(64),
    @UserID uniqueidentifier,
    @Label nvarchar(255),
    @Description_Clear bit = 0,
    @Description nvarchar(1000) = NULL,
    @Status nvarchar(20) = NULL,
    @ExpiresAt_Clear bit = 0,
    @ExpiresAt datetimeoffset = NULL,
    @LastUsedAt_Clear bit = 0,
    @LastUsedAt datetimeoffset = NULL,
    @CreatedByUserID uniqueidentifier,
    @KeyPrefix_Clear bit = 0,
    @KeyPrefix nvarchar(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[APIKey]
            (
                [ID],
                [Hash],
                [UserID],
                [Label],
                [Description],
                [Status],
                [ExpiresAt],
                [LastUsedAt],
                [CreatedByUserID],
                [KeyPrefix]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @Hash,
                @UserID,
                @Label,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                ISNULL(@Status, 'Active'),
                CASE WHEN @ExpiresAt_Clear = 1 THEN NULL ELSE ISNULL(@ExpiresAt, NULL) END,
                CASE WHEN @LastUsedAt_Clear = 1 THEN NULL ELSE ISNULL(@LastUsedAt, NULL) END,
                @CreatedByUserID,
                CASE WHEN @KeyPrefix_Clear = 1 THEN NULL ELSE ISNULL(@KeyPrefix, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[APIKey]
            (
                [Hash],
                [UserID],
                [Label],
                [Description],
                [Status],
                [ExpiresAt],
                [LastUsedAt],
                [CreatedByUserID],
                [KeyPrefix]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @Hash,
                @UserID,
                @Label,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                ISNULL(@Status, 'Active'),
                CASE WHEN @ExpiresAt_Clear = 1 THEN NULL ELSE ISNULL(@ExpiresAt, NULL) END,
                CASE WHEN @LastUsedAt_Clear = 1 THEN NULL ELSE ISNULL(@LastUsedAt, NULL) END,
                @CreatedByUserID,
                CASE WHEN @KeyPrefix_Clear = 1 THEN NULL ELSE ISNULL(@KeyPrefix, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwAPIKeys] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAPIKey] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ: API Keys */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateAPIKey] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: spUpdateAPIKey
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR APIKey
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateAPIKey]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateAPIKey];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateAPIKey]
    @ID uniqueidentifier,
    @Hash nvarchar(64) = NULL,
    @UserID uniqueidentifier = NULL,
    @Label nvarchar(255) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(1000) = NULL,
    @Status nvarchar(20) = NULL,
    @ExpiresAt_Clear bit = 0,
    @ExpiresAt datetimeoffset = NULL,
    @LastUsedAt_Clear bit = 0,
    @LastUsedAt datetimeoffset = NULL,
    @CreatedByUserID uniqueidentifier = NULL,
    @KeyPrefix_Clear bit = 0,
    @KeyPrefix nvarchar(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[APIKey]
    SET
        [Hash] = ISNULL(@Hash, [Hash]),
        [UserID] = ISNULL(@UserID, [UserID]),
        [Label] = ISNULL(@Label, [Label]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [Status] = ISNULL(@Status, [Status]),
        [ExpiresAt] = CASE WHEN @ExpiresAt_Clear = 1 THEN NULL ELSE ISNULL(@ExpiresAt, [ExpiresAt]) END,
        [LastUsedAt] = CASE WHEN @LastUsedAt_Clear = 1 THEN NULL ELSE ISNULL(@LastUsedAt, [LastUsedAt]) END,
        [CreatedByUserID] = ISNULL(@CreatedByUserID, [CreatedByUserID]),
        [KeyPrefix] = CASE WHEN @KeyPrefix_Clear = 1 THEN NULL ELSE ISNULL(@KeyPrefix, [KeyPrefix]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwAPIKeys] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwAPIKeys]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAPIKey] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the APIKey table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateAPIKey]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateAPIKey];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateAPIKey
ON [${flyway:defaultSchema}].[APIKey]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[APIKey]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[APIKey] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ: API Keys */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateAPIKey] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ: API Keys */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: API Keys
-- Item: spDeleteAPIKey
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR APIKey
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteAPIKey]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteAPIKey];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteAPIKey]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[APIKey]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAPIKey] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ: API Keys */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteAPIKey] TO [cdp_Developer], [cdp_Integration];
