-- Grant CanDelete to the Developer role on entities where it currently lacks it.
--
-- Context: CodeGen's default EntityPermission for the Developer role is
-- {Read:1, Create:1, Update:1, Delete:0}. The original "core" wave of entities
-- had Delete turned on manually long ago, but every entity added since has been
-- stuck on the default. As of this migration, Developer has Create+Update on
-- 311 entities but Delete on only 77 of them.
--
-- This migration grants Delete on every entity Developer can already create and
-- update, EXCEPT the categories below, which should remain locked:
--   - Audit / log entities (immutable history)
--   - System cache / runtime state
--   - OAuth security-sensitive runtime tables
--   - Global system configuration
--   - End-user-owned content (notifications, settings, saved searches)
--
-- Developer Role ID: DEAFCCEC-6A37-EF11-86D4-000D3A4E707E

UPDATE ep
SET CanDelete = 1
FROM ${flyway:defaultSchema}.EntityPermission ep
INNER JOIN ${flyway:defaultSchema}.Entity e ON ep.EntityID = e.ID
WHERE ep.RoleID = 'DEAFCCEC-6A37-EF11-86D4-000D3A4E707E'
  AND ep.CanDelete = 0
  AND e.AllowDeleteAPI = 1
  AND e.SchemaName = '__mj'
  AND e.Name NOT IN (
      -- Audit / log entities
      'MJ: Action Execution Logs',
      'MJ: API Key Usage Logs',
      'MJ: Communication Logs',
      'MJ: MCP Tool Execution Logs',
      'MJ: Record Changes',
      'MJ: Record Change Replay Runs',
      'MJ: Search Execution Logs',
      'MJ: Tag Audit Logs',
      -- System cache / runtime state
      'MJ: AI Result Cache',
      -- OAuth security-sensitive runtime
      'MJ: O Auth Tokens',
      'MJ: O Auth Authorization States',
      'MJ: O Auth Client Registrations',
      'MJ: O Auth Auth Server Metadata Caches',
      -- Global system configuration
      'MJ: Environments',
      'MJ: Instance Configurations',
      -- End-user-owned content
      'MJ: User Notifications',
      'MJ: User Notification Preferences',
      'MJ: User Settings',
      'MJ: Knowledge Hub Saved Searches'
  );





































/* Base View SQL for MJ: Artifact Uses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Uses
-- Item: vwArtifactUses
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: Artifact Uses
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ArtifactUse
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwArtifactUses]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwArtifactUses];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwArtifactUses]
AS
SELECT
    a.*,
    MJArtifactVersion_ArtifactVersionID.[VersionNumber] AS [ArtifactVersion],
    MJUser_UserID.[Name] AS [User]
FROM
    [${flyway:defaultSchema}].[ArtifactUse] AS a
INNER JOIN
    [${flyway:defaultSchema}].[ArtifactVersion] AS MJArtifactVersion_ArtifactVersionID
  ON
    [a].[ArtifactVersionID] = MJArtifactVersion_ArtifactVersionID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[User] AS MJUser_UserID
  ON
    [a].[UserID] = MJUser_UserID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwArtifactUses] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* Base View Permissions SQL for MJ: Artifact Uses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Uses
-- Item: Permissions for vwArtifactUses
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwArtifactUses] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for MJ: Artifact Uses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Uses
-- Item: spCreateArtifactUse
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ArtifactUse
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateArtifactUse]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateArtifactUse];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateArtifactUse]
    @ID uniqueidentifier = NULL,
    @ArtifactVersionID uniqueidentifier,
    @UserID uniqueidentifier,
    @UsageType nvarchar(20),
    @UsageContext_Clear bit = 0,
    @UsageContext nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ArtifactUse]
            (
                [ID],
                [ArtifactVersionID],
                [UserID],
                [UsageType],
                [UsageContext]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ArtifactVersionID,
                @UserID,
                @UsageType,
                CASE WHEN @UsageContext_Clear = 1 THEN NULL ELSE ISNULL(@UsageContext, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ArtifactUse]
            (
                [ArtifactVersionID],
                [UserID],
                [UsageType],
                [UsageContext]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ArtifactVersionID,
                @UserID,
                @UsageType,
                CASE WHEN @UsageContext_Clear = 1 THEN NULL ELSE ISNULL(@UsageContext, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwArtifactUses] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateArtifactUse] TO [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for MJ: Artifact Uses */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateArtifactUse] TO [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for MJ: Artifact Uses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Uses
-- Item: spUpdateArtifactUse
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ArtifactUse
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateArtifactUse]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateArtifactUse];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateArtifactUse]
    @ID uniqueidentifier,
    @ArtifactVersionID uniqueidentifier = NULL,
    @UserID uniqueidentifier = NULL,
    @UsageType nvarchar(20) = NULL,
    @UsageContext_Clear bit = 0,
    @UsageContext nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ArtifactUse]
    SET
        [ArtifactVersionID] = ISNULL(@ArtifactVersionID, [ArtifactVersionID]),
        [UserID] = ISNULL(@UserID, [UserID]),
        [UsageType] = ISNULL(@UsageType, [UsageType]),
        [UsageContext] = CASE WHEN @UsageContext_Clear = 1 THEN NULL ELSE ISNULL(@UsageContext, [UsageContext]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwArtifactUses] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwArtifactUses]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateArtifactUse] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ArtifactUse table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateArtifactUse]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateArtifactUse];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateArtifactUse
ON [${flyway:defaultSchema}].[ArtifactUse]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ArtifactUse]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ArtifactUse] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for MJ: Artifact Uses */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateArtifactUse] TO [cdp_Developer], [cdp_Integration]



/* spDelete SQL for MJ: Artifact Uses */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Uses
-- Item: spDeleteArtifactUse
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ArtifactUse
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteArtifactUse]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteArtifactUse];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteArtifactUse]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ArtifactUse]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteArtifactUse] TO [cdp_Developer], [cdp_Integration]
    

/* spDelete Permissions for MJ: Artifact Uses */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteArtifactUse] TO [cdp_Developer], [cdp_Integration]



/* Base View SQL for MJ: Artifact Version Attributes */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Version Attributes
-- Item: vwArtifactVersionAttributes
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: Artifact Version Attributes
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ArtifactVersionAttribute
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwArtifactVersionAttributes]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwArtifactVersionAttributes];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwArtifactVersionAttributes]
AS
SELECT
    a.*,
    MJArtifactVersion_ArtifactVersionID.[VersionNumber] AS [ArtifactVersion]
FROM
    [${flyway:defaultSchema}].[ArtifactVersionAttribute] AS a
INNER JOIN
    [${flyway:defaultSchema}].[ArtifactVersion] AS MJArtifactVersion_ArtifactVersionID
  ON
    [a].[ArtifactVersionID] = MJArtifactVersion_ArtifactVersionID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwArtifactVersionAttributes] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* Base View Permissions SQL for MJ: Artifact Version Attributes */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Version Attributes
-- Item: Permissions for vwArtifactVersionAttributes
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwArtifactVersionAttributes] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for MJ: Artifact Version Attributes */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Version Attributes
-- Item: spCreateArtifactVersionAttribute
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ArtifactVersionAttribute
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateArtifactVersionAttribute]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateArtifactVersionAttribute];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateArtifactVersionAttribute]
    @ID uniqueidentifier = NULL,
    @ArtifactVersionID uniqueidentifier,
    @Name nvarchar(255),
    @Type nvarchar(500),
    @Value_Clear bit = 0,
    @Value nvarchar(MAX) = NULL,
    @StandardProperty_Clear bit = 0,
    @StandardProperty nvarchar(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ArtifactVersionAttribute]
            (
                [ID],
                [ArtifactVersionID],
                [Name],
                [Type],
                [Value],
                [StandardProperty]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ArtifactVersionID,
                @Name,
                @Type,
                CASE WHEN @Value_Clear = 1 THEN NULL ELSE ISNULL(@Value, NULL) END,
                CASE WHEN @StandardProperty_Clear = 1 THEN NULL ELSE ISNULL(@StandardProperty, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ArtifactVersionAttribute]
            (
                [ArtifactVersionID],
                [Name],
                [Type],
                [Value],
                [StandardProperty]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ArtifactVersionID,
                @Name,
                @Type,
                CASE WHEN @Value_Clear = 1 THEN NULL ELSE ISNULL(@Value, NULL) END,
                CASE WHEN @StandardProperty_Clear = 1 THEN NULL ELSE ISNULL(@StandardProperty, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwArtifactVersionAttributes] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateArtifactVersionAttribute] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for MJ: Artifact Version Attributes */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateArtifactVersionAttribute] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for MJ: Artifact Version Attributes */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Version Attributes
-- Item: spUpdateArtifactVersionAttribute
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ArtifactVersionAttribute
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateArtifactVersionAttribute]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateArtifactVersionAttribute];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateArtifactVersionAttribute]
    @ID uniqueidentifier,
    @ArtifactVersionID uniqueidentifier = NULL,
    @Name nvarchar(255) = NULL,
    @Type nvarchar(500) = NULL,
    @Value_Clear bit = 0,
    @Value nvarchar(MAX) = NULL,
    @StandardProperty_Clear bit = 0,
    @StandardProperty nvarchar(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ArtifactVersionAttribute]
    SET
        [ArtifactVersionID] = ISNULL(@ArtifactVersionID, [ArtifactVersionID]),
        [Name] = ISNULL(@Name, [Name]),
        [Type] = ISNULL(@Type, [Type]),
        [Value] = CASE WHEN @Value_Clear = 1 THEN NULL ELSE ISNULL(@Value, [Value]) END,
        [StandardProperty] = CASE WHEN @StandardProperty_Clear = 1 THEN NULL ELSE ISNULL(@StandardProperty, [StandardProperty]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwArtifactVersionAttributes] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwArtifactVersionAttributes]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateArtifactVersionAttribute] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ArtifactVersionAttribute table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateArtifactVersionAttribute]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateArtifactVersionAttribute];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateArtifactVersionAttribute
ON [${flyway:defaultSchema}].[ArtifactVersionAttribute]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ArtifactVersionAttribute]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ArtifactVersionAttribute] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for MJ: Artifact Version Attributes */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateArtifactVersionAttribute] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* spDelete SQL for MJ: Artifact Version Attributes */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Artifact Version Attributes
-- Item: spDeleteArtifactVersionAttribute
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ArtifactVersionAttribute
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteArtifactVersionAttribute]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteArtifactVersionAttribute];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteArtifactVersionAttribute]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ArtifactVersionAttribute]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteArtifactVersionAttribute] TO [cdp_Developer], [cdp_Integration]
    

/* spDelete Permissions for MJ: Artifact Version Attributes */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteArtifactVersionAttribute] TO [cdp_Developer], [cdp_Integration]



/* Base View SQL for MJ: Collection Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Collection Artifacts
-- Item: vwCollectionArtifacts
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: Collection Artifacts
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  CollectionArtifact
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwCollectionArtifacts]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwCollectionArtifacts];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwCollectionArtifacts]
AS
SELECT
    c.*,
    MJCollection_CollectionID.[Name] AS [Collection],
    MJArtifactVersion_ArtifactVersionID.[VersionNumber] AS [ArtifactVersion]
FROM
    [${flyway:defaultSchema}].[CollectionArtifact] AS c
INNER JOIN
    [${flyway:defaultSchema}].[Collection] AS MJCollection_CollectionID
  ON
    [c].[CollectionID] = MJCollection_CollectionID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[ArtifactVersion] AS MJArtifactVersion_ArtifactVersionID
  ON
    [c].[ArtifactVersionID] = MJArtifactVersion_ArtifactVersionID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwCollectionArtifacts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* Base View Permissions SQL for MJ: Collection Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Collection Artifacts
-- Item: Permissions for vwCollectionArtifacts
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwCollectionArtifacts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for MJ: Collection Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Collection Artifacts
-- Item: spCreateCollectionArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR CollectionArtifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateCollectionArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateCollectionArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateCollectionArtifact]
    @ID uniqueidentifier = NULL,
    @CollectionID uniqueidentifier,
    @Sequence int = NULL,
    @ArtifactVersionID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[CollectionArtifact]
            (
                [ID],
                [CollectionID],
                [Sequence],
                [ArtifactVersionID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @CollectionID,
                ISNULL(@Sequence, 0),
                @ArtifactVersionID
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[CollectionArtifact]
            (
                [CollectionID],
                [Sequence],
                [ArtifactVersionID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @CollectionID,
                ISNULL(@Sequence, 0),
                @ArtifactVersionID
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwCollectionArtifacts] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateCollectionArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for MJ: Collection Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateCollectionArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for MJ: Collection Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Collection Artifacts
-- Item: spUpdateCollectionArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR CollectionArtifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateCollectionArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateCollectionArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateCollectionArtifact]
    @ID uniqueidentifier,
    @CollectionID uniqueidentifier = NULL,
    @Sequence int = NULL,
    @ArtifactVersionID uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[CollectionArtifact]
    SET
        [CollectionID] = ISNULL(@CollectionID, [CollectionID]),
        [Sequence] = ISNULL(@Sequence, [Sequence]),
        [ArtifactVersionID] = ISNULL(@ArtifactVersionID, [ArtifactVersionID])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwCollectionArtifacts] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwCollectionArtifacts]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateCollectionArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the CollectionArtifact table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateCollectionArtifact]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateCollectionArtifact];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateCollectionArtifact
ON [${flyway:defaultSchema}].[CollectionArtifact]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[CollectionArtifact]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[CollectionArtifact] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for MJ: Collection Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateCollectionArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* spDelete SQL for MJ: Collection Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Collection Artifacts
-- Item: spDeleteCollectionArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR CollectionArtifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteCollectionArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteCollectionArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteCollectionArtifact]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[CollectionArtifact]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteCollectionArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
    

/* spDelete Permissions for MJ: Collection Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteCollectionArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* Base View SQL for MJ: Conversation Detail Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Artifacts
-- Item: vwConversationDetailArtifacts
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: Conversation Detail Artifacts
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ConversationDetailArtifact
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwConversationDetailArtifacts]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwConversationDetailArtifacts];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwConversationDetailArtifacts]
AS
SELECT
    c.*,
    MJConversationDetail_ConversationDetailID.[Message] AS [ConversationDetail],
    MJArtifactVersion_ArtifactVersionID.[VersionNumber] AS [ArtifactVersion]
FROM
    [${flyway:defaultSchema}].[ConversationDetailArtifact] AS c
INNER JOIN
    [${flyway:defaultSchema}].[ConversationDetail] AS MJConversationDetail_ConversationDetailID
  ON
    [c].[ConversationDetailID] = MJConversationDetail_ConversationDetailID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[ArtifactVersion] AS MJArtifactVersion_ArtifactVersionID
  ON
    [c].[ArtifactVersionID] = MJArtifactVersion_ArtifactVersionID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwConversationDetailArtifacts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* Base View Permissions SQL for MJ: Conversation Detail Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Artifacts
-- Item: Permissions for vwConversationDetailArtifacts
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwConversationDetailArtifacts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for MJ: Conversation Detail Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Artifacts
-- Item: spCreateConversationDetailArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ConversationDetailArtifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateConversationDetailArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateConversationDetailArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateConversationDetailArtifact]
    @ID uniqueidentifier = NULL,
    @ConversationDetailID uniqueidentifier,
    @ArtifactVersionID uniqueidentifier,
    @Direction nvarchar(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ConversationDetailArtifact]
            (
                [ID],
                [ConversationDetailID],
                [ArtifactVersionID],
                [Direction]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ConversationDetailID,
                @ArtifactVersionID,
                ISNULL(@Direction, 'Output')
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ConversationDetailArtifact]
            (
                [ConversationDetailID],
                [ArtifactVersionID],
                [Direction]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ConversationDetailID,
                @ArtifactVersionID,
                ISNULL(@Direction, 'Output')
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwConversationDetailArtifacts] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateConversationDetailArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for MJ: Conversation Detail Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateConversationDetailArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for MJ: Conversation Detail Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Artifacts
-- Item: spUpdateConversationDetailArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ConversationDetailArtifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateConversationDetailArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateConversationDetailArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateConversationDetailArtifact]
    @ID uniqueidentifier,
    @ConversationDetailID uniqueidentifier = NULL,
    @ArtifactVersionID uniqueidentifier = NULL,
    @Direction nvarchar(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ConversationDetailArtifact]
    SET
        [ConversationDetailID] = ISNULL(@ConversationDetailID, [ConversationDetailID]),
        [ArtifactVersionID] = ISNULL(@ArtifactVersionID, [ArtifactVersionID]),
        [Direction] = ISNULL(@Direction, [Direction])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwConversationDetailArtifacts] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwConversationDetailArtifacts]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateConversationDetailArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ConversationDetailArtifact table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateConversationDetailArtifact]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateConversationDetailArtifact];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateConversationDetailArtifact
ON [${flyway:defaultSchema}].[ConversationDetailArtifact]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ConversationDetailArtifact]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ConversationDetailArtifact] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for MJ: Conversation Detail Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateConversationDetailArtifact] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* spDelete SQL for MJ: Conversation Detail Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Artifacts
-- Item: spDeleteConversationDetailArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ConversationDetailArtifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteConversationDetailArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteConversationDetailArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteConversationDetailArtifact]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ConversationDetailArtifact]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteConversationDetailArtifact] TO [cdp_Developer], [cdp_Integration]
    

/* spDelete Permissions for MJ: Conversation Detail Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteConversationDetailArtifact] TO [cdp_Developer], [cdp_Integration]



/* Base View SQL for MJ: Conversation Detail Attachments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Attachments
-- Item: vwConversationDetailAttachments
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: Conversation Detail Attachments
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ConversationDetailAttachment
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwConversationDetailAttachments]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwConversationDetailAttachments];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwConversationDetailAttachments]
AS
SELECT
    c.*,
    MJConversationDetail_ConversationDetailID.[Message] AS [ConversationDetail],
    MJAIModality_ModalityID.[Name] AS [Modality],
    MJFile_FileID.[Name] AS [File],
    MJArtifactVersion_ArtifactVersionID.[VersionNumber] AS [ArtifactVersion]
FROM
    [${flyway:defaultSchema}].[ConversationDetailAttachment] AS c
INNER JOIN
    [${flyway:defaultSchema}].[ConversationDetail] AS MJConversationDetail_ConversationDetailID
  ON
    [c].[ConversationDetailID] = MJConversationDetail_ConversationDetailID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[AIModality] AS MJAIModality_ModalityID
  ON
    [c].[ModalityID] = MJAIModality_ModalityID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[File] AS MJFile_FileID
  ON
    [c].[FileID] = MJFile_FileID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ArtifactVersion] AS MJArtifactVersion_ArtifactVersionID
  ON
    [c].[ArtifactVersionID] = MJArtifactVersion_ArtifactVersionID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwConversationDetailAttachments] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* Base View Permissions SQL for MJ: Conversation Detail Attachments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Attachments
-- Item: Permissions for vwConversationDetailAttachments
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwConversationDetailAttachments] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for MJ: Conversation Detail Attachments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Attachments
-- Item: spCreateConversationDetailAttachment
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ConversationDetailAttachment
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateConversationDetailAttachment]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateConversationDetailAttachment];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateConversationDetailAttachment]
    @ID uniqueidentifier = NULL,
    @ConversationDetailID uniqueidentifier,
    @ModalityID uniqueidentifier,
    @MimeType nvarchar(100),
    @FileName_Clear bit = 0,
    @FileName nvarchar(4000) = NULL,
    @FileSizeBytes int,
    @Width_Clear bit = 0,
    @Width int = NULL,
    @Height_Clear bit = 0,
    @Height int = NULL,
    @DurationSeconds_Clear bit = 0,
    @DurationSeconds int = NULL,
    @InlineData_Clear bit = 0,
    @InlineData nvarchar(MAX) = NULL,
    @FileID_Clear bit = 0,
    @FileID uniqueidentifier = NULL,
    @DisplayOrder int = NULL,
    @ThumbnailBase64_Clear bit = 0,
    @ThumbnailBase64 nvarchar(MAX) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @ArtifactVersionID_Clear bit = 0,
    @ArtifactVersionID uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ConversationDetailAttachment]
            (
                [ID],
                [ConversationDetailID],
                [ModalityID],
                [MimeType],
                [FileName],
                [FileSizeBytes],
                [Width],
                [Height],
                [DurationSeconds],
                [InlineData],
                [FileID],
                [DisplayOrder],
                [ThumbnailBase64],
                [Description],
                [ArtifactVersionID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ConversationDetailID,
                @ModalityID,
                @MimeType,
                CASE WHEN @FileName_Clear = 1 THEN NULL ELSE ISNULL(@FileName, NULL) END,
                @FileSizeBytes,
                CASE WHEN @Width_Clear = 1 THEN NULL ELSE ISNULL(@Width, NULL) END,
                CASE WHEN @Height_Clear = 1 THEN NULL ELSE ISNULL(@Height, NULL) END,
                CASE WHEN @DurationSeconds_Clear = 1 THEN NULL ELSE ISNULL(@DurationSeconds, NULL) END,
                CASE WHEN @InlineData_Clear = 1 THEN NULL ELSE ISNULL(@InlineData, NULL) END,
                CASE WHEN @FileID_Clear = 1 THEN NULL ELSE ISNULL(@FileID, NULL) END,
                ISNULL(@DisplayOrder, 0),
                CASE WHEN @ThumbnailBase64_Clear = 1 THEN NULL ELSE ISNULL(@ThumbnailBase64, NULL) END,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                CASE WHEN @ArtifactVersionID_Clear = 1 THEN NULL ELSE ISNULL(@ArtifactVersionID, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ConversationDetailAttachment]
            (
                [ConversationDetailID],
                [ModalityID],
                [MimeType],
                [FileName],
                [FileSizeBytes],
                [Width],
                [Height],
                [DurationSeconds],
                [InlineData],
                [FileID],
                [DisplayOrder],
                [ThumbnailBase64],
                [Description],
                [ArtifactVersionID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ConversationDetailID,
                @ModalityID,
                @MimeType,
                CASE WHEN @FileName_Clear = 1 THEN NULL ELSE ISNULL(@FileName, NULL) END,
                @FileSizeBytes,
                CASE WHEN @Width_Clear = 1 THEN NULL ELSE ISNULL(@Width, NULL) END,
                CASE WHEN @Height_Clear = 1 THEN NULL ELSE ISNULL(@Height, NULL) END,
                CASE WHEN @DurationSeconds_Clear = 1 THEN NULL ELSE ISNULL(@DurationSeconds, NULL) END,
                CASE WHEN @InlineData_Clear = 1 THEN NULL ELSE ISNULL(@InlineData, NULL) END,
                CASE WHEN @FileID_Clear = 1 THEN NULL ELSE ISNULL(@FileID, NULL) END,
                ISNULL(@DisplayOrder, 0),
                CASE WHEN @ThumbnailBase64_Clear = 1 THEN NULL ELSE ISNULL(@ThumbnailBase64, NULL) END,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                CASE WHEN @ArtifactVersionID_Clear = 1 THEN NULL ELSE ISNULL(@ArtifactVersionID, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwConversationDetailAttachments] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateConversationDetailAttachment] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for MJ: Conversation Detail Attachments */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateConversationDetailAttachment] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for MJ: Conversation Detail Attachments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Attachments
-- Item: spUpdateConversationDetailAttachment
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ConversationDetailAttachment
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateConversationDetailAttachment]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateConversationDetailAttachment];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateConversationDetailAttachment]
    @ID uniqueidentifier,
    @ConversationDetailID uniqueidentifier = NULL,
    @ModalityID uniqueidentifier = NULL,
    @MimeType nvarchar(100) = NULL,
    @FileName_Clear bit = 0,
    @FileName nvarchar(4000) = NULL,
    @FileSizeBytes int = NULL,
    @Width_Clear bit = 0,
    @Width int = NULL,
    @Height_Clear bit = 0,
    @Height int = NULL,
    @DurationSeconds_Clear bit = 0,
    @DurationSeconds int = NULL,
    @InlineData_Clear bit = 0,
    @InlineData nvarchar(MAX) = NULL,
    @FileID_Clear bit = 0,
    @FileID uniqueidentifier = NULL,
    @DisplayOrder int = NULL,
    @ThumbnailBase64_Clear bit = 0,
    @ThumbnailBase64 nvarchar(MAX) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @ArtifactVersionID_Clear bit = 0,
    @ArtifactVersionID uniqueidentifier = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ConversationDetailAttachment]
    SET
        [ConversationDetailID] = ISNULL(@ConversationDetailID, [ConversationDetailID]),
        [ModalityID] = ISNULL(@ModalityID, [ModalityID]),
        [MimeType] = ISNULL(@MimeType, [MimeType]),
        [FileName] = CASE WHEN @FileName_Clear = 1 THEN NULL ELSE ISNULL(@FileName, [FileName]) END,
        [FileSizeBytes] = ISNULL(@FileSizeBytes, [FileSizeBytes]),
        [Width] = CASE WHEN @Width_Clear = 1 THEN NULL ELSE ISNULL(@Width, [Width]) END,
        [Height] = CASE WHEN @Height_Clear = 1 THEN NULL ELSE ISNULL(@Height, [Height]) END,
        [DurationSeconds] = CASE WHEN @DurationSeconds_Clear = 1 THEN NULL ELSE ISNULL(@DurationSeconds, [DurationSeconds]) END,
        [InlineData] = CASE WHEN @InlineData_Clear = 1 THEN NULL ELSE ISNULL(@InlineData, [InlineData]) END,
        [FileID] = CASE WHEN @FileID_Clear = 1 THEN NULL ELSE ISNULL(@FileID, [FileID]) END,
        [DisplayOrder] = ISNULL(@DisplayOrder, [DisplayOrder]),
        [ThumbnailBase64] = CASE WHEN @ThumbnailBase64_Clear = 1 THEN NULL ELSE ISNULL(@ThumbnailBase64, [ThumbnailBase64]) END,
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [ArtifactVersionID] = CASE WHEN @ArtifactVersionID_Clear = 1 THEN NULL ELSE ISNULL(@ArtifactVersionID, [ArtifactVersionID]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwConversationDetailAttachments] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwConversationDetailAttachments]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateConversationDetailAttachment] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ConversationDetailAttachment table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateConversationDetailAttachment]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateConversationDetailAttachment];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateConversationDetailAttachment
ON [${flyway:defaultSchema}].[ConversationDetailAttachment]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ConversationDetailAttachment]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ConversationDetailAttachment] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for MJ: Conversation Detail Attachments */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateConversationDetailAttachment] TO [cdp_UI], [cdp_Developer], [cdp_Integration]



/* spDelete SQL for MJ: Conversation Detail Attachments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Conversation Detail Attachments
-- Item: spDeleteConversationDetailAttachment
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ConversationDetailAttachment
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteConversationDetailAttachment]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteConversationDetailAttachment];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteConversationDetailAttachment]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ConversationDetailAttachment]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteConversationDetailAttachment] TO [cdp_Developer], [cdp_Integration]
    

/* spDelete Permissions for MJ: Conversation Detail Attachments */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteConversationDetailAttachment] TO [cdp_Developer], [cdp_Integration]



