/* SQL text to update entity field related entity name field map for entity field ID 0C1AE9BD-D895-4ECF-B65B-43EA80D9949C */
EXEC [${flyway:defaultSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='0C1AE9BD-D895-4ECF-B65B-43EA80D9949C', @RelatedEntityNameFieldMap='ArchiveRun'

/* Base View SQL for MJ: Archive Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Archive Run Details
-- Item: vwArchiveRunDetails
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ: Archive Run Details
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ArchiveRunDetail
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwArchiveRunDetails]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwArchiveRunDetails];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwArchiveRunDetails]
AS
SELECT
    a.*,
    MJArchiveRun_ArchiveRunID.[StartedAt] AS [ArchiveRun],
    MJEntity_EntityID.[Name] AS [Entity]
FROM
    [${flyway:defaultSchema}].[ArchiveRunDetail] AS a
INNER JOIN
    [${flyway:defaultSchema}].[ArchiveRun] AS MJArchiveRun_ArchiveRunID
  ON
    [a].[ArchiveRunID] = MJArchiveRun_ArchiveRunID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[Entity] AS MJEntity_EntityID
  ON
    [a].[EntityID] = MJEntity_EntityID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwArchiveRunDetails] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* Base View Permissions SQL for MJ: Archive Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Archive Run Details
-- Item: Permissions for vwArchiveRunDetails
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwArchiveRunDetails] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for MJ: Archive Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Archive Run Details
-- Item: spCreateArchiveRunDetail
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ArchiveRunDetail
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateArchiveRunDetail]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateArchiveRunDetail];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateArchiveRunDetail]
    @ID uniqueidentifier = NULL,
    @ArchiveRunID uniqueidentifier,
    @EntityID uniqueidentifier,
    @RecordID nvarchar(750),
    @Status nvarchar(50),
    @StoragePath nvarchar(1000),
    @BytesArchived bigint = NULL,
    @ErrorMessage nvarchar(MAX),
    @ArchivedAt datetimeoffset,
    @VersionStamp datetimeoffset,
    @IsRecordChangeArchive bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ArchiveRunDetail]
            (
                [ID],
                [ArchiveRunID],
                [EntityID],
                [RecordID],
                [Status],
                [StoragePath],
                [BytesArchived],
                [ErrorMessage],
                [ArchivedAt],
                [VersionStamp],
                [IsRecordChangeArchive]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ArchiveRunID,
                @EntityID,
                @RecordID,
                @Status,
                @StoragePath,
                ISNULL(@BytesArchived, 0),
                @ErrorMessage,
                @ArchivedAt,
                @VersionStamp,
                ISNULL(@IsRecordChangeArchive, 0)
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ArchiveRunDetail]
            (
                [ArchiveRunID],
                [EntityID],
                [RecordID],
                [Status],
                [StoragePath],
                [BytesArchived],
                [ErrorMessage],
                [ArchivedAt],
                [VersionStamp],
                [IsRecordChangeArchive]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ArchiveRunID,
                @EntityID,
                @RecordID,
                @Status,
                @StoragePath,
                ISNULL(@BytesArchived, 0),
                @ErrorMessage,
                @ArchivedAt,
                @VersionStamp,
                ISNULL(@IsRecordChangeArchive, 0)
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwArchiveRunDetails] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateArchiveRunDetail] TO [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for MJ: Archive Run Details */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateArchiveRunDetail] TO [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for MJ: Archive Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Archive Run Details
-- Item: spUpdateArchiveRunDetail
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ArchiveRunDetail
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateArchiveRunDetail]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateArchiveRunDetail];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateArchiveRunDetail]
    @ID uniqueidentifier,
    @ArchiveRunID uniqueidentifier,
    @EntityID uniqueidentifier,
    @RecordID nvarchar(750),
    @Status nvarchar(50),
    @StoragePath nvarchar(1000),
    @BytesArchived bigint,
    @ErrorMessage nvarchar(MAX),
    @ArchivedAt datetimeoffset,
    @VersionStamp datetimeoffset,
    @IsRecordChangeArchive bit
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ArchiveRunDetail]
    SET
        [ArchiveRunID] = @ArchiveRunID,
        [EntityID] = @EntityID,
        [RecordID] = @RecordID,
        [Status] = @Status,
        [StoragePath] = @StoragePath,
        [BytesArchived] = @BytesArchived,
        [ErrorMessage] = @ErrorMessage,
        [ArchivedAt] = @ArchivedAt,
        [VersionStamp] = @VersionStamp,
        [IsRecordChangeArchive] = @IsRecordChangeArchive
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwArchiveRunDetails] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwArchiveRunDetails]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateArchiveRunDetail] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ArchiveRunDetail table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateArchiveRunDetail]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateArchiveRunDetail];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateArchiveRunDetail
ON [${flyway:defaultSchema}].[ArchiveRunDetail]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ArchiveRunDetail]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ArchiveRunDetail] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for MJ: Archive Run Details */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateArchiveRunDetail] TO [cdp_Developer], [cdp_Integration]



/* spDelete SQL for MJ: Archive Run Details */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ: Archive Run Details
-- Item: spDeleteArchiveRunDetail
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ArchiveRunDetail
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteArchiveRunDetail]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteArchiveRunDetail];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteArchiveRunDetail]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ArchiveRunDetail]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteArchiveRunDetail] TO [cdp_Integration]
    

/* spDelete Permissions for MJ: Archive Run Details */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteArchiveRunDetail] TO [cdp_Integration]



/* SQL text to insert new entity field */

      IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[EntityField] WHERE ID = 'ec2a696b-acb1-4b02-bc57-10c5dac8dbc7' OR (EntityID = 'C30F80EC-E7CE-468E-B6C6-B8888F0F45C6' AND Name = 'ArchiveRun')) BEGIN
         INSERT INTO [${flyway:defaultSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'ec2a696b-acb1-4b02-bc57-10c5dac8dbc7',
            'C30F80EC-E7CE-468E-B6C6-B8888F0F45C6', -- Entity: MJ: Archive Run Details
            100028,
            'ArchiveRun',
            'Archive Run',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            NULL,
            0,
            0,
            1,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END

/* Set field properties for entity */

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET UserSearchPredicateAPI = 'Contains'
               WHERE ID = '2CD99CC3-14AC-466E-B9D1-CE5E050B58AA'
               AND AutoUpdateUserSearchPredicate = 1
            

/* Set categories for 15 fields */

-- UPDATE Entity Field Category Info MJ: Archive Run Details.ID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '79525349-F1A7-45CD-BDDB-15D45E1EA4D5' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.__mj_CreatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B90E24FD-D3A9-4D00-A94B-17E2B1FB2FE3' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.__mj_UpdatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'EB7FEB68-C246-4B48-9518-B8BCF5793611' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.ArchiveRunID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '0C1AE9BD-D895-4ECF-B65B-43EA80D9949C' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.EntityID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Entity ID',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '6170C43C-462B-42B1-972B-1D8B7789682B' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.RecordID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '2CD99CC3-14AC-466E-B9D1-CE5E050B58AA' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.Entity 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Entity Name',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '0A500C87-F127-4776-8EEF-7ECA8E7A414C' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.ArchiveRun 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   Category = 'Archive Context',
   GeneratedFormSection = 'Category',
   DisplayName = 'Archive Run Timestamp',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'EC2A696B-ACB1-4B02-BC57-10C5DAC8DBC7' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.Status 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B67B2260-8850-40F9-8902-5D91D0159FE7' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.StoragePath 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '2A48A363-DC62-4DD2-833B-EB7CFBABB283' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.BytesArchived 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '5B53CD8F-01E4-41C3-A6E3-313A83103ECF' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.ErrorMessage 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '0823FBF5-191B-4799-A64E-778C6AF033A1' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.ArchivedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'BFCCF263-AF8A-405C-B57D-473AAC8A9E90' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.VersionStamp 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '07F192B4-3A6D-4FEB-869B-6ED067BB82F0' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info MJ: Archive Run Details.IsRecordChangeArchive 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '4959B7F3-AD32-40DD-8E3F-8DF97E4C6844' AND AutoUpdateCategory = 1

