import { RecordMetadata } from "@pinecone-database/pinecone"

export type Customer = RecordMetadata & {
    ID: number,
    BCMID: string,
    FirstName: string,
    NickName: string,
    LastName: string,
    AccountID: string,
    LastReviewedDate: Date,
    Tile: string,
    Email1: string,
    Email2: string,
    EmailSource: string,
    PhoneNumber: string,
    ProfilePictureURL: string,
    Twitter: string,
    Instagram: string,
    LinkedIn: string,
    Facebook: string,
    EmailStatus: string,
    RoleID: number,
    LevelID: number,
    Prefix: string,
    Suffix: string,
    Tags: string,
    Status: string,
    ActivityCount: number,
    LatestActivityDate: Date,
    EarliestActivityDate: Date,
    RecordSource: string,
    CreatedAt: Date,
    UpdatedAt: Date,
    LastEnrichedAt: Date,
    FirstLast: string,
    EmailDomain: string,
    Account: string,
    Domain: string,
    Website: string,
    Role: string,
    Level: string,
    AccountCustomerCount: number
}