name: Build and publish docker images

on:
  workflow_run:
    workflows: [Build and publish new package versions]
    branches: [main]
    types:
      - completed

  workflow_dispatch:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Get version
        id: version
        run: |
          VERSION=$(jq -r .version packages/MJCore/package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.CRAIG_BC_DOCKER_USERNAME }}
          password: ${{ secrets.CRAIG_BC_DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            memberjunction/api:latest
            memberjunction/api:v${{ steps.version.outputs.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64
          file: docker/MJAPI/Dockerfile
          context: .

      - name: Log in to the AskSkip Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: askskip.azurecr.io
          username: ${{ secrets.ASKSKIP_AZ_SP_CLIENT_ID }}
          password: ${{ secrets.ASKSKIP_AZ_SP_CLIENT_SECRET }}

      - name: Push image to AskSkip Azure Container Registry
        run: |
          docker buildx imagetools create \
            --tag askskip.azurecr.io/memberjunction/api:latest \
            --tag askskip.azurecr.io/memberjunction/api:v${{ steps.version.outputs.VERSION }} \
            memberjunction/api:latest
