name: Update package documentation

on:
  workflow_run:
    workflows: [Build and publish new package versions]
    branches: [main]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    name: Generate and deploy package documentation
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Error out if the trigger did not succeed
        run: |
          if [ "${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion || 'success' }}" != "success" ]; then
            echo "::error::The triggering workflow did not succeed"
            exit 1
          fi

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Generate doumentation
        run: npm run docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
