#!/usr/bin/env python3
"""
Emit the V and U migration pair, per dialect, for the per-connection integration catalog.

    python3 scripts/catalog-migration/generate.py --baseline-dir <dir> --out <dir> [--version <yyyymmddHHMMSS>]

Applied with:
    mj migrate --schema mjc_integration_catalog --dir "SQL Scripts/mjc-migrations-pg"     # Postgres
    mj migrate --schema mjc_integration_catalog --dir "SQL Scripts/mjc-migrations"        # SQL Server

Statement ORDER is load-bearing and is the order every precedent migration in the MJ repository
uses. In particular the base views must land BEFORE anything relies on the field metadata
surviving: `R__RefreshMetadata` runs on every migrate and deletes any field row whose column is
absent from the entity's base view.
"""
import argparse, io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from baseline import Baseline
import model as M
import ddl
import metadata as MD

try:
    import routines            # written separately; the CRUD procedures
    HAVE_ROUTINES = True
except ImportError:
    HAVE_ROUTINES = False

BANNER = '-- ' + '=' * 94

HEADER = """{banner}
-- {title}
{banner}
--
-- Per-connection integration catalog. Ticket MJC-264; register MJ-CAT-1 through MJ-CAT-9.
--
-- WHY THIS EXISTS. `IntegrationObject` and `IntegrationObjectField` are keyed by IntegrationID
-- alone, so two connections of the same connector share one set of object and field definitions:
-- one tenant's discovery rewrites the other's, and one tenant's column-cap enforcement disables
-- the object for everybody. These two tables give each connection its own catalog, with
-- provenance, and with SELECTION as an axis separate from STATUS.
--
-- WHY IT REGISTERS ITSELF. Tenant CodeGen excludes the `__mj` schema, so nothing else will ever
-- create the views, the CRUD procedures or the entity metadata for these tables.
--
-- WHY DIRECT INSERTS. `spCreateEntity` and `spCreateEntityField` are CodeGen-generated CRUD
-- procedures and omit every not-updatable-through-the-API column — which is every schema-derived
-- one. `spCreateEntity` has no @BaseTable and `spCreateEntityField` has no @EntityID/@Name/@Type,
-- all NOT NULL with no default, so every call fails. Direct INSERT is what CodeGen itself emits.
--
-- WHY ${{mjSchema}} AND NOT THE FLYWAY DEFAULT-SCHEMA PLACEHOLDER. This migration is applied
-- under `--schema mjc_integration_catalog` so it keeps its own flyway history. Under that flag the
-- flyway built-in resolves to the HISTORY schema, not the core schema — so it must not appear in
-- this file at all, not even in a comment, because placeholders are substituted in comments too.
--
-- GENERATED by scripts/catalog-migration/generate.py from the MJ v5.51.0 baseline. Every column,
-- default and metadata row for a copied column is LIFTED from the source table's own definition,
-- because on Postgres nothing reconciles this metadata after the fact and the metadata records
-- SQL Server type names and byte lengths on every dialect.
{banner}

"""


def emit_v(b, dialect, version):
    d = dialect
    parts = [HEADER.format(banner=BANNER,
                           title=f'V{version} — CompanyIntegrationObject / CompanyIntegrationObjectField')]

    def sect(t):
        parts.append(f'\n{BANNER}\n-- {t}\n{BANNER}\n')

    sect('1. Tables')
    parts.append(ddl.build_table(b, 'IntegrationObject', M.TABLE_CIO, M.CIO_EXTRA, [], None))
    parts.append(ddl.build_table(b, 'IntegrationObjectField', M.TABLE_CIOF, M.CIOF_EXTRA,
                                 M.CIOF_DROP_REAL, None))

    sect('2. Defaults')
    parts.append(ddl.build_defaults(b, 'IntegrationObject', M.TABLE_CIO, M.CIO_EXTRA, []))
    parts.append(ddl.build_defaults(b, 'IntegrationObjectField', M.TABLE_CIOF, M.CIOF_EXTRA,
                                    M.CIOF_DROP_REAL))

    sect('3. Keys, foreign keys and checks')
    parts.append(ddl.build_constraints(d, M.TABLE_CIO, ['CompanyIntegrationID', 'Name'], M.CIO_EXTRA))
    parts.append(ddl.build_constraints(d, M.TABLE_CIOF, ['CompanyIntegrationObjectID', 'Name'],
                                       M.CIOF_EXTRA))

    sect('4. Indexes')
    parts.append(ddl.build_indexes(d, M.TABLE_CIO, [
        (f'IX_{M.TABLE_CIO}_Connection_Status_Sequence',
         ['CompanyIntegrationID', 'Status', 'Sequence']),
        (f'IX_{M.TABLE_CIO}_IntegrationObjectID', ['IntegrationObjectID']),
    ]))
    parts.append(ddl.build_indexes(d, M.TABLE_CIOF, [
        (f'IX_{M.TABLE_CIOF}_Object_Status', ['CompanyIntegrationObjectID', 'Status']),
        (f'IX_{M.TABLE_CIOF}_RelatedObject', ['RelatedCompanyIntegrationObjectID']),
    ]))

    sect('5. Base views — MUST precede the metadata, or R__RefreshMetadata deletes the field rows')
    cio_real = [c[0] for c in b.table_columns('IntegrationObject')] + [c['name'] for c in M.CIO_EXTRA]
    parts.append(ddl.build_view(d, M.TABLE_CIO, M.VIEW_CIO, cio_real, {}, None))
    ciof_real = ([c[0] for c in b.table_columns('IntegrationObjectField')
                  if c[0] not in M.CIOF_DROP_REAL] + [c['name'] for c in M.CIOF_EXTRA])
    parts.append(ddl.build_view(d, M.TABLE_CIOF, M.VIEW_CIOF, ciof_real,
                                M.CIOF_VIRTUAL_ALIASES,
                                ('RelatedIntegrationObject', 'RelatedCompanyIntegrationObjectID'),
                                related_table=M.TABLE_CIO))

    sect('6. CRUD procedures')
    if HAVE_ROUTINES:
        for src, tgt, extra, drop in (
            ('IntegrationObject', M.TABLE_CIO, M.CIO_EXTRA, []),
            ('IntegrationObjectField', M.TABLE_CIOF, M.CIOF_EXTRA, M.CIOF_DROP_REAL)):
            r = routines.build_crud(b, src, tgt, extra, drop)
            parts += [r['create'], '\n', r['update'], '\n', r['delete'], '\n']
    else:
        parts.append('-- !! routines.py absent — CRUD procedures NOT emitted. '
                     'This migration is INCOMPLETE and must not be applied.\n')

    sect('7. Entity metadata')
    parts.append(MD.build_entity_row(
        d, M.ENTITY_ID_CIO, M.ENTITY_NAME_CIO, M.TABLE_CIO, M.VIEW_CIO,
        'Per-connection copy of an integration object. Each connection of a connector gets its own '
        'row, so one tenant discovery cannot rewrite another tenant definitions.'))
    parts.append(MD.build_entity_row(
        d, M.ENTITY_ID_CIOF, M.ENTITY_NAME_CIOF, M.TABLE_CIOF, M.VIEW_CIOF,
        'Per-connection copy of an integration object field, carrying the observed width and the '
        'provenance of every attribute alongside the value the schema builder will use.'))

    sect('8. Entity fields')
    cols, io_rows = b.entity_field_rows(M.SOURCE_ENTITY_ID_IO)
    parts.append(MD.build_field_rows(
        d, cols, io_rows, M.ENTITY_ID_CIO,
        [c[0] for c in b.table_columns('IntegrationObject')], {}, M.CIO_EXTRA, {'Integration'}))
    cols2, iof_rows = b.entity_field_rows(M.SOURCE_ENTITY_ID_IOF)
    parts.append(MD.build_field_rows(
        d, cols2, iof_rows, M.ENTITY_ID_CIOF,
        [c[0] for c in b.table_columns('IntegrationObjectField') if c[0] not in M.CIOF_DROP_REAL],
        {}, M.CIOF_EXTRA, set(M.CIOF_VIRTUAL_ALIASES) | {'RelatedIntegrationObject'}))

    sect('9. Permissions')
    parts.append(MD.build_permissions(d, M.ENTITY_ID_CIO, M.ROLES))
    parts.append(MD.build_permissions(d, M.ENTITY_ID_CIOF, M.ROLES))

    return ''.join(parts)


def emit_u(dialect, version):
    d = dialect
    o = ddl.obj
    p = [HEADER.format(banner=BANNER, title=f'U{version} — undo'),
         '-- Reverses the V in reverse order. Additive migration, so this is a clean rollback.\n\n']
    tbl = (lambda n: f'[${{mjSchema}}].[{n}]') if d == 'ss' else (lambda n: f'${{mjSchema}}."{n}"')
    lit = (lambda s: f"N'{s}'") if d == 'ss' else (lambda s: f"'{s}'")

    for eid in (M.ENTITY_ID_CIOF, M.ENTITY_ID_CIO):
        p.append(f'DELETE FROM {tbl("EntityPermission")} WHERE '
                 f'{"[EntityID]" if d=="ss" else chr(34)+"EntityID"+chr(34)} = {lit(eid)};\n')
        p.append(f'DELETE FROM {tbl("EntityField")} WHERE '
                 f'{"[EntityID]" if d=="ss" else chr(34)+"EntityID"+chr(34)} = {lit(eid)};\n')
        p.append(f'DELETE FROM {tbl("Entity")} WHERE '
                 f'{"[ID]" if d=="ss" else chr(34)+"ID"+chr(34)} = {lit(eid)};\n')
    p.append('\n')

    if HAVE_ROUTINES:
        for t in (M.TABLE_CIOF, M.TABLE_CIO):
            p.append(routines.build_drop_crud(d, t))
    p.append('\n')

    for v in (M.VIEW_CIOF, M.VIEW_CIO):
        p.append(f'DROP VIEW IF EXISTS {o(d, v)}'
                 + (';\nGO\n' if d == 'ss' else ' CASCADE;\n'))
    for t in (M.TABLE_CIOF, M.TABLE_CIO):
        p.append(f'DROP TABLE IF EXISTS {o(d, t)}'
                 + (';\nGO\n' if d == 'ss' else ' CASCADE;\n'))
    return ''.join(p)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--baseline-dir', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--version', default='202609091900')
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    slug = 'mjccatalog__CompanyIntegrationObjects'
    for d, fn, ext in (('ss', 'mj-base-ss.sql', '.sql'), ('pg', 'mj-base-pg.sql', '.pg.sql')):
        b = Baseline(io.open(os.path.join(a.baseline_dir, fn), encoding='utf-8',
                             errors='replace').read(), d)
        for kind, text in (('V', emit_v(b, d, a.version)), ('U', emit_u(d, a.version))):
            path = os.path.join(a.out, f'{kind}{a.version}__{slug}{ext}')
            io.open(path, 'w', encoding='utf-8').write(text)
            print(f'  {path}  {text.count(chr(10))} lines')
    if not HAVE_ROUTINES:
        print('\n  WARNING: routines.py absent — the emitted V files have NO CRUD procedures '
              'and must not be applied.')


if __name__ == '__main__':
    main()
